### PR TITLE
[IDBFS] Do not fail when syncing existing directories.

### PR DESCRIPTION
**Pull request by VinnyOG**
When a directory with a different timestamp exists in IDB and we sync back to memfs an `EEXIST` error is thrown.

This is not the case when syncing files and is incorrect behavior. There is no reason why the directory should not be updated.

Following the spirit of `mkdirTree` https://github.com/emscripten-core/emscripten/blob/eabd82cb1d5890b3c1ed545997a94c460488a6ee/src/library_fs.js#L688

I suggest we catch the case of an existing directory, remove it and recreate it in order to update it.

EDIT: we can't `rmdir` an non-empty directory. Since my understanding is the `mode` doesn't do much then perhaps we can just ignore this `EEXIST` all together and not worry about re-creating (as is the case in `mkdirTree`)?

### CODE REVIEW

**Comment by VinnyOG** [comment]
To address #12562

**Comment by VinnyOG** [comment]
I updated this to use `mkdirTree` instead. Diff is much smaller now. `mkdirTree` ignores `EEXIST` already

**Comment by kripken** [comment]
Thanks @VinnyOG ! This looks right to me.

Can you please add something to one of the existing tests for this? (I think those are `test_fs_idbfs_sync, test_fs_idbfs_sync_force_exit, test_fs_idbfs_fsync`) Hopefully just a small addition is necessary. That would really help avoid future problems.

**Comment by VinnyOG** [comment]
Hey @kripken yup working on it now. Found an issue running tests locally in that after the test finishes it doesn't clean up IndexedDB so when I run again in my default browser some steps fail (like ensuring the directory is empty and that files were created on open) so there's a few changes I'm working on and hope to have them pushed within the next day.

**Comment by camilstaps** [comment]
Any news on this @VinnyOG? I have an application that is broken due to this, so it would be nice to get this merged.

**Comment by camilstaps** [comment]
@kripken I had a look if I could extend the test suite myself, but I run into some issues. I'm looking at `test_idbfs_sync`. The problem is that when you call `syncfs(true, ...)` within `main`:

- The files which you just deleted are recreated.
- The program does not wait for the sync to finish, because it is asynchronous. The same problem actually affects what happens with `EXTRA_WORK`.

Especially the second point makes this quite hairy. Maybe I'm overlooking an easier way?

**Comment by kripken** [comment]
@camilstaps I think the program needs to be made asynchronous. So that when the update is done we continue to run?

**Comment by camilstaps** [comment]
Thanks @kripken. I have implemented this by creating a directory before populating from IndexedDB (the file system in IndexedDB also contains that directory). It's a bit simpler than what I had in mind first, but it fails on the current master and passes on my branch, so I hope it's sufficient. Please see #13574 if you have time :slightly_smiling_face:

**Comment by VinnyOG** [comment]
Closing as @camilstaps provided the tests along with this change in #13574.

**Pull request closed without merging**
