### PR TITLE
Optimize memcmp

### PR DESCRIPTION
**Pull request by kripken**
This does similar things to what we already do for memcpy etc.,
doing word-sized operations where possible.

On artificial benchmarks this is up to 3.7x faster. This is motivated
by a real-world benchmark where memcmp is very high in the profile.

For consistency, also apply `EMSCRIPTEN_OPTIMIZE_FOR_OZ` as we
do for memcpy etc., to not unroll loops in clang in that case.

### CODE REVIEW

**Comment by sbc100** [comment]
Can llvm not do this kind of thing for us?

**Review by sbc100 — APPROVED** [review]

**Comment by kripken** [comment]
I verified LLVM doesn't do this. It can unroll loops, but synthesizing an extra word-size loop before is pretty hard to do, and also it might make things slower if the inputs are very small.

**Comment by dschuff** [comment]
I'd be curious to see what the autovectorizer does to this. Have you tried it? /cc @tlively

**Comment by kripken** [comment]
Interesting idea to try the autovectorizer. I spent some time with things like
```cpp
#pragma clang loop vectorize(enable) interleave(enable)
```
but I couldn't get past
```
warning: loop not vectorized: the optimizer was unable to perform the requested transformation
```
Perhaps that the loop has an unfixed number of iterations is a problem.

**Comment by tlively** [comment]
Interesting. I have some bugs about how trivial loops are not properly vectorized, so maybe there's something simple to fix in the backend.

**Comment by kripken** [comment]
Meanwhile, any objections to landing this? It should be a significant speedup for the user that brought it to my attention.

**Review by tlively — APPROVED** [review]

**Pull request merged**
