### PR TITLE
Remove STATIC* JS vars and STATIC_BUMP setting

### PR DESCRIPTION
**Pull request by kripken**
These used to make sense when we had static allocations in JS. We'd use the
"bump" to track the total size, which was increased by the JS compiler, and at
runtime we'd have STATIC_BASE and STATICTOP. Now that we disallow static
allocations from the JS compiler, we don't need them.

Note that we do still track "staticBump" in the metadata from finalize. That is
the total size of static memory from lld, which never changes. We use it to
compute where the stack begins (which determines the rest of memory layout).

In principle since all that layout was done by lld, we could just receive it from
there instead of computing it in emscripten.py. Perhaps finalize should return
the value of `__heap_base` and other relevant globals? Is there a list of all
of them?

See https://github.com/emscripten-core/emscripten/issues/11860

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]
Great!!

**Comment by dschuff** [comment]
This is nice, but I also like the idea of getting more from the linker and tracking less in the metadata. Could we use a link map for this purpose? (I know we had a discussion about link maps sometime recently but I can't find it atm).

**Comment by sbc100** [comment]
Here is the map file PR: https://reviews.llvm.org/D77187

I agree hopefully there is a lot more cleanup to do here but this is an important step to get landed.

**Comment by sbc100** [comment]
I agree, using the map file is an interesting idea because it allows us get to get information about the wasm without needing extra exports.

**Comment by kripken** [comment]
Sounds like the link map will let us read all the layout info from there? That could be a nice further simplification to remove all the `Memory()` computations in `emscripten.py`.

**Pull request merged**
