### PR TITLE
Make emscripten::val default constructible

### PR DESCRIPTION
**Pull request by xbcnn**
The default ctor of `val` is deleted and it can't be default constructed.
This limits some usages such as create an array of it but without an explicit
 initialization list. (More: https://en.wikipedia.org/wiki/Default_constructor)

The default constructed val is same as val::undefined().

### CODE REVIEW

**Comment by xbcnn** [comment]
@RReverser  Do you have any concerns about this?  Thanks.

**Comment by sbc100** [comment]
Add tests?

**Comment by RReverser** [comment]
I wouldn't do this. Null is a desired default value only in certain contexts. Undefined would be a better choice and closer reflect JS behaviour, but I'd much rather users be explicit about what they want.

**Comment by xbcnn** [comment]
Yes, I agree with `Undefined`. 

> I'd much rather users be explicit about what they want.
Explicit initialized is good except that sometimes it can't, such as use an array of val as buffer.

**Comment by xbcnn** [comment]
Sorry for the confusing.  A example could be like this:

`
template<size_t N>
class Cache {
public:
  Cache() = default;
  void put(val&& v) { vals_[val_cnt_++] = std::move(v); }
  ...

private:
  std::array<emscripten::val, N> vals_;  // cached vals
  size_t val_cnt_ = 0;
  ...
};

`

Using std::vector<val> works but has some overheads like multiple dynamic allocations.

**Comment by sbc100** [comment]
I see.. std::array elements are always default constructued.  I that case I think that seems reasonable.  @RReverser what do you see as the risk of letting vals default of undefined like this?

**Comment by RReverser** [comment]
> @RReverser what do you see as the risk of letting vals default of undefined like this?

Not really a risk, just wanted people to always think about explicit value they want to initialize with (e.g. `0` for numbers, `null` for objects etc.). But the `std::array` limitation is compelling enough that maybe default constructor is needed...

**Review by sbc100 — APPROVED** [review]

**Pull request merged**
