### PR TITLE
Mark 3.1.30 as released

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Review by aheejin — APPROVED** [review]

**Comment by aheejin** [comment]
Do we usually write about LLVM changes in the ChangeLog.md here?

**Comment by dschuff** [comment]
Sometimes (although usually it's in conjunction with an emscripten commit). But since emscripten keeps up with LLVM trunk and we don't have another good way to log LLVM changes, I think it would make sense to mention notable LLVM changes that affect wasm. I'll add a note to the changelog.

**Comment by dschuff** [comment]
WDYT of this note?

**Comment by aheejin** [comment]
Sounds good. Maybe mention `LiveDebugValues` analysis? But either way is fine.

**Comment by dschuff** [comment]
Yeah I decided that users wouldn't care much about the mechanism, and just went for putting the link to the CL in there instead in case people are curious.

**Pull request merged**
