### PR TITLE
Fixup ws usage for newer versions

### PR DESCRIPTION
**Pull request by lewing**
Upgrade to ws 8.5.0.  Fixes https://github.com/emscripten-core/emscripten/issues/5971 https://github.com/emscripten-core/emscripten/issues/10264 https://github.com/emscripten-core/emscripten/issues/12813

### CODE REVIEW

**Comment by lewing** [comment]
Looks like the tests/sockets/ws can be removed as well.  I think the Buffer wrapping can be removed by setting websocket.binaryType='arraybuffer' but I haven't tested.  I'm happy to make those changes if desired.

**Comment by sbc100** [comment]
Ah yes it looks like `tests/sockets/ws` have been unused since #7536.   Do you want to open a separate PR to remove that?

**Comment by sbc100** [comment]
> Ah yes it looks like `tests/sockets/ws` have been unused since #7536. Do you want to open a separate PR to remove that?

If not, I can do it.

**Comment by lewing** [comment]
> Ah yes it looks like `tests/sockets/ws` have been unused since #7536. Do you want to open a separate PR to remove that?

sure

**Comment by lewing** [comment]
https://github.com/emscripten-core/emscripten/pull/16732

**Review by sbc100 — APPROVED** [review]
lgtm.   I'll let @juj give final approval since he wrote this code and knows it better than me.

**Comment by lewing** [comment]
I see this missed 3.1.8?  I know it isn't considered urgent but it would be great if it could make it in soon.

**Pull request merged**
