### PR TITLE
Move internal-only parts of emscripten/threading.h

### PR DESCRIPTION
**Pull request by sbc100**
The layout of the em_called_queue struct does not need to
be public as fast as I can tell.

### CODE REVIEW

**Comment by sbc100** [comment]
@juj, am I correct in thinking that these parts of the API don't need to be exposed.

At least the tests that we have don't need to access any of this directly it seems.

**Review by juj — APPROVED** [review]
Yeah, that's true - these are internal.

**Comment by sbc100** [comment]
Nice!

**Comment by tlively** [comment]
This change (specifically where the definition of `em_queued_call` moved) seems to make `emscripten_sync_run_in_main_thread` unusable because it takes an `em_queued_call*` argument, but there is no API to create an appropriate `em_queued_call*` to pass in there.

This was reported by a user on emscripten-discuss, so perhaps we should fix this. Alternatively we could remove `emscripten_sync_run_in_main_thread` and keep `em_queued_call` an internal detail.

**Comment by sbc100** [comment]
I'm a big fan of making the public API as small a possible.   Is there a specific use case that emscripten_sync_run_in_main_thread enabled?

It looks like we have an separate `emscripten_sync_run_in_main_runtime_thread` which is directly usable and looks like they are designed to be user facing.

The `emscripten_sync_run_in_main_thread` family look like they are indended for internal JS library use:

```
void *emscripten_sync_run_in_main_thread_0(int function);                        
void *emscripten_sync_run_in_main_thread_1(int function, void *arg1);            
void *emscripten_sync_run_in_main_thread_2(int function, void *arg1, void *arg2);
void *emscripten_sync_run_in_main_thread_3(int function, void *arg1, void *arg2, void *arg3);
void *emscripten_sync_run_in_main_thread_7(int function, void *arg1, void *arg2, void *arg3, void *arg4, void *arg5, void *arg6, void *arg7); 
```

Node the function here is that `int` which corresponds to an JS function enum which is (IIUC) constructed at build time to call JS functions on the main thread.

So my hope would be that we can instead move the `run_in_main_thread` family to `internal.h` and keep the `run_in_main_runtime_thread` as the external facing API.

I'm a little confused about the naming of these two families of functions since its not possible (IIUC) to ever have a setup where there exists a `main thread` but that is not also the `main runtime thread`.   The only setup I can think of where these are not the same thing is when there is no `main thread` at all... and the `main runtime` is running in worker.  In this case however it wouldn't make any sense to talk about the `main thread`.. as separate to the `main runtime` thread as emscripten would simply not be running on main browser thread at all.. and could not run things there or send messages there.

**Pull request merged**
