### PR TITLE
Enable SSE2 test cases.

### PR DESCRIPTION
**Pull request by juj**
Enable test cases from test_sse2_full which pass with optimizations enabled after https://github.com/kripken/emscripten-fastcomp/pull/124. Merge only after https://github.com/kripken/emscripten-fastcomp/pull/124 is merged.

### CODE REVIEW

**Comment by juj** [comment]
Looks like https://github.com/kripken/emscripten-fastcomp/pull/124 works quite strong at fixing the remaining test cases. After that PR is applied, I see the two following failures still:
    1. All except one SSE2 function, `_mm_cvtepi32_ps` now work in `test_sse2_full` test.
    2. building Bullet with SSE2 enabled still fails with a `<4 x f32>` to `<i128>` cast. I'm trying to dig into why that is now.

**Comment by kripken** [comment]
This breaks the test for me, on

````
/media/alon/d69dd9b2-4791-4b8e-aeb3-f6353b45d710/home/alon/Dev/emscripten/tests/test_sse2_full.cpp:130:21: error: use of undeclared
      identifier '_mm_cvtsd_si64'
        Ret_M128d(int64_t, _mm_cvtsd_si64); // _mm_cvtsd_si64x is an alias to this.
                           ^
/media/alon/d69dd9b2-4791-4b8e-aeb3-f6353b45d710/home/alon/Dev/emscripten/tests/test_sse_full.h:410:19: note: expanded from macro 'Ret_M128d'
                        Ret_type ret = func(m1); \
                                       ^
````

**Comment by kripken** [comment]
This breaks the test for me, on

````
/media/alon/d69dd9b2-4791-4b8e-aeb3-f6353b45d710/home/alon/Dev/emscripten/tests/test_sse2_full.cpp:130:21: error: use of undeclared
      identifier '_mm_cvtsd_si64'
        Ret_M128d(int64_t, _mm_cvtsd_si64); // _mm_cvtsd_si64x is an alias to this.
                           ^
/media/alon/d69dd9b2-4791-4b8e-aeb3-f6353b45d710/home/alon/Dev/emscripten/tests/test_sse_full.h:410:19: note: expanded from macro 'Ret_M128d'
                        Ret_type ret = func(m1); \
                                       ^
````

**Comment by juj** [comment]
If you replace `_mm_cvtsd_si64` with `_mm_cvtsd_si64x`, does that compile?

**Comment by kripken** [comment]
No, same error. There are also 6 other errors, that is just the first.

Why does that test build natively? Can't we just store the proper output and check against that?

**Comment by juj** [comment]
We could, but the whole results file is 116000 lines long and takes up 14MB on disk. When the test is changed, we would need to reupload a new version of the results text file, which would quickly accumulate a lot of useless history data to the Emscripten git repo and slow down cloning.

Can you print the full error log?

**Comment by kripken** [comment]
Got it, makes sense.

On my machine here I get

````
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse2_full.cpp:293:23: error: no matching function for call to '_mm_stream_si64'
        void_OutIntPtr_int64(_mm_stream_si64, int64_t*, 8, 1);
                             ^~~~~~~~~~~~~~~
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse_full.h:501:5: note: expanded from macro 'void_OutIntPtr_int64'
                                func((Ptr_type)out, m1); \
                                ^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/fastcomp/build/bin/../lib/clang/3.7.0/include/emmintrin.h:1256:1: note: candidate function not viable: no known conversion from 'int64_t *'
      (aka 'long *') to 'long long *' for 1st argument
_mm_stream_si64(long long *__p, long long __a)
^
1 error generated.
````

on my machine at home I saw more errors, I can paste that later.

**Comment by juj** [comment]
This sounds like `long long` vs `int64_t` issues. There was this commit before, 82460666b561e4157ec081b4e049508a80e98bf6 , I remember you reported some signature errors before as well.

What happens if you change `test_sse2_full.cpp:293` from

    void_OutIntPtr_int64(_mm_stream_si64, int64_t*, 8, 1);

to

    void_OutIntPtr_int64(_mm_stream_si64, long long*, 8, 1);

?

**Comment by kripken** [comment]
Yes, that fixes that error. Test passes on this machine with that change.

**Comment by kripken** [comment]
Err, the testcase now compiles but fails to pass. Long error, starts with

````
--- expected
+++ actual
@@ -96191,353 +96191,353 @@
 _mm_srli_epi16([0x00000000,0x00000001,0x00000002,0x00000003], 1) = [0x00000000,0x00000000,0x00000001,0x00000001]
 _mm_srli_epi16([0x00000001,0x00000002,0x00000003,0x01020304], 1) = [0x00000000,0x00000001,0x00000001,0x00810182]
 _mm_srli_epi16([0x00000002,0x00000003,0x01020304,0x10203040], 1) = [0x00000001,0x00000001,0x00810182,0x08101820]
-_mm_srli_epi16([0x00000003,0x01020304,0x10203040,0x7FFFFFFF], 1) = [0x00000001,0x00810182,0x08101820,0x3FFF7FFF]
-_mm_srli_epi16([0x01020304,0x10203040,0x7FFFFFFF,0xFFFFFFFF], 1) = [0x00810182,0x08101820,0x3FFF7FFF,0x7FFF7FFF]
-_mm_srli_epi16([0x10203040,0x7FFFFFFF,0xFFFFFFFF,0xFFFFFFFE], 1) = [0x08101820,0x3FFF7FFF,0x7FFF7FFF,0x7FFF7FFF]
-_mm_srli_epi16([0x7FFFFFFF,0xFFFFFFFF,0xFFFFFFFE,0x12345678], 1) = [0x3FFF7FFF,0x7FFF7FFF,0x7FFF7FFF,0x091A2B3C]
-_mm_srli_epi16([0xFFFFFFFF,0xFFFFFFFE,0x12345678,0x9ABCDEF1], 1) = [0x7FFF7FFF,0x7FFF7FFF,0x091A2B3C,0x4D5E6F78]
-_mm_srli_epi16([0xFFFFFFFE,0x12345678,0x9ABCDEF1,0x80000000], 1) = [0x7FFF7FFF,0x091A2B3C,0x4D5E6F78,0x40000000]
-_mm_srli_epi16([0x12345678,0x9ABCDEF1,0x80000000,0x80808080], 1) = [0x091A2B3C,0x4D5E6F78,0x40000000,0x40404040]
-_mm_srli_epi16([0x9ABCDEF1,0x80000000,0x80808080,0x7F7F7F7F], 1) = [0x4D5E6F78,0x40000000,0x40404040,0x3FBF3FBF]
-_mm_srli_epi16([0x80000000,0x80808080,0x7F7F7F7F,0x01010101], 1) = [0x40000000,0x40404040,0x3FBF3FBF,0x00800080]
-_mm_srli_epi16([0x80808080,0x7F7F7F7F,0x01010101,0x11111111], 1) = [0x40404040,0x3FBF3FBF,0x00800080,0x08880888]
+_mm_srli_epi16([0x00000003,0x01020304,0x10203040,0x7FFFFFFF], 1) = [0x00000001,0x00810182,0x08101820,0x3FFFFFFF]
+_mm_srli_epi16([0x01020304,0x10203040,0x7FFFFFFF,0xFFFFFFFF], 1) = [0x00810182,0x08101820,0x3FFFFFFF,0xFFFFFFFF]
+_mm_srli_epi16([0x10203040,0x7FFFFFFF,0xFFFFFFFF,0xFFFFFFFE], 1) = [0x08101820,0x3FFFFFFF,0xFFFFFFFF,0xFFFFFFFF]
+_mm_srli_epi16([0x7FFFFFFF,0xFFFFFFFF,0xFFFFFFFE,0x12345678], 1) = [0x3FFFFFFF,0xFFFFFFFF,0xFFFFFFFF,0x091A2B3C]
+_mm_srli_epi16([0xFFFFFFFF,0xFFFFFFFE,0x12345678,0x9ABCDEF1], 1) = [0xFFFFFFFF,0xFFFFFFFF,0x091A2B3C,0xCD5EEF78]
+_mm_srli_epi16([0xFFFFFFFE,0x12345678,0x9ABCDEF1,0x80000000], 1) = [0xFFFFFFFF,0x091A2B3C,0xCD5EEF78,0xC0000000]
+_mm_srli_epi16([0x12345678,0x9ABCDEF1,0x80000000,0x80808080], 1) = [0x091A2B3C,0xCD5EEF78,0xC0000000,0xC040C040]
+_mm_srli_epi16([0x9ABCDEF1,0x80000000,0x80808080,0x7F7F7F7F], 1) = [0xCD5EEF78,0xC0000000,0xC040C040,0x3FBF3FBF]
+_mm_srli_epi16([0x80000000,0x80808080,0x7F7F7F7F,0x01010101], 1) = [0xC0000000,0xC040C040,0x3FBF3FBF,0x00800080]
+_mm_srli_epi16([0x80808080,0x7F7F7F7F,0x01010101,0x11111111], 1) = [0xC040C040,0x3FBF3FBF,0x00800080,0x08880888]
````

**Comment by juj** [comment]
Hmm, that is a real bug. `_mm_srli_epi16` shifts right logically, so in the very first line, `0xFFFF` shifted right by one should become `0x7FFF`, but in your case, it is shifting in arithmetically, and sign-extending the one bit, resulting in `0xFFFF`.

Running this in my Nightly web console makes it look like there's a bug in Firefox:

    SIMD.Int16x8.extractLane(SIMD.Int16x8.shiftRightLogicalByScalar(SIMD.Int16x8.splat(65535), 1), 0)

that returns `-1`, whereas it would be expected to return `32767`. Running in the node.js polyfill gives the correct result. The reason why this error is not caught is that the bots don't yet have the most recent SpiderMonkey.

However, it's a bit more awkward: The function `.shiftRightLogicalByScalar` does no longer exist in the SIMD.js spec, but instead there are separate types `SIMD.Int16x8` and `SIMD.Uint16x8` which both have a function `.shiftRightByScalar`, and on signed type it does an arithmetic shift, and on the unsigned type it does a logical shift. This has not yet been implemented in Firefox (was reported as bug https://bugzilla.mozilla.org/show_bug.cgi?id=1201934). I chose to implement the functionality according to the old behavior because Firefox still has that.

Perhaps we should skip the test in SpiderMonkey then until the above bug is resolved and we've upgraded our codegen to match the up-to-spec impl? I assume if you run locally in node.js, the test does pass?

**Comment by kripken** [comment]
Yes, it passes in node.

Sounds ok to me to skip in sm for now.

**Comment by kripken** [comment]
I do still get errors on my other machine, though. It's 32-bit. I see the same on this machine with `-m32` added to the clang command,

````
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse2_full.cpp:130:21: error: use of undeclared identifier '_mm_cvtsd_si64'
        Ret_M128d(int64_t, _mm_cvtsd_si64); // _mm_cvtsd_si64x is an alias to this.
                           ^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse_full.h:410:19: note: expanded from macro 'Ret_M128d'
                        Ret_type ret = func(m1); \
                                       ^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse2_full.cpp:132:21: error: use of undeclared identifier '_mm_cvtsi128_si64'
        Ret_M128i(int64_t, _mm_cvtsi128_si64); // _mm_cvtsi128_si64x is an alias to this.
                           ^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse_full.h:588:19: note: expanded from macro 'Ret_M128i'
                        Ret_type ret = func(m1); \
                                       ^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse2_full.cpp:135:27: error: use of undeclared identifier '_mm_cvtsi64_sd'; did you mean '_mm_cvtsi32_sd'?
        Ret_M128d_int64(__m128d, _mm_cvtsi64_sd); // _mm_cvtsi64x_sd is an alias to this.
                                 ^~~~~~~~~~~~~~
                                 _mm_cvtsi32_sd
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse_full.h:398:21: note: expanded from macro 'Ret_M128d_int64'
                                        Ret_type ret = func(m1, m2); \
                                                       ^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/fastcomp/build/bin/../lib/clang/3.7.0/include/emmintrin.h:413:1: note: '_mm_cvtsi32_sd' declared here
_mm_cvtsi32_sd(__m128d __a, int __b)
^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse2_full.cpp:136:21: error: use of undeclared identifier '_mm_cvtsi64_si128'
        Ret_int64(__m128i, _mm_cvtsi64_si128); // _mm_cvtsi64x_si128 is an alias to this.
                           ^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse_full.h:608:19: note: expanded from macro 'Ret_int64'
                        Ret_type ret = func(m1); \
                                       ^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse2_full.cpp:141:21: error: use of undeclared identifier '_mm_cvttsd_si64'; did you mean '_mm_cvttss_si64'?
        Ret_M128d(int64_t, _mm_cvttsd_si64); // _mm_cvttsd_si64x is an alias to this.
                           ^~~~~~~~~~~~~~~
                           _mm_cvttss_si64
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse_full.h:410:19: note: expanded from macro 'Ret_M128d'
                        Ret_type ret = func(m1); \
                                       ^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/fastcomp/build/bin/../lib/clang/3.7.0/include/xmmintrin.h:453:1: note: '_mm_cvttss_si64' declared here
_mm_cvttss_si64(__m128 __a)
^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse2_full.cpp:293:23: error: use of undeclared identifier '_mm_stream_si64'; did you mean '_mm_stream_si32'?
        void_OutIntPtr_int64(_mm_stream_si64, long long*, 8, 1);
                             ^~~~~~~~~~~~~~~
                             _mm_stream_si32
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse_full.h:501:5: note: expanded from macro 'void_OutIntPtr_int64'
                                func((Ptr_type)out, m1); \
                                ^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/fastcomp/build/bin/../lib/clang/3.7.0/include/emmintrin.h:1249:1: note: '_mm_stream_si32' declared here
_mm_stream_si32(int *__p, int __a)
^
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse2_full.cpp:293:2: error: cannot initialize a parameter of type 'int *' with an rvalue of type 'long long *'
        void_OutIntPtr_int64(_mm_stream_si64, long long*, 8, 1);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/emscripten/tests/test_sse_full.h:501:10: note: expanded from macro 'void_OutIntPtr_int64'
                                func((Ptr_type)out, m1); \
                                     ^~~~~~~~~~~~~
/media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/fastcomp/build/bin/../lib/clang/3.7.0/include/emmintrin.h:1249:22: note: passing argument to parameter '__p' here
_mm_stream_si32(int *__p, int __a)
                     ^
7 errors generated.
ERROR
````

Perhaps we should skip this test on 32-bit machines?

**Comment by juj** [comment]
Hmm, yeah, it definitely looks like some of the intrinsics are not available in 32-bit SSE2. I think it is simplest to just skip the test then. (Alternatively, we could detect this in python and build in a mode that #ifdefs out the 64bit intrinsics) Pushed https://github.com/kripken/emscripten/commit/eb2ad4099686c6fc7b47234f9032f15875654dc6 to do that. Does that look good?

**Comment by kripken** [comment]
Sure. So with skipping in 32-bit and skipping sm for now, this lgtm.

**Comment by kripken** [comment]
Looks like we never got around to finishing this for asm.js. But maybe this PR can be useful for wasm SIMD :) cc @tlively

**Comment by juj** [comment]
Closing this as old, SSE was removed.

**Pull request closed without merging**
