### PR TITLE
Replacing config file with cmake for freetype v2.10.4 port update

### PR DESCRIPTION
**Pull request by HCLJason**
Freetype 2.10.4 doesn't compile using emconfigure and emmake. I rebuilt the configuration using cmake instead based on issue 4 from the freetype port.

This needs to get edited and merged after the matching emscripten-ports/freetype PR gets merged.

### CODE REVIEW

**Comment by sbc100** [comment]
If possible I would rather not increase our dependency on external tools like `cmake` and `make`.   Currently only one port (harfbuzz) using an external build tool and that has caused us several issues over the last few months since sdl2_ttf started depending on it.  Most of the problem stem from windows users not have the right tools installed.

Is there any fundamental reason we can't keep the old method?

**Comment by sbc100** [comment]
By the way the existing method doesn't use `emconfigure` either.. it just builds the sources directly.

**Comment by HCLJason** [comment]
When I updated this file to test the building v2.10.4 using the old method, there were 40k lines worth of compiler errors, mostly duplicates spread across files. One example file that covers most of them is below.

There's some discussion about cmake in the port's issues:
https://github.com/emscripten-ports/FreeType/issues/4#issuecomment-832213811

/local/emsdk/upstream/emscripten/cache/ports-builds/freetype/src/psaux/psobjs.c:347:27: error: use of undeclared identifier 'FT_ERR_PREFIXInvalid_File_Format'; did you mean 'FT_Err_Invalid_File_Format'?
    FT_Error      error = FT_ERR( Invalid_File_Format );
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          FT_Err_Invalid_File_Format
/local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fttypes.h:599:22: note: expanded from macro 'FT_ERR'
#define FT_ERR( e )  FT_ERR_CAT( FT_ERR_PREFIX, e )
                     ^
/local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fttypes.h:595:30: note: expanded from macro 'FT_ERR_CAT'
#define FT_ERR_CAT( x, y )   FT_ERR_XCAT( x, y )
                             ^
/local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fttypes.h:594:30: note: expanded from macro 'FT_ERR_XCAT'
#define FT_ERR_XCAT( x, y )  x ## y
                             ^
<scratch space>:73:1: note: expanded from here
FT_ERR_PREFIXInvalid_File_Format
^
/local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fterrdef.h:65:3: note: 'FT_Err_Invalid_File_Format' declared here
  FT_ERRORDEF_( Invalid_File_Format,                         0x03,
  ^
/local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fterrors.h:187:24: note: expanded from macro 'FT_ERRORDEF_'
          FT_ERRORDEF( FT_ERR_CAT( FT_ERR_PREFIX, e ), v + FT_ERR_BASE, s )
                       ^
/local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fttypes.h:595:30: note: expanded from macro 'FT_ERR_CAT'
#define FT_ERR_CAT( x, y )   FT_ERR_XCAT( x, y )
                             ^
/local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fttypes.h:594:30: note: expanded from macro 'FT_ERR_XCAT'
#define FT_ERR_XCAT( x, y )  x ## y

**Comment by sbc100** [comment]
> When I updated this file to test the building v2.10.4 using the old method, there were 40k lines worth of compiler errors, mostly duplicates spread across files. One example file that covers most of them is below.
> 
> There's some discussion about cmake in the port's issues:
> [emscripten-ports/FreeType#4 (comment)](https://github.com/emscripten-ports/FreeType/issues/4#issuecomment-832213811)
> 
> /local/emsdk/upstream/emscripten/cache/ports-builds/freetype/src/psaux/psobjs.c:347:27: error: use of undeclared identifier 'FT_ERR_PREFIXInvalid_File_Format'; did you mean 'FT_Err_Invalid_File_Format'?
> FT_Error error = FT_ERR( Invalid_File_Format );
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> FT_Err_Invalid_File_Format
> /local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fttypes.h:599:22: note: expanded from macro 'FT_ERR'
> #define FT_ERR( e ) FT_ERR_CAT( FT_ERR_PREFIX, e )
> ^
> /local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fttypes.h:595:30: note: expanded from macro 'FT_ERR_CAT'
> #define FT_ERR_CAT( x, y ) FT_ERR_XCAT( x, y )
> ^
> /local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fttypes.h:594:30: note: expanded from macro 'FT_ERR_XCAT'
> #define FT_ERR_XCAT( x, y ) x ## y
> ^
> :73:1: note: expanded from here
> FT_ERR_PREFIXInvalid_File_Format
> ^
> /local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fterrdef.h:65:3: note: 'FT_Err_Invalid_File_Format' declared here
> FT_ERRORDEF_( Invalid_File_Format, 0x03,
> ^
> /local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fterrors.h:187:24: note: expanded from macro 'FT_ERRORDEF_'
> FT_ERRORDEF( FT_ERR_CAT( FT_ERR_PREFIX, e ), v + FT_ERR_BASE, s )
> ^
> /local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fttypes.h:595:30: note: expanded from macro 'FT_ERR_CAT'
> #define FT_ERR_CAT( x, y ) FT_ERR_XCAT( x, y )
> ^
> /local/emsdk/upstream/emscripten/cache/ports-builds/freetype/include/freetype/fttypes.h:594:30: note: expanded from macro 'FT_ERR_XCAT'
> #define FT_ERR_XCAT( x, y ) x ## y

I'm think you will need to figure out where those error are coming from.   Switching to relying on cmake + the actual build tool (make on UNIX and mingw-make on windows) is probably not direction we want to go in here.. at least not lightly.

**Pull request closed without merging**
