### PR TITLE
Avoid using ES6 syntax outside of core module code

### PR DESCRIPTION
**Pull request by drwwoob**
This makes the output compatible with at least Node v10

Fixes: #22290

### CODE REVIEW

**Comment by kripken** [comment]
Is this needed if we go with #22390? That should then transpile this code, I hope?

**Comment by drwwoob** [comment]
> Is this needed if we go with #22390? That should then transpile this code, I hope?

yes, this is just an alternative solution

**Comment by sbc100** [comment]
I'm fine with landing this change now since I think #22390 would be a little harder to land. 

Can you update the PR description to say something like "Avoid using ES6 syntax outside of core module code".

**Review by sbc100 — APPROVED** [review]

**Comment by drwwoob** [comment]
> I'm fine with landing this change now since I think #22390 would be a little harder to land.
> 
> Can you update the PR description to say something like "Avoid using ES6 syntax outside of core module code".

sure, I will change do changes on this PR and close #22390.

**Comment by sbc100** [comment]
> > I'm fine with landing this change now since I think #22390 would be a little harder to land.
> > Can you update the PR description to say something like "Avoid using ES6 syntax outside of core module code".
> 
> sure, I will change do changes on this PR and close #22390.

I still think the goal of #22390 is a good one.. its just a hard change to make.  Feel free to close it or leave it open aspirationally.

**Comment by drwwoob** [comment]
> > > I'm fine with landing this change now since I think #22390 would be a little harder to land.
> > > Can you update the PR description to say something like "Avoid using ES6 syntax outside of core module code".
> > 
> > 
> > sure, I will change do changes on this PR and close #22390.
> 
> I still think the goal of #22390 is a good one.. its just a hard change to make. Feel free to close it or leave it open aspirationally.

Hmmm... For solution #22390, do you think it is possible to specify the portion of code that needs to be transpile, so the transile step skips through wasm2js and other needless parts?

**Comment by sbc100** [comment]
> > > > I'm fine with landing this change now since I think #22390 would be a little harder to land.
> > > > Can you update the PR description to say something like "Avoid using ES6 syntax outside of core module code".
> > > 
> > > 
> > > sure, I will change do changes on this PR and close #22390.
> > 
> > 
> > I still think the goal of #22390 is a good one.. its just a hard change to make. Feel free to close it or leave it open aspirationally.
> 
> Hmmm... For solution #22390, do you think it is possible to specify the portion of code that needs to be transpile, so the transile step skips through wasm2js and other needless parts?

Why wouldn't you also want to transpile the wasm2js output?

**Comment by drwwoob** [comment]
> Why wouldn't you also want to transpile the wasm2js output?

so in #22390, it is mentioned that

>It looks like moving this to later will cause it to run after wasm2js. That might not be harmful, but it is potentially a lot more work, to process all the wasm2js output and not do anything on it.

I thought this comment is saying that the wasm2js part does not need to be transpile and for efficiency should not be transpiled.

**Comment by sbc100** [comment]
> > Why wouldn't you also want to transpile the wasm2js output?
> 
> so in #22390, it is mentioned that
> 
> > It looks like moving this to later will cause it to run after wasm2js. That might not be harmful, but it is potentially a lot more work, to process all the wasm2js output and not do anything on it.
> 
> I thought this comment is saying that the wasm2js part does not need to be transpile and for efficiency should not be transpiled.

Fair enough.. although most users won't be transpiling, especially in debug builds, so I personally don't think its a big deal if we slow down the release builds a little.

**Pull request merged**
