### PR TITLE
Update SDL2 for #16462

### PR DESCRIPTION
**Pull request by Daft-Freak**
As this also pulls in all the other upstream changes, I had to update to https://github.com/libsdl-org/SDL/commit/a485ffc3c8d040fc87893b61cd8cddda4248243f to not break audio.

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Some failures:
`test_sdl2_mouse`: We don't get the initial mouse move after https://github.com/libsdl-org/SDL/pull/5387
`test_sdl2_canvas_write` and `test_sdl2_unwasteful` fails seem to be because framebuffer rendering is going through webgl now (https://github.com/libsdl-org/SDL/commit/60ddb74cfe6b8c20a1e0c6afa473990c6467ea40?)

**Comment by Daft-Freak** [comment]
"Fixed" the last two by force-disabling "texture framebuffers", which as a bonus removes > 200k wasm if you're not using the renderer API...

**Review by sbc100 — APPROVED** [review]

**Comment by kripken** [comment]
The wasm2js1 errors look unrelated (they may have been fixed on `main`, merging in latest may fix them). The browser-chrome errors though look like they might be real?

**Comment by Daft-Freak** [comment]
Ah, still need to do something about the missing first mouse event

**Comment by kripken** [comment]
Tests look good!

**Pull request merged**
