### PR TITLE
fix: assign userData to __attribute

### PR DESCRIPTION
**Pull request by TroyTae**
Currently, data is not being properly transferred to `Fetch.js`.
So if I try to get the data in `Fetch.js`, I get wrong value.
https://github.com/emscripten-core/emscripten/blob/df5f6d150a4206b6935346b51fbd84da664c4b58/src/Fetch.js#L294
```
console.log(getValue(userData, 'i32'));
```

### CODE REVIEW

**Comment by juj** [comment]
Hmm, can you instead try the following fix?

```diff
diff --git a/src/Fetch.js b/src/Fetch.js
index 758c0385b..314e3224e 100644
--- a/src/Fetch.js
+++ b/src/Fetch.js
@@ -291,7 +291,7 @@ function __emscripten_fetch_xhr(fetch, onsuccess, onerror, onprogress, onreadyst
   var fetch_attr = fetch + {{{ C_STRUCTS.emscripten_fetch_t.__attributes }}};
   var requestMethod = UTF8ToString(fetch_attr);
   if (!requestMethod) requestMethod = 'GET';
-  var userData = HEAPU32[fetch_attr + {{{ C_STRUCTS.emscripten_fetch_attr_t.userData }}} >> 2];
+  var userData = HEAPU32[fetch + {{{ C_STRUCTS.emscripten_fetch_t.userData }}} >> 2];
   var fetchAttributes = HEAPU32[fetch_attr + {{{ C_STRUCTS.emscripten_fetch_attr_t.attributes }}} >> 2];
   var timeoutMsecs = HEAPU32[fetch_attr + {{{ C_STRUCTS.emscripten_fetch_attr_t.timeoutMSecs }}} >> 2];
   var withCredentials = !!HEAPU32[fetch_attr + {{{ C_STRUCTS.emscripten_fetch_attr_t.withCredentials }}} >> 2];
```

The userData field is present in both the emscripten_fetch_t and emscripten_fetch_attr_t objects - once we have a fetch going on, it should be read from the fetch instance object instead.

If the above patch works, let's land that instead?

**Comment by TroyTae** [comment]
First time, I try to do that and run this code:
https://github.com/TroyTae/emscripten/blob/issue-11590/tests/fetch/test_async_xhr.cpp

But if I do not assign to `__attribute.userData`, I get wrong pointer address.
And you know, the variable `userData` in `Fetch.js` is not used.

**Comment by TroyTae** [comment]
Additionally I find this issue when I try to resolve this issue: https://github.com/emscripten-core/emscripten/issues/11590
Now we cannot pass userData, only char pointer is possible.
If you have any idea, please tell me :)

**Comment by TroyTae** [comment]
@juj 
Do you have no opinion about this?
Why only char pointers can be passed by `userData`..?

**Comment by TroyTae** [comment]
@juj 
It seems this code isn't related with #11590
I reflect you review

**Comment by kripken** [comment]
It would also be good to add a test for this.

**Pull request merged**
