### PR TITLE
[webgpu] Remove pipeline statistics query feature

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Following https://github.com/webgpu-native/webgpu-headers/pull/238 and https://dawn-review.googlesource.com/c/dawn/+/157220, this PR cleans the experimental pipeline statistics query feature. It also supersedes https://github.com/emscripten-core/emscripten/pull/20489

@kainino0x Please review

### CODE REVIEW

**Comment by kainino0x** [comment]
I'll review this once we've ironed out https://dawn-review.googlesource.com/c/dawn/+/157220

**Review by kainino0x — COMMENTED** [review]
Resolved over there - ping me here once this is updated with fully removing the pipeline statistics stuff.

**Comment by beaufortfrancois** [comment]
I'll do that tomorrow. Thank you!

**Comment by sbc100** [comment]
For this type of PR an you prefix the title with `[webgpu]`?

**Comment by beaufortfrancois** [comment]
@kainino0x This PR has been updated and is now ready for review.
Thanks for updating the title as suggested by @sbc100

**Review by kainino0x — APPROVED** [review]
LGTM!

**Comment by kainino0x** [comment]
The struct sizes need rebaselining, will fix. Based on the command of the test that failed, I think this will be:
`./test/runner other.test_gen_struct_info --crossplatform-only --rebaseline`

**Comment by kainino0x** [comment]
ok, my build environment seems partially broken. I'll just try updating it manually?

**Comment by sbc100** [comment]
> > The struct sizes need rebaselining, will fix. Based on the command of the test that failed, I think this will be: `./test/runner other.test_gen_struct_info --crossplatform-only --rebaseline`
> 
> I remember running `./tools/gen_struct_info.py` et al as mentioned in https://github.com/emscripten-core/emscripten/blob/main/system/include/webgpu/README.md. Did I miss another command somehow?

Perhaps you forgot to run `./tools/gen_struct_info.py --wasm64` too?  I always run the test with `--rebase` which covers both 32 and 64 bit.

**Comment by kainino0x** [comment]
> Perhaps you forgot to run `./tools/gen_struct_info.py --wasm64` too? I always run the test with `--rebase` which covers both 32 and 64 bit.

I also tried using that script, both with and without --wasm64, but it didn't regenerate the thing that needed to be regenerated. I assumed it didn't work because my build environment was broken, but maybe that wasn't it.

**Pull request merged**
