### PR TITLE
Rebaseline code size tests

### PR DESCRIPTION
**Pull request by RReverser**
Not sure why they weren't caught by CI (does it skip those tests?), but it looks like there are some differences in unoptimized code size on main.

### CODE REVIEW

**Comment by sbc100** [comment]
> Not sure why they weren't caught by CI (does it skip those tests?), but it looks like there are some differences in unoptimized code size on main.

The auto-rollers skip these tests yes.

**Comment by sbc100** [comment]
I have llvm built from 77c2b623ca4c and binaryn built from 02e5b160a BTW.. which I think matches the current tot build.

**Comment by RReverser** [comment]
> I'm not seeing any deltas on `main` when I run `test/runner other.*code_size* other.*metadce* --rebase`... so maybe something is off here with your setup?

Sigh, not again...

I cleaned the cache, installed latest emsdk, did `./bootstrap` and then did `./test/runner other.*code_size*` and this is what I got.

What else am I missing at this point? 😅

**Comment by sbc100** [comment]
> > I'm not seeing any deltas on `main` when I run `test/runner other.*code_size* other.*metadce* --rebase`... so maybe something is off here with your setup?
> 
> Sigh, not again...
> 
> I cleaned the cache, installed latest emsdk, did `./bootstrap` and then did `./test/runner other.*code_size*` and this is what I got.

emsdk `tot` right?

> 
> What else am I missing at this point? 😅

**Comment by RReverser** [comment]
What's also interesting (?) is that for this test I'm not seeing a failure.

> emsdk `tot` right?
> 
> >

Yup.

```
> emsdk install tot 
Fetching latest changes to the branch/tag 'main' for 'C:/Users/me/Documents/emsdk/releases'...
refs/heads/main
Updating 2a590b5d..918d8878
Fast-forward
 DEPS | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
Successfully updated and checked out branch/tag 'main' on repository 'C:/Users/me/Documents/emsdk/releases'
Current repository version: "Tue, 24 Oct 2023 22:32:27 +0000 918d8878b1e832bd3a35a888f32c32b15b792c12"
Installing SDK 'sdk-releases-0572a66cd471c367a4892b468d55c10c0a6183af-64bit'..
Skipped installing node-16.20.0-64bit, already installed.
Skipped installing python-3.9.2-nuget-64bit, already installed.
Skipped installing java-8.152-64bit, already installed.
Skipped installing releases-0572a66cd471c367a4892b468d55c10c0a6183af-64bit, already installed.
All SDK components already installed: 'sdk-releases-0572a66cd471c367a4892b468d55c10c0a6183af-64bit'.
```

**Comment by RReverser** [comment]
@sbc100 Did you find why you had different size locally?

**Comment by sbc100** [comment]
I'm now seeing some differences with `main` but they are different to the ones you are seeing: https://github.com/emscripten-core/emscripten/pull/20557

Can you re-run with current tot... i normally just submit these changes directly without review but in this case maybe with worth investigating.

**Comment by RReverser** [comment]
> Can you re-run with current tot... i normally just submit these changes directly without review but in this case maybe with worth investigating.

Rerunning now... still seeing my differences, and yours in addition (but I actually didn't run metadce tests when making this PR, so they might've been always there).

**Comment by RReverser** [comment]
Rebased, reran with latest tot and pushed my metadce changes as well (there is tons of those, seems more than in your PR).

But either way, the original code size difference I saw is still there.

**Comment by brendandahl** [comment]
I installed tot and ran a rebase against main. I seem to get the same results as Sam. https://gist.github.com/brendandahl/51da397222be9dc64bf336ff09852a47

**Comment by RReverser** [comment]
Unless there is still something in my environment despite multiple cleanups and rebases and tot installations this far, I'm getting suspicious of this being somehow a Windows vs Unix issue, even though those tests already set some settings to avoid cross-platform differences.

Does anyone else have a Windows machine to try that unoptimized code size test on?

I'll try on WSL later as well.

**Comment by RReverser** [comment]
I guess another thing I could try is ask one of you to upload your output JS from `test_unoptimized_code_size` so that I could do a diff locally against one produced on my machine.

**Comment by brendandahl** [comment]
[Archive.zip](https://github.com/emscripten-core/emscripten/files/13193225/Archive.zip)

**Comment by RReverser** [comment]
Looks like the difference is indeed in newlines only: my hello_world.js has CRLF and yours has LF endings, but otherwise they're identical.

**Comment by RReverser** [comment]
Ah right, the main `test_minimal_runtime_code_size` test sets `'--output_eol', 'linux',` but this test doesn't.

I'll send a fix.

**Pull request closed without merging**
