### PR TITLE
Update the list of CXX_COMPILE_FEATURES in Emscripten.cmake to include C++20

### PR DESCRIPTION
**Pull request by dschuff**
Newer versions of CMake recognize cxx_std_20 as a thing that a compiler
frontend can support, and indeed the emscripten frontend supports it.

### CODE REVIEW

**Comment by sbc100** [comment]
Thank you!  I've been wondering why that test fails for me locally for ages now.

**Comment by dschuff** [comment]
I still think most of this file is unneeded and CMake should be able to detect most of the stuff in it, perhaps using CMAKE_CROSSCOMPILING_EMULATOR or some such. But haven't figured it out yet.

**Comment by dschuff** [comment]
hm, isn't [ci skip] supposed to skip CI?

**Comment by dschuff** [comment]
it did skip CI on that commit. now the status on the bottom seems confused, like it's waiting for CI on the last commit. The other tests are all passing though, so I'll just land this.

**Pull request merged**
