### PR TITLE
Make asbytes actually convert unicode to bytes

### PR DESCRIPTION
**Pull request by quantum5**

### CODE REVIEW

**Comment by kripken** [comment]
Curious to see what breaks...

but a problem we just saw is that this CI is not enough. We don't test both python2 and 3 on everything (the chromium CI does some more configurations).

**Comment by quantum5** [comment]
I am going to run the upstream tests locally with python 2 for additional converage.

**Comment by quantum5** [comment]
Locally ran upstream tests seemed to pass.

**Comment by tlively** [comment]
LGTM, but it would be good to re-run the test-browser-chrome CI first. The server seemed to die and that may not be a flake.

**Comment by quantum5** [comment]
Seems like it is a flake.

**Pull request merged**
