### PR TITLE
Minify generated a.worker.js file for pthreads builds.

### PR DESCRIPTION
**Pull request by juj**
Minify generated a.worker.js file for pthreads builds. Adds uglify-js 3.7.3 to achieve the task.

### CODE REVIEW

**Comment by VirtualTim** [comment]
I like this, in theory, however I don't like uglify-js as that only supports ES5.
I realise that worker.js should only contain ES5 code, but I can imagine this causing headaches for some people, and it would make it harder to switch over to allowing ES6 in the future.

Another note, if you're doing this would it be easy/worthwhile to also minify a.fetch.js?
This would address #8773.

**Comment by kripken** [comment]
I'm confused why it makes sense to add uglify just for the worker.js file? We can minify it the way we minify the main JS file, I think - the only necessary change might be to disable closure advanced (but simple should be fine, and as good as uglify)?

**Comment by juj** [comment]
Sure, I'll refactor this to do Closure simple.

**Comment by juj** [comment]
Updated this to use our own JS optimizer pass.

**Pull request merged**
