### PR TITLE
Use preventDefault() on more keyDown codes to prevent browser scrolling on arrow keys etc.

### PR DESCRIPTION
**Pull request by blitz-research**
This change prevents 'navigation' keys such as arrow keys and home/end etc from scrolling the browser page around while you're trying to play a game that's on a larger page. This issue only seems to affect Chrome, not Firefox. I haven't tried Edge or Safari but the fix should be benign either way.

One side effect of this change is that these keys will no longer produce unicode 'char' events, where-as currently 'space' at least does. Space is a weird one  - if you don't preventDefault it, it appears to scroll to bottom of document. I've added a special case workaround so thjat keydown for space does also generate a unicode char event, as it should.

Apart from space, the others such as arrow keys, home/end etc shouldn't produce unicode char events anyway IMO as they're not 'printable' keys/chars.

The original GLFW code is actually based on SDL, and I had a quick look at that and it probably suffers from the same problem and would benefit from the same fix, although I haven't attempted it as I'm not so comfortable with SDL as yet.

Bye!
Mark

### CODE REVIEW

**Comment by Daft-Freak** [comment]
The list of "always `preventDefault`-ed" keys for SDL2 is here: https://github.com/libsdl-org/SDL/blob/6e6e425e23eb38ed4e111b1f4ce83d7d86812585/src/video/emscripten/SDL_emscriptenevents.c#L587-L594.

It also `preventDefault`s everything if text input events are disabled. (Unless key events are disabled as well, then it does nothing)

**Comment by blitz-research** [comment]
I'll update the PR to add the F-keys to glfw and more nav-keys to SDL...

**Comment by blitz-research** [comment]
Ok, I tried this out but I'm a bit worried about losing F11 fullscreen as myapp (and therefore possibly others) depend on it to toggle fullscreen. I'ts not a big deal for me to this programmatically, but it may be for others so I don't consider this a minor change any more. I'll miss F12 for console too, but there's at least a menu option for that.
Personally I kind of like knowing that F11 is 'the standard' fullscreen toggle for browsers (a bit like 'alt-enter' on windows) and use it as a sort of 'panic button' quite often! But I am happy with whatever the plan is...just thought I'd bring this up before changing the PR.

**Comment by blitz-research** [comment]
@kripken OK, function keys added to the PR.

**Comment by blitz-research** [comment]
Hi, is this likely to be merged any time soon? Without it, 'windowed' glfw apps are kind of broken, or have to avoid using a bunch of useful keys.

If not, is there a way I can tweak EMSDK so it grabs the upstream/emscripten dir from my own fork of the 'emscricpten' repo that contains the relevant change, or is there some cheezy way to do this with links or something?

**Comment by sbc100** [comment]
There are a couple of ways to use your own emscripten with llvm+binaryn from emsdk:

1.  Checkout your version and put it in your PATH.  Create a `.emscripten` file in that directory that points to emsdk/upstream version of LLVM_ROOT and BINARYN_ROOT.  This is the best method is you plan on continuing to work on emscripten (i.e for emscripten devs)
2. You can do `./emsdk install emscripten-main-64bit` and use the `--override-repository` option.  e.g. `--override-repository emscripten-main@https://github.com/<fork>/emscripten/tree/<refspec>`.   I don't use that option so I can't vouch for how well it works.

**Comment by kripken** [comment]
About merging this, I'm ok with that if it matches the SDL2 behavior. But looks like this handles more things like pageup for example?

**Comment by blitz-research** [comment]
Yes it does, I might actually just maintain my own version because at the very least I like having space key in my game!

**Comment by kripken** [comment]
Makes sense. I think many projects probably end up doing that since it really depends on their needs.

I think it would be great to document this better, in particular, links to examples for how to customize this would be great if someone wants to open a PR. If your code is open source @blitz-research that could be a good thing to link to perhaps?

**Pull request closed without merging**
