### PR TITLE
Fix multitouch support - problem with leaking `isChanged` state between touch phases

### PR DESCRIPTION
**Pull request by trzecieu**
Current implementation of touch support uses JS's `Touch` instances of touching points to store `changed` flag. Which is problematic as those instances can recirculate. This PR makes sure that we clean old flags before handling new touches.

I was able to reproduce this scenario by:
* hooking onto all *touch events
* put one finger and start moving it (which adds one Touch instance).
* while first finger was still moving I taped quickly with another finger. 

While a logic might look kind of correct, as I'm still moving the first finger, but it doesn't follow separation which is quarantined by standard: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/changedTouches
That is, if I have a handler hooked into `touchstart` only touch points that actually have started should be placed in `changedTouched` list (or in case of Emscripten, I'd expect that only those are marked with `isChanged` flag) 

In current scenario it's possible that `isChanged` flag (carried by `[Touch].changed`) leaks from `touchmove` to either `touchstart` or `touchend`, which makes handling multi touch support much harder / impossible. 

----

For people struggling with that issue: It's possible to "patch" your current build with: 
```c++
const char* target = "#canvas";
const int useCapture = 1;

// Mitigation for: https://github.com/emscripten-core/emscripten/issues/8699
// It can be added in any time (after of before your target handlers)
// clang-format off
EM_ASM_({
    var targetName = UTF8ToString($0);
    var useCapture = $1;
    Module.touch_sanitizer = function(event) {
        var e = event || window.event;
        for (var i = 0; i < e.touches.length; i++) {
            e.touches[i].changed = false;
        }
    };
    var target = JSEvents.findEventTarget(targetName);
    if (target) {
        target.addEventListener("touchcancel", Module.touch_sanitizer, useCapture);
        target.addEventListener("touchstart", Module.touch_sanitizer, useCapture);
        target.addEventListener("touchmove", Module.touch_sanitizer, useCapture);
        target.addEventListener("touchend", Module.touch_sanitizer, useCapture);
    }
}, target, useCapture);
// clang-format on

```

Then `touch_sanitizer` will clean up old flags.

### CODE REVIEW

**Comment by trzecieu** [comment]
Hi, what I can do more to make it merged?

**Comment by sbc100** [comment]
You probably want to get approval from @juj who wrote this code.

**Comment by kripken** [comment]
Would be good if @juj can take a look, but this looks right to me.

Please merge in latest incoming, so the tests can pass.

**Comment by juj** [comment]
Thanks for the patch! This is really subtle - looks like browser reuses the object instances of the touches it reports in subsequent event handlers (which is nice for avoiding JS garbage). That then causes the `isChanged` fields leak, as code expected that field to be nonexistent on the touch objects, so that only flagging `isChanged=true` would be needed. This patch looks good, I'll land this in, CI failures look unrelated.

**Pull request merged**
