### PR TITLE
Support 4GB in sbrk/brk

### PR DESCRIPTION
**Pull request by kripken**
This is necessary for when VMs support 4GB.

This changes the actual comparisons to be unsigned. It also removes the check for allocating more then 2GB (i.e., if the signed value was negative). That is actually bad in the sense that the code will no longer catch a class of bugs for VMs with just 2GB (where trying to allocate 2GB was impossible anyhow) but I'm not sure we can do better (without some compile-time flag for "I expect 2GB vs 4GB", which seems best to avoid). We should be catching that case in the JS code for `enlargeMemory`, though, and we have a test.

Luckily, other code like the JS safe-heap checks just does JS `x + y` etc., without `| 0`, so it should just work. TODO, though, is the GL code, where I see a bunch of things (currently being refactored in #7842, so holding off on that).

### CODE REVIEW

**Comment by kripken** [comment]
We also need to change `enlargeMemory`, which hardcodes 2GB as a limit. If we change that tests will fail. Perhaps we do need a flag for 2/4GB?

**Comment by juj** [comment]
Great to finally see that 4GB allocations are becoming supported.

Currently we do geometric growth in `enlargeMemory()`, which has

```js
var LIMIT = 2147483648 - PAGE_MULTIPLE; // We can do one page short of 2GB as theoretical maximum.

...
    if (TOTAL_MEMORY <= 536870912) {
      TOTAL_MEMORY = alignUp(2 * TOTAL_MEMORY, PAGE_MULTIPLE); // Simple heuristic: double until 1GB...
    } else {
      // ..., but after that, add smaller increments towards 2GB, which we cannot reach
      TOTAL_MEMORY = Math.min(alignUp((3 * TOTAL_MEMORY + 2147483648) / 4, PAGE_MULTIPLE), LIMIT);
...
```

we should make sure that when bumping up the size, we will always try the 2GB-1 limit if possible. E.g. if previous heap size is, say, 1.5GB, and new requested heap size is still < 2GB, we should make sure that we don't casually overshoot with geometric growth to trying e.g. 2.2GB or some other size without having tried 2GB-1 first, but instead try the exact 2GB-1 size as a possible stop. That way we can utilize the maximum that 2GB browsers can support, but also expand past it on browsers that do support 4GB.

Don't we need to mass change all memory loads and stores to do `HEAP32[ptr>>>0]` instead of `HEAP32[ptr|0]`? This would affect all JS libraries that have direct heap accesses? asm.js probably  won't validate with `HEAP32[ptr>>>0]` so this might be a wasm-only thing?

Btw, afaik Chrome still has the bug that sometimes `new ArrayBuffer(very large number);` can directly aww-snap the page instead of throwing a JS exception that page could handle.

(Also reading back now, the heuristic above of doubling heap size until reaching 1GB feels extremely wasteful now. In practice getting heap sizes of 256MB or 512MB is hard in the wild, I think the geometric heuristic should be much more conservative. Perhaps we should even consider removing the geometric growth, and e.g. choose the desired heap size rounded up to next 64MB multiple, or next 4MB multiple if total heap size is smaller than 64MB, or similar - depending on how slow it is exactly to grow the heap. Jumping to double from 256MB -> 512MB or 512MB -> 1024MB feels like an high % chance of OOMing. Though this kind of strategy change could be done in completely another time)

**Comment by kripken** [comment]
> we should make sure that when bumping up the size, we will always try the 2GB-1 limit if possible. 

Good point, yeah.

> Don't we need to mass change all memory loads and stores to do HEAP8[ptr>>>0]

The ones in JS, yes. The ones in asm.js wouldn't validate, so probably this will only be useful for wasm.

Overall the more I think about it, after this discussion, there's probably quite a lot of small stuff. I think I'll wait on this until there's a VM to test against, so I'm not working blindly. And then I'll run the test suite when `GLOBAL_BASE=2GB`, so all pointers will be in the high range, to find bugs.

**Comment by kripken** [comment]
We definitely do still want 4GB support; main blocker is that no VM supports that yet, so it's not possible to test.

However this PR is no longer needed as sbrk/brk are now implemented in wasm, which doesn't have asm.js overflow issues.

**Pull request closed without merging**
