### PR TITLE
More ENVIRONMENT_MAY_BE_NODE ifdefs

### PR DESCRIPTION
**Pull request by VirtualTim**
Re-creating PR since I didn't notice we moved to master.

Should reduce code size a little, for non-NodeJS builds.

### CODE REVIEW

**Comment by Akaricchi** [comment]
Tip for the future: you can change the base branch by pressing the "edit" button right of the PR title
Screenshot_20200122_181703

**Comment by kripken** [comment]
This may need to get master merged in, as the diff is too big - it shows stuff from master in it.

Sometimes it's annoying to move PRs between branches, sorry about that. (This is the last time we'll change main branch though I'm pretty sure!) How I sometimes do it is to just give up on rebasing/merging/etc., get a text diff (by diffing the last good place in the original PR to the relevant commit before it), then just apply that on the target branch and open a PR with that. May be better ways though.

**Comment by Akaricchi** [comment]
> How I sometimes do it is to just give up on rebasing/merging/etc., get a text diff (by diffing the last good place in the original PR to the relevant commit before it), then just apply that on the target branch and open a PR with that. May be better ways though.

This is just rebasing done manually. In this case it should be enough to just run `git rebase -i master`, drop commit e41cecf933838d19f90f8097a07bf950da4d448c, then force-push the branch.

**Comment by kripken** [comment]
@Akaricchi does `rebase -i` still work if the other branch has been squashed (which happens here as we squash to master)? It always ends up with conflicts in my experience. But maybe I've done it wrong :smile:

**Comment by Akaricchi** [comment]
In this PR's case I'm not seeing any squashing involved, otherwise we'd see much more commits that shouldn't be there. But since `rebase -i` is interactive, you can simply tell it to drop the squashed commits.

If that's too much work, then you can instead re-create your branch on top of the new base and `git cherry-pick` the relevant commits from your other branch. This is closer to your manual approach, just instead of extracting the diffs by hand git does it for you.

**Comment by VirtualTim** [comment]
I doubt this is relevant, and even if it is Emscripten has probably changed a lot since then.

**Pull request closed without merging**
