### PR TITLE
Removed Harfbuzz Dependency from SDL2_ttf on Windows

### PR DESCRIPTION
**Pull request by vkaytsanov**
The removal of the dependency solves the problem with compiling SDL2 with SDL2_ttf on Windows

### CODE REVIEW

**Comment by sbc100** [comment]
While this fixes you immediate issue, I'm not sure its a solution we want to land.    We want emscripten to behave the same on all platforms, in general.

The long term fix is probably to remove out dependency on cmake and make when building harfbuzz since those tools are not necessarily available on all emsdk installations.

As a quick fix we could add `SDL_TTF_USE_HARFBUZZ` option (we could have this disabled by default 0 so users would have to opt into building SDL_TTF with harfbuzz).  @mehdisadeghi, you originally added the harfbuzz support, would you be OK making this opt-in?  (at least for now).

**Comment by sbc100** [comment]
Long term solutions:

1. Convert harfbuzz build away from cmake + make
2. Include `ninja` and `cmake` as part of emsdk and build with ninja (avoiding the need for mingw make to be installed on windows machines).

**Comment by mehdisadeghi** [comment]
@sbc100 of course it is fine to make it opt-in to solve the immediate problem. However, I'm a bit confused. Wasn't HarfBuzz already ported? Or this is a problem specific to my original PR?

**Comment by sbc100** [comment]
> @sbc100 of course it is fine to make it opt-in to solve the immediate problem. However, I'm a bit confused. Wasn't HarfBuzz already ported? Or this is a problem specific to my original PR?

HarfBuzz was already ported, but unlike the other ports it depends on cmake (and in the windows case, on mingw make).   We can't the harfbuzz build itself easily but we can make the default build of sdl2_ttf not depend on it I think.

**Comment by mehdisadeghi** [comment]
I'd personally make it opt-out instead of opt-in by adding the `SDL_TTF_USE_HARFBUZZ` option and set it to 1 by default. People who run into problems on Windows can disable it and people on Unix machines won't notice a change. Moreover, the build instructions remain the same everywhere except when explicitely changed by developers. 

FWIW, I just checked the SDL_ttf mercurial repository, apparently they have since moved to [GitHub](https://github.com/libsdl-org/SDL_ttf/). I did a quick search and there are some [open issues/requests regarding HarfBuzz](https://github.com/libsdl-org/SDL_ttf/issues?q=is%3Aissue+harfbuzz+) and its inclusion in future releases. One user [suggests](https://github.com/libsdl-org/SDL_ttf/issues/123) a straightforward meson build on Windows. Please have a look.  

Ultimately as maintainer you know better which option serves the project better and saves maintainers time most.

Thanks.

**Comment by sbc100** [comment]
> I'd personally make it opt-out instead of opt-in by adding the `SDL_TTF_USE_HARFBUZZ` option and set it to 1 by default. People who run into problems on Windows can disable it and people on Unix machines won't notice a change. Moreover, the build instructions remain the same everywhere except when explicitely changed by developers.
> 
> FWIW, I just checked the SDL_ttf mercurial repository, apparently they have since moved to [GitHub](https://github.com/libsdl-org/SDL_ttf/). I did a quick search and there are some [open issues/requests regarding HarfBuzz](https://github.com/libsdl-org/SDL_ttf/issues?q=is%3Aissue+harfbuzz+) and its inclusion in future releases. One user [suggests](https://github.com/libsdl-org/SDL_ttf/issues/123) a straightforward meson build on Windows. Please have a look.
> 
> Ultimately as maintainer you know better which option serves the project better and saves maintainers time most.
> 
> Thanks.

I think adding any extra requirements (be it meson or cmake) goes against the goals of emscripten where we want everything to work out of the box (without having to install extra third party stuff).   The harfbuzz build has from the very beginning violated this.. but it went mostly unnoticed until now :(

**Comment by ericoporto** [comment]
@sbc100 just a heads-up, Harfbuzz has releases that ship with the pytho (and perl?) code generation parts already run. Check the tar.xz package here: https://github.com/harfbuzz/harfbuzz/releases

From then you just build [harfbuzz.cc](https://github.com/harfbuzz/harfbuzz/blob/main/src/harfbuzz.cc) and it's done.

**Comment by mehdisadeghi** [comment]
FYI: SDL_ttf HarfBuzz support will be release as part of [2.0.18](https://github.com/libsdl-org/SDL_ttf/issues/123#issuecomment-1003466164) [release](https://github.com/libsdl-org/SDL_ttf/milestone/1).

**Comment by vkaytsanov** [comment]
Closing in this case.

**Pull request closed without merging**
