### PR TITLE
Remove a static allocation from Fetch JS code

### PR DESCRIPTION
**Pull request by kripken**
Helps https://github.com/WebAssembly/binaryen/issues/3043

### CODE REVIEW

**Comment by juj** [comment]
-1 for this and #12039  :( I think this is significantly worse direction in terms of code-gen. It regresses code size, but also carries a runtime branch á la style of static C function local initialization.

Is there some other way we could keep the original feature, it is very useful for this: eagerly doing the needed work once up front at startup is much better than lazily checking every time whether the needed thing was done yet.

**Comment by sbc100** [comment]
In the case of the allocation being on the JS side I agree this is not ideal and C-style globals would be better.  

In other places we have moved these static allocations into `.c` or `.s` files so that the the linker (wasm-ld) can include them.    Perhaps we can do that in this case too?  Although I'm not in this particular example if makes sense since fetching is already a very heavy operation, no?    Is it worth fixing in this particular case?

**Comment by sbc100** [comment]
Actually in this case it looks like maybe there is simple fix: #12049

**Comment by kripken** [comment]
@juj

The c++ exceptions fix was also a correctness fix (to avoid a possible race condition), so it's unavoidable I think.

I agree that things like this one could be better, as in #12049 , thanks @sbc100 !

In general I think it's ok to take a iny tstep back in some cases as in this PR. The benefits of getting rid of static allocations from JS are going to be worth it - once we get rid of all of them, we can remove `DYNAMICTOP_PTR` entirely from JS, for example, which I hope to land soon. That both simplifies the code and makes it smaller.

And, fundamentally these changes tend to make it easier to move code from JS to C, because they remove special JS magic (e.g. #12052 and #12055), so they are incremental steps towards further code size improvements.

**Pull request merged**
