### PR TITLE
Update mktime to match C expected behavior

### LINKED ISSUE #12241: mktime does not modify std::tm input
I think this is related to #2393

```
#include <ctime>
#include <iostream>
using namespace std;

int main() {
  tm t = { 0 };
  t.tm_sec = 212;
  t.tm_year = 119;
  t.tm_mday = 351;                     // January 351
  mktime(&t);
  printf("%.4d-%.2d-%.2dT%.2d:%.2d:%.2d Z\n", 1900 + t.tm_year, t.tm_mon + 1, t.tm_mday + 1, t.tm_hour, t.tm_min, t.tm_sec);
  return 0;
}

> 2019-01-352T00:00:212 Z
Expected output: 2019-12-18T00:03:32 Z
```
The above code functions in [g++.](https://tio.run/##bY/LTsMwEEX3/oqroqJUpGkcyqIN9ANYs0JIyHJMa1FPIj8WUdVvDzYghwVeXGmOZjxn5DCsj1JO040meQ6dwqP02qgDm4HunbdKmAMLTtMRJIxyg5AKznctY5o8jNBUrHBhgDfweMIFNa5tqitv3p2SkTW8yWRUwkbE@S4j04kxovsH3uK/t9ngWVAQdkw9ccp8Jtfi1q/SH4ONJh/FYlltu/Wyan7iJcU@B17faFGC7@oad7NJ@WvQU6S8/OMzl6c@5D5NZT7se7lVPlhC3bLrNH0B)
According to the C reference:
> If the conversion is successful, the time object is modified. All fields of time are updated to fit their proper ranges. time->tm_wday and time->tm_yday are recalculated using information available in other fields. 

This code works as expected in em++:
```
#include <ctime>
#include <iostream>
using namespace std;
int main() {
        tm t{0};
        t.tm_sec = 212;
        t.tm_mday = 351;
        t.tm_year = 119;

        time_t ms = mktime(&t);
        const tm lt = *localtime(&ms);
        printf("%.4d-%.2d-%.2dT%.2d:%.2d:%.2d Z\n",
                        1900 + lt.tm_year,
                        lt.tm_mon + 1,
                        lt.tm_mday + 1,
                        lt.tm_hour,
                        lt.tm_min,
                        lt.tm_sec);
        return 0;
}

> 2019-12-18T00:03:32 Z
```

Version `emcc (Emscripten gcc/clang-like replacement) 1.39.18 (a3beeb0d6c9825bd1757d03677e817d819949a77)`
(I don't know if this has been fixed recently, changelog has no entries for mktime)

### PR DESCRIPTION
**Pull request by jkae**
Resolves #12241

### CODE REVIEW

**Comment by jkae** [comment]
I'm not super positive how to create a test (or where to create the test), I'll update with advice & add myself to AUTHORS in the final commit.

**Comment by sbc100** [comment]
The test for this function is `tests/core/test_time.cpp` which you can run using `./tests/runner.py wasm2.test_time`

**Comment by sbc100** [comment]
Oh, and the expected output lives in `tests/core/test_time.out.`

**Comment by jkae** [comment]
I can't see why circleci is failing but the tests seem to pass locally... Going to try this on another machine or something.

**Review by kripken — APPROVED** [review]
This looks good to me, thanks @jkae !

For the test failures on CI, perhaps merging in latest master to here would fix them?

**Comment by jkae** [comment]
I've pulled Master in 👍 
A problem I'm having running the tests myself is that I can't seem to get the correct binaryen version through emsdk. Though the output, when I compile the test file & execute with node, matches what's in the test `.out` so I expected circleci to pass 🤷 

"Allow Edits by Maintainers" is checked tho.

**Comment by kripken** [comment]
The failure happens in optimized modes. Maybe it will fail for you locally if you build with one of `-O1, -O2, -O3`?

If not, you can run the test suite locally, see https://emscripten.org/docs/getting_started/test-suite.html#debugging-test-failures - let me know if you have any issues with that.

**Comment by jkae** [comment]
Updating everything, I cannot run tests because I don't have acorn. 🤷 
Just verifying the output for different optimization modes, I get the following values for `tm2` vs `tm_local`:
```
No optimization
40 56 8 7 2 1 65
40 56 8 7 2 1 65

O1+
40 56 8 7 2 1 65
24 28 2 30 0 5 29
```
Checking the `time_t` value returned by `mktime(&tm2)`, I get something interesting:
```
No optimization
510595000

O1+
3761049400
```
Which suggests to me there's a separate bug when converting to a timestamp, though I'm not sure where it is.

**Comment by jkae** [comment]
@kripken I could remove the one test and try to work on another patch / submit an issue, or I could try to fix it in this PR as well.

**Comment by kripken** [comment]
@jkae 

I think it would be good to understand why the test fails here. If you get stuck let me know and I can take a look too.

Did you figure out the acorn issue btw? Maybe you just need to do `npm install`?

**Comment by jkae** [comment]
It turns out I was just being dumb. For some reason (through another project) I had assumed structs auto-init to 0 no matter the em++ compile mode. Turns out that assumption was super wrong and was probably just a coincidence.

**Comment by jkae** [comment]
Alright, @kripken the tests pass locally now so I don't know why they're failing on CircleCI. I can't check the details because I'm not about to give it full access to my orgs but for some of the failures here's what I'm getting:

```
$ python runner.py wasm2.test_time
runner:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
shared:INFO: (Emscripten: config changed, clearing cache)
shared:INFO: (Emscripten: Running sanity checks)
test_time (test_core.wasm2) ... cache:INFO: generating system library: libc.a... (this will be cached in "D:\git\emsdk\upstream\emscripten\cache\wasm\libc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "D:\git\emsdk\upstream\emscripten\cache\wasm\libcompiler_rt.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++-noexcept.a... (this will be cached in "D:\git\emsdk\upstream\emscripten\cache\wasm\libc++-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++abi-noexcept.a... (this will be cached in "D:\git\emsdk\upstream\emscripten\cache\wasm\libc++abi-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libdlmalloc.a... (this will be cached in "D:\git\emsdk\upstream\emscripten\cache\wasm\libdlmalloc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libpthread_stub.a... (this will be cached in "D:\git\emsdk\upstream\emscripten\cache\wasm\libpthread_stub.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc_rt_wasm.a... (this will be cached in "D:\git\emsdk\upstream\emscripten\cache\wasm\libc_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libsockets.a... (this will be cached in "D:\git\emsdk\upstream\emscripten\cache\wasm\libsockets.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "D:\git\emsdk\upstream\emscripten\cache\wasm\generated_struct_info.json" for subsequent builds)
cache:INFO:  - ok
ok

----------------------------------------------------------------------
Ran 1 test in 95.916s

OK
WARNING: no 'numpy' module, HyBi protocol will be slower
WARNING: no 'resource' module, daemonizing is disabled
Test suites:
['test_core']
Running test_core: (1 tests)
(checking sanity from test runner)
extra tz test: EST+05EDT
env_modify: {'TZ': 'EST+05EDT'}
extra tz test: UTC+0
env_modify: {'TZ': 'UTC+0'}

$ python runner.py wasm0.test_time
runner:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
shared:INFO: (Emscripten: Running sanity checks)
test_time (test_core.wasm0) ... ok

----------------------------------------------------------------------
Ran 1 test in 12.792s

OK
WARNING: no 'numpy' module, HyBi protocol will be slower
WARNING: no 'resource' module, daemonizing is disabled
Test suites:
['test_core']
Running test_core: (1 tests)
(checking sanity from test runner)
extra tz test: EST+05EDT
env_modify: {'TZ': 'EST+05EDT'}
extra tz test: UTC+0
env_modify: {'TZ': 'UTC+0'}

$ python runner.py wasm3.test_time
runner:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
shared:INFO: (Emscripten: Running sanity checks)
test_time (test_core.wasm3) ... ok

----------------------------------------------------------------------
Ran 1 test in 17.582s

OK
WARNING: no 'numpy' module, HyBi protocol will be slower
WARNING: no 'resource' module, daemonizing is disabled
Test suites:
['test_core']
Running test_core: (1 tests)
(checking sanity from test runner)
extra tz test: EST+05EDT
env_modify: {'TZ': 'EST+05EDT'}
extra tz test: UTC+0
env_modify: {'TZ': 'UTC+0'}
```

**Comment by kripken** [comment]
@jkae I think those are because this PR is off of an older version of trunk. Merging in latest upstream should fix it.

**Comment by jkae** [comment]
Yeah, that did it. Solid 👍

**Comment by kripken** [comment]
Perfect, thanks @jkae !

**Pull request merged**
