### PR TITLE
Better message when a side module needs exceptions

### PR DESCRIPTION
**Pull request by kripken**
The main module needs to be built with exceptions support for a side module to use it, both for system libs and for the current JS support. This informs users they need to do that if a side module throws and the main wasn't built properly to support that.

Helps #9691

Btw @sbc100 I noticed while writing this patch that `EXPORT_ALL` is needed for main module to add the JS glue code to where it can be imported from side modules. I was surprised we don't enable that flag by default, maybe I'm missing something?

### CODE REVIEW

**Comment by kripken** [comment]
review ping @sbc100

**Comment by kripken** [comment]
Yeah, not sure there's a shorter way. We don't have many such tests in other.

@sbc100 did you see my question in the PR title about EXPORT_ALL?

**Comment by sbc100** [comment]
I wasn't aware of any differences between EXPORT_ALL with llvm backend vs fastcomp?  or are you seeing the same issue with fastcomp?

**Comment by kripken** [comment]
It doesn't look related to the backend, same on fastcomp.

I investigated a bit more and opened https://github.com/emscripten-core/emscripten/issues/9793

**Pull request merged**
