### PR TITLE
Docs proofreading. NFC

### PR DESCRIPTION
**Pull request by RequireSun**

### CODE REVIEW

**Comment by sbc100** [comment]
Is this ready to submit now?

**Comment by RequireSun** [comment]
yes, please

**Comment by RequireSun** [comment]
i'm new to contribute in open source project, how can i make a pr looks like `ready to merge`? or should i use WIP in the unready project?

**Comment by sbc100** [comment]
We don't have a standard way to signal that (at least not that I know if)

**Pull request merged**
