### PR TITLE
CI: Run chrome tests using the new headless mode. NFC

### PR DESCRIPTION
**Pull request by sbc100**
See https://developer.chrome.com/articles/new-headless/

### CODE REVIEW

**Review by kripken — APPROVED** [review]
lgtm if it works

**Comment by kripken** [comment]
Looks like chrome tests hang here, but actually I notice they hang on `main` as well as of a few commits, for no obvious reason. Nothing that landed looks relevant. Perhaps a chrome or CircleCI update? @sbc100 were the errors on `main` why you opened this branch perhaps, or coincidence?

**Comment by sbc100** [comment]
I think it is related to the new headless.    I'll take another look when I get some time.

**Comment by sbc100** [comment]
Closing since this already landed in #20069

**Pull request closed without merging**
