### PR TITLE
[tsgen] Handle different get/set types for value_objects too.

### PR DESCRIPTION
**Pull request by brendandahl**
Mentioned in #22387

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by sbc100** [comment]
I wonder if we should start writing tests that actually use these `.ts` definitions to verify they are correct and working?

**Comment by brendandahl** [comment]
> I wonder if we should start writing tests that actually use these `.ts` definitions to verify they are correct and working?

We do at least [run them through](https://github.com/emscripten-core/emscripten/blob/9a1a67a48668ba70bf58986ed2b2417e43929146/test/test_other.py#L3355-L3356) the `tsc` compiler to ensure they compile.

**Comment by sbc100** [comment]
> > I wonder if we should start writing tests that actually use these `.ts` definitions to verify they are correct and working?
> 
> We do at least [run them through](https://github.com/emscripten-core/emscripten/blob/9a1a67a48668ba70bf58986ed2b2417e43929146/test/test_other.py#L3355-L3356) the `tsc` compiler to ensure they compile.

Right, but it would be pretty cool to actually wrong some typescript to use the module via the generated interface maybe?

**Comment by sbc100** [comment]
> > > I wonder if we should start writing tests that actually use these `.ts` definitions to verify they are correct and working?
> > 
> > 
> > We do at least [run them through](https://github.com/emscripten-core/emscripten/blob/9a1a67a48668ba70bf58986ed2b2417e43929146/test/test_other.py#L3355-L3356) the `tsc` compiler to ensure they compile.
> 
> Right, but it would be pretty cool to actually wrong some typescript to use the module via the generated interface maybe?

Maybe we should even start wriing embind tests in TypeScript instead of JS?

**Comment by brendandahl** [comment]
> > > > I wonder if we should start writing tests that actually use these `.ts` definitions to verify they are correct and working?
> > > 
> > > 
> > > We do at least [run them through](https://github.com/emscripten-core/emscripten/blob/9a1a67a48668ba70bf58986ed2b2417e43929146/test/test_other.py#L3355-L3356) the `tsc` compiler to ensure they compile.
> > 
> > 
> > Right, but it would be pretty cool to actually wrong some typescript to use the module via the generated interface maybe?
> 
> Maybe we should even start wriing embind tests in TypeScript instead of JS?

Yeah, I don't think it would be too hard to write some TS tests. What we also probably want is a way to make sure the TS definitions that we generate match what the JS actually provides at runtime. I'm not aware of a great way to do that, beside maybe compiling all the JS with the TS definitions.

**Comment by sbc100** [comment]
> > > > > I wonder if we should start writing tests that actually use these `.ts` definitions to verify they are correct and working?
> > > > 
> > > > 
> > > > We do at least [run them through](https://github.com/emscripten-core/emscripten/blob/9a1a67a48668ba70bf58986ed2b2417e43929146/test/test_other.py#L3355-L3356) the `tsc` compiler to ensure they compile.
> > > 
> > > 
> > > Right, but it would be pretty cool to actually wrong some typescript to use the module via the generated interface maybe?
> > 
> > 
> > Maybe we should even start wriing embind tests in TypeScript instead of JS?
> 
> Yeah, I don't think it would be too hard to write some TS tests. What we also probably want is a way to make sure the TS definitions that we generate match what the JS actually provides at runtime. I'm not aware of a great way to do that, beside maybe compiling all the JS with the TS definitions.

Won't manually exercising the API from the outside do this?   I kind of like that idea of writing `.ts` tests that run against the ts defintions that the actually run the underlying JS that in turn runs that actual wasm.  So many layers!

**Comment by brendandahl** [comment]
> > > > > > I wonder if we should start writing tests that actually use these `.ts` definitions to verify they are correct and working?
> > > > > 
> > > > > 
> > > > > We do at least [run them through](https://github.com/emscripten-core/emscripten/blob/9a1a67a48668ba70bf58986ed2b2417e43929146/test/test_other.py#L3355-L3356) the `tsc` compiler to ensure they compile.
> > > > 
> > > > 
> > > > Right, but it would be pretty cool to actually wrong some typescript to use the module via the generated interface maybe?
> > > 
> > > 
> > > Maybe we should even start wriing embind tests in TypeScript instead of JS?
> > 
> > 
> > Yeah, I don't think it would be too hard to write some TS tests. What we also probably want is a way to make sure the TS definitions that we generate match what the JS actually provides at runtime. I'm not aware of a great way to do that, beside maybe compiling all the JS with the TS definitions.
> 
> Won't manually exercising the API from the outside do this? I kind of like that idea of writing `.ts` tests that run against the ts defintions that the actually run the underlying JS that in turn runs that actual wasm. So many layers!

Yeah, that should work. I was thinking of trying something a little more automated that would auto check the "shape" of JS objects against their TS definition at runtime.

**Comment by brendandahl** [comment]
Filed #22444

**Pull request merged**
