### PR TITLE
fix for binding member functions from base classes

### PR DESCRIPTION
**Pull request by Boris-Rasin**
Fix for the following case, which today produces error:
error: no matching member function for call to 'function'
emscripten/bind.h:1282:48: note: candidate template ignored: could not match 'B' against 'A'

```cpp
#include <emscripten/bind.h>

class A
{
protected:
	void func();
};

class B : public A
{
public:
	using A::func;
};

EMSCRIPTEN_BINDINGS(B)
{
	emscripten::class_<B>("B")
		.function("func", &B::func)
	;
}
```

### CODE REVIEW

**Comment by sbc100** [comment]
Can you add a test to `test_embind`?

**Comment by kripken** [comment]
cc @chadaustin @brion

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

Re-opening and re-targeting to master.

**Comment by jgravelle-google** [comment]
Tried to fix the conflicts in the web editor, it's not completely trivial though so @Boris-Rasin please take a look

**Comment by Boris-Rasin** [comment]
This problem no longer exists, it appears to have been fixed by some other commit since this request was submitted.

**Pull request closed without merging**
