### PR TITLE
[test] Cleanup gcc pthread operations tests

### PR DESCRIPTION
**Pull request by sbc100**
- Tabs to spaces
- And some print status

### CODE REVIEW

**Comment by sbc100** [comment]
Because I did a bunch of formatting as well as re-name git doesn't do a good job of showing what actually changed.  If you would prefer I can split this into 2 PRs.  The first a pure rename, and the second the formatting changes.

**Comment by sbc100** [comment]
I split into 2 commits so git should show the changes better now.

**Review by kripken — APPROVED** [review]
Thanks for the separate commits, much easier to read that way!

**Comment by sbc100** [comment]
I think I will land this manually rather then squashing, so that both commits are preserved.

**Comment by kripken** [comment]
Squashing is ok here, I think. In the rare event we end up bisecting to this, the original commits are in the PR. But, either way.

**Comment by sbc100** [comment]
I landed them separately.

**Pull request merged**
