### PR TITLE
Error on relative --cache arg.

### PR DESCRIPTION
**Pull request by thomasballinger**
resolves https://github.com/emscripten-core/emscripten/issues/14184

### CODE REVIEW

**Comment by sbc100** [comment]
I guess we should add a test.  Should be easy enough to add to `test_other.py` (or maybe `test_sanity.py` since the other tests for EM_CACHE are there).

Should we do this for all settings in config.py that take paths?  e.g. Does it ever make sense to use a relative LLVM_ROOT?  I guess it could work?

Finally, can I ask why you are specifying `EM_CACHE` / `--cache` ?  I was kind of hoping there were no more valid use cases for doing that.

**Comment by sbc100** [comment]
Actually I think maybe we should instead fix the bug in `copytree_exist_ok` which seems to just be broken for relative paths (since it does `chdir`)

**Comment by sbc100** [comment]
> Actually I think maybe we should instead fix the bug in `copytree_exist_ok` which seems to just be broken for relative paths (since it does `chdir`)

I was curious as to why this didn't just work and ended up fixing the bug: https://github.com/emscripten-core/emscripten/pull/14209/

Using a relative path is still bad... but it will at least work now.

**Comment by thomasballinger** [comment]
I was using --cache for CI, in my case Netlify, where it was easy to specify a directory to preserve between runs. I think by writing my own emsdk build plugin I wouldn't have needed this, it just seemed like the simplest way to specify what to cache.

**Comment by sbc100** [comment]
> I was using --cache for CI, in my case Netlify, where it was easy to specify a directory to preserve between runs. I think by writing my own emsdk build plugin I wouldn't have needed this, it just seemed like the simplest way to specify what to cache.

Can you explain a little more?  Why wouldn't you want to preserve the entire emsdk directory?  Or the entire emscripten directory between builds?  Or if you really want to preserve just the cache why not specify emscripten's default cache as the directory to preserve (`emsdk/upstream/emscripten/cache`) and avoid needing to customize it?  

I don't know anything about Netlify.. how do you use emsdk there?

**Comment by thomasballinger** [comment]
> Why wouldn't you want to preserve the entire emsdk directory?

It sounds like that's what I should have done, I just saw the word "cache" and thought I'd cache that.

Netlify is a hosting provider primarily for frontend-only sites, I was using them to create "deploy previews" (per-commit deploys at unique urls) for a project that uses emscripten.

The naive way to use emscripten with Netlify is [a build script which installs it fresh each time](https://github.com/bmeurer/emscripten-dbg-stories/blob/main/build.sh), and I wasn't doing much fancier than that; I was installing fresh every time, then wanted to start caching. When I get this working again I will write a reusable plugin that takes an emsdk version as a cache key and caches the whole emsdk folder.

**Comment by sbc100** [comment]
> > Why wouldn't you want to preserve the entire emsdk directory?
> 
> It sounds like that's what I should have done, I just saw the word "cache" and thought I'd cache that.
> 
> Netlify is a hosting provider primarily for frontend-only sites, I was using them to create "deploy previews" (per-commit deploys at unique urls) for a project that uses emscripten.
> 
> The naive way to use emscripten with Netlify is [a build script which installs it fresh each time](https://github.com/bmeurer/emscripten-dbg-stories/blob/main/build.sh), and I wasn't doing much fancier than that; I was installing fresh every time, then wanted to start caching. When I get this working again I will write a reusable plugin that takes an emsdk version as a cache key and caches the whole emsdk folder.

Sounds good.

A couple of things to bear in mind.

1) The emsdk comes pre-packaged with a largely pre-populated cache, so for most uses cases there is no need for an additional layer of caching.
2) Re-using object files and libraries (e.g. the emscripten cache) doesn't generally work between emsdk versions.. in fact emscripten will clear out the cache completely if it sees a cache that was created with a different version.  So you need to be aware of this and re-generated your cache each time you update the version emsdk you are using (that probably also rules out using `latest` I guess).

**Pull request closed without merging**
