### PR TITLE
Streamline WebGL context creation

### PR DESCRIPTION
**Pull request by juj**
Streamline WebGL context creation: drop magic concept of "default" WebGL context version, and simplify initialization flow. Optimizes minimal WebGL demo by -374 bytes (-6.68%)

### CODE REVIEW

**Comment by juj** [comment]
SDL2 related tests fail here on Chrome, although I am unable to reproduce the failures locally. Running `browser.test_sdl2*` on this passes for me on Windows.

**Comment by kripken** [comment]
If the tests only fail on CI, I've used this (from runner.py) to debug things, it gets useful logging from browser errors,
```
          To get logging to the console from browser tests, add this to
          print/printErr/the exception handler in src/shell.html:

            var xhr = new XMLHttpRequest();
            xhr.open('GET', encodeURI('http://localhost:8888?stdout=' + text));
            xhr.send();
```

**Comment by kripken** [comment]
One guess would be, chrome doesn't have full GL on our CI, so perhaps the change in this PR makes it create a GL context or a different type of one than before? To debug it, can locally see exactly what params end up being send on context creation, perhaps.

**Comment by juj** [comment]
Debugged to verify that the WebGL context attributes that are passed to `.getContext()` function are identical with this PR and in incoming, i.e. they are

```
Object { alpha: false, depth: true, stencil: false, antialias: false, majorVersion: 1, minorVersion: 0 }
```

Before this PR, context initialization would read

```js
createContext:function (canvas, webGLContextAttributes) {
  if (typeof webGLContextAttributes.majorVersion === 'undefined' && typeof webGLContextAttributes.minorVersion === 'undefined') {
    webGLContextAttributes.majorVersion = 1;
    webGLContextAttributes.minorVersion = 0;
  }

  var ctx;
  var errorInfo = '?';
  function onContextCreationError(event) {
    errorInfo = event.statusMessage || errorInfo;
  }
  try {
    canvas.addEventListener('webglcontextcreationerror', onContextCreationError, false);
    try {
      if (webGLContextAttributes.majorVersion == 1 && webGLContextAttributes.minorVersion == 0) {
        ctx = canvas.getContext("webgl", webGLContextAttributes) || canvas.getContext("experimental-webgl", webGLContextAttributes);
      } else {
        throw 'Unsupported WebGL context version ' + webGLContextAttributes.majorVersion + '.' + webGLContextAttributes.minorVersion + '!'
      }
    } finally {
      canvas.removeEventListener('webglcontextcreationerror', onContextCreationError, false);
    }
    if (!ctx) throw ':(';
  } catch (e) {
    return 0;
  }

  if (!ctx) return 0;
  var context = GL.registerContext(ctx, webGLContextAttributes);
  return context;
}
```

and after this PR, it reads

```js
createContext:function (canvas, webGLContextAttributes) {
  var ctx = canvas.getContext("webgl", webGLContextAttributes) || canvas.getContext("experimental-webgl", webGLContextAttributes);
  return ctx && GL.registerContext(ctx, webGLContextAttributes);
}
```

The only difference that there exists is that the code no longer registers the `'webglcontextcreationerror'` listener.

Looking at the test suite, it seems that all SDL 1 tests have been marked to require graphics hardware, and some random SDL2 tests, but not the ones that currently fail. Updated this PR to mark those tests to require graphics hardware as well.

**Comment by juj** [comment]
Ok, this looks green now. I don't know why the SDL2 tests would have been passing in the Chrome CI before since they do use WebGL, and at the same time the corresponding SDL1 tests were disabled as requiring graphics hardware. Updated the SDL2 tests to also disable as requiring graphics hardware.

**Pull request merged**
