### PR TITLE
Temporarily set -Wno-pointer-sign for zlib build

### PR DESCRIPTION
**Pull request by dschuff**
zlib's configure script assumes that test compiles failed if there is any output on stderr (rather than being based on exit status). Sometimes emscripten prints "building libc" or similar if it needs to build a library. This causes flaky failures in running the tests. See #16908 for details.
This PR works around the problem by disabling the warning, but doesn't fix the underlying problem.

### CODE REVIEW

**Review by sbc100 — COMMENTED** [review]
I'd like to dig a little more into exactly how the bots are failing and what the best solution is.

Perhaps default to cmake the temporarily disable the explicitly `_autoconf` version of this test for now?

**Comment by kripken** [comment]
> Sometimes emscripten prints "building libc" or similar if it needs to build a library.

On CI here we [pre-build the libraries](https://github.com/emscripten-core/emscripten/blob/3c1bd9565d6a02d2b513b2df1059383c8ff73f4e/.circleci/config.yml#L100) to speed up builds. Maybe adding `embuilder.py build MINIMAL` (not sure we need `ALL`) would be enough to fix this?

**Comment by dschuff** [comment]
We also pre-build the libraries on chromium CI (https://chromium.googlesource.com/emscripten-releases/+/refs/heads/main/src/build.py#1071). Maybe the difference is that we use `ALL` on github CI and that's actually needed?

**Comment by sbc100** [comment]
I think its worth getting to bottom of the actual cause.. emcc is printing something.. but we can't tell what without adding more debugging,.

**Comment by dschuff** [comment]
OK, For now I disabled the warning, and the tests still run.

**Review by sbc100 — APPROVED** [review]

**Pull request merged**
