### PR TITLE
Implement rawPrint and async input in browsers (requires PROXY_TO_PTHREAD)

### PR DESCRIPTION
**Pull request by eclecticdave**
The main goal of this PR is to improve how stdio works when reading and writing to the tty, so it behaves more like the way native stdio programs behave.  The main changes are to allow for stdin input in browsers to work with an async keydown event handler rather than relying on 'prompt'. However smaller changes have been made for the benefit of Node and Spidermonkey shell.

* Implement rawPrint and rawPrintErr (see Issue #4366)

These methods print to stdout and stderr without requiring strings to be terminated with newlines.  They have been added to the Module object for Node and to shell[_minimal].html for browsers.  Unfortunately spidermonkey has no equivalent of putstr that prints to stderr so only rawPrint is implemented there.

In addition tty.read on Node and SpiderMonkey has been modified to return when a whole line has been entered, rather than waiting for EOF.

* Implement support for async input in browsers when compiled
  with USE_PTHREADS and PROXY_TO_PTHREAD.  Worker will sit in
  'wait' state until a whole line is read using a keydown event handler

On browsers things are more interesting ... currently the code uses 'prompt' to capture input as this is the only synchronous method available.  This is still the case for single-threaded builds, but if we take advantage of USE_PTHREADS and PROXY_TO_PTHREAD we can do better.

Currently when a proxied program does a read, the thread goes into 'wait' state and the syscall is proxied back to the main thread.  This captures the input using 'prompt' and then wakes the thread.

In order to allow an async method to be used to capture input, such as a keydown handler, some changes need to be made.  Accordingly a 'get_char' method is added to the Module object which is called by the tty.get_char function.  This method returns 'undefined' when there no input in its buffer, which gets translated into an EAGAIN error code.  This is then intercepted in the pthreads code and causes function emscripten_main_thread_process_queued_calls to return prematurely, leaving the read syscall on the queue and the thread still in wait state.  A simple keydown handler is also implemented, which is then left to read keystrokes as needed until 'Enter' is pressed, at which point emscripten_main_thread_process_queued_calls is called again to allow processing to continue.

For testing I've added test_stdio2 which is a modified version of test_stdio.  For node and spidermonkey this will run as part of the 'others' suite.  I haven't added this to the browser suite as it is necessarily an interactive test, but it can be run by compiling as follows:

emcc -o test_stdin2.html test_stdin2.c -g3 -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1 -s NO_EXIT_RUNTIME=0

Then run a local webserver (e.g. python -m SimpleHTTPServer 8000) and open localhost:8000/test_stdin2.html in the browser.

Incidentally, note the addition of NO_EXIT_RUNTIME=0.  I've noticed that stdio calls in the browser just seem to return error code 9 (EBADF) without this on the current incoming branch, when USE_PTHREADS and PROXY_TO_PTHREAD are used.  Is this expected behaviour for some reason or does this need investigating further?

### CODE REVIEW

**Comment by kripken** [comment]
Interesting work, but I'm not sure I understand all the pieces. First, could the pthreads stuff be in a separate PR from the general stuff (rawPrint etc.)? Or are those mutually dependent?

Also, this looks like it adds a bunch of complexity, and I don't fully understand the motivation. Is it just to get around `prompt()` being synchronous on the web? We do have existing ways to mitigate that, including the emterpreter, how do this PR's results compare to that approach?

> Incidentally, note the addition of NO_EXIT_RUNTIME=0. I've noticed that stdio calls in the browser just seem to return error code 9 (EBADF) without this on the current incoming branch, when USE_PTHREADS and PROXY_TO_PTHREAD are used. Is this expected behaviour for some reason or does this need investigating further?

That sounds very bad, but also surprising we didn't notice it in our tests. Odd. Do you have a small testcase showing the issue?

**Comment by juj** [comment]
This is definitely what we want, but let me ponder on this a bit, I think this has an issue of head-of-line blocking when it returns from do_call without processing it?

I have an implementation of synchronous stdin for ASMFS in another tree, I'll get that up as a PR soon so we can look at if that would extend to MEMFS as well. Although I was hoping that we wouldn't care about synchronous stdin for MEMFS since it has really poor performance in multithreaded apps anyways, and ASMFS fixes that. Does your use case care about MEMFS specifically, or would this be enough for ASMFS?

**Comment by eclecticdave** [comment]
@kripken - The rawPrint bits are independent to pthreads - I've included them in the same PR mostly because printing without linefeeds sort of goes together with prompting for input.  I can split it up if you want?

The rest is about replacing 'prompt', or more generally providing a terminal like experience in the browser, with stdio programs working the same way as native programs as much as possible. Also ideally I want this to work without the programs needing significant changes.  I'm not familiar with emterpreter but from the docs it seems more effort would required to analyse and port each program to get it to work well without a performance hit?

My long term goal is to be able to port 'bash' and other terminal programs.  I realise that's a fairly chunky piece of work, and there are a number of other missing pieces to make that possible, I'm just taking baby steps towards it here.

My 'test_stdio2' should be a fairly simple test case for the EBADF issue - just compile for the browser as described above, but with NO_EXIT_RUNTIME=1.  I'll see if I can track down the cause of this when I've fixed the last two test failures (I think I've got these, just running the test suite to make sure I haven't broken something else...).  My suspicion is the stdout/stderr/stdin streams are not being initialised correctly.

@juj - I don't care about MEMFS as such - this would be a poor choice for any realistic implementation of bash in any case as doing anything useful would need numerous other programs and files available for it to execute/access. I think ASMFS is definitely the way to go.

You're right - my changes introduce a potential issue with blocking the queue until get_char calls emscripten_main_thread_process_queued_calls.  This is OK as long as there's only one worker sitting waiting for input, but if you're running a multi-threaded process that wants to proxy something else to the main thread then that's a problem.  I did consider this - ideally the main thread needs to be able to work on multiple items at the same time, but that seems as though it would be tricky to get right.  However as 'prompt' also blocks the main thread, what I've done is, I think, no worse than the current behaviour in this respect.

**Comment by kripken** [comment]
I see, yeah, running bash etc. is definitely interesting to work towards.

Separate PRs as much as possible would be very helpful, I think. Looks like @juj already understands what's going on here, but to me the details are still to complicated, and part of that is I'm not sure what part is pthreads related and what isn't.

**Comment by eclecticdave** [comment]
Hi @kripken.

No problem, I've split out rawPrint and rawPrintErr implementation, along with the small change to tty.read into PR #6080.  Not sure whether to create a PR for the rest just yet as it makes more sense to build it on top of rawPrint - if for no other reason than it allows me to reuse the same test - so maybe it would be best to work through them one at a time?

**Pull request closed without merging**
