### PR TITLE
Rapidjson port

### PR DESCRIPTION
**Pull request by gabrielcuvillier**
Hi,

Here is a small emscripten-port for the RapidJSON library, which is a header-only toolkit for JSON data in C++. It is used by a couple of existing C++ projects. While for sure people could use the Javascript JSON.parse API for that, having to rely on EM_ASM to manipulate JSON is not convenient from C++.

I've included a sample test that will build some JSON data from C++ using RapidJSON library, serialize it to a string, and then let Javascript JSON.parse API to check and load that string into a Javascript object, convert the object back to JSON string, and be sure both string matches in the end.

The port uses directly the releases from original Rapidjson github repository. No need to create a new emscripten-port subproject.

### CODE REVIEW

**Comment by sbc100** [comment]
I'm not sure why we would want to add this directly to emscripten?  Isn't it easy enough to just download and use without being part of the upstream emscripten project?

**Comment by gabrielcuvillier** [comment]
I agree this is might sound questionable at a first glance, but here's my arguments for its inclusion:

While it is OK to copy/paste the RapidJSON header files directly in a project (that's 600kb in 35 header files though, so it is not just a tiny lib), I do think C++ projects prefer to use the "cmake way" to find 3rd party dependencies (find_package(...) stuff) for anything but non trivial single-header libraries. At least, this is what I observed on the recent projects I have been working on. 

As the find_package paradigm does not works well on emscripten (where to find the sysroot ? see #7633 and #9353), providing "emscripten ports" looks like to be an alternative for libraries that could be usefull on the Web (such as manipulating JSON from C++).

... and pretty much, that's it for the arguments :)

Anyway, feel free to reject the PR if I this does not make enough sense, of course. On my side, I do have some workarounds to find the lib through find_package (I just don't want to copy them directly in my project).

**Comment by sbc100** [comment]
I think my preference would be to invest in making "find_package()" and autoconf work better with emscripten.  I've actually been making progress in that direction recently.

**Comment by gabrielcuvillier** [comment]
Ok, that's fine. For sure, the work to have better find_package() support will make the need for various "emscripten ports" much less important

**Pull request closed without merging**
