### PR TITLE
Bump binaryen version to 97

### PR DESCRIPTION
**Pull request by attilaolah**
Version 97 has just been released (https://github.com/WebAssembly/binaryen/pull/3140).

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]
Can you at yourself to AUTHORS?

**Comment by attilaolah** [comment]
> Can you at yourself to AUTHORS?

Done. (I put it in a separate commit in order to see CI status on the previous commit, you're welcome to squash them when merging.)

I actually had some issues with the previous version of binaryen (due to `--minimize-wasm-changes` flag), but apparently that isn't passed any more since https://github.com/emscripten-core/emscripten/pull/12090 so I'm not sure what was going on there…

In any case, I tried with binaryen 97 and compilation seems to work.

**Comment by sbc100** [comment]
Is this still a draft or is it ready to submit?

**Comment by attilaolah** [comment]
Some browser checks are failing, otherwise this should be good to go.

**Pull request merged**
