### PR TITLE
Remove tools/maint from list of directories excluded from install

### PR DESCRIPTION
**Pull request by dschuff**
This is needed after #20586 because e.g. gen_struct_info.py is used to generate system libraries, which can be done at runtime.

### CODE REVIEW

**Comment by dschuff** [comment]
The other option would be to move some/all of these tools back out of maint/ if they are actually needed by emcc at runtime rather than only offline?

**Comment by sbc100** [comment]
I think I'd rather figure out how/why gen_struct_info might be needed in an installed version of emscripten.  Can you point to the failure you are seeing?

**Comment by dschuff** [comment]
https://ci.chromium.org/ui/p/emscripten-releases/builders/try/linux/b8765606004314153377/overview

**Comment by dschuff** [comment]
(basically it looks like it's just explicitly a test of `gen_struct_info` itself...)

**Comment by sbc100** [comment]
> (basically it looks like it's just explicitly a test of `gen_struct_info` itself...)

I guess we do something to that install to make able to run the whole tests suite.. I guess we should also deploy the `maint` directory in that case.

**Comment by sbc100** [comment]
https://chromium-review.googlesource.com/c/emscripten-releases/+/4998909

**Pull request closed without merging**
