### PR TITLE
Don't set NODE_PATH during testing

### PR DESCRIPTION
**Pull request by sbc100**
I'm not sure why this was here, but its generally frowned upon to use
NODE_PATH:
https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders

### CODE REVIEW

**Comment by sbc100** [comment]
Dates back to 462875aa0e5b2820868b539e2a185db7783653f8 which makes sense... maybe it is needed for ws tests?  I hope not.

**Comment by juj** [comment]
Not sure how this passed tests, but after this landed the sockets suite is now failing. E.g. https://github.com/emscripten-core/emscripten/pull/10005 with https://circleci.com/gh/emscripten-core/emscripten/216793?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link that has

```
======================================================================
FAIL: test_enet (test_sockets.sockets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/tests/test_sockets.py", line 286, in test_enet
    with harness:
  File "/root/project/tests/test_sockets.py", line 115, in __enter__
    assert child.returncode == 0, '"ws" node module not found.  you may need to run npm install'
AssertionError: "ws" node module not found.  you may need to run npm install

======================================================================
FAIL: test_nodejs_sockets_echo (test_sockets.sockets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/tests/test_sockets.py", line 420, in test_nodejs_sockets_echo
    with harness:
  File "/root/project/tests/test_sockets.py", line 115, in __enter__
    assert child.returncode == 0, '"ws" node module not found.  you may need to run npm install'
AssertionError: "ws" node module not found.  you may need to run npm install

======================================================================
FAIL: test_sdl2_sockets_echo (test_sockets.sockets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/tests/test_sockets.py", line 192, in test_sdl2_sockets_echo
    with harness:
  File "/root/project/tests/test_sockets.py", line 115, in __enter__
    assert child.returncode == 0, '"ws" node module not found.  you may need to run npm install'
AssertionError: "ws" node module not found.  you may need to run npm install

======================================================================
FAIL: test_sockets_async_echo (test_sockets.sockets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/tests/test_sockets.py", line 212, in test_sockets_async_echo
    with harness:
  File "/root/project/tests/test_sockets.py", line 115, in __enter__
    assert child.returncode == 0, '"ws" node module not found.  you may need to run npm install'
AssertionError: "ws" node module not found.  you may need to run npm install

======================================================================
FAIL: test_sockets_echo (test_sockets.sockets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/tests/test_sockets.py", line 187, in test_sockets_echo
    with harness:
  File "/root/project/tests/test_sockets.py", line 115, in __enter__
    assert child.returncode == 0, '"ws" node module not found.  you may need to run npm install'
AssertionError: "ws" node module not found.  you may need to run npm install

======================================================================
FAIL: test_sockets_echo_bigdata (test_sockets.sockets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/tests/test_sockets.py", line 241, in test_sockets_echo_bigdata
    with harness:
  File "/root/project/tests/test_sockets.py", line 115, in __enter__
    assert child.returncode == 0, '"ws" node module not found.  you may need to run npm install'
AssertionError: "ws" node module not found.  you may need to run npm install

======================================================================
FAIL: test_sockets_partial (test_sockets.sockets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/tests/test_sockets.py", line 250, in test_sockets_partial
    with harness:
  File "/root/project/tests/test_sockets.py", line 115, in __enter__
    assert child.returncode == 0, '"ws" node module not found.  you may need to run npm install'
AssertionError: "ws" node module not found.  you may need to run npm install

======================================================================
FAIL: test_sockets_select_server_closes_connection_rw (test_sockets.sockets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/tests/test_sockets.py", line 270, in test_sockets_select_server_closes_connection_rw
    with harness:
  File "/root/project/tests/test_sockets.py", line 115, in __enter__
    assert child.returncode == 0, '"ws" node module not found.  you may need to run npm install'
AssertionError: "ws" node module not found.  you may need to run npm install

======================================================================
FAIL: test_sockets_select_server_down (test_sockets.sockets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/tests/test_sockets.py", line 259, in test_sockets_select_server_down
    with harness:
  File "/root/project/tests/test_sockets.py", line 115, in __enter__
    assert child.returncode == 0, '"ws" node module not found.  you may need to run npm install'
AssertionError: "ws" node module not found.  you may need to run npm install
```
Also https://github.com/emscripten-core/emscripten/pull/9972 with https://circleci.com/gh/emscripten-core/emscripten/216716?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link is the same error.

**Comment by kripken** [comment]
Looks like sockets tests didn't run - maybe the parent commit here was before sockets were added? So this was a race, basically.

If so, should we revert this @sbc100 ?

**Comment by sbc100** [comment]
Sure we can revert.

**Comment by sbc100** [comment]
Sorry.  Reverting.  I will try to figure out why my PR passes at all.

**Pull request merged**
