### PR TITLE
[js-compiler] Reuse compile time context using `vm.runInContext`. NFC

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by dschuff** [comment]
it looks like 'runInNewContext' is the thing that's going away, not the thing that's being added?

**Comment by sbc100** [comment]
> it looks like 'runInNewContext' is the thing that's going away, not the thing that's being added?

Oops fixed PR titel

**Review by dschuff — APPROVED** [review]
LGTM: is this just a better use of the API?

**Comment by sbc100** [comment]
> LGTM: is this just a better use of the API?

yup, I think so

**Pull request merged**
