### PR TITLE
Fix test_unicode_js_library under windows and run it during CI

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Interesting, why does only windows need `r` prefixing here? Something with python file reading there?

**Comment by sbc100** [comment]
> Interesting, why does only windows need `r` prefixing here? Something with python file reading there?

This took be me a while to debug but its pretty simple.. the windows paths have `\` in them.. and `\User` is interpreted as `\U` unicode escape sequence without this.

**Comment by dschuff** [comment]
It looks like test_dylink_basics is still failing under windows: https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket/8805449560393000865/+/u/Emscripten_testsuite__core0_/stdout

**Comment by sbc100** [comment]
> It looks like test_dylink_basics is still failing under windows: https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket/8805449560393000865/+/u/Emscripten_testsuite__core0_/stdout

Fix is in #17682

**Pull request merged**
