### PR TITLE
asm_library_variables

### PR DESCRIPTION
**Pull request by juj**
Add support for creating asm.js/wasm variables from JS libraries.

### CODE REVIEW

**Comment by kripken** [comment]
This feature won't work in the wasm backend, at best we can create a normal JS variable on the outside. Instead, the safe thing is to compile C code for stuff that goes in wasm/asm.js, or use a JS variable for stuff that goes on the outside JS.

**Comment by juj** [comment]
Oh, I wrote this because library.js currently has this

```js
  // asm.js-style setjmp/longjmp support for wasm binaryen backend.
  // In asm.js compilation, various variables including setjmpId will be
  // generated within 'var asm' in emscripten.py, while in wasm compilation,
  // wasm side is considered as 'asm' so they are not generated. But
  // saveSetjmp() needs setjmpId and no other functions in wasm side needs it.
  // So we declare it here if WASM_BACKEND=1.
#if WASM_BACKEND == 1
  $setjmpId: 0,
#endif

  saveSetjmp__asm: true,
  saveSetjmp__sig: 'iii',
#if WASM_BACKEND == 1
  saveSetjmp__deps: ['realloc', '$setjmpId'],
#else
  saveSetjmp__deps: ['realloc'],
#endif
  saveSetjmp: function(env, label, table, size) {
```

after this PR the above can become just

```js
  $setjmpId: 0,

  saveSetjmp__asm: true,
  saveSetjmp__sig: 'iii',
  saveSetjmp__deps: ['realloc', '$setjmpId'],
  saveSetjmp: function(env, label, table, size) {
```

which gives the impression that wasm backend would be able to do this as well?

**Comment by kripken** [comment]
The comment might be misleading - in the wasm backend there is no mechanism for asm.js globals. We just use JS globals on the outside instead - same for asm.js functions, in fact, which means we need to replace those with C code if perf matters (in practice most of those are already in wasm-libc, like memcpy).

In theory we could compile asm.js functions to wasm (say, using asm2wasm), but that's complicated and I'd rather not go down that path.

**Comment by kripken** [comment]
I don't think we want to add this to the wasm backend - it would mean using asm2wasm to compile asm.js to wasm, as I mentioned, and that has some downsides, like writing the source in asm.js. Better to move things into C libraries. C libraries also have the benefit that they allow LTO to work on them, which right now we can't do on asm.js library functions and globals.

I think the future is to remove asm.js library functions over time, or at least not add any more. JS libraries are good for JS code, and for compiled code going into asm.js/wasm, we should use C or such.

**Comment by juj** [comment]
Ok, I'll close this then and resort to manual DCEing.

**Pull request closed without merging**
