### PR TITLE
Revert "Delete EH specification in test_dlmalloc_partial (#11201)"

### PR DESCRIPTION
**Pull request by aheejin**
This reverts commit 20529bb67559fea50a9389d9ba7548c66671f271.

The reason it started failing was actually a bug.
https://github.com/llvm/llvm-project/commit/d94bacbcf87a06abc0c1fc3405406399460debc3
started to warn on exception specifications with types, but it should
have done that only when wasm EH is used, i.e., `-fwasm-exceptions` is
enabled. This should not generate a warning when no EH is used or
Emscripten EH is used. This test does not use wasm EH, so it should've
not generate an error even if it has an exception specification.
https://github.com/llvm/llvm-project/commit/48acac36293805cef10b448d49d336da7db7bfa9
fixes this. Anyway, I don't think this particular test needs that
exception spec, but feel it's better to restore the old state, because
the error shouldn't have been there in the first place.

### CODE REVIEW

**Comment by aheejin** [comment]
The CI won't work until https://github.com/llvm/llvm-project/commit/48acac36293805cef10b448d49d336da7db7bfa9 passes the roller.

**Comment by aheejin** [comment]
Ping :) You think it's OK to revert this?

**Comment by sbc100** [comment]
Hmm, this seems a little unnecessary.. especially if exception specifiers like this are being deprecated in the future.  No harm I guess..

**Comment by aheejin** [comment]
Yeah the motivation was mostly just it wasn't supposed to fail in the first place... and even though it will be deprecated there are still people using this out there, having a test that has this will be no harm I guess too.

**Pull request merged**
