### PR TITLE
Revert "Remove some of the magic from emcmake (#12595)"

### PR DESCRIPTION
**Pull request by sbc100**
This reverts commit 72364b6a02bcfe23d1288416371448bf402c14d0.

It turns out these code paths were actually being used.  See #12595.

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Can we add a test for this?

**Comment by sbc100** [comment]
Yes we should.   I think I will add a bug instead though so this can land now and fix @juj.

**Comment by sbc100** [comment]
See #12691

**Comment by juj** [comment]
Great, thanks for tending to this!

**Pull request merged**
