### PR TITLE
Move dynamic linking docs from wiki to main site. NFC

### PR DESCRIPTION
**Pull request by sbc100**
This was mostly generated directly from the wiki using
`site/ource/get_wiki.py`.

I plan to modify the content in-place once this initial change
lands.

### CODE REVIEW

**Review by dschuff — APPROVED** [review]
even though this is just a copy, it's probably still worth putting a disclaimer or something up at the top saying the doc is WIP, (especially if there may be a release while the doc is incomplete)

**Comment by sbc100** [comment]
> even though this is just a copy, it's probably still worth putting a disclaimer or something up at the top saying the doc is WIP, (especially if there may be a release while the doc is incomplete)

Do you think this would be enough:
```
.. note:: Dynamic linking in emscripten is still somewhat experimental and subject to change.
```

**Comment by dschuff** [comment]
That's good, we should do that. but also just that this document itself out of date wrt the the code.

**Comment by sbc100** [comment]
> That's good, we should do that. but also just that this document itself out of date wrt the the code.

I yes, I see.  Done.

**Pull request merged**
