### PR TITLE
embuilder: Add MINIMAL_PIC mode

### PR DESCRIPTION
**Pull request by kripken**
This is like MINIMAL, but adds enough to run the PIC tests we have on CI, which
is slightly larger than other modes that already used MINIMAL. For that reason
we used SYSTEM for PIC, but that is much larger than the new MINIMAL_PIC.

The embuilder step for PIC goes from ~23 minutes to ~6 with this change, making
the `build-linux` step that blocks everything else 15-20 minutes faster, so overall
build iteration should be faster by that amount.

After this, `SYSTEM` is untested. Is it worth testing?

(`build-linux` is now less than an hour, but it's still quite a lot...)

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by dschuff** [comment]
Looks great to me.
I think `SYSTEM` is what's run on the Chromium CI builders. So, small risk that something sneaks past CircleCI and breaks the autorollers, but it seems fairly small.

**Comment by kripken** [comment]
Perhaps we should change the Chromium CI builders to also use `MINIMAL_PIC`, to avoid that? But they do run a different set of tests, so perhaps that wouldn't just work.

**Comment by dschuff** [comment]
well, you could see it as an advantage (i.e. you get additional test coverage there that you don't get on GH?). I don't think there's a separate test suite for PIC, right? So I think they end up running the same tests in the end?

**Comment by kripken** [comment]
>  I don't think there's a separate test suite for PIC, right? So I think they end up running the same tests in the end?

Correct, but I was worried about Chromium CI running different modes, like `-Oz` which we don't run here. But I guess those should all be the same libraries? Anyhow, I realize that the Chromium build scripts also build the emsdk packages, so we need to run `SYSTEM` there anyhow.

**Pull request merged**
