### PR TITLE
More ENVIRONMENT_MAY_BE_NODE ifdefs

### PR DESCRIPTION
**Pull request by VirtualTim**

### CODE REVIEW

**Comment by VirtualTim** [comment]
Should have merged to master, not incoming.

**Comment by sbc100** [comment]
You know you can locally rebase.. and change the target branch in the github UI?

**Comment by VirtualTim** [comment]
I did not. I often find with git the more I try to fix things the more of a mess I make, and it's just easier to delete and start the PR again.

**Comment by kripken** [comment]
Another option is to figure things out with git locally in a side branch, then force-push to the PR's branch, replacing all the old stuff.

**Pull request closed without merging**
