### PR TITLE
Change EM_ASM_ usages to EM_ASM.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This was deprecated years ago.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Well, there's still a usage of `EM_ASM_ARGS` that I was going to remove separately ... I wish we could deprecate macros in C / C++ with a warning.

**Comment by sbc100** [comment]
I wonder if we could use `__pragma` to put a warning inside the macro?  https://docs.microsoft.com/en-us/cpp/preprocessor/pragma-directives-and-the-pragma-keyword?view=vs-2017

**Comment by sbc100** [comment]
Looks like maybe `_Pragma("message \"foo is deprecated\"")` might work.

**Comment by waywardmonkeys** [comment]
We can try to address that via follow up PRs. :) Let's get this one and the other one(s) in ... and we'll see. @kripken can tell you how much I like to delete things.

**Comment by kripken** [comment]
Thanks @waywardmonkeys ! And yes, great to delete obsolete stuff like this and the others mentioned :)

**Pull request merged**
