### PR TITLE
[doc] PTHREAD_POOL_SIZE supports JS expressions

### LINKED ISSUE #12302: Document that PTHREAD_POOL_SIZE accepts JS expressions
`PTHREAD_POOL_SIZE` was made to accept arbitrary JS expressions back in https://github.com/emscripten-core/emscripten/pull/10263, but not documented.

I feel it's important to call out in docs that you can use `navigator.hardwareConcurrency` in that context as that's, arguably, one of the most useful values for multi-threaded apps.

### PR DESCRIPTION
**Pull request by RReverser**
Fixes #12302.

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Thanks!

**Comment by RReverser** [comment]
@kripken Actually, I just remembered that someone suggested `_emscripten_num_logical_cores` on the original issue instead: https://github.com/emscripten-core/emscripten/issues/12302#issuecomment-696773893

I guess we should recommend it instead?

**Comment by kripken** [comment]
I think the PR is good as it is. To use a C method, it would need to be exported, for one thing, which adds complexity to the example. Using a natural JS example in this PR seems best.

**Comment by RReverser** [comment]
Can't merge it due to the same Firefox CI issues :(

**Comment by kripken** [comment]
Sorry about that, I'll merge it now.

**Pull request merged**
