### PR TITLE
Fix wasm workers to work with closure

### PR DESCRIPTION
**Pull request by tklajnscek**

### CODE REVIEW

**Comment by juj** [comment]
This dependency was certainly missing. Though given that `_emscripten_create_wasm_worker` already does have a dependency to '_wasm_worker_appendToQueue', I think that a Closure would only give an error if one did not call `emscripten_create_wasm_worker` in the codebase at all? I.e. building code that links against Wasm Workers, but does not actually yet use them? Was that the case you were seeing?

**Comment by tklajnscek** [comment]
Yes, this was not using `_emscripten_create_wasm_worker` because I merely included all the wasm worker code to be able to use the new sync primitives as mentioned in my comments on https://github.com/emscripten-core/emscripten/pull/16449

**Comment by tklajnscek** [comment]
@juj this is still an issue for us :) can we merge it or not?

**Comment by juj** [comment]
Ops, very sorry, I had moved on thinking that this would have autolanded.

**Review by juj — APPROVED** [review]

**Comment by sbc100** [comment]
We should probably have test for this

**Pull request merged**
