### PR TITLE
test: check waka file & mount/unmount the second time

### LINKED ISSUE #11420: MEMFS unmounting multiple times
I can't seem to unmount a MEMFS mount dir multiple times. If I call: mount(), unmount(), mount() and unmount() again I get an error message in the last unmount() when using MEMFS.

I see: error properties: null({ node: undefined, setErrno: Function, errno: 28, code: 'EINVAL', constructor: Function })

### PR DESCRIPTION
**Pull request by TroyTae**
resolve #11420

### CODE REVIEW

**Comment by TroyTae** [comment]
Ummm am I write something wrong?
Below message prints even if there is no changes:
```
/root/emsdk-master/emsdk_env.sh: line 26: /root/emsdk-master/emsdk_set_env.sh: No such file or directory
```

**Comment by sbc100** [comment]
> Ummm am I write something wrong?
> Below message prints even if there is no changes:
> 
> ```
> /root/emsdk-master/emsdk_env.sh: line 26: /root/emsdk-master/emsdk_set_env.sh: No such file or directory
> ```

That was a transient issue with emsdk, unrelated to this change.  If you either re-run the tests, or push something new here to treigger a re-run the issue should be fixed.

**Comment by TroyTae** [comment]
@sbc100 
I cannot re-produce this issue and there is no reply from issuer.
But I think this test is still reasonable.
If you also think like that please merge this, if not please close this :)

**Comment by sbc100** [comment]
Lets give it a couple more days for the OP to respond.. perhaps there is something specific about that failure case they are seeing.

**Comment by b-katt** [comment]
Apologies for the delay on this. It seems I had a subtle bug in my code which caused the actual flow to be mount(), unmount(), and unmount(). Thank you for investigating this issue! Feel free to resolve.

**Comment by kripken** [comment]
Thanks for the update @b-katt !

**Pull request merged**
