### PR TITLE
Support symbols files for different options

### PR DESCRIPTION
**Pull request by aheejin**
This aims at automating symbol generation a bit more and supporting
different symbols files for different set of build options. For example,
a library can be built with different sets of options: such as with `-mt`
and `-noexcept`, only `-mt`, only `-noexcept`, or with none of them. And
libraries built with those different options can expose different set of
symbols. Currently this kind of info is hard-coded into the code.

After this PR, all system libraries read symbols file in
`system/lib/symbols/wasm/[library_filename].symbols` when using the wasm
backend, and `system/lib/symbols/asmjs/[library_filename].symbols` when
using fastcomp. For example, if the filename of a library we are
considering to link is `libc++-mt.a`, it will search for
`system/lib/symbols/wasm/libc++-mt.symbols`. And if it doesn't exist, it
will try the default library name without any options:
`system/lib/symbols/wasm/libc++.symbols`.

`tools/update_symbols.py` generates all symbols files automatically. It
does not have `--asmjs` anymore: it will read `.emscripten` just as the
normal emcc toolchain does. This script has `target_libs` variable, in
which we only list several libraries that need symbol files. (This set
of libraries is the libraries we currently have `.symbols` files.)
This script builds all possible combination of those libraries if they
don't exist in cache, and run `llvm-nm` on them, and generate files
within `system/lib/symbols/wasm` or `system/lib/symbols/asmjs`
directories. As mentioned above, to prevent proliferation of symbols
files with same contents, if symbols files generated with different
options are the same as the 'default' symbol file without any suffices,
those symbol files will be deleted and the linking algorithm will fall
back to the default symbol files for the library.

One of the reasons I did this was, when we add the new wasm exception
handling, the set of symbols exposed by different options for libraries
such as libcxxabi will certainly be different, and I hoped to make it
more general.

### CODE REVIEW

**Comment by kripken** [comment]
I see, thanks.

I worry a little that this diff is 2.6MB in size. I guess the new files won't change frequently, but still this is pretty big...

**Comment by aheejin** [comment]
> I see, thanks.
> 
> I worry a little that this diff is 2.6MB in size. I guess the new files won't change frequently, but still this is pretty big...

Hmm yes, that's unfortunate, there are a lot of overlaps between asmjs version and wasm version, and between the different options of a single library... But it's hard to reduce them without introducing hardcoded info like before. The emscripten toolchain's whole size is around 138MB, so would that be a big problem? If you think so, do you have any suggestions? (Such as, not doing this at all and just add some more hardcoded info until we remove symbols file?)

**Comment by sbc100** [comment]
I'm working on a change that should hopefully remove the need for many of these files by including a lot of the system libraries by default (i.e. unconditionally).. so hopefully they won't be around too long.

**Comment by aheejin** [comment]
Is that gonna delete symbols files altogether?

**Comment by sbc100** [comment]
Yes, but only for truly system library like libc that are always supposed to be linked in.

**Comment by aheejin** [comment]
Should we link in libc even when using C++? And should we link in libc++ when using C? Currently the sizes of libc++ symbols files are the biggest, and libc symbols file don't occupy much.

**Comment by sbc100** [comment]
yes, libc and libc++ will no longer need symbols if my change langs.   libc will alwasy be included (its needed for C++ programs too).  libc++ we can include when em++ is used as the driver or -xc++ is pass.. just like for clang and clang++

**Comment by aheejin** [comment]
Sounds good. Will land this then.

**Comment by kripken** [comment]
@sbc100 that sounds good, but we should check if compile times regress. In the past linking them in just to dce them out was painful. But perhaps today it's fine with .a linking etc.

**Comment by sbc100** [comment]
Maybe this is true for fastcomp but it shouldn't make much difference for lld with archive files.   So we would be taking a regression in link time for fastcomp users... 

Actually not that i think about it the only libraries of any size are libc and libc++ its hard to imagine anyone with long link times who doesn't already pull those in.    I imagine it will only regress users who don't reference *any* libc symbols..

**Comment by kripken** [comment]
@sbc100 yeah, that makes sense. we should verify but i bet you're right.

**Pull request merged**
