### PR TITLE
Fix $getSocketAddress__deps

### PR DESCRIPTION
**Pull request by andrewevstyukhin**
Fixes: https://github.com/emscripten-core/emscripten/issues/15238

### CODE REVIEW

**Comment by sbc100** [comment]
Looks like maybe you need to also add `htons` to the `connect` line in `tools/deps_info.py` (line 75).

**Comment by andrewevstyukhin** [comment]
I use emscripten 2.0.14 temporary. But in version 2.0.30 we faced `htons` problem.

**Comment by andrewevstyukhin** [comment]
When I run `tests\runner test_REVERSE_DEPS` on Windows 10 machine I hang with
> test_REVERSE_DEPS (test_core.wasm0) ...
wasm-ld: error: cannot open output file a.out.wasm: function not supported

This happens when path is specified to source .c / .cpp
For example: `emcc tests/hello_world.cpp` fails, `cd tests & emcc hello_world.cpp` works.

**Comment by andrewevstyukhin** [comment]
I use physical computer with only Windows 10. I also have installed bash in the path (from git-scm).
Should I debug wasm-ld locally?

**Comment by sbc100** [comment]
> I use physical computer with only Windows 10. I also have installed bash in the path (from git-scm). Should I debug wasm-ld locally?

So you are using the windows version of emsdk?  Which version?   Are you using bash when this issue occurs?  Does it occur also when you run in a cmd.exe shell?

**Comment by sbc100** [comment]
If `emcc tests/hello_world.cpp` fails but `emcc hello_world.cpp` then is there anything special about the top level directory of emcc?   Does it fail when `emcc` is run on any file inside a subdirectory?  Super odd.

**Comment by andrewevstyukhin** [comment]
`cmd` & `bash` both don't work. I installed latest (2.0.30) emsdk.
Current directory does matter. Failure occurs on ram-disk (ImDiskTk20210125).
bash: works with D:\ and D:\folder, but not with ram-disk R:\ and R:\folder
cmd: same situation.

**Comment by sbc100** [comment]
That is super odd.  There are a couple of possibly-related issue: 

- https://github.com/emscripten-core/emsdk/issues/686
- https://github.com/emscripten-core/emscripten/issues/13067

But they don't report "function not supported" as the error code.

This seems like an llvm.   Can you try with `2.0.30-asserts`  (the `-asserts` variant of the SDK includes asserts and is also not build itself with LTO).

**Comment by sbc100** [comment]
So you have been using emscripten for while on windows (since you ran into this unrelated bug) but have not run into this wasm-ld issue before?

**Comment by sbc100** [comment]
You say that `emcc tests/hello_world.cpp` fails, but is there a ram disk in use in that situation?

**Comment by andrewevstyukhin** [comment]
This bug occurs only in tests. Other repositories from HDD compiles fine.
I think tests use temporary folder somehow and breaks.
`emsdk activate 2.0.30-asserts` print no additional info:
> R:\>emcc hello_world.cpp
wasm-ld: error: cannot open output file a.out.wasm: function not supported

Current directory really matter: `d:\>emcc r:\hello_world.cpp` works, `r:\>emcc d:\hello_world.cpp` fails.

**Comment by sbc100** [comment]
I think you need to `emsdk install 2.0.30-asserts && emsdk activate 2.0.30-asserts` BTW.  

Can you try `2.0.31-asserts` which just came out?

**Comment by sbc100** [comment]
Indeed the tests run in a subdirectory of the temporary directory.    I guess your temporary directory is on a RAM disk?

**Comment by sbc100** [comment]
Do see if this is recent perhaps you could also test with an older emsdk version 2.0.10 perhaps?

**Comment by sbc100** [comment]
Thanks for helping to debug this.   So it looks like an issue (most likely and llvm issue) that was introduced between 2.0.8 and 2.0.9?   Do you think you should help my bisecting down the specific emsdk change:  https://emscripten.org/docs/contributing/developers_guide.html#bisecting.   That should give us a (hopefully) small llvm revision range.

**Comment by sbc100** [comment]
By the way would mind opening a different issue for this?   We should be able to land this deps change independently.

**Comment by andrewevstyukhin** [comment]
I'll try to debug and show facts. Only then new issue can be usefully written. Currently I stuck with tests...

**Comment by andrewevstyukhin** [comment]
`tmp` and `temp` don't influence on wasm-ld: `clang++` successfully executed, `llvm-nm.exe` successfully executed,
emcc:DEBUG: linking:
wasm-ld: error: cannot open output file a.out.wasm: function not supported

**Comment by sbc100** [comment]
> Variables `tmp` and `temp` can repair tests tada Anyway wasm-ld can't link on ram disk and I want to better understand the problem.

Indeed, that looks very serious, but also unrelated to this issue so perhaps we can land this and continue the discussion of the wasm-ld bug elsewhere?

**Comment by andrewevstyukhin** [comment]
Now I can't understand `tests/runner other.test_deps_info` because of
> internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'acorn'

CI found 3 errors:
test_deps_info (test_other.other)
test_linking_send (test_other.other)
test_syslog (test_other.other) - helpful

> test_linking_send (test_other.other) ...
runner: error: es-check was not found! Please run "npm install" in Emscripten root directory to set up npm dependencies

**Comment by sbc100** [comment]
As the message says, running `npm install` in the emscripten directory is probably the solution there.

**Comment by sbc100** [comment]
> As the message says, running `npm install` in the emscripten directory is probably the solution there.

For the test_deps_info failure, that can be quite a long test to run so if you know which symbol is that issue you can modify the test code and set `start_at = "xxx"` where xxx is the name of the symbol giving you issues.

**Comment by andrewevstyukhin** [comment]
I crossed fingers to bypass CI.
> d:\Emscripten>npm install
npm WARN saveError ENOENT: no such file or directory, open 'd:\Emscripten\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'd:\Emscripten\package.json'
npm WARN Emscripten No description
npm WARN Emscripten No repository field.
npm WARN Emscripten No README data
npm WARN Emscripten No license field.
up to date in 1.168s
found 0 vulnerabilities

Maybe `es-check` require additional hints or `directory should be specified in the message`... I hope it's my bad and not another problem. Yes, it should be a root of repository, not emsdk's root.

**Comment by andrewevstyukhin** [comment]
PR compiled ✔️ Thanks for the help!

**Review by sbc100 — APPROVED** [review]
Nice!

**Pull request merged**
