### PR TITLE
Skip unsupported POSIX threads tests. NFC.

### PR DESCRIPTION
**Pull request by kleisauke**
See: https://github.com/emscripten-core/posixtestsuite/pull/4.

### CODE REVIEW

**Comment by sbc100** [comment]
Why not continue to at least compile these and have them report unsupported?  What is the point is skipping them completely?

Perhaps we could maintain a separate lists of tests that build and run but are expected to skip?  Then we would continue to get compile-coverage and we would also get a failures if they ever go from "unsupported" to some other status such as "failed" or "passed"?

**Comment by kleisauke** [comment]
See https://github.com/emscripten-core/emscripten/pull/13051#discussion_r545030772 for the reason why some tests needs to be skipped completely within the test runner. But I agree, we should at least try to compile and test it. We could mark certain tests as expected to fail at runtime (likewise I did in that PR) to ensure compile-coverage.

If the approach of introducing a `xfail` parameter is desired, then this PR depends on https://github.com/emscripten-core/emscripten/pull/13051.

**Comment by sbc100** [comment]
No, this approach seems fine to me after reconsideration.

Can you perhaps split the the list of know failures into ones that we should fix and ones that we don't have any plans to (at least not without adding larger features like signal handling of multi-process).    (so we can see how many actual failures we have).

**Review by sbc100 — APPROVED** [review]

**Comment by kleisauke** [comment]
I've split the dictionaries with commit https://github.com/kleisauke/emscripten/commit/640cd80ba6b65f821b59fd7ca3993300f8e2016d and added a TODO-item for supporting semaphores. It seems that some semaphore tests are already supported, so I removed those with commit https://github.com/kleisauke/emscripten/commit/fa9ebf27587a1e447de4d3d5ef269253206c704c (the remaing 3 semaphore tests never return anything, so perhaps they should be moved to the `disabled` dictionary instead).

**Comment by kleisauke** [comment]
Rebased on top of the master branch to resolve merge conflict.

**Comment by sbc100** [comment]
Is this change read to land now?    I will land it if so.

I might re-title something to something like "Update posixtestsuite" or at lest something that include that fact?

**Comment by kleisauke** [comment]
It's ready, feel free to land and to revisit the title/description of this PR.

**Comment by sbc100** [comment]
See: https://github.com/emscripten-core/posixtestsuite/pull/4.

**Pull request merged**
