### PR TITLE
Remove 'exception of type' prefix when the exception has a message

### PR DESCRIPTION
**Pull request by hoodmane**
I think this makes the message a bit more readable. @aheejin

### CODE REVIEW

**Comment by hoodmane** [comment]
This also makes it easier to discriminate between the two cases:
https://github.com/pyodide/pyodide/pull/2828/files#diff-7c12fd059c6331a427e2319a8f1335d6b5513372ccf8f9449599bdacff305540R52-R63

**Comment by hoodmane** [comment]
In fact it would be most useful if the API returned a pair (type, message).

**Comment by aheejin** [comment]
I tried to match the message printed here in libcxxabi: https://github.com/emscripten-core/emscripten/blob/697c3d940ee4fb97b2be48e3b4836020f9117aec/system/lib/libcxxabi/src/cxa_default_handlers.cpp#L63-L73

So attaching `exception of type` to one place and not the other feels little inconsistent to me. Why do you need to remove `exception of type` only for typed exceptions?

**Comment by sbc100** [comment]
I think the idea with this API was that it was supposed to be useful for getting string descriptions of exceptions out of emscripten.
  
Both "terminating with" and "exception of type" seem like extra stuff that isn't necessarily useful.  Perhaps the test could inject that prefix but I don't see why the API should include it.

**Comment by hoodmane** [comment]
Right, as I said I think the best thing would be for the API to return the type of the exception and the `what` of the exception or an empty string if no `what` is available.

**Comment by hoodmane** [comment]
@sbc100 I could close this and make a PR to do that instead?

**Comment by sbc100** [comment]
> @sbc100 I could close this and make a PR to do that instead?

Sounds good, but maybe @aheejin has more thoughts on this.

**Review by aheejin — APPROVED** [review]
> Right, as I said I think the best thing would be for the API to return the type of the exception and the `what` of the exception or an empty string if no `what` is available.
> @sbc100 I could close this and make a PR to do that instead?

Is that PR you have in mind different from this? I thought this does that...

Anyway, I don't feel too strongly about the message, and this is fine with me.

**Pull request closed without merging**
