### PR TITLE
Remove unused `hasExportedFunction` helper from  src/parseTools.js. NFC

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Review by aheejin — APPROVED** [review]

**Comment by juj** [comment]
Sorry, this really frustrating. Please can we stop and take a minute to catch up here. This kind of change should not land at a whim.

1. This change breaks external facing API boundary for user JS libraries. I think we have been using `hasExportedFunction()` in our JS library code. The function `hasExportedFunction()` has been used in the past, but looks like some refactor in the past must have removed its uses.

2. The direction of this change does not look good. Having a dedicated function `hasExportedFunction()` for this kind of check seems much more robust than exposing the use of internalish looking data structure name `EXPORTED_FUNCTIONS` to user code and exposing its type. We will not be able to affect behavior of `#if x in EXPORTED_FUNCTIONS` in the future without breaking users, but we would retain a higher amount of control to adjusting internal behavior if we had a `#if hasExportedFunction(x)` API.

3. @sbc100 the speed at which you jump to refactoring the repository from underneath when when another PR is about to land is maybe a bit too eager. This has happened several times to my PRs, now with #13883, and earlier on other PRs, most majorly with the wasm stack scanning PR, where you land a bunch of review requests to the PR and then drive in refactors that immediately cause conflicts. I do think that your PRs are of excellent quality, but can we maybe be a bit more reserved on jumping in to adjust code, and retain maybe an ordering of first-come-first-to-land order on PRs? In this case the conflict was not at all big, but it feels like this pattern commonly repeats. :( I feel a bit embarrassed to bring this up since your work is amazing, though maybe a pinch of patience?

**Comment by sbc100** [comment]
Apologies, in my cleanup efforts I have often overlooked the possibilities of user JS libraries depending on otherwise-dead code.   I will look into restoring this and possibly using internally so that it is no longer dead code.

I do wish we had some way to cleanup dead code in our JS runtime and libraries but I can see that its almost impossible to know what user-JS is out there using this code.

**Comment by kripken** [comment]
Perhaps we should have an explicit list of JS functions that are known to be used externally? Concretely we might document that they are intended to be public APIs, + add a test that uses them.

If that makes sense, would it be possible to get a list of the "internal" JS methods used by your codebase @juj ?

**Comment by sbc100** [comment]
I would love to find a way to partition the address space so that only certain symbols are available to user JS code.. then we would write tests that cover those user-visible APIs.   

We should write such tests anyway, specifically we should have tests for any JS function that are known to be used in the wild, such as this one.

**Comment by juj** [comment]
> Perhaps we should have an explicit list of JS functions that are known to be used externally? Concretely we might document that they are intended to be public APIs, + add a test that uses them.
> 
> If that makes sense, would it be possible to get a list of the "internal" JS methods used by your codebase @juj ?

Yeah, I agree. We have been a bit bad historically in documenting the JS API surface area, mostly it has been a case of "let's monkey off of what the existing src/library_*.js files do".

I think with the exception of maybe very few special constructs, everything that we expose to src/library_*.js we should think as being public.

Phrased another way: why should our own authored src/library_*.js files have any special constructs available that user JS library files should not be able to enjoy? I think we should be at the very same line when we author these vs when users author their own.

**Comment by sbc100** [comment]
I think the problem comes from the fact that its easy to add helper functions `src/library_*.js` and to `src/parseTools.js` but if we assume everything we add is public then it makes it hard/impossible to remove stuff or refactor/rename.   As in this PR where we have a function that was dead code from the POV of emscripten core but possibly used by some user's library code.

It think it would be nice to be able to write library/utility functions without having to commit to maintaining them in perpetuity.    If we can't find some way to add thing without that commitment then I think we should have a *much* higher bar for adding anything to our JS library code.    In that world, (its not clear to me if that is the world we live in today) we would want to be very careful when adding any new utility functions.  I would suggest at the very least that each one would need documentation and testing outside of actual usage in our own library code.

**Pull request merged**
