### PR TITLE
Rename "heap" functions that actually relate the whole wasm memory

### PR DESCRIPTION
**Pull request by sbc100**
This is an attempt to fix some of the confusion between the terms "memory" (the whole linear memory) and "heap" (normally referring to malloc region).

We still have some confusing names such as HEAP8, etc, in the JS code but I'll leave that for a separate change.

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Side note about the JS side - I'm not sure it's worth renaming `HEAP8` etc. The name is imperfect, I agree, but that would be a breaking change for lots of users, so the downside might be bigger than the upside. But this PR lgtm as the old names still work + a deprecation warning.

**Comment by juj** [comment]
Hey, wow, let's hold on in this one. This is a massive breaking change. (sure, not just yet now, but this would be a "foot in the door" towards a direction of an absolutely massive breaking disruption in the future)

I think the disruption that is caused will be much worse than not doing the change. I do appreciate the two points that
a) unfortunately Emscripten's coinage of the terms heap does not follow the spec name of WebAssembly.Memory, and
b) the word heap is also used to refer to the dynamic malloc heap.

But there are a few issues that I have here, which I find are much bigger:

1. The main issue is that the new word "memory" is a much more vague and general term compared to "heap". This rename change is going from a more specific word towards a less specific word, which is not a good direction at all. I.e. "memory" is a more ambiguous and casual word compared to "heap". So it is much much better to overload on the term "heap" than on "memory".

2. To fix the above danger of ambiguity, an author will have to prefix memory in full, "WebAssembly memory". But when we do that, we realize that the original terms already weren't that confusing. For example, when you write

> This is an attempt to fix some of the confusion between the terms "memory" (the whole linear memory) and "heap" (normally referring to malloc region).

I would argue that the root problem is when people write about "memory" and "heap", when they should be talking about "WebAssembly memory" and "WebAssembly heap". When the terms are put in that context, there is no ambiguity with either the new or old words - the term "WebAssembly heap" reads as clearly as well.

Similarly, talking about "WebAssembly heap" vs "dynamic heap" reads unambiguous to me to distinguish between the malloc heap and the wasm heap.

So overloading on the word **heap** has much less risk of confusion compared to overloading on the word **memory**. If someone casually writes "X is stored on the heap", sure, there might be a chance to confuse a native C programmer whether it was explicitly meant that X is in WebAssembly memory, or X is in the malloc heap. But at least the author knows it will be somewhere in the Wasm memory. Native web developers will not have this confusion, since they do not come from the "C malloc heap" education background.

Compare to if someone casually writes "X is stored in memory": it can't get more vague than that, and could mean anything (JS memory? Wasm memory? dynamic malloc heap memory?), and now all native web developers can be confused, and all the native C developers from before can also get confused as well.

So both before and after, there is danger of confusion, and one will in both cases need to prefix the term "WebAssembly" to clear the ambiguity.

The fact is that the term WebAssembly.Memory is not great and does not lend well to a general term. Sure, if we started from scratch, we'd follow the API naming to reuse the word memory, but now that we are in this situation, I don't think there is much usefulness to be gained from this change, and it will be more harm than gain.

3. Right now this PR does do the backwards compatibility emulation via #define and #include routing, but it still does not save from the fact that it will cause a huge disruption down the line. If we allow this precedent, we will then have the massive problem of what to do with the `HEAPxx` global variables. These are referenced thousands of times in external codebases and renaming them to e.g. `MEMxx` will cause massive breakages. One could write an automated code converter pass, but that only works for closed JS code, it will greatly increase maintenance, and at some point there will be huge shockwaves of code rewrites needed in all projects. At some point such backwards compatibility emulation layers are desired to be torn down, which will eventually cause breakages to old code.

Using the terms "WebAssembly heap" and "WebAssembly memory" synonymously has worked for more than half a decade now. I do recall there being one vocal rant from someone about this, but it read very much like the person already knew what the terms actually meant, and was arguing philosophically rather than actually having impacted in productivity or bugs in their codebase. I would say that is most of the cases that we have, and I'd wish we would not trade this issue with actual disruptions to people's code.

It is unfortunate that there are two terms, though to me this has been one of those things that were pragmatically on the "very harmless" side of the scale. This PR direction will produce a massive refactor headache that would turn this to a "very harmful" side of the scale, so I would not at all want to do this if possible. Sorry to be a brake, but this seems like a huge practical complication and eventual breakages. :( Also sorry to write, but **Can we improve this type of confusion in documentation instead?**

**Comment by sbc100** [comment]
You make some good arguments.   For me the most compelling argument for not doing this is that it could be very disruptive if we try to take to the limit and covert HEAP8 to MEMORY8.

I will close this PR (I might still try to land the internal/documention parts of it).

**Comment by sbc100** [comment]
I myself don't particularly understand the term "dynamic heap".  Do you know where this comes from?    The term dynamic could also be used with the webassembly memory (at least when building with ALLOW_MEMORY_GROWTH), as well as with the stack (which grow downwards).   So I do think there is some more work to do in finding the unambiguous terms here.

**Comment by juj** [comment]
Great, thanks for accommodating. I think "Dynamic heap" as in "dynamic allocation heap". Or maybe directly, "malloc heap", might be the most unambiguous term(?)

**Pull request closed without merging**
