### PR TITLE
Unify code for setting up nodefs tests. NFC

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Review by hoodmane — APPROVED** [review]
Thanks! It's a nice cleanup.

**Comment by sbc100** [comment]
@hoodmane are you able to approve this with your current permissions?

**Comment by hoodmane** [comment]
Looks like I can't.

**Comment by sbc100** [comment]
> Looks like I can't.

Ok try now

**Comment by hoodmane** [comment]
Looks like I do have permission now.

**Pull request merged**
