### PR TITLE
Add missing WASM_BIGINT directives in MINIMAL_RUNTIME preamble, and micro-optimize code size in memory creation.

### PR DESCRIPTION
**Pull request by juj**

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]
Did this change the output of `./tests/runner other.*code_size* other.*metadce*`?   I guess maybe it improved some results but not enough to make the tests fail?

Sometimes for this change of change I submit the output of `./tests/runner other.*code_size* other.*metadce* --rebaseline` before the change and then re-run with the change to confirm the improvement/change.   Not that you have to do that, but in cases where its not do clear I will do this just to confirm the improvement.

**Comment by juj** [comment]
> Did this change the output of ./tests/runner other.*code_size* other.*metadce*? I guess maybe it improved some results but not enough to make the tests fail?

It actually does not improve that test, because Closure Compiler undoes this kind of optimization. It does not see or care about multiple comma-separated vars vs vars as separate statements, and it builds its AST the same from either way, and then randomly either writes out individual vars or comma-separated vars, depending on lucky chance.

> Sometimes for this change of change I submit the output of ./tests/runner other.*code_size* other.*metadce* --rebaseline before the change

I work on a Windows and macOS systems as my daily drivers, but unfortunately the code size test no longer is operational on either of those systems, so I'll spin up my Linux box only if that test fails and really needs rebaselining.

**Comment by sbc100** [comment]
> I work on a Windows and macOS systems as my daily drivers, but unfortunately the code size test no longer is operational on either of those systems, so I'll spin up my Linux box only if that test fails and really needs rebaselining.

Do you mean the `--rebaseline` flag is somehow not working?    The tests themselves are known to pass I think because they run as part of CI (at least for mac we run the entire `other` test suite on mac in github CI).

**Comment by juj** [comment]
No I mean the tests are skipped because the tests don't produce the same results on Windows and macOS than on Linux.

**Comment by sbc100** [comment]
> No I mean the tests are skipped because the tests don't produce the same results on Windows and macOS than on Linux.

Oh yeah, that is bad... we should fix that.

**Comment by sbc100** [comment]
> > No I mean the tests are skipped because the tests don't produce the same results on Windows and macOS than on Linux.
> 
> Oh yeah, that is bad... we should fix that.

Interesting the metadce tests (those based on `run_metadce_test`) are not skipped but they also measure code size (perhaps they are not as sensitive).

**Pull request merged**
