### PR TITLE
Proposed fix for race condition in websocket_to_posix_proxy (#15341)

### PR DESCRIPTION
**Pull request by ddiminnie**
This pull request contains our proposed fix for #15341.  We are essentially protecting calls that modify the socket registry using a mutex lock.

### CODE REVIEW

**Comment by juj** [comment]
Hey, thanks for working on this!

Instead of placing the lock/unlock calls to callers of the functions that access shared state, can you put the mutex lock & unlocks directly inside the code that mutates the shared state, i.e. inside these functions: https://github.com/emscripten-core/emscripten/blob/main/tools/websocket_to_posix_proxy/src/socket_registry.cpp

That way the callers don't need to remember to do that on their own.

**Comment by ddiminnie** [comment]
I thought about putting the lock in the CloseSocketByConnection and TrackSocketUsedByConnection calls, but didn't because I'm lazy :-) (the websocket_to_posix_proxy.cpp file already had the apparatus set up for locking the websocket connection...)

I'm happy to make the change, but it will have to wait until this evening to be uploaded (GitHub's authenticator REALLY hates our corporate proxy).
Thanks for the suggestion!

**Comment by ddiminnie** [comment]
I've moved the lock/unlock calls into socket_registry.cpp.  This was a bit tricky.  For example, in :
```
bool IsSocketPartOfConnection(int proxyConnection, SOCKET_T usedSocket)
{
	bool result;
	if (usedSocket == 0) return true; // Allow all proxy connections to access "socket 0" when/if they need to refer to socket that does not exist.

	LOCK_MUTEX(&socketRegistryLock);

	if (socketsPerProxyConnection.find(proxyConnection) == socketsPerProxyConnection.end())
	{
		UNLOCK_MUTEX(&socketRegistryLock);
		return false;
	}

	std::vector<SOCKET_T> &sockets = socketsPerProxyConnection[proxyConnection];
	result = std::find(sockets.begin(), sockets.end(), usedSocket) != sockets.end();

	UNLOCK_MUTEX(&socketRegistryLock);

	return result;
}
```
We want `socketsPerProxyConnection` to be the same between the first call to `find` and the call to `end`, but does it need to remain unchanged before accessing the socket vector for the current `proxyConnection`?  Should we lock and unlock twice?

At any rate, I tested the latest changes by making 500,000 calls against an emscripten build of `sample_add_server` from an old version of the  [xmlrpc-c](http://xmlrpc-c.sourceforge.net/) library.  (This server creates, uses, and closes a new ephemeral socket for each 30 XML-RPC calls, for a total of 500,000 XML-RPC requests over 16667 ephemeral sockets.  Prior to the changes above attempting this many calls would cause the server to hang after 15000 or 30000 calls.  After the change each run successfully completes all 500,000 requests.)

I wish I had a simple unit test I could add for this change.  (On the other hand, if such a test existed then this problem would have been fixed a long time ago... :-) )

**Review by juj — APPROVED** [review]
Looks great, thanks!

**Comment by ddiminnie** [comment]
Thank you!

**Pull request merged**
