### PR TITLE
Remove artifacts from Emscripten_logo_full.png, added logo.svg/png

### PR DESCRIPTION
**Pull request by trzecieu**
Closes: #13783 

* Fixed site/source/_static/Emscripten_logo_full.png by removing bright artifacts from background masking - that looked not so good on dark backgrounds 
* Added logo.svg / logo.png that with an intention to update logo of https://github.com/emscripten-core - so that posts linked in social media will look better. Used SVG is a modified version of switch_logo.svg by removing label and adjust page size.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

Here is a comparison of the changed file, the lower is the new version:

compare

There are some other changes than the cleanup, which is I guess because the source had differences. I don't remember the history here, but maybe a filter was applied to try to make it more "3d" and that introduced the artifacts... anyhow, this looks better.

Thoughts from anyone else?

**Comment by trzecieu** [comment]
Good notice, looks like there was added drop shadow, which is not a part of SVG file. Also colours are a little bit different (there is a gradient and little colder gray), I will try to replicate that and flex my vector skills.

**Comment by trzecieu** [comment]
I've tried to reconstruct the image as close I could, also relevant SVG was added.

**Review by kripken — APPROVED** [review]
Looks great, thanks! Much better art skills than me :smile:

**Comment by kripken** [comment]
Updated logo on emscripten-core, hopefully I did that right...

**Comment by trzecieu** [comment]
Looks good! Now it's just a matter of time that portals will update their cache. Thanks!

**Pull request merged**
