### PR TITLE
Always export underlying functions for EM_ASM

### PR DESCRIPTION
**Pull request by Wirtos**
Calling variadic functions directly is the only way you can use emscripten asm functionality from a C89/C99 (ANSI/ISO) project without altering its build file much.

### CODE REVIEW

**Comment by sbc100** [comment]
Can you explain a little why this is useful in the description?   I was a little bit confused by the title since "asm" is pretty overloaded.  Can you replace it with "EM_ASM" which is the feature these function exist to serve.  

It seems like the these its strict ansi case that you care about?  

TBH part of me would prefer to consider these functions and internal detail of the EM_ASM macros.   Do you have a use case for calling them directly?

**Comment by Wirtos** [comment]
> It seems like the these its strict ansi case that you care about?

Calling variadic functions directly is the only way you can use them from a C89/C99 project without altering its config much (for example it'd require you to add special case CMAKE_C_STANDARD_REQUIRED and CMAKE_C_EXTENSIONS). Besides that some people might find it cleaner to store a JS code inside a string. It also seems that many IDEs don't like this kind of EM_ASM magic syntax and it also triggers a gnu-zero-variadic-macro-arguments warning.

**Comment by sbc100** [comment]
> > It seems like the these its strict ansi case that you care about?
> 
> Calling variadic functions directly is the only way you can use them from a C89/C99 project without altering its config much (for example it'd require you to add special case CMAKE_C_STANDARD_REQUIRED and CMAKE_C_EXTENSIONS). Besides that some people might find it cleaner to store a JS code inside a string, some IDEs don't like this kind of EM_ASM magic syntax much and it also triggers a gnu-zero-variadic-macro-arguments warning, especially hurts on Werror enabled.

Ok thats a fair argument.  Remember has EM_JS these days which is the preferred way to embed JS in C/C++.   Doesn't mean we should make this change though.  

Can you update the PR and we can land this.

**Review by sbc100 — APPROVED** [review]

**Comment by kripken** [comment]
Sorry @Wirtos , looks like we approved this but forgot to land it. I'll do that now.

**Pull request merged**
