### PR TITLE
Leak checker

### PR DESCRIPTION
**Pull request by wingo**
This PR builds on #8474, adding support for leak-checking instead of automatic finalization.

### CODE REVIEW

**Comment by kripken** [comment]
What is the benefit of finding leaks, instead of enabling the automatic cleanup?

**Comment by wingo** [comment]
@kripken The use case is where you are writing both the C/C++ and JS sides of an app and you want to manually manage memory on the JS side.  But, it's hard to be sure that you've called `.destroy()` everywhere that you need to be doing it.  So, you use the finalizer support as a leak-checker -- if a JS object becomes finalizable and its associated Wasm memory hasn't been released, we want to know about it so that we can add appropriate `.destroy()` calls.  The logged object includes some information about the object's type, so the developer can inspect the console to see where to look.

For me it's not necessarily leak-check versus automatic cleanup -- to my mind when you enable leak-checking it's a developer tool, not production, so whether to to actually invoke the finalizer or not doesn't matter a whole lot.  I think it could make sense to run the finalizer in this case, no problem.

As another data point for this use case:

  https://www.hboehm.info/gc/leak.html

Not quite the same but very similar.

**Comment by kripken** [comment]
I see, thanks @wingo - that does sound useful!

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

Re-opening and re-targeting to master.

**Comment by chadaustin** [comment]
I'm going to stamp this. I love the idea of the feature and I trust that if it passes tests it's probably fine.

I did not audit any possible performance implications.

I would suggest a mechanism to detect leaks other than console.warn! It would be awesome to attach a callback that your application could use to report memory leaks, even to the application's telemetry.

**Comment by jgravelle-google** [comment]
No strong opinion here, seems fine. Can merge after fixing CI and conflicts.

**Pull request closed without merging**
