### PR TITLE
[emrun] Use HTTP/1.1, instead of the default of HTTP/1.0

### PR DESCRIPTION
**Pull request by VirtualTim**
I can't think of any reason to use HTTP/1.0 over HTTP/1.1.
Hopefully none of the tests depend on 1.0.

### CODE REVIEW

**Comment by VirtualTim** [comment]
`test_glgears_deriv` was the only failure. I'm assuming this is unrelated.

**Comment by kripken** [comment]
glgears is unrelated, yeah.

We do have few emrun tests, though, so I am not entirely confident in our test suite for this.

Do newer Python versions not user newer HTTP automatically? (If not, why?)

**Comment by VirtualTim** [comment]
The default in the python library emrun uses is HTTP/1.0. This the same for python 2 and 3. Apparently it's for backwards compatibility reasons.

I would think any clients that support Emscripten would support HTTP/1.1, since that's about 20 years old now.

[https://docs.python.org/3/library/http.server.html#http.server.BaseHTTPRequestHandler.protocol_version](https://docs.python.org/3/library/http.server.html#http.server.BaseHTTPRequestHandler.protocol_version)
[https://docs.python.org/2/library/basehttpserver.html#BaseHTTPServer.BaseHTTPRequestHandler.protocol_version](https://docs.python.org/2/library/basehttpserver.html#BaseHTTPServer.BaseHTTPRequestHandler.protocol_version)

The reason I wanted this is that I've started trying to integrate my work into a sdk which loads about 600 scripts. With HTTP/1.0 it's pretty slow to start, but with HTTP/1.1 able to reuse connections it should be better. I know I can webpack those scripts, but I'm trying to debug them, and obviously webpack makes that harder. Supporting HTTP/1.1 just seems like a trivial way to increase performance of the server.

**Comment by kripken** [comment]
Fair points. How about mentioning this in the changelog, to in theory help anyone that is surprised by this? lgtm with that.

**Comment by VirtualTim** [comment]
Ah good idea, I always forget about the changelog.

**Comment by kripken** [comment]
Great!

**Pull request merged**
