### PR TITLE
Add an option to avoid minifying imports and exports.

### PR DESCRIPTION
**Pull request by eyebrowsoffire**

### CODE REVIEW

**Comment by sbc100** [comment]
We do have an existing option called `DECLARE_ASM_MODULE_EXPORTS` which does already disable this minifiction, so perhaps that is best way forward.

See https://github.com/emscripten-core/emscripten/blob/19f691d5cbc03192bf921845a99d5279dea3d829/emcc.py#L2490-L2494

**Comment by sbc100** [comment]
https://github.com/emscripten-core/emscripten/blob/19f691d5cbc03192bf921845a99d5279dea3d829/src/settings.js#L266-L277

**Comment by sbc100** [comment]
Upon initial investigation it looks like `DECLARE_ASM_MODULE_EXPORTS=0` is perhaps not yet working/testing without `MINIMAL_RUNTIME`

**Comment by kripken** [comment]
There is already an internal setting for this, `MINIFY_WASM_IMPORTS_AND_EXPORTS`,

https://github.com/emscripten-core/emscripten/blob/e66f0e70efaf0db4af38ab1510f2833b11862e43/src/settings_internal.js#L162-L164

We could make it public perhaps?

**Pull request closed without merging**
