### PR TITLE
Add python version check for 2.7.12 and above

### LINKED ISSUE #8269: Emcc command error
I installed Emscripten using the instructions from the emscripten website and tried to run emcc  -v not sure what this error means. How do I fix it?
``` [emsdk]# emcc -v
Traceback (most recent call last):
File "/root/emsdk/emscripten/1.38.28/emcc.py", line 41, in <module>
from tools import shared, system_libs, client_mods, js_optimizer, jsrun
File "/root/emsdk/emscripten/1.38.28/tools/system_libs.py", line 676
system_libs_map = {l.shortname: l for l in system_libs}
^
SyntaxError: invalid syntax```

### PR DESCRIPTION
**Pull request by sbc100**
Fixes #8269

### CODE REVIEW

**Comment by dcodeIO** [comment]
Looks like this broke the binaryen.js buildbot because travis ci has 2.7.6 by default (which it worked with so far). Not really an issue ofc, but thought I mention it in case supporting travis out of the box is of interest.

**Comment by sbc100** [comment]
Hmm, was just going by what the docs say the requirement is:

https://emscripten.org/docs/building_from_source/toolchain_what_is_needed.html#emscripten-tools-and-dependencies

So unless we want to change that I would say we should probably fix the bots... I'm happy to take a look that if you like?

**Comment by dcodeIO** [comment]
Do you know where the exact requirement for 2.7.12 comes from? Just wondering because what the bot did so far worked with 2.7.6 as well.

For reference, adding the following to `.travis.yml` makes it compile again but also adds about a minute to build time:

```yaml
install:
- pyenv install 2.7.12 && pyenv global 2.7.12
```

**Comment by kripken** [comment]
I think 2.7.12 came from it being the first version that supports the current https stuff from github (which they upgraded at some point and it broke all our downloading from python, in older pythons).

**Comment by sbc100** [comment]
I'm actually surprised that travis doesn't have  more recent python.  Debian stable uses 2.7.13 (https://packages.debian.org/stretch/python) and the latest ubuntu LTS Ubuntu 18.04 has 2.7.1 (https://packages.ubuntu.com/bionic/python).   I guess maybe they are using the previous ubunto TLS which only has 2.7.11 (https://packages.ubuntu.com/xenial/python).

On a related a note I was really hoping to drop python2 support completely and mandate python3.

**Comment by brion** [comment]
Note that macOS 10.13/10.14 have python 2.7.10. To get things working I had to install Homebrew's python2 package, which provides a more up to date version.

**Comment by sbc100** [comment]
Another reason to switch to python3 only perhaps?  (Does macos ship with python3).

Also, does the emsdk ship its own copy of python on mac?  IIRC we do this on windows so that the version on the system is a non-issue.. not sure if we do this for mac too?

The default path for most of our users should be use the emsdk, so if non-emsdk user have to run brew install, its of somewhat less concern.

**Comment by brion** [comment]
No system python3 on macOS, either, just the out of date 2.7. :( Currently emsdk does not ship its own Python for Mac, so it's dependent on the system (or custom-installed) one. Probably should go ahead and bundle it, then can rely on newer versions or 3.x...

**Pull request merged**
