### PR TITLE
tests: improve maybe_closure() and use it more. NFC

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
This is needed fix a bunch of asan failures we are currently seeing on emscripten-releases.. the problem is that I recently added `--profiling` to the asan configuration but `--closure` + `--profiling` is currently a warning (with with `-Werror` an error).

**Comment by sbc100** [comment]
Do we care about `asan` + `--closure` coverage?  If so we could have `maybe_closure` remove the `--profiling` arg.

**Review by kripken — APPROVED** [review]
lgtm, but please verify if you haven't already that closure still runs in at least one test, that is, that there is no typo here that we are both missing. (as not running closure would have no noticeable effect)

**Comment by sbc100** [comment]
> lgtm, but please verify if you haven't already that closure still runs in at least one test, that is, that there is no typo here that we are both missing. (as not running closure would have no noticeable effect)

Done... 

I wonder if we should change 

```
-        logger.debug('using closure compiler..')
+        print('using closure compiler..')
```

 so it shows in the output by default?  Leaving it be for now.

**Pull request merged**
