### PR TITLE
Bump expected LLVM version from 18 to 19. NFC

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
I am planning on landing this without waiting for the full test suite to pass since its currently effecting all other PRs.

**Comment by curiousdannii** [comment]
What exactly does this mean when more recent PRs are still updating things to LLVM 18? (ex. https://github.com/emscripten-core/emscripten/pull/21638)

I'm investigating LTO with Rust which needs compatible LLVM versions.

**Comment by sbc100** [comment]
This is the version of the compiler that we depend on.   We basically always depend on LLVM/clang tip-of-tree and we integrate new revisions constantly (several times a day).

https://github.com/emscripten-core/emscripten/pull/21638 relates the version libc++, libc++-abi and libcompiler-rt, which also happen to live in the llvm tree, but are mostly independent of the compiler itself.   They get compiled and built into your wasm module.   For these libraries we pin the llvm stabe which changes only ever 6 months or so.

**Comment by curiousdannii** [comment]
Do you bump this variable basically immediately after version 18 is finished? I'm which case it's not useful for identifying when the compiler actually becomes incompatible for LTO? I wonder if there's any other way of knowing when LTO will be compatible, or if the only way is just to try it...

**Comment by sbc100** [comment]
> Do you bump this variable basically immediately after version 18 is finished? I'm which case I guess it's not useful for identifying when the compiler actually becomes incompatible for LTO.
> 
> I wonder if there's any other way of knowing when LTO will be compatible, or if the only way is just to try it...

I don't think llvm breaks LTO compatibility very often, but I'm also not sure that hey make any guarantees.

If you are worried about static libraries being compatible between emscripten versions, there are no guarantees here.   This is true regardless of LTO.  This is because the we don't make any guarantees about that libc or system APIs being ABI compatible between emscripten versions.

**Comment by sbc100** [comment]
You best bet is to avoid sharing libraries between emscripten versions completely.

**Comment by curiousdannii** [comment]
Right, I'm not using multiple Emscripten versions. I'm building a Rust staticlib and linking it into my Emscripten projects. The C ABI means they don't need equivalent LLVM versions, but cross language LTO won't be possible unless they start matching in the future some time.

**Comment by sbc100** [comment]
My understanding is that llvm don't really document when they break the bitcode/LTO ABI, so its hard to make guarantees.  Having said that I imagine it will work in most cases and should fail in obvious ways when it breaks.

It you are interesting in using emscripten with a stable version of llvm then see https://github.com/emscripten-core/emscripten/issues/11362, and maybe we can continue this conversation there?

**Pull request merged**
