### PR TITLE
Use `-pthread` compiler flag and associated _REENTRANT macro. NFC.

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
Have not tested this yet.. will rely on CI to test

**Comment by quantum5** [comment]
According to the [glibc documentation](https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html):

> Macro: _REENTRANT
> Macro: _THREAD_SAFE
> These macros are obsolete. They have the same effect as defining _POSIX_C_SOURCE with the value 199506L.
> Some very old C libraries required one of these macros to be defined for basic functionality (e.g. getchar) to be thread-safe.

**Comment by sbc100** [comment]
As far as I know, this is the way one detects the presence of the `-pthread` flag.   Its defined directly by the compiler (both gcc and clang) when `-pthread` is passed.  

Although to be fair thats the first time I'm seeing that its deprecated.

**Comment by dschuff** [comment]
I didn't know that either. AFAIK that's currently the only define that's different between wasm-clang's threaded and non-threaded predefined macros. We may want to consider adding something else if we don't want people depending on _REENTRANT to tell the difference.

**Pull request closed without merging**
