### PR TITLE
Bump ES version to 2020

### LINKED ISSUE #11303: Cannot use EXPORT_ES6=1 and USE_PTHREADS=1 at the same time
If I try to invoke emcc using both the EXPORT_ES6 and USE_PTHREADS flags, I receive an error relating to the acorn optimizer:

**Command**
`emcc file.cpp -o bin/file.js --bind -s MODULARIZE=1 -s EXPORT_ES6=1 -O3 -s USE_PTHREADS=1`

**Output**
```
C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:2780
  throw err
  ^

SyntaxError: 'import' and 'export' may only appear at the top level (61:6)
      import(e.data.urlOrBlob).then(function(PhysicsModule) {
      ^

    at Parser.pp$4.raise (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:2778:13)
    at Parser.pp$1.parseStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:831:16)
    at Parser.pp$1.parseBlock (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:1145:23)
    at Parser.pp$1.parseStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:825:34)
    at Parser.pp$1.parseIfStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:965:26)
    at Parser.pp$1.parseStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:814:31)
    at Parser.pp$1.parseBlock (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:1145:23)
    at Parser.pp$1.parseTryStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:1041:21)
    at Parser.pp$1.parseStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:818:32)
    at Parser.pp$1.parseBlock (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:1145:23) {
  pos: ?[33m2136?[39m,
  loc: Position { line: ?[33m61?[39m, column: ?[33m6?[39m },
  raisedAt: ?[33m2142?[39m
}
emcc: error: 'C:/emsdk/node/12.9.1_64bit/bin/node.exe C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\...\bin\physics.worker.js minifyWhitespace' failed (1)
```

Looks like it is complaining about this line in the outputted "bin/file.worker.js" file:
```
      import(e.data.urlOrBlob).then(function(Module) {
        return Module.default(Module);
      }).then(function(instance) {
        Module = instance;
        postMessage({ 'cmd': 'loaded' });
      });
```

### PR DESCRIPTION
**Pull request by RReverser**
Fixes #11303.

### CODE REVIEW

**Comment by sbc100** [comment]
Hmm.. looks like we need to update closure first.

I think we should that separately.  IIRC upgrading our closure version might not be trivial since we push up against all its limits and often hit its bugs.  But we should try.  Do you want to open a separate PR for that, or should I?

**Comment by RReverser** [comment]
Hmm, looks like this also needs an update of Closure Compiler. Not sure who'd be the best person to do this, perhaps @sbc100?

**Comment by RReverser** [comment]
Oh hah, almost at the same time :) I'd probably leave it to you, I have ~zero experience with Closure.

**Comment by RReverser** [comment]
@sbc100 Looks like the tests passed.

**Review by sbc100 — APPROVED** [review]

**Pull request merged**
