### PR TITLE
No warning for using setTimout while the document is hidden

### PR DESCRIPTION
**Pull request by cwoffenden**
The warning gets shown the next when the page is next visible. See #10051 for details.

### CODE REVIEW

**Comment by kripken** [comment]
Personally this looks good to me, as does the related PR @juj filed. I'm not opposed to both landing, or is there some incompatibility?

Side issue, this code should probably only be shown when `ASSERTIONS`; also it can use `warnOnce`.

**Comment by juj** [comment]
IE9 does not have [document.hidden](https://caniuse.com/#feat=mdn-api_document_hidden), not sure if that matters anything though, it'll just return `undefined` and avoid the print altogether, for the 0.001% of users.

Though I don't think this is a good way to fix, as whether the document is hidden or not should not have any effect on whether calling `emscripten_set_main_loop(func, 45, 0);` is a good idea or not.

**Comment by juj** [comment]
+1 for `warnOnce`

**Comment by kripken** [comment]
I thought the idea was that a timer that runs when the window is hidden is likely not one that you can replace with an RAF, as the RAF would not run at that time?

That seems reasonable to me, however, this does get complex and I'm unsure of size of the benefit.

**Comment by cwoffenden** [comment]
Closing because #10090 is a better approach.

**Pull request closed without merging**
