### PR TITLE
library_egl: enable proxying

### PR DESCRIPTION
**Pull request by jakogut**
Enable proxing EGL calls to main thread. Tested with `tests/test_egl.c` and `PROXY_TO_PTHREAD=1`.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks @jakogut! I think this is good, but perhaps @juj can take a look too.

Please add a test for this. Can maybe run that test you mention also in `PROXY_TO_PTHREADS` mode, we have a few tests like that already.

Please also add yourself to AUTHORS.

**Comment by jakogut** [comment]
@kripken Thanks for the review. For testing PROXY_TO_PTHREAD, this is what I'm thinking for wrapping and extending existing tests.

```python
  @requires_graphics_hardware
  def _test_egl_base(self, *args):
    create_test_file('test_egl.c', self.with_report_result(open(path_from_root('tests', 'test_egl.c')).read()))

    run_process([PYTHON, EMCC, '-O2', 'test_egl.c', '-o', 'page.html', '-lEGL', '-lGL', *args])
    self.run_browser('page.html', '', '/report_result?1')

  def test_egl(self):
    _test_egl_base()

  @requires_threads
  def test_egl_with_proxy_to_pthread(self):
      _test_egl_base('-s', 'USE_PTHREADS=1', '-s', 'PROXY_TO_PTHREAD=1')
```

**Comment by kripken** [comment]
Thanks! Testing looks good, I agree that's a nice approach.

Please merge latest incoming into here - there are some test failures from older incoming that should go away now.

**Comment by jakogut** [comment]
@kripken Done.

**Comment by kripken** [comment]
Thanks!

@juj, if you have time later, please take a look.

**Pull request merged**
