### PR TITLE
Fixing issues with pthread implementation

### PR DESCRIPTION
**Pull request by abujalski**
This PR aim at fixing some pthread implementation defects (in JavaScript glue layer) discovered when running POSIX tests from http://posixtest.sourceforge.net/ compiled to WebAssembly.

### CODE REVIEW

**Comment by VirtualTim** [comment]
Hey just so you know I'm working on a PR that implements/fixes detachable threads (and also fixes the leak in PThread.pthreads): #8286. Our changes look pretty independent, but I just thought you'd like to know.

**Comment by abujalski** [comment]
@VirtualTim thanks for info :)

**Comment by kripken** [comment]
@juj, can you please take a look at this one, you know this code the best?

**Comment by kripken** [comment]
I think this was closed by mistake when we deleted the incoming branch (after switching to master), sorry about that. If this PR is still relevant please reopen and retarget to master.

**Comment by abujalski** [comment]
I've checked and this PR is still relevant (tests from POSIX test suite hangs without this PR). However I've created new PR https://github.com/emscripten-core/emscripten/pull/10524 with these changes.

**Pull request closed without merging**
