### PR TITLE
[not for commit] Fetch: Calling runtimeKeepalivePop before user callbacks causes undesired runtime exit with sync fetch 

### PR DESCRIPTION
**Pull request by dschuff**
We got a report that when using synchronous fetch on a thread, the code after `emscripten_fetch()` returns wasn't being run (the thread was instead exiting after the user callback was called). I think what is happening is that we are decrementing the keepalive count in `runtimeKeepalivePop` (which reduces the count to 0) and then `calluserCallback` calls `maybeExit()` after the user callback returns, and exits the thread immediately rather than returning to the caller of emscripten_fetch().
That seems like the desired behavior in the async case (where the XHR callback is coming from the event loop and no user code is on the stack), but not right for the sync case where the user code is on the stack (you could perhaps think of that as being a reference that should keep the runtime alive).

But I checked and we have a test for this case (fetch/sync_xhr.cpp) and it's not failing for me locally or on the bots. Also I realized that we always want to return from `emscripten_fetch()` and `startFetch` even has a keepalivePush at the top which should be preventing. so maybe something else is going on there. 

Anyway I experimented with the change in this PR, but I don't think it's quite right.

### CODE REVIEW

**Comment by dschuff** [comment]
@sbc100 can you think of any reason the refcount could get to 0 and cause an exit after the success callback but before `emscripten_fetch()` returns?

**Comment by dschuff** [comment]
Actually the user said they are not even registering callbacks. But I don't think that actually matters because it looks like Fetch is attaching a callback (wrapped in `callUserCallback` to all of the XHRs anyway, which just do nothing if there are no user callbacks).

**Comment by sbc100** [comment]
I imagine its related to the EXIT_RUNTIME settings.   Does the test for synchronous fetch set this to 1 or 0?

**Comment by dschuff** [comment]
For me the behavior of sync_xhr is the same with EXIT_RUNTIME=1 or not. That setting doesn't affect the behavior of a thread anyway, does it? (I guess I failed to mention it but all of this is on a thread; the test also uses PROXY_TO_PTHREAD)

**Comment by dschuff** [comment]
I split out https://github.com/emscripten-core/emscripten/pull/13843 which should cover this behavior. With EXIT_RUNTIME=1 I'm seeing strange behavior when I run this test locally:

1) the pthread is in fact exiting (due to the counter reaching 0)
2) the worker is calling `PThread.threadExit` and the main thread is receiving the resulting message about pthread exit
3) the `"unwind"` exception is being thrown in `maybeExit`
4) the main thread is receiving the worker.onerror event with the text "Uncaught unwind"
5) the exception (despite being reported as uncaught to the main thread) is being swallowed by `xhr.send`, and it's returning as if nothing happened.
6) despite all of the above, the test is passing (both before and with this change); presumably because REPORT_RESULT was still being called before, and the result returns 0 now

Because the behavior of sync XHR calling callbacks while `xhr.send` is still on the stack is weird for the web platform, it might not necessarily be too surprising that `xhr.send` is not propagating the exception, although it is kind of surprising that the main thread is getting an onerror callback in that case, and it also doesn't explain why users are seeing behavior different from this. (Perhaps they have some other kind of error handler installed in the worker or main thread, that is shutting things down?). Either way the current behavior is wrong.

We discussed offline and think that maybe the best fix for the runtime-exit behavior is to have an argument to `callUserCallback` that would make it just call the function without wrapping it in a try/catch or calling `maybeExit` (i.e. give it a synchronous mode). It could potentially also do the `runtimeKeepalivePop` itself to save code size.

**Comment by dschuff** [comment]
I think this is fixed now.

**Pull request closed without merging**
