### PR TITLE
Update libcxx and libcxxabi to LLVM 15

### PR DESCRIPTION
**Pull request by sbc100**
Fixes: #17680

### CODE REVIEW

**Comment by kripken** [comment]
Looks good in general, but any idea what's going on with the metadce regressions? The new appearances of `__cxa_allocate_exception` and `malloc` etc. look worrying, and the code size.

**Comment by sbc100** [comment]
> Looks good in general, but any idea what's going on with the metadce regressions? The new appearances of `__cxa_allocate_exception` and `malloc` etc. look worrying, and the code size.

I did try to investigate but nothing jumped out as suspicious.  It looked like the result of normal libc++ chrurn.  I can re-do my investigation and post the result here maybe.

One thing to note is that only a single one of the codesize and metadata test regressed, so this doesn't effect all programs.

**Comment by sbc100** [comment]
Looking into the regression it seems that the difference is that  `std::__throw_length_error` is being included at compile time with the new libc++,    Then we get __throw_length_error -> __cxa_allocate_exception + __cxa_throw which also leads to malloc being included.

I spend a bunch of time investigating but I couldn't pin down why the old code was able to avoid `__throw_length_error` and why the new code was not able to.

If I build with `-fno-exceptions` then the differences go away, and it seems that any reasonably complex C++ program that isn't built with `-fno-exceptions` will most likely depend on `__cxa_allocate_exception`.. so I'm temped to declare my investigations over.   It seems like adding and/or removing a dependency on `__throw_length_error` for a given program is within the set of changes one might expect from a libc++ change in general.

**Comment by kripken** [comment]
I see, thanks for investigating. Yes, that seems reasonable, lgtm.

**Pull request merged**
