### PR TITLE
Not all DeviceMotionEvent fields are necessarily supported

### PR DESCRIPTION
**Pull request by juj**
Not all browsers support all DeviceMotionEvent fields on all devices. Microsoft Edge is reported to not have DeviceMotionEvent.acceleration on some devices, and in https://developer.mozilla.org/en-US/docs/Web/API/DeviceMotionEvent/acceleration, see also specific note 'Note: If the hardware doesn't know how to remove gravity from the acceleration data, this value may not be present in the DeviceMotionEvent. In this situation, you'll need to use DeviceMotionEvent.accelerationIncludingGravity instead.'

### CODE REVIEW

**Comment by kripken** [comment]
If I understand correctly, this puts the burden of Edge support on the user (who needs to state that certain fields are or are not supported)? I guess there isn't a way to support this automatically?

(btw, as newer Edge is Chromium-based, so this problem should go away I assume, might be worth adding a comment that this is just for older Edge and can be removed eventually)

**Comment by juj** [comment]
The limitation that DeviceMotionEvent might not contain a field `acceleration` for example is probably not an Edge limitation, but rather a limitation of the particular devices (that our Unity users have been running on that reported the problem) - presumably not all devices have a physical accelerometer that separates gravity. The official specification of DeviceMotionEvent says that the unsupported fields may be omitted - so it is something that the web spec acknowledges. In that light, even though we have only observed this issue for Edge, it is possible that other browsers may have the same behavior on some mobile devices, although since I don't have such a device to check, I can't verify.

Nevertheless, since the web spec states that not all the fields need to be present, this seems like the correct thing to do for all browsers. (we should seek a spec change if we want to unconditionally rely on all the fields needing to be present?)

**Comment by kripken** [comment]
This does seem like a problem in the spec, yeah, but I'm still not sure I get how this works. How are you actually using this in Unity - what do you use to decide which fields to tell the API  are not present?

**Comment by juj** [comment]
> How are you actually using this in Unity - what do you use to decide which fields to tell the API are not present?

When the browser does not support acceleration without gravity, the HTML5 API will then not have the bit `EMSCRIPTEN_DEVICE_MOTION_EVENT_SUPPORTS_ACCELERATION` present in the `supportedFields` enum, in which case we disable accelerometer support. (Unity only utilizes acceleration without gravity, but some other applications might be able to look at that bit and then fall back to acceleration with gravity)

**Comment by kripken** [comment]
I see, thanks, lgtm.

**Pull request merged**
