### PR TITLE
Enable -sASYNCIFY + -sMEMORY64=2

### PR DESCRIPTION
**Pull request by sbc100**
It turns out that simply running the memory64 lowering pass after the asyncify pass is enough to make this work.

### CODE REVIEW

**Comment by sbc100** [comment]
@dakenf

**Review by kripken — APPROVED** [review]
Nice this works so easily... I see we already made Asyncify track the pointer type of its memory, so makes sense it should work to run Asyncify first. I am slightly curious why running it second fails...

**Comment by sbc100** [comment]
> Nice this works so easily... I see we already made Asyncify track the pointer type of its memory, so makes sense it should work to run Asyncify first. I am slightly curious why running it second fails...

The asyncify pass creates a bunch of helper functions (and a global) that use the current pointer size (based on the index size of the memory), and we want that pointer size to be i64 ... even when using the memory64 lowering pass.  This is because the API used by `-sMEMORY64=2` with the outside world is still "pointers are i64".   The lowering pass is designed only to effect the loads and stores.   Any function that take pointers should use i64 and any global that holds a pointer should be i64.. even after lowering.   If we lower first, then asyncify assumes (wrongly) that pointers are i32.

**Comment by kripken** [comment]
I see, thanks. We could make it track pointer types for those globals, I guess, but this seems like a good enough solution.

**Comment by sbc100** [comment]
> I see, thanks. We could make it track pointer types for those globals, I guess, but this seems like a good enough solution.

Those globals do track the pointer type, but the problem is that after wam64 lowering binaryen's method of detecting what the pointer type of the program is no longer works and gives the wrong result.  This is because the pointer type stays constant (i64) but the memory index is converted to i32.   

Note: The lowering pass does not change the pointer type per-say, but just adds pointer truncation to every load/store.

**Comment by sbc100** [comment]
One option would be to add a "--force-pointer-type=i64" to binaryen to override its auto-detection.   But doing the lowering last seems simpler.

**Pull request merged**
