### PR TITLE
[WasmFS] mmap: avoid setting *allocated too early

### PR DESCRIPTION
**Pull request by kleisauke**
Setting `*allocated` here is probably too early, as read errors
may occur (causing the pointer to be `free()`'d).

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Good catch!

**Comment by kleisauke** [comment]
It seems that CI failed, not related to this change. Should I restart it or rebase this PR?

**Comment by kleisauke** [comment]
FWIW, `test-mac` failed with `This job was rejected because the image is unavailable` due to the macOS image deprecation on CircleCI, see:
https://status.circleci.com/incidents/q2cp3cspv6by
https://github.com/emscripten-core/emscripten/blob/9c127fea199b4ec720134c9b95b8404f2ad56981/.circleci/config.yml#L26

**Comment by kripken** [comment]
Thanks, I'll open a PR to update the xcode image then.

**Comment by kripken** [comment]
Regardless of the xcode error I think this can land, landing.

**Pull request merged**
