### PR TITLE
Rename `-sTOTAL_STACK` to `-sSTACK_SIZE`

### PR DESCRIPTION
**Pull request by sbc100**
This name seems to be more obvious/accurate.

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Sounds better. I guess `TOTAL_STACK` used to make sense alongside `TOTAL_MEMORY` but we improved that one already.

**Comment by dschuff** [comment]
I don't see a part of the change that keeps TOTAL_STACK as an alias?

**Comment by sbc100** [comment]
See  LEGACY_SETTINGS in settings.js

```
// For renamed settings the format is:
// [OLD_NAME, NEW_NAME]
```

**Comment by dschuff** [comment]
oh sure enough, I just missed it; thanks

**Pull request merged**
