### PR TITLE
[port] [contrib.glfw3] Add compile time define

### PR DESCRIPTION
**Pull request by ypujante**
In a project that wants to use my port, the issue is that the user can use either the built-in glfw3 port (`-sUSE_GLFW=3`) or the new one (`--use-port=contrib.glfw3`). There is a (somewhat hacky) way to figure out at runtime which port is being used (using the `glfwGetVersionString()` call). But there is no compile time way. And since this project does not want to force their user to use the new port, there needs to be a way to distinguish at compile time...

Hence this PR which adds the define `EMSCRIPTEN_USE_PORT_CONTRIB_GLFW3` when compiling with the new port.

```
// example
./emcc --verbose --use-port=contrib.glfw3 ./test/hello_world.cpp -o /tmp/index.js
 "/usr/local/emsdk/upstream/bin/clang-19" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all 
-disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name 
hello_world.cpp -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math 
-mconstructor-aliases -target-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/usr/local/emsdk/emscripten/main 
-v -fcoverage-compilation-dir=/usr/local/emsdk/emscripten/main -resource-dir /usr/local/emsdk/upstream/lib/clang/19 -isystem /usr/local/emsdk/emscripten/main/cache/sysroot/include/contrib.glfw3 
-D EMSCRIPTEN -D EMSCRIPTEN_USE_PORT_CONTRIB_GLFW3 
-isysroot /usr/local/emsdk/emscripten/main/cache/sysroot -I/usr/local/include -internal-isystem /usr/local/emsdk/emscripten/main/cache/sysroot/include/wasm32-emscripten/c++/v1 
-internal-isystem /usr/local/emsdk/emscripten/main/cache/sysroot/include/c++/v1 
-internal-isystem /usr/local/emsdk/upstream/lib/clang/19/include 
-internal-isystem /usr/local/emsdk/emscripten/main/cache/sysroot/include/wasm32-emscripten 
-internal-isystem /usr/local/emsdk/emscripten/main/cache/sysroot/include -Werror=implicit-function-declaration 
-fdeprecated-macro -ferror-limit 19 -fvisibility=default -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf 
-fcxx-exceptions -fignore-exceptions -fexceptions -fcolor-diagnostics -iwithsysroot/include/fakesdl 
-iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj 
-mllvm -disable-lsr -o /var/folders/wz/zqhny4ks031bqlr6r27bfkzm0000gn/T/emscripten_temp_obwaqlpy/hello_world_0.o -x c++ ./test/hello_world.cpp
```

### CODE REVIEW

**Comment by ypujante** [comment]
Failing tests are:

```
# test-other
======================================================================
FAIL [0.001s]: test_pthread_print_override_modularize (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/root/project/test/common.py", line 324, in decorated
    f(self, *args, **kwargs)
  File "/root/project/test/common.py", line 175, in modified
    raise AssertionError('Flaky test has failed too many times') from preserved_exc
AssertionError: Flaky test has failed too many times

# test-browser-chrome
======================================================================
FAIL [3.043s]: test_wasmfs_opfs_jspi (test_browser.browser)
----------------------------------------------------------------------
...
======================================================================
FAIL [3.028s]: test_wasmfs_opfs_jspi_wasm_bigint (test_browser.browser)
----------------------------------------------------------------------
...
```

They are unrelated to my changes

**Comment by ypujante** [comment]
I merged with main branch and now all tests are passing.

**Comment by Jeremy-Boyle** [comment]
Hello, came here from your imgui post, 

When adding -g for dwarf debugging it seems that using --use-port=contrib.glfw3 breaks the compile.

Are you seeing the same thing? when switching just to -s USE_GLFW=3 -g works fine.

**Comment by ypujante** [comment]
Hey @Jeremy-Boyle , can you delete this comment and post it on the pongasoft/emscripten-glfw project instead? I don't want to pollute this PR with unrelated items. Thank you

**Comment by Jeremy-Boyle** [comment]
> Hey @Jeremy-Boyle , can you delete this comment and post it on the [pongasoft/emscripten-glfw](https://github.com/pongasoft/emscripten-glfw) project instead? I don't want to pollute this PR with unrelated items. Thank you

I was able to figure it out, comment removed due to it being unrelated to this PR.

**Comment by sbc100** [comment]
Could you perhaps just define this, or something like it, in your glfw header?

**Comment by sbc100** [comment]
I don't have a strong opinion.  I seems easy to modify your `glfw3.h` and I don't think you need to be supporting folks that want to use their own header with your version of the library.. that sounds strange.  However, we also just land this if you prefer.

**Comment by ypujante** [comment]
Since this change is isolated to `contrib/glfw3.py` and simply add a define to the command line, I can still work on the other solution of changing "GLFW/glfw3.h" and adding the define there, and then remove the define on the command line when I push the port change for the new version of the contrib port: that would be a totally transparent change to the user.

So yes, if you could merge this now so that it unblocks my progress with the other PR in ImGui. And then I can revisit it in another PR later on.

Thank you for your feedback and point of view. It is always much appreciated.

**Review by sbc100 — APPROVED** [review]

**Pull request merged**
