### PR TITLE
Fix binding for wgpuDeviceCreateQuerySet

### PR DESCRIPTION
**Pull request by DDoS**

### CODE REVIEW

**Review by kainino0x — APPROVED** [review]
Thanks!

**Comment by kripken** [comment]
Side question: @kainino0x how did you do the `Merge branch 'main' into main` operation? I don't think I've ever seen that before (in this situation where you aren't the PR author).

(and thanks for the quick review!)

**Comment by kainino0x** [comment]
I used the "Resolve conflicts" button on GitHub. You can commit to the PR source branch (either online or via git push) as long as the PR author checked the "Allow edits and access to secrets by maintainers" box when creating the PR.

**Comment by kripken** [comment]
Got it, thanks @kainino0x !

**Pull request merged**
