### PR TITLE
Remove usages of deprecated `EM_ASM` variants.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This is a precursor to trying to remove the actual definitions again. I already submitted changes to SDL3 and they were back ported to SDL2. But at least we can clean up this part now...

**Review by kripken — APPROVED** [review]

**Comment by sbc100** [comment]
Do we flag these as deprecated at build time using some kind of clang attribute?    Either way I wonder if its worth adding a test specifically for the deprecated name, at least until they are actually removed?

**Comment by kripken** [comment]
I didn't see a clang attribute on these, but in the header they are described as deprecated,

https://github.com/emscripten-core/emscripten/blob/da0a1e9a8b640a4257fec4874f796373ae38fb21/system/include/emscripten/em_asm.h#L262-L268

A test for this sgtm, though I could go either way as in the worst case if we break this the advice we'd give the user reporting it is to use the new EM_ASM forms. So it's not silent breakage, and only affects legacy code. (But if we get such a report, that would indicate something is missing from our docs I guess...).

**Comment by sbc100** [comment]
I don't think we necessarily need test for these.   It would be cool if there was some way to have clang complain when they are used though.. (I seem to remember such as thing exists, but I don't remember it of the top of my head).

**Comment by kripken** [comment]
There is [deprecated](https://clang.llvm.org/docs/AttributeReference.html#deprecated), maybe you mean that? Maybe we can use those, but these are `#defines` as quoted above so we'd need to add a layer of indirection I guess, so there is a function to put the attribute on.

**Comment by sbc100** [comment]
> There is [deprecated](https://clang.llvm.org/docs/AttributeReference.html#deprecated), maybe you mean that? Maybe we can use those, but these are `#defines` as quoted above so we'd need to add a layer of indirection I guess, so there is a function to put the attribute on.

Indeed, I was hoping for a way to mark pre-processor macro as deprecated.. (IIRC it does exist).

**Pull request merged**
