### PR TITLE
Add missing opt flags to system libraries

### PR DESCRIPTION
**Pull request by kripken**
We forgot to add these in a few cflags options for system libraries. I noticed
this because of wasmfs, where I read the emitted code and it looked very
unoptimized.

I doubt this matters much except for wasmfs. Testing there I see it reduce
code size by almost half.

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by kripken** [comment]
Perhaps we could have a default of `-O2` that libraries can override. Or maybe we could add an assertion that verifies we specified some opt level. Either sgtm (as a followup?)

For this PR, it looks like one wasmfs now crashes, `other.test_wasmfs_getdents` - my first guess is that the optimizer is finding some undefined behavior there...

**Comment by kripken** [comment]
Stack trace is

```
RuntimeError: Aborted(native code called abort())
    at abort (/tmp/emscripten_test_other_adq_bgrk/wasmfs_getdents.js:1501:11)
    at _abort (/tmp/emscripten_test_other_adq_bgrk/wasmfs_getdents.js:1900:7)
    at std::__2::__throw_bad_weak_ptr() (<anonymous>:wasm-function[26]:0x15e8)
    at wasmfs::FileTable::Handle::Entry::locked() (<anonymous>:wasm-function[24]:0x153c)
    at __syscall_getdents64 (<anonymous>:wasm-function[43]:0x338e)
    at getdents (<anonymous>:wasm-function[176]:0x9ac0)
    at print (<anonymous>:wasm-function[18]:0x67b)
    at __original_main (<anonymous>:wasm-function[19]:0x91e)
    at main (<anonymous>:wasm-function[20]:0x107d)
```
so it looks like a weak_ref bug...

**Comment by sbc100** [comment]
> Perhaps we could have a default of `-O2` that libraries can override. Or maybe we could add an assertion that verifies we specified some opt level. Either sgtm (as a followup?)
> 
> For this PR, it looks like one wasmfs now crashes, `other.test_wasmfs_getdents` - my first guess is that the optimizer is finding some undefined behavior there...

Yes, lets leave that for a followup.

**Comment by kripken** [comment]
WasmFS opts were added in #15738 so this just adds the remaining two libraries now.

**Pull request merged**
