### PR TITLE
Use default browser for emrun on macOS

### LINKED ISSUE #8179: emrun Default Browser
By default on macOS, `emrun` always opens Safari. However, simply [removing `-a Safari` here](https://github.com/emscripten-core/emscripten/blob/3e0c3e129d4534f099412c810bbcad6208a95031/emrun.py#L1562) would open the URL with the user's default browser! For example, if you have Chrome set as your default browser, it would just open up a new tab as expected, rather than using Safari by default. AFAIK, there isn't currently any way to change the **default** browser except for passing `--browser` every time.

I would open a PR to fix this, but the `emrun` script is a bit convoluted IMHO, and I don't want to break anything/anybody's workflow. If using the browser set in `System Preferences` would not be a good idea, maybe the best way would be setting an environment variable to override the default browser? Or maybe both; an environment variable, if set, overrides System Preferences. IMHO either way is better than having [a hardcoded default of Safari](https://github.com/emscripten-core/emscripten/blob/3e0c3e129d4534f099412c810bbcad6208a95031/emrun.py#L1458). Thoughts?

### PR DESCRIPTION
**Pull request by Coder-256**
Fixes #8179.

This works due to what seems to be existing, unfinished [support for the default browser on macOS](https://github.com/emscripten-core/emscripten/blob/922cd57cf9a8e4d62c817f33f54add841d39d273/emrun.py#L1092-L1093).

### CODE REVIEW

**Comment by Coder-256** [comment]
I think the test fails are unrelated because they're Linux

**Comment by kripken** [comment]
Thanks!

Yeah, test failures are unrelated (was temporary breakage on incoming earlier).

If this works for you on MacOS it sounds good to me to land. Unless anyone else has thoughts?

Oh, and please add yourself to AUTHORS before we merge.

**Comment by Coder-256** [comment]
@kripken Sorry for the late reply. Thanks for the feedback, I added myself to `AUTHORS` and double-checked that it works for me on macOS. I think this is probably ready.

**Comment by kripken** [comment]
Thanks @Coder-256!

**Pull request merged**
