### PR TITLE
Take advantage of JS default parameters in JS library code. NFC

### PR DESCRIPTION
**Pull request by sbc100**
I used `git grep -P "\w* = \w* \|\|" src/` to find these but there may be other patterns I missed.

See #18545

### CODE REVIEW

**Review by juj — APPROVED** [review]
Awesome!

**Review by kripken — APPROVED** [review]

**Review by RReverser — APPROVED** [review]

**Comment by RReverser** [comment]
Btw I see this didn't cover the `Module = {}` stuff we discussed in https://github.com/emscripten-core/emscripten/pull/18528, is it intentional?

**Comment by sbc100** [comment]
I will update #18528 use use default params now.   As it stands, prior to #18528, the local and param have different names so it made more sense to me to update #18528.

**Comment by sbc100** [comment]
Oh wait, your are right, I should have done that as part of this PR.

**Pull request merged**
