### PR TITLE
Refactor the threading.h C proxying API

### PR DESCRIPTION
**Pull request by tlively**
Refactor the C proxying API to separate the proxying logic from the logic for
creation and use of em_queued_call objects. Also provide a richer and more
orthogonal set of `emscripten_dispatch_to_thread_*` variants:

 - emscripten_dispatch_to_thread - send a task to a thread for asynchronous
   execution.

 - emscripten_dispatch_to_thread_async - same, but schedule for asynchronous
   execution even if already on the target thread.

 - emscripten_dispatch_to_thread_sync - wait for the dispatched function to
   finish before returning.

 - emscripten_dispatch_to_thread_async_as_sync - wait for the dispatched task to
   be marked finished via an explicit call to `emscripten_async_as_sync_finish`.

Each of these functions comes in a lower-level `*_ptr` variant that accepts
function pointers and void* arguments as well as higher-level variants that
construct and dispatch `em_queued_call` objects.

Each variant builds incrementally on some other variant, all bottoming out at
`emscripten_dispatch_to_thread_ptr`, so it should be easy to incrementally
understand how each layer works. The other miscellaneous proxying functions
exposed in threading.h are now implemented in terms of the most appropriate
`emscripten_dispatch_to_thread*` variant as well.

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
`threading.h` changes look nice!

Before I start to read the code, the description mentions both a refactoring and the addition of new things. Could this be split into a NFC refactoring in an initial PR?

**Comment by tlively** [comment]
I can split out a few things, yes. Others would be more difficult to split out because they are now implemented in terms of the new functions. I just reopened https://github.com/emscripten-core/emscripten/pull/15648 as a first step. I'll make another preliminary PR or two.

**Comment by tlively** [comment]
Just added a commit to fix some tests. First, the code size increased and the exports changed in the metadce test. Second, `emscripten_dispatch_to_thread` now returns 1 if the call was successfully scheduled while previously it only returned 1 if the call was synchronously executed so a test expectation had to be updated.

 I'm still investigating the posixtest.test_pthread_setcanceltype_1_1 failure.

The tests I just fixed were the

**Comment by tlively** [comment]
Another preliminary NFC change: #15686

**Comment by tlively** [comment]
Another smaller change, this one not NFC: #15690

**Comment by tlively** [comment]
Another NFC change: #15691.

**Comment by tlively** [comment]
Closing this in favor of the plan in https://github.com/emscripten-core/emscripten/pull/15705#issuecomment-985884887.

**Pull request closed without merging**
