### PR TITLE
[WasmFS] Implement `fdatasync`

### LINKED ISSUE #16672: WasmFS: `fdatasync`
[man page](https://man7.org/linux/man-pages/man2/fdatasync.2.html)

### PR DESCRIPTION
**Pull request by tlively**
As an alias for `__wasi_fd_sync` (i.e. `fsync`). This flushes data more
conservatively than necessary, but it's not worth maintaining a separate code
path to avoid flushing file metadata right now.

Resolves #16672.

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
lgtm % testing

Is the new test because the existing test that covers this (`unistd/misc.c`) also tests other stuff we don't pass? Or because we want more fine-grained testing?

The existing test also checks for an error so if we want a new test we should add that here too.

If this test is temporary please add a TODO to remove it. If it's meant to be permanent then let's remove the relevant lines from the existing test?

**Comment by kripken** [comment]
Oh, the new test is not enough to replace the old because the new one is wasmfs-only?

**Comment by tlively** [comment]
I'll add a TODO to remove this test in favor of unistd/misc.c and make it WasmFS-only since there's no reason to run this test on the classic FS.

**Comment by tlively** [comment]
Merging given previous LGTM.

**Pull request merged**
