### PR TITLE
Fix test_minimal_runtime_export_all_modularize not working on Windows

### PR DESCRIPTION
**Pull request by DavidPeicho**
Fixes: #18596

### CODE REVIEW

**Comment by DavidPeicho** [comment]
Don't have a Windows available, not sure why all the tests are red here

**Comment by sbc100** [comment]
Sorry about all the unrelated test failures.  We are in the middle of an llvm version update.

**Comment by DavidPeicho** [comment]
@sbc100 Is the Windows CI the same as the one that failed in #17911?

Just to know if this green build is reliable

**Comment by DavidPeicho** [comment]
Done! Just wanted to be sure it's not going to fail again 😄

**Pull request merged**
