### PR TITLE
Upgrade musl floatscan.c to latest, which fixes some bugs

### PR DESCRIPTION
**Pull request by kripken**
We don't seem to have a readme.txt for musl with a list of local changes, not sure if this should be mentioned anywhere?

### CODE REVIEW

**Comment by sbc100** [comment]
Mention in system/lib/libc/musl/readme?

**Comment by kripken** [comment]
Do you mean to create a new file at that location, and mention this there? (there isn't one atm - we don't seem to have ever maintained a log of local changes, and to just annotate in the source if at all)

**Comment by sbc100** [comment]
We have system/lib/libc/README.md... looks like it lists the backports there

**Comment by kripken** [comment]
Thanks! Not sure how I missed that when I looked before...

**Pull request merged**
