### PR TITLE
Bump v8 to 9.1.269, update V8 flags for SIMD

### PR DESCRIPTION
**Pull request by ngzhian**
--experimental-wasm-simd is no longer needed for v8.

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by kripken** [comment]
I think we agreed to stop pinning when possible? Looks like the breakage back then has been fixed, so we can resume using latest jsvu.

To recap my argument for that, breakage is pretty rare, and when it happens, we want to know about it - no other system would detect it so early and prevent v8 regressions.

**Comment by ngzhian** [comment]
> I think we agreed to stop pinning when possible? Looks like the breakage back then has been fixed, so we can resume using latest jsvu.

Sg, I reverted my update, and also reverted the original change that pinned the version.

**Comment by sbc100** [comment]
sgtm.   I wish there was some way we could leave the pinning logic in there for next time we need to do it.. but I don't see any easy way without making the logic more complicated.

**Comment by ngzhian** [comment]
We could leave a comment pointing to https://github.com/emscripten-core/emscripten/commit/0bc3640ac8e0772f7e3bc22f2e503229aaaec2af so it is easier to make the changes next time we need to pin?

**Comment by sbc100** [comment]
> We could leave a comment pointing to [0bc3640](https://github.com/emscripten-core/emscripten/commit/0bc3640ac8e0772f7e3bc22f2e503229aaaec2af) so it is easier to make the changes next time we need to pin?

Maybe yes.. I'm fine with this either way.

**Review by kripken — APPROVED** [review]

**Pull request merged**
