### PR TITLE
Refactor debug info tests

### PR DESCRIPTION
**Pull request by dschuff**
Previously different tests verified the existence of DWARF, sourcemap, and name section output, for non-overlapping sets of flags. This refactoring unifies the testing logic for the 3 forms of debug info and adds a few combinations.

It doesn't change tests that verify the DWARF contents or JS output.

### CODE REVIEW

**Comment by dschuff** [comment]
Also a question for the author of [test_debuginfo](https://github.com/emscripten-core/emscripten/blob/main/test/test_other.py#L2576) (who I thought was @kripken but actually appears to be @sbc100): This test appears to be verifying whether wasm-emscripten-finalize gets passed the `-g` flag or not. Is this independently useful outside of verifying the outputs? Are there other properties of the actual emcc output that we should check that would make a test of internal flags unnecessary?

**Comment by sbc100** [comment]
> Also a question for the author of [test_debuginfo](https://github.com/emscripten-core/emscripten/blob/main/test/test_other.py#L2576) (who I thought was @kripken but actually appears to be @sbc100): This test appears to be verifying whether wasm-emscripten-finalize gets passed the `-g` flag or not. Is this independently useful outside of verifying the outputs? Are there other properties of the actual emcc output that we should check that would make a test of internal flags unnecessary?

If we verify that debug info is actually preserved in the output I don't see any reason to verify if the `-g` flag is passed internally..  I think that answers your question?

**Review by kripken — APPROVED** [review]
Nice!

**Comment by kripken** [comment]
Maybe testing for `wasm-emscripten-finalize -g` has some performance benefit, to see we don't pass `-g` and later strip the debug info at the end. But that seems very minor. So I agree that test looks redundant.

**Comment by dschuff** [comment]
Great thanks, that's what I suspected. I'm working on fixing `-gsource-maps` with ERROR_ON_WASM_CHANGES_AFTER_LINK, so I may remove or tune that test in the next PR.

**Review by aheejin — APPROVED** [review]

**Pull request merged**
