### PR TITLE
Update list of supported extensions

### PR DESCRIPTION
**Pull request by ngzhian**
SSE3 and SSSE3 added in 17960af5ea7c0ff1ef82eb1a9a4d46d3eda29233.
SSE4.1, SSE4.2, and 128-bit AVX added in
968c7a557dcb7b8e332e5b990bc600ea417c4602.

### CODE REVIEW

**Comment by ngzhian** [comment]
@juj fyi @tlively for review, ptal, thanks!

**Review by tlively — APPROVED** [review]
Excellent, thanks for this fix! Will merge if @juj agrees.

**Review by juj — APPROVED** [review]

**Comment by juj** [comment]
Great, thanks!

**Comment by juj** [comment]
Btw, the GitHub UI says "First-time contributors need a maintainer to approve running workflows.". This suggests that your contributor information might not reside in AUTHORS? If so, can you add your info?

**Comment by ngzhian** [comment]
Added, thanks!

**Comment by tlively** [comment]
Thank you both!

**Pull request merged**
