### PR TITLE
Update SDL2

### PR DESCRIPTION
**Pull request by kripken**
This updates it to the very latest there.

I used a direct commit hash like we do for other ports. The old
`version_x` notation doesn't seem to actually add much (aside
from extra work to add the tag).

@Daft-Freak - is now a good time to do this, or are there
pending changes or something else?

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Hmm, `version_24` == `6a72595649456d1aaa8d15e152c830aab1c4c422`, so this isn't actually updating anything, right?

Don't think there are any pending changes, though I should really resync with upstream at some point.

**Comment by kripken** [comment]
@Daft-Freak Oh, good point! I'm not sure how I missed that... yeah, this doesn't actually do anything.

I assumed there were changes since I saw some issue go by that mentioned updating. But I guess that was changes from upstream?

**Comment by Daft-Freak** [comment]
Ah, there is an issue about updating to latest upstream. SDL moving to git has made that harder (different history to the old mirror, can't merge).

I've managed to rebase on the new repo [at the version the ports repo is currently at](https://github.com/Daft-Freak/SDL/tree/em-2.0.10) (no changes), but that's in a new fork... [Also attempted an update](https://github.com/Daft-Freak/SDL/tree/em-2.0.14), but untested and probably requires changes to the file list.

**Comment by kripken** [comment]
Oh, interesting they switched to git...

Do we have any local changes at all compared to upstream? If not, we can just make our ports look directly at a specific commit in upstream.

If we do have local changes, then maybe it would be easiest to create a new repo in ports (`SDL2-git`?) that switches to git, and includes cherry-picks of our local changes?

**Comment by Daft-Freak** [comment]
Just a few compared to upstream `main`: https://github.com/libsdl-org/SDL/compare/main...Daft-Freak:em

Audio fix should go upstream, I just haven't done it yet. The config.h possibly too (but would need updated). We've had the timer patches downstream for quite a while and I don't remember why they're not upstream... Maybe they need some improving to not #ifdef out most of the file? (They're also only relevant with threads disabled)

**Pull request closed without merging**
