### PR TITLE
escape single quotes in file paths

### PR DESCRIPTION
**Pull request by revmischa**
If a file name contains a `'` then the file preloading basename arg explodes. Untested.

### CODE REVIEW

**Comment by kripken** [comment]
@revmischa - sorry this got forgotten for so long! I think it's still a useful fix. Are you still interested to work on it? If not I can pick it up.

**Comment by revmischa** [comment]
I wouldn't really know how to help but go for it

**Comment by revmischa** [comment]
Can someone review this please?

**Comment by revmischa** [comment]
Reopened in #9754

**Pull request closed without merging**
