### PR TITLE
Initialize emmalloc of first use rather than via a static ctor. NFC

### PR DESCRIPTION
**Pull request by sbc100**
This costs one extra branch each time the emmalloc lock is acquired
(i.e. on each emmalloc entry point), but avoids the issue of ordering
the ctors WRT to each other, which is currently breaking the pthreads
build.  It also delays the cost of initalizing emmalloc until it is
actually needed.

Also, make `emmalloc_blank_slate_from_orbit` thread safe like the
rest of the emmalloc functions.

Fixes: #14766

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
Could we adjust the global ctor priority of the other things, as an alternative to this?

If not, then this might be good to benchmark. An extra branch doesn't seem that bad, but it would be good to confirm on e.g. the Havlak benchmark which stresses many mallocs/frees.

**Comment by sbc100** [comment]
> Could we adjust the global ctor priority of the other things, as an alternative to this?
> 

That is an alternative yes but I think its worse overall, considering the pros and cons of both approaches.

> If not, then this might be good to benchmark. An extra branch doesn't seem that bad, but it would be good to confirm on e.g. the Havlak benchmark which stresses many mallocs/frees.

Sure I will run that, but it seem very unlikely that single branch is going to make any measurable difference.

**Comment by kripken** [comment]
lgtm with that benchmarking. But what is the downside of reordering the ctors? (Are they hard to find, or we expect more to be added, or something else?)

**Comment by sbc100** [comment]
> lgtm with that benchmarking. But what is the downside of reordering the ctors? (Are they hard to find, or we expect more to be added, or something else?)

ctors are a less elegant solution in my mind for several reasons:

1. They are harder to DCE (if any function in the object is needed the ctor is *always* needed even, i.e. the dependency that pullis it is on the granularity of the object file, not that actual direct usage)
2. ctors like this require carefull global ordering (the fewer we have the better).
3. The cost is paid up front instead of on-demand.    i.e.  for a program that calls malloc on some runs but not on others, this is wasted work.
4. They rely on the rather mysterious and not-really-specified ctor numbering/ordering rather than normal C language features.  This hurts readability IMHO.

**Comment by kripken** [comment]
Good points. sgtm.

**Comment by juj** [comment]
> Sure I will run that, but it seem very unlikely that single branch is going to make any measurable difference.

The branch is awkward, I find it is worse code design, and increases code size.

We have been able to work with the malloc priority ctor before, why can't we use that anymore?

**Comment by juj** [comment]
> 1. They are harder to DCE (if any function in the object is needed the ctor is _always_ needed even, i.e. the dependency that pullis it is on the granularity of the object file, not that actual direct usage)

We have the -s MALLOC= flag already, so automatic DCEability is not a concern here.

> 3\. The cost is paid up front instead of on-demand.    i.e.  for a program that calls malloc on some runs but not on others, this is wasted work.

This seems like a contrived drawback? The initialization is not much of a bottleneck to slow down operation.



> 4\. They rely on the rather mysterious and not-really-specified ctor numbering/ordering rather than normal C language features.  This hurts readability IMHO.

> 2\. ctors like this require carefull global ordering (the fewer we have the better).

If we are introducing more ctor ordering in the system libraries (that I presume is causing the breakage here?), then I think we should resolve this by documenting the ordering numbers on some common page where we can establish a practice.

If we wanted to remove ctor priorities use, then maybe those should all be removed, not just emmalloc's one? It seems a bit arbitrary to just remove emmalloc's use of ctor priority, but leave the rest intact. Or - if we just have this one use of ctor priorities, then it would not be expected to be much of an issue?

Or is the issue with ordering against user defined code ctors? There should not be a problem to make this the highest priority ctor since there should not exist any dependencies that emmalloc has?

**Comment by sbc100** [comment]
The breakage only occurs in pthread builds due to the fact that TLS init also uses ctor priority when running on the main thread:

https://github.com/emscripten-core/emscripten/blob/ad6c0361998deec1b5d43776604536a55f8e80f4/system/lib/pthread/emscripten_tls_init.c#L31-L44

I'm keen to remove the use of static ctor here too if we can.   I think we should try to avoid all static ctors, especially those in system libraries, and especially those that use a numbers priority.   


While we can avoid the chicken and egg issue today by adjusting the priorities, we could do if emmalloc depended on TLS variables (since then we would mutual dependency).   I don't mind uploading a version of this fix that just adjusts and documents the priority instead, but I still think the solution in this PR is nicer since it works in all circumstances and doesn't really cost anything (a few of bytes of code size maybe).

**Comment by sbc100** [comment]
Closing in favor of https://github.com/emscripten-core/emscripten/pull/14806.  We can potentially look into removing any/all use of ctors as a followup issue.

**Pull request closed without merging**
