### PR TITLE
Update ChangeLog.md with #9054, #9088, #9089

### PR DESCRIPTION
**Pull request by yeputons**
This PR update `ChangeLog.md` with #9054, #9088, #9089

### CODE REVIEW

**Comment by sbc100** [comment]
otherwise we would probably just be replicating the git log

**Comment by yeputons** [comment]
The first one is potentially breaking, so I think it's nice to mention it.

The second _may_ be of some use for people who do binary diffs on outputs (not sure if there is anyone except emscripten devs). Probably not worth it.

The third is relatively minor, non-breaking, and is of interest to those watching #9022. Probably worth mentioning in the issue, but not in changelog.

**Comment by kripken** [comment]
I think this is fine personally. I don't think we're close to the point where the changelog is too long. Unless you object @sbc100 I'd support merging this.

**Comment by sbc100** [comment]
Nope, I'm fine with it,

**Comment by kripken** [comment]
Sounds good @sbc100, merging. Thanks @yeputons!

**Pull request merged**
