### PR TITLE
add __deps entries for $WS object in library_websocket.js.  Issue #11268

### PR DESCRIPTION
**Pull request by bpaterson2000**
I encountered "Uncaught ReferenceError: WS is not defined at _emscripten_websocket_send_binary" at runtime trying to call getaddrinfo in C (it happens for all socket based functions).   

sbc mentioned in discord "Hmm, looks like emscripten_websocket_send_binary is missing a __deps entry.  can you open bug?  and also you can try fixing locally by adding the __deps entry in library_websocket.js similar to those for other functions.
e.g. emscripten_websocket_new__deps: ['$WS']"

I have done this for any functions that I can see that use WS.

### CODE REVIEW

**Comment by sbc100** [comment]
Thanks!   Looks like the right fix.   I imagine our current testing didn't catch this because we tend to test many socket function at once rather than one at a time.  I'm also not sure how wide our test coverage is for the socket code anyway.

I'm tempted to let this land as is without requiring more narrow tests to prove it is needed.  What do you think @kripken , @juj?

**Comment by juj** [comment]
Looks correct, thanks for the PR!

Previously we only had this dep:
```js
  emscripten_websocket_new__deps: ['$WS'],
```
which seems that it should be enough - one can't call any other websocket functions without first creating a websocket itself.

Not sure how the error occurred for @bpaterson2000 , perhaps there are no websockets being created for some reason in your test code? 

Although the PR is certainly more precise this way.

**Comment by bpaterson2000** [comment]
You are correct, at the time I did not know that a websocket had to be set up, I can now see a reference to tcp_echo_client.cpp , which uses emscripten_init_websocket_to_posix_socket_bridge.  For me this spins forever on readystate = 0, but I will have to look into this separately.

**Comment by kripken** [comment]
I think we can use `autoAddDeps()` for this, see e.g. `library_webgl.js`, might be nice as a followup.

**Pull request merged**
