### PR TITLE
Add support for reading strings from custom section

### PR DESCRIPTION
**Pull request by vikram-kangotra**
In this commit, we introduce functionality to read strings from a custom section in WebAssembly modules. This is crucial for enabling Rust code to work seamlessly with Emscripten, as Rust writes to custom sections rather than the em_asm section (https://github.com/emscripten-core/emscripten/issues/13838#issuecomment-820656350).

The changes made in this commit include:
- The addition of the `get_wasm_custom_section` function, which retrieves custom sections by name from a WebAssembly module.
- Reading and parsing strings from the specified custom section.
- Storing the extracted strings in a dictionary for further processing.

This enhancement addresses an issue #13838 where Rust code interacts with Emscripten, and the ability to read strings from custom sections is necessary for proper integration.

This commit is a work in progress, as we still need to determine the correct offset value for the `string_key` variable.

Please note that this commit depends on the changes introduced in Merge Request #20218.

### CODE REVIEW

**Comment by sbc100** [comment]
I still think this is something that should be fixed upstream in rust in the long run.

I guess it OK to land a temporary workaround here in emscripten, but it should come with a comment and FIXME with a link the upstream rust but that this works around.

**Comment by vikram-kangotra** [comment]
Yeah, I agree that it should be fixed upstream in Rust, but it can work as a workaround for the time being. I will add a comment mentioning that it's a temporary workaround.

Also, I'm not able to determine the offset that needs to be set. Can you help with this?

**Comment by vikram-kangotra** [comment]
Hi,

I guess I understand it now but would like someone to confirm it. 

- In rust, writing to the custom section `em_asm` causes it to write to both the custom section
  as well as the data section. At least that's what I have observed.
- When I pass the string to emscripten main thread function, it passes the address of the string 
  in the data section, not the `em_asm` section.
- The code I have written to read from custom section, gets the address of the string from the 
  custom section and hence different addresses.
- I need some way to tell wasm to read the string from the custom section address stored in 
  ASM_CONSTS and not the data section (previously I was passing the address of the string 
  from the data section and hence it was working. But that needed manual update to offset in emscripten)

**Comment by sbc100** [comment]
> * In rust, writing to the custom section `em_asm` causes it to write to both the custom section
>   as well as the data section. At least that's what I have observed.

In that case (if the data is already in the data section) it should be easy to to make sure that the name of the data segment where it lives is `em_asm`.  Then the linker will be able to correctly generated `__start_em_asm` and `__stop_em_asm` which is then ready by emscripten.

In other words I think think we should go back to trying to fix Rust rather than emscripten.

**Pull request closed without merging**
