### PR TITLE
Added entry `FS_readFile` to the exportable list

### PR DESCRIPTION
**Pull request by genki**
Solve the issue #19863 I reported.

### CODE REVIEW

**Comment by genki** [comment]
@kripken Thanks letting me know.
I am struggling on creating env for testing as it depends on the llvm-17 with WebAssembly backend...

**Comment by kripken** [comment]
Oh, you don't need to set that stuff up manually. You can use the emsdk to get LLVM and Binaryen etc. Docs are here:

https://emscripten.org/docs/contributing/developers_guide.html#setting-up

**Comment by genki** [comment]
Thanks but I have done the built llvm :)
On the other hand, the current HEAD of this repo is seemed failing the test...

**Comment by kripken** [comment]
Not sure what was wrong, but I reran tests and they passed now...

**Review by kripken — APPROVED** [review]

**Pull request merged**
