### PR TITLE
Add port for sqlite

### PR DESCRIPTION
**Pull request by msabramo**
Add port for sqlite

### CODE REVIEW

**Comment by msabramo** [comment]
I noticed after submitting this that @kripken has https://github.com/kripken/sql.js

Perhaps this PR is overly simple and perhaps there are bits from sql.js that could be incorporated in a sqlite port?

**Comment by sbc100** [comment]
I'm not sure if we really need this.  IIRC sqlite is single C file and easy for anyone to integrate without that need for a port.

More generally, I'm not sure if we want to continue to add more and more ports of random stuff.  @kripken what do you think?   My feeling is that is that we should instead be trying to reduce the amount of features/libraries that emscripten includes .. but maybe thats just me.

**Comment by msabramo** [comment]
Curious to see what the ideas are about ports. At first I was excited to see that there was a way to easily build WASMized versions of various libs I needed. But now that I've messed around more with the tools, I wonder if the ports feature makes more sense in emsdk than in emscripten...?

It feels weird to pass special command-line flags to a compiler to make it download and build dependencies. This seems more like something that a package manager would do and I wonder if emsdk could be that package manager, since it's already managing  other aspects of the toolchain.

So instead of:

```
emcc tests/jpeg_test.c -s USE_LIBJPEG=1
```

One could do:

```
emsdk port install libjpeg
emcc tests/jpeg_test.c -ljpeg
```

I could imagine other commands too that would be self-explanatory:

```
emsdk port uninstall libjpeg
emsdk port list
emsdk port search
```

Essentially, `emsdk port` could be the [Homebrew](https://brew.sh/) of Emscripten.

What do you think?

**Comment by sbc100** [comment]
I tend to agree.  I makes more sense to for this kind of thing to be "built on top of" rather than "inside of" the compiler/toolchain.

However, given that the status quo, I won't block this CL if you want to land it.

**Comment by kripken** [comment]
Yeah, perhaps ports could be moved to a separate tool and not emcc itself - like emports.py?

About SQLite specifically - yeah, it's a single file, and really easy to bundle in projects, unlike SDL, libjpeg, etc. So I'd lean towards not merging this one, unless there's another reason to.

(btw, sql.js is kind of separate - it focuses on JS bindings for sqlite, so it's easy to use from JS, while a port would be for compiled C code.)

**Comment by msabramo** [comment]
OK, I'll close this then. I didn't realize that `sqlite.c` could simply be embedded in a project. I guess the "don't be evil" license/blessing of sqlite allows that, which I didn't realize.

**Pull request closed without merging**
