### PR TITLE
Mention `MEMORY64` in ChangeLog. NFC

### PR DESCRIPTION
**Pull request by sbc100**
From #22864

### CODE REVIEW

**Comment by dschuff** [comment]
Maybe it's worth adding the versions of Chrome and firefox that need to be used to work. For chrome this is 132 (flag required, and 132 is currently Canary). Not sure about firefox.

**Comment by sbc100** [comment]
> Maybe it's worth adding the versions of Chrome and firefox that need to be used to work. For chrome this is 132 (flag required, and 132 is currently Canary). Not sure about firefox.

Since neither browser has yet shipped a version that doesn't require a flag I'm not sure there is much I can say here.   They have both always required and a flag and continue to, likely until the new year, right?

**Comment by sbc100** [comment]
I could say "At time of writing all browsers still require a flag to run the resulting binaries but that should change in   
  the coming months since the propsal is now at stage 4."?

**Comment by sbc100** [comment]
ping..

**Pull request merged**
