### PR TITLE
Remove regal port

### PR DESCRIPTION
**Pull request by sbc100**
The regal project seems like its been dead for many years and the repo from which it was forked doesn't seem to exist anymore: https://github.com/p3/regal

I'm not sure we want to continue supporting it as first class thing if there is nobody upstream to report issues to.  If it turns out that there are folks who really depend on this we can consider moving it into `tools/ports/conrib`.

See #21885

### CODE REVIEW

**Comment by sbc100** [comment]
One other motivation for removing this is that it is one of the slower ports to build, coming it at 8x slower than musl/libc (16 seconds vs 2 seconds on my machine with 56 cores), so it adds to our build/test overheads.

**Comment by dschuff** [comment]
I think this makes sense to me, interested to get @kripken's opinion too

**Comment by kripken** [comment]
I'd lean against removing this entirely, since it does give us some more GL ES coverage, indirectly (in the GL ES it ends up emulating desktop GL using). But maybe that's not a strong reason. If no one responds on the mailing list I'd be ok removing it.

**Comment by Hex4dec** [comment]
I'm depending on Regal, since unfortunately OpenJDK does not have GL ES support. `gl4es` would only solve half of the issue, since many Java libraries also dynamically link to GL.

**Comment by sbc100** [comment]
Closing for now.  @kripken pointed out that the regal build actually provides a quite a bit of test coverage for our GLES implementation.

**Pull request closed without merging**
