### PR TITLE
Fix combined use of Closure, MINIMAL_RUNTIME and EXIT_RUNTIME=1

### PR DESCRIPTION
**Pull request by juj**

### CODE REVIEW

**Comment by sbc100** [comment]
Thanks for the fix!

**Comment by sbc100** [comment]
(Did you see the new "auto-merge" button here.. you can tell the PR to land as soon as tests pass now!)

**Comment by juj** [comment]
Thanks, yeah, did not notice that. However things have been very red recently that I don't think they'll resolve on their own on this one(?)

**Comment by juj** [comment]
Test failures look unrelated, landing.

**Pull request merged**
