### PR TITLE
Disable deprecated find event target behavior

### PR DESCRIPTION
**Pull request by juj**
Continuing from #9895.

### CODE REVIEW

**Comment by juj** [comment]
One test failure remains with `browser.test_emscripten_animate_canvas_element_size`, but ran out of time to look at this today.

**Comment by sbc100** [comment]
Nice! 

Do you think we are retaining enough testing of the legacy behaviour?   I see some but I don't know enough about this feature to judge.

Can you remove DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR from the documentation of STRICT and also the implementation of STRICT in emcc.py?

**Comment by VirtualTim** [comment]
Thanks for picking this up juj.

**Comment by juj** [comment]
Now passes test suite, good to land.

**Pull request merged**
