### PR TITLE
Remove setThrew hack in wasm backend

### PR DESCRIPTION
**Pull request by kripken**
Instead of always adding it, only add it using the usual
`deps_info` mechanism.

This removes some unnecessary code in builds with
metadce (as metadce would remove it anyhow), and
also enables exceptions in MINIMAL_RUNTIME. Without
this, we could still make MINIMAL_RUNTIME work but
it would regress the code size tests there (due to adding
`setThrew` to the output, which wasn't there before).

### CODE REVIEW

**Comment by kripken** [comment]
cc @juj - note this enabled wasm backend exceptions testing with minimal runtime

**Comment by juj** [comment]
Looks great!

**Comment by juj** [comment]
Wait, looking closer, I am not sure I follow this after all. We have

```js
#if WASM_BACKEND == 0
  setThrew__asm: true,
  setThrew__sig: 'vii',
  setThrew: function(threw, value) {
    threw = threw|0;
    value = value|0;
    if ((__THREW__|0) == 0) {
      __THREW__ = threw;
      threwValue = value;
    }
  },
#endif
```
so `setThrew` is a JS function in fastcomp, but a wasm function in wasm backend. But then we have places that always depend on `setThrew`, like

```js
  longjmp__deps: ['saveSetjmp', 'testSetjmp', 'setThrew'],
  __cxa_end_catch__deps: ['__exception_caught', '__exception_last', '__exception_decRef', '__exception_deAdjust', 'setThrew'],
```
Should those two JS-side `setThrew` deps be gated behind `#if WASM_BACKEND == 0`?

**Comment by kripken** [comment]
They could be gated that way. It's not strictly needed though as the js library logic sees that `setThrew` is already provided by compiled code, so it just doesn't do anything for `setThrew`. That's why things work (and don't even warn).

But there is a slight benefit to having `setThrew` in the list of dependencies that way, as it will error in the wasm backend case if the symbol is not in compiled code (as opposed to just emitting the code and erroring at runtime if it's called).

**Pull request merged**
