### PR TITLE
Use python3 in sdl-config batch files

### PR DESCRIPTION
**Pull request by dschuff**
`python` may not be present on the system.

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by dschuff** [comment]
Oh, those tests don't run on Windows on Circle anyway. worth adding, you think, or should I just submit this?

**Comment by sbc100** [comment]
> Oh, those tests don't run on Windows on Circle anyway. worth adding, you think, or should I just submit this?

Yeah, maybe add them now..  the windows bot passed quite fast.. and you can land once its passed I think

**Comment by dschuff** [comment]
hm, apparently just invoking 'python3' doesn't work on the circleCI bot. Should we make this wrapper the same as the entry point wrappers?

**Comment by sbc100** [comment]
> hm, apparently just invoking 'python3' doesn't work on the circleCI bot. Should we make this wrapper the same as the entry point wrappers?

I think maybe that is because the windows python3 installation only installs python.exe not python3.exe.  yes, I guess we need to be a little more complicated here.

Can we use EMSDK_PYTHON if it exists?

**Comment by sbc100** [comment]
Yup, confirmed th     1018  2021-02-19 14:20   Lib/lib2to3/fixes/fix_exec.py
     2101  2021-02-19 14:20   Lib/lib2to3/fixes/fix_execfile.py
    65536  2021-02-19 14:20   Lib/site-packages/setuptools/cli-32.exe
    65536  2021-02-19 14:20   Lib/site-packages/setuptools/gui.exe
    65536  2021-02-19 14:20   Lib/site-packages/setuptools/cli.exe
    75264  2021-02-19 14:20   Lib/site-packages/setuptools/gui-64.exe
    65536  2021-02-19 14:20   Lib/site-packages/setuptools/gui-32.exe
    74752  2021-02-19 14:20   Lib/site-packages/setuptools/cli-64.exe
    90112  2021-02-19 14:20   Lib/site-packages/pip/_vendor/distlib/w32.exe
    99840  2021-02-19 14:20   Lib/site-packages/pip/_vendor/distlib/w64.exe
    96768  2021-02-19 14:20   Lib/site-packages/pip/_vendor/distlib/t32.exe
   105984  2021-02-19 14:20   Lib/site-packages/pip/_vendor/distlib/t64.exe
   537264  2021-02-19 14:20   Lib/venv/scripts/nt/python.exe
   535728  2021-02-19 14:20   Lib/venv/scripts/nt/pythonw.exe
   101552  2021-02-19 14:20   python.exe
   100016  2021-02-19 14:20   pythonw.exe
at only `python.exe` and `pythonw.exe` are part of the package.

**Comment by dschuff** [comment]
WDYT of adding it to create_entry_points.py?

**Comment by sbc100** [comment]
Something like this should do it I think

```
@if "%EMSDK_PYTHON%"=="" (                                                              
  set EMSDK_PYTHON=python3
)   

"%EM_PY%" -E "%~dp0\sdl-config" %*
```

**Comment by sbc100** [comment]
> WDYT of adding it to create_entry_points.py?

I'm not sure if create_entry_points.py depends on that entry points living in the emscripten tree.. in this case the file in question gets installed into the sysroot.

**Comment by dschuff** [comment]
Is sdl-config a file meant to be run by users or their build systems in the same way that emcc is? If so, why wouldn't we want the same wrappers?

WRT the sysroot, it looks tools/system_libs.py just copies everything in system/bin into the sysroot along with the headers, so it seems like it should work?

**Comment by sbc100** [comment]
> Is sdl-config a file meant to be run by users or their build systems in the same way that emcc is?

Yes, users (build systems) are expected to run this scripte.


> WRT the sysroot, it looks tools/system_libs.py just copies everything in system/bin into the sysroot along with the headers, so it seems like it should work?

Yes, but all our other current entry points (the ones created by create_entry_points.py) are in the emscripten root itself (or at least are created and used in place relative to the emscripten root).   If you want to use create_entry_points that could work, but there could be some wrikles.

**Comment by sbc100** [comment]
I don't see that modification to the create_entry_points script itself?

**Comment by dschuff** [comment]
Oops, forgot to add that to the change. It's just adding system/bin/sdl-config and system/bin/sdl2-config to the list. I'm going to wait to push it until the already-running test finishes, though.

**Comment by sbc100** [comment]
> Oops, forgot to add that to the change. It's just adding system/bin/sdl-config and system/bin/sdl2-config to the list. I'm going to wait to push it until the already-running test finishes, though.

Sounds good!

**Pull request merged**
