### PR TITLE
Ensure pthread key dtors run on main thread too

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Review by kleisauke — APPROVED** [review]

**Comment by kleisauke** [comment]
I just noticed that the `destructor` function in `test_pthread_setspecific_mainthread.c` is never called when testing this on Linux. According to https://stackoverflow.com/a/6357265 pthread key dtors are only run when a thread exits (or when `pthread_exit` is explicitly called), so not on application exit (i.e. when the main thread exits). Sorry for not catching this earlier.

I could fix this in PR #13007 with commit https://github.com/emscripten-core/emscripten/pull/13007/commits/dce4aa09059227aa2283f2ece7b592e9f6582612, but let me know if a separate PR is preferred rather than deferring this to the upcoming musl upgrade.

**Comment by sbc100** [comment]
> I just noticed that the `destructor` function in `test_pthread_setspecific_mainthread.c` is never called when testing this on Linux. According to https://stackoverflow.com/a/6357265 pthread key dtors are only run when a thread exits (or when `pthread_exit` is explicitly called), so not on application exit (i.e. when the main thread exits). Sorry for not catching this earlier.
> 
> I could fix this in PR #13007 with commit [dce4aa0](https://github.com/emscripten-core/emscripten/commit/dce4aa09059227aa2283f2ece7b592e9f6582612), but let me know if a separate PR is preferred rather than deferring this to the upcoming musl upgrade.

Thanks for noticing that!   I would love to see that commit land as its own PR.   In general, I'm always a fan of splitting out each and every commit/change in separate PRs.

**Comment by sbc100** [comment]
BTW I'm really focused on getting the musl upgrade done in the next week or so... I'm hopeful :)

**Comment by kleisauke** [comment]
A pull request has been made for this at #14751.

> BTW I'm really focused on getting the musl upgrade done in the next week or so... I'm hopeful :)

Thanks for continuing to work on the musl upgrade!

**Pull request merged**
