### PR TITLE
[SjLj] Remove old unused library methods

### PR DESCRIPTION
**Pull request by aheejin**
After https://github.com/llvm/llvm-project/pull/84137 and #21502, these methods are no longer used.

cc @yamt

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]
Nice work!

**Comment by yamt** [comment]
i thought you wanted to keep older llvm support for a while. isn't it the case?

**Comment by sbc100** [comment]
No, we only keep that kind of thing around long enough for a new version of llvm to be integrated by out auto-rollers.  In general emscripten only support tip-of-tree llvm.

**Comment by yamt** [comment]
ok. thank you for explanation. how frequently do the auto-rollers run?

**Comment by yamt** [comment]
> > ok. thank you for explanation. how frequently do the auto-rollers run?
> 
> They run continuously, which means we normally get several rolls per day.
> 
> See https://autoroll.skia.org/r/llvm-project-emscripten-releases
> 
> And https://ci.chromium.org/p/emscripten-releases/g/main/console

ok. thank you.

**Pull request merged**
