### PR TITLE
Refactor test_autodebug

### PR DESCRIPTION
**Pull request by sbc100**
Re-enable this test.   Since WASM_OBJECT_FILES is the default
this test has not been running at all.

This change is in preparation for moving the build_ll_hook feature
from the generic test running since autodebug is now the only user
of this feature in the whole codebase.

### CODE REVIEW

**Comment by kripken** [comment]
lgtm, but very good point that the .ll version of autodebug testing has not been tested anymore. We can remove all the .ll stuff, and add a test using `EMCC_AUTODEBUG=1` in the env (which is the easy way to use it, but that I see is not tested). And we should test that with `WASM_OBJECT_FILES=0` I guess, perhaps in `other`. I can look into that if you don't want to.

**Comment by sbc100** [comment]
This change re-enables the test by forcing WASM_OBJECT_FILES to 0.

**Comment by sbc100** [comment]
I was going to do a followup to actually remove all the ll stuff once this lands.

**Comment by sbc100** [comment]
The thing is we probably do want to run this test with both fastcomp and llvm backend bitcode objects.. and at different O levels.. so maybe moving it to other doesn't make sense?  I'm not sure.

In any case I think we can take the next step in a followup PR.

**Comment by sbc100** [comment]
OK if I land this or would you rather combine it with the larger change?

**Pull request merged**
