### PR TITLE
Fix Emscripten to not impose a license on the generated output

### LINKED ISSUE #11258: Emscripten imposes a license to the output
After a recent compiler update we have started getting an Emscripten-imposed license text to all our output files:

```
emcc tests/small_hello_world.c -o a.html -s MINIMAL_RUNTIME=1
```
the output `a.js` will read

```js
if(typeof Module==="undefined"){var Module={};}/**
d
 * @license
 * Copyright 2010 The Emscripten Authors
 * SPDX-License-Identifier: MIT
 */

var Module = Module;


var ENVIRONMENT_IS_NODE = typeof process === 'object';

var ENVIRONMENT_IS_SHELL = typeof read === 'function';

var ENVIRONMENT_IS_WEB = !ENVIRONMENT_IS_NODE && !ENVIRONMENT_IS_SHELL;

if (ENVIRONMENT_IS_NODE && ENVIRONMENT_IS_SHELL) {
  throw 'unclear environment';
}

// Wasm or Wasm2JS loading:
if (ENVIRONMENT_IS_NODE) {
  var fs = require('fs');

...
```

Note also the stray 'd' character in the license block.

What is this about? IIUC the software license of Emscripten compiler should not dictate the license of the output itself? E.g. GCC is GPL, but one should not distribute everything compiled with GCC as GPL as well. And Emscripten certainly has a more permissive license, so I don't expect that it makes claims about the license of the output?

Running with 
```
emcc tests/small_hello_world.c -o a.html -s MINIMAL_RUNTIME=1 -s EMIT_EMSCRIPTEN_LICENSE=0
```
does not help the case, but the license block still remains.

### PR DESCRIPTION
**Pull request by juj**
Fixes #11258.

### CODE REVIEW

**Comment by juj** [comment]
> these ifdefs are not needed with the non-minimal runtime

All of those files are just concatenated to the build output. This does not seem to be specific to MINIMAL_RUNTIME, but just the build step appending these files will cause the license to be present.

**Comment by juj** [comment]
> we check if `EMIT_EMSCRIPTEN_LICENSE` is set and remove the license if not.

Hmm, isn't that the opposite? We check if `EMIT_EMSCRIPTEN_LICENSE` is set, and readd it, since Closure ate it up?

**Comment by juj** [comment]
Updated the test, it was missing -O0 variation handling.

**Comment by kripken** [comment]
> All of those files are just concatenated to the build output. This does not seem to be specific to MINIMAL_RUNTIME, but just the build step appending these files will cause the license to be present.

But the test shows that without minimal runtime things worked ok? Either the test is wrong, or minimal runtime is different, unless I'm missing a third option.

> Hmm, isn't that the opposite? We check if EMIT_EMSCRIPTEN_LICENSE is set, and readd it, since Closure ate it up?

It's confusing maybe, but it's the opposite, see this comment from the source:

```python
      # closure compiler will automatically preserve @license blocks, but we
      # have an explicit flag for that (EMIT_EMSCRIPTEN_LICENSE), which we
      # don't have a way to tell closure about. remove the comment here if we
      # don't want it (closure will aggregate all such comments into a single
      # big one at the top of the file)
```

So before this PR we always had the license info in intermediate files, but relied on the JS minifiers to strip out all comments.  That happens for acorn/uglify properly, but closure will not strip license comments and has no option for that, so we manually stripped it after closure.

OTOH I think I might like your idea to just ifdef out the license info. If we do that though, let's first answer the first question in this comment (is the test wrong, or is minimal different), and then remove that special closure code near that comment.

**Comment by sbc100** [comment]
I'd rather not have to ifdef out all the licence blocks in every file, its messy, error prone, and non-centralized.

If possible can we handle this centrally in single place at the end of the pipeline, no?

Also, IANAL, but the generated code *is* covered by the emscripten source license.. we don't have a special exception for the output do we?   I believe gcc has a special exception for this: https://www.gnu.org/licenses/gcc-exception-3.1.en.html.   I don't think emscripten needs such a thing because out licence is already permissive, but technically the JS output from our libraries doesn't change its license terms when we inject it into the output, right?

**Comment by kripken** [comment]
> If possible can we handle this centrally in single place at the end of the pipeline, no?

I also hoped to do it that way, but I think @juj's approach might be better. The central code needs to do hacky stuff like we have for closure right now. Also it doesn't work properly on `-O0` atm which @juj noticed, so we'd need to add some new hacks for that. While ifdefing does apply to more files, it is at least more straightforward.

> Also, IANAL, but the generated code is covered by the emscripten source license.. we don't have a special exception for the output do we? I

IANAL as well, but as I think I said in the discussion about the license option, it was my intention back in 2010 that people should *not* need to attribute anything in the compiler output. Just like clang or gcc's output. My reading of the MIT license was (and still is) that that is how it applies here. But, IANAL, and so we have an option for it.

**Comment by sbc100** [comment]
> > If possible can we handle this centrally in single place at the end of the pipeline, no?
> 
> I also hoped to do it that way, but I think @juj's approach might be better. The central code needs to do hacky stuff like we have for closure right now. Also it doesn't work properly on `-O0` atm which @juj noticed, so we'd need to add some new hacks for that. While ifdefing does apply to more files, it is at least more straightforward.
> 

Does this mean that users who include that license will now get multiple copies?

**Comment by juj** [comment]
> But the test shows that without minimal runtime things worked ok? Either the test is wrong,

The test was wrong, it was missing -O0 case testing, and it was mismatched in the string search for the license (`Copyright 2010 The Emscripten Authors` vs `Copyright 2010 Emscripten authors`)

> It's confusing maybe, but it's the opposite, see this comment from the source:

Ops, of course you're right, I was confused.

> If possible can we handle this centrally in single place at the end of the pipeline, no?

I am happy either way, although I don't want to implement that. This PR should now fix things up, including fixing the test, so feel free to refactor the implementation if you'd like to centralize the handling.

I do agree that the way things now stand, given that we liberally copy-paste the license block to every JS file in src/, it will be easy to accidentally include the license block in the output, and the test `other.test_emscripten_license` covers only a small case of all possible input files.

> Also, IANAL, but the generated code _is_ covered by the emscripten source license

> technically the JS output from our libraries doesn't change its license terms when we inject it into the output, right?

Currrently the .js files output by Emscripten will start with
```js
/**
 * @license
 * Copyright 2010 The Emscripten Authors
 * SPDX-License-Identifier: MIT
 */
```
Any reader of such a file can only make the conclusion that the text would apply to the whole file, since there is no separation or disclaimer about what the text applies to. (It is in the beginning of the file, so naturally would be expected to apply to the whole file)

But certainly the Emscripten Authors do not own the copyright of all output produced with Emscripten! Nor is it in our/their rights to state that the output should be licensed under the MIT license.

Either the generated code output should be separated out to two sections, one that the "Copyright Emscripten Authors" applies to, clearly marked with start/end parts, and then the rest that the copyright does not apply to. (that would be pretty cumbersome to implement, and awkward)

Or if placed at the top of the file, the license should read something like

/**
 * @license
 * Contains portions of the Emscripten runtime, under Copyright 2010 of The Emscripten Authors
 * The runtime is licensed under SPDX-License-Identifier: MIT
 */

to not make an "applies to the whole file" statement.

Although, I do not think that Emscripten authors can claim to retain the rights to making copies of the output files, not even of a portion of them.

Also not all that Emscripten outputs should be required to be MIT-licensed again - that would e.g. mean that people who desire to generate GPL-licensed content could not use Emscripten.

But I submit to that I don't know how this stuff generally works either.

> Does this mean that users who include that license will now get multiple copies?

Before this PR, users were getting multiple copies, this PR now fixes only one copy to occur.

**Comment by hujiajie** [comment]
With this change the header comment will not start from the first line, is there any risk of breaking tools which scan SPDX license identifiers?

Any my understanding of GCC is that:

* Most of GCC itself is GPL-licensed
* The GCC runtime library is licensed under https://www.gnu.org/licenses/gcc-exception-3.1.en.html as mentioned above
* GCC does not enforce the license of code generated from user C/C++ sources

Maybe src/library*.js act more like the GCC runtime library, instead of generated code. But I'm not a lawyer, so it would be nice if it can be clarified.

Nevertheless, having multiple copies of the license info in the final output is absolutely non-optimal.

**Comment by juj** [comment]
> With this change the header comment will not start from the first line

Hmm, how so?

```
emcc tests/hello_world.c -o a.html -s EMIT_EMSCRIPTEN_LICENSE=1
```
outputs an `a.js` with
```js
/**
 * @license
 * Copyright 2010 The Emscripten Authors
 * SPDX-License-Identifier: MIT
 */

// The Module object: Our interface to the outside world. We import
// and export values on it. There are various ways Module can be used:
// 1. Not defined. We create it here
// 2. A function parameter, function(Module) { ..generated code.. }
// 3. pre-run appended it, var Module = {}; ..generated code..
// 4. External script tag defines var Module.
// We need to check if Module already exists (e.g. case 3 above).
// Substitution will be replaced with actual code on later stage of the build,
// this way Closure Compiler will not mangle it (e.g. case 4. above).
// Note that if you want to run closure, and also to use Module
// after the generated code, you will need to define   var Module = {};
// before the code. Then that object will be used in the code, and you
// can continue to use Module afterwards as well.
var Module = typeof Module !== 'undefined' ? Module : {};


// --pre-jses are emitted after the Module integration code, so that they can

...
```

**Comment by hujiajie** [comment]
Sorry for the ambiguity, I mean the header in src/*.js, not the header in the generated output.

**Comment by kripken** [comment]
@hujiajie Interesting point, yeah, the ifdef does move it down a line. But would any other tool see the `src/*.js` files? (only emscripten itself should I think)

About multiple copies, I'm not worried about `-O0` output having multiple copies of comments and stuff like that. But we should verify that in `-O2+`, and with and without closure, that just a single one is emitted.

**Comment by kripken** [comment]
I opened https://github.com/emscripten-core/emscripten/pull/11277 which fixes bugs in a more centralized way, without ifdefing. I don't feel strongly between the two.

**Comment by hujiajie** [comment]
> @hujiajie Interesting point, yeah, the ifdef does move it down a line. But would any other tool see the `src/*.js` files? (only emscripten itself should I think)

License scanners are told to scan these files, and I believe that's the exact point of the machine-parsable SPDX license identifiers. Some typical scenarios are:

* I want to bundle Emscripten in my project, along with other components, and I (or the tool) would like to know if their licenses are compatible.
* I just want to re-use certain files in src/ in my project, so I copied them, but the legal department of my organization want to ensure all code snippets are clearly licensed and the license scan report is clean.
* Ensure the license of files in src/ does not conflict with other parts of Emscripten, which may come from 3rd-parties.

I'm not sure if code scan tools will be fooled by the ifdefs, but they look quite non-conventional to me.

**Comment by kripken** [comment]
@hujiajie 

Oh I see, you scan them in the source tree, and not in the generated code? Yes, I can see that this might be a problem for that.

**Comment by juj** [comment]
The other version to resolve this landed, so closing this as unnecessary.

**Pull request closed without merging**
