### PR TITLE
Update WebGPU to the latest changes

### PR DESCRIPTION
**Pull request by hugoam**
Here is the PR that updates WebGPU to the changes that have happened in WebGPU (and Dawn) since last time.
This includes mostly the changes presented in this PSA: https://hackmd.io/@webgpu/HJdib9rOD

Probably needs review from some people among:
@kainino0x 
@austinEng
@Kangz

### CODE REVIEW

**Comment by hugoam** [comment]
While building the examples I'm noticing something that might interest Emscripten people:
```
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libgl-webgl2.a... (this will be cached in "/home/hugoam/emsdk/emscripten/main/cache/sysroot/lib/wasm32-emscripten/libgl-webgl2.a" for subsequent builds)
```
I assume this means there is still a dependency on `libgl-webgl2` when building with `-s USE_WEBGPU=1`. Maybe we want to fix this at some point ? Even if it doesn't have a binary size influence because of optimizations, we might still want to clean this up ? Just a thought

**Review by austinEng — COMMENTED** [review]
Looks good! Some nits:
- CopyTextureForBrowser is a Chromium-implementation detail for Dawn. We probably shouldn't include it here
- Also the current form of the ExternalTexture object is mostly Chromium-specific. We haven't put it in webgpu.h yet. Not sure if it will take the same form as the js `GPUExternalTexture` created from video/canvas.

**Review by kainino0x — COMMENTED** [review]
hugoam's changes LGTM, but @austinEng could you review the changes I pushed at the end?

**Comment by hugoam** [comment]
I realized I also forgot the `setBlendColor` -> `setBlendConstant` rename on the `library_webgpu.js` side

**Review by austinEng — APPROVED** [review]
LGTM!

**Comment by kripken** [comment]
The single code size test failure on random_printf can be ignored, it was breakage on `main`.

**Review by kainino0x — APPROVED** [review]

**Comment by kainino0x** [comment]
@sbc100 Still having trouble landing this. Previously it was blocked on what I think was fixed in #13989, but there is still one failure left over (which seems to have also affected main: https://app.circleci.com/pipelines/github/emscripten-core/emscripten/12725/workflows/85848321-15fe-41c8-82cc-c57165b0a89a). Possible this was missed in #13989?

**Comment by Kangz** [comment]
Pinging again. @sbc100 is there something we should do to unblock this?

**Comment by sbc100** [comment]
Remaining failures are unrealted and no longer exist on head.. landing as is.

**Pull request merged**
