### PR TITLE
Fix embind map compilation issues

### LINKED ISSUE #9330: bind failure with register_map / "implicit instantiation of undefined template"
This is actually the exact same problem as #9005 except with `register_map`, and the (possible bandaid) solution is exactly the same.

I can submit a PR for it if desired.

### PR DESCRIPTION
**Pull request by jkae**
Fixes #9330.

Solution via #9027.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This seems plausible to me. Are there other methods that might need this?

(And ping @jgravelle-google ?)

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

Re-opening and re-targeting to master.

**Comment by billti** [comment]
Ping... besides the accidental deletion today, looks like this was inactive for a couple months. Is it just waiting on the AUTHORS update? I'm hitting this today with some basic "register_map" code (using tip-of-tree).

**Comment by kripken** [comment]
Yes, looks like this is only waiting on the AUTHORS update. @jkae please let us know if adding yourself to AUTHORS is a problem, and we can work something out.

**Comment by waywardmonkeys** [comment]
Ping again.

**Comment by kripken** [comment]
It looks like @jkae may no longer be available to respond here. As this is a tiny 2-line change, I think we can just merge it in as an exception to the usual policy.

**Pull request merged**
