### PR TITLE
Generate port settings in ports

### PR DESCRIPTION
**Pull request by kripken**
Instead of a port having to modify `settings.js`, give them a hook to
add new settings.

See discussion in #11066

### CODE REVIEW

**Comment by sbc100** [comment]
Hmm..  I think I like this approach.  I was going to suggest an alternative approach, which I think maybe we should still take in addition to this.   

We have a single setting called `USE_PORT=foo` which triggers the loading and activation of a port called `foo.py`.    This would mean that `foo.py` wouldn't even get parse or loaded unless that user ask for it and ports would not need to register their own settings (making each port slightly simpler and ensuring consistency).

I think either way this change you have here is a nice simplification and cleanup up `settings.js` quite nicely.

**Comment by kripken** [comment]
I don't feel strongly between the approaches - your approach may be a simpler change actually.

**Comment by sbc100** [comment]
I think we could do both maybe?  This approach for the current set.. and the USE_PORT for any new ones we add?

**Comment by sbc100** [comment]
Actually I think I do like my idea better and maybe this PR just makes this more complicated for the existing ports?

**Comment by kripken** [comment]
@sbc100 your idea sounds better to me too, yeah, it's nice to avoid having to do any work for a port unless it's actually used.

I'll close this then.

**Pull request closed without merging**
