### PR TITLE
Add onError to Module.

### PR DESCRIPTION
**Pull request by bas-d**
If the `onError` is set on the Module, it is called before the error is being thrown and returns.

### CODE REVIEW

**Comment by kripken** [comment]
In general we try to avoid adding new hooks like these, as they increase code size, and most users don't need them.

Is onAbort not good enough? If there's a strong use case, we may add this, but we may want to start doing things like this behind a flag.

**Comment by bas-d** [comment]
Well, the documentation for `onAbort` says:
>After calling this function, program termination occurs (i.e., you can’t use this to try to do something else instead of stopping; there is no possibility of recovering here).

But recovering is exactly what we want here, because we want to fall back to asm. The error that is being thrown in abort cannot be catched if async is used, because it results in unhandled promise rejection.
It would also be possible to have an optional boolean return value for `onAbort` to prevent the error from being thrown, instead of an extra hook.

But I think disabling the throw with a flag should work too. I'll test it and update this PR!

**Comment by kripken** [comment]
I'm still unsure about this even with the new flag. It seems like just doing a catch in the outside JS is enough to recover, isn't it?

**Comment by bas-d** [comment]
Well, I don't think that works if async is used. `instantiateAsync()` calls `abort()`, which throws the error. This terminates the program, which I assume is the desired behavior if there's no intention of recovering. But since here https://github.com/emscripten-core/emscripten/blob/60c036e13fd13d3f14143b560673d8c013bda548/src/preamble.js#L1105-L1106 
the promise (which will reject because of the error thrown in `abort()`) is not returned, this promise rejection cannot be catched (except by listening for a `unhandledrejection`-event, which is a rather ugly way to solve this).

**Comment by kripken** [comment]
Good point, yeah, if it's async you can't just catch it.

I'm not sure about an option to not throw - that leaves it to continue running, which may be very confusing.

Perhaps another option is to look into cleaning up the abort/exit/quit path. We do allow `Module.quit` to be provided by the user, but we don't call it from abort and exit. We probably should, I think, but I'm not sure if there isn't some assumption about a difference between abort and quit that matters here. Trying it out and seeing what happens on the test suite is probably best.

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

**Pull request closed without merging**
