### PR TITLE
Use CI skip on release-marking PRs

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by dschuff** [comment]
How does [ci skip] work, anyway?

**Comment by sbc100** [comment]
> How does [ci skip] work, anyway?

Its some kind of circle-ci or github actions specific string that causes the steps not to run.

I don't know that it also makes the "required" steps magically not required?

**Comment by sbc100** [comment]
I think `[skip ci]` does in the PR description normally, not in the title

**Comment by sbc100** [comment]
More info: https://circleci.com/docs/skip-build/#the-skip-ci-process

**Comment by dschuff** [comment]
Aha ok interesting it's not supported for fork PRs, that's why it's not working here.

**Comment by dschuff** [comment]
But that's a good point about branch protections; my guess would be that the PR won't be blocked by CI that isn't run; just by CI that fails.

**Comment by sbc100** [comment]
> But that's a good point about branch protections; my guess would be that the PR won't be blocked by CI that isn't run; just by CI that fails.

I'm not sure the circleci <-> github integration is smart enough to do that.. but I hope so.

**Review by sbc100 — APPROVED** [review]

**Comment by sbc100** [comment]
We can always land these change by force I guess?

**Comment by dschuff** [comment]
Yeah, and if that turns out to be more annoying than just waiting for the CI and landing them the normal way we can just revert it.

**Pull request merged**
