### PR TITLE
added FS.trackingDelegate documentation

### PR DESCRIPTION
**Pull request by ethanalee**
Added documentation for FS.trackingDelegate

### CODE REVIEW

**Review by tlively — APPROVED** [review]
Thanks, this looks good to me! @kripken, do you have any comments?

**Comment by tlively** [comment]
Oh yeah, you should also add yourself to the AUTHORS file.

**Review by kripken — APPROVED** [review]
Thanks!

**Comment by kripken** [comment]
AUTHORS is optional now, yes - no need to do anything regarding that.

**Pull request merged**
