### PR TITLE
fix: EXPORT_ES6 + USE_ES6_IMPORT_META=0 has no effect in worker

### PR DESCRIPTION
**Pull request by RequireSun**

### CODE REVIEW

**Comment by kripken** [comment]
cc @RReverser

**Comment by RReverser** [comment]
I don't think this is correct - the code in question doesn't depend on import.meta, and, as such, shouldn't be guarded behind this condition.

**Comment by RequireSun** [comment]
@RReverser Ok, I think I have misunderstand of `USE_ES6_IMPORT_META=0`, but when I use this option, all other imports(wasm & worker) will change back to the ES5 format. But only the main script's importation in worker script, is there any way to control it?

**Comment by RReverser** [comment]
`USE_ES6_IMPORT_META` only controls where `import.meta` can be used (since some older browsers support ES6 but not `import.meta` yet), and, as such, whether generated JS will be able to find generated Wasm & Worker automatically, without manual `locateFile` override.

If you don't want any ES6 imports / exports, you can disable `EXPORT_ES6` instead.

**Comment by RequireSun** [comment]
@RReverser I think I seen what your mean, thanks for your answer me~ I ll close the pr.

**Pull request closed without merging**
