### PR TITLE
Use llvm-objcopy to strip DWARF debug info when not running wasm-opt

### PR DESCRIPTION
**Pull request by kripken**
Relative to / followup to #12075. This does the same for debug info, it gets
us back to the same output as before (even stripping it in unoptimized
builds if `-g` is not present) by using llvm-objcopy when wasm-opt isn't
being run anyhow.

Together these PRs make our work on https://github.com/WebAssembly/binaryen/issues/3043
have less noticeable effect that could surprise users.

Note that wasm-ld has `--strip-debug` which we could use, but it will
strip both the Names section and DWARF sections, and we may want
just the Names section, so we can't just use that.

### CODE REVIEW

**Comment by sbc100** [comment]
But if we know we don't want debug in the final output why not pass `--strip-debug` to `wasm-ld` to avoid generating it in the first place?

**Comment by kripken** [comment]
It looks like we do pass that to wasm-ld, but it's not enough,

https://github.com/emscripten-core/emscripten/blob/ef108c67d9c683dbd80e5ed8022dc49aea47043c/tools/building.py#L493-L496

Maybe it just strips the names section but not DWARF debug sections?

**Comment by sbc100** [comment]
> It looks like we do pass that to wasm-ld, but it's not enough,
> 
> https://github.com/emscripten-core/emscripten/blob/ef108c67d9c683dbd80e5ed8022dc49aea47043c/tools/building.py#L493-L496
> 
> Maybe it just strips the names section but not DWARF debug sections?

Interesting... maybe a bug in wasm-ld?   The code looks like it should be doing the right thing: https://github.com/llvm/llvm-project/blob/eb2a405c181c9833eb8676d147619b8c893dc6fa/lld/wasm/Writer.cpp#L127

If you land this can you add a TODO with link to a new llvm bug about `--strip-debug` not doing what it should?

**Comment by kripken** [comment]
Oh yes, that lld code does look right. Looking into this more carefully, yes, wasm-ld does do what it should. The problem is that the condition in building.py won't send lld that flag if we need the Names section (`-g2`, and some other situations). We want to just remove DWARF debug info in that case, but leave the names section alone, but `--strip-debug` does both unconditionally.

**Comment by sbc100** [comment]
OK, lgtm.   Maybe add comment and update PR description to mention why the existing `--strip-debug` is not always sufficient.

**Pull request merged**
