### PR TITLE
Make toolchain profiler start/exit automatic. NFC

### PR DESCRIPTION
**Pull request by sbc100**
Make the import of `tools/toolchain_profiler.py` (which
happens exactly once per process) the thing that causes
profiling to start and use `atexit` to handle exiting.

### CODE REVIEW

**Comment by sbc100** [comment]
I verified this manually by looking at the resulting profiles for a simple hello world build as well as `./embuilder build libc`.   The results looked pretty much the same both before and after this change.

**Comment by juj** [comment]
Works for me. While you are at it, can you move the import of the profiler script to the top of these files? I think at some point to appease flake the code was moved to alphabetical order or something like that, but since we do a nontrivial amount of work at top level of importing scripts, we will skew the profiling results by importing the profiler script after other imports.

**Comment by sbc100** [comment]
> Works for me. While you are at it, can you move the import of the profiler script to the top of these files? I think at some point to appease flake the code was moved to alphabetical order or something like that, but since we do a nontrivial amount of work at top level of importing scripts, we will skew the profiling results by importing the profiler script after other imports.

Done. 

Bear in mind that because the profiler is included at the very top of `shared.py` it is less important now where it appears in other places as this one will most likely get hit very early on and register the profiler on import.     Assuming that scripts import shared this should mean that the profiler kicks in early then than it did in the past.

**Review by kripken — COMMENTED** [review]
I'm not familiar with `toolchain_profiler.py` but this seems ok.

Is this code well tested?

**Comment by sbc100** [comment]
I am currently landing a change to increase testing somewhat:  #13416

But no, this code is not well tested.  I manually test that this didn't have any noticeable results and worked as expected.

**Comment by sbc100** [comment]
I mean the null-versions of the profiler are very well tested!  .. but the `EMPROFILE` mode where it is active has just one test.  #13416 begins to improve on that.

**Review by kripken — APPROVED** [review]
In that case lgtm, but probably best that @juj review this too.

**Comment by sbc100** [comment]
I think @juj already signal approval above..  browser test failures are know and unrealted.

**Pull request merged**
