### PR TITLE
Fix emar invocation on Windows and restore test other.test_emar_respo…

### PR DESCRIPTION
**Pull request by juj**
…nse_file

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]
lgtm!

I've been trying to fix the windows difference upstream BTW: https://reviews.llvm.org/D80876

**Comment by sbc100** [comment]
> lgtm!
> 
> I've been trying to fix the windows difference upstream BTW: https://reviews.llvm.org/D80876

The problem I'm trying to fix upstream is that unlike llvm-ar and other tools, clang itself does *not* use windows style response files, even when running on windows.  It only does that when its running as `clang-cl` (i.e. emulating cl.exe).   So this is change might have some risks?

**Comment by juj** [comment]
>  So this is change might have some risks?

Hmm, maybe? I think we should go by our test suite on things like this, and have test cases that prove or disprove the risks, i.e. if there is some yet escaping scenario that this would break, we should unsurface it to another test.

I am not particularly bitten about this behavior in present, but was just looking at this when searching whether we have response file tests in the suite for #13673.

**Comment by sbc100** [comment]
> > So this is change might have some risks?
> 
> Hmm, maybe? I think we should go by our test suite on things like this, and have test cases that prove or disprove the risks, i.e. if there is some yet escaping scenario that this would break, we should unsurface it to another test.

Agreed.

**Pull request merged**
