### PR TITLE
Remove ctype compat macros. NFC

### PR DESCRIPTION
**Pull request by sbc100**
The code here was unused because of the fact that we already define `_LIBCPP_HAS_MUSL_LIBC` in `libcxx/include/__config_site` which means that `_LIBCPP_PROVIDES_DEFAULT_RUNE_TABLE` is
defined by `libcxx/include/__config` which in turn mean that the first branch of this if/else
tree is the that is being used.

This change should really have been part of #17022 which was when we started defining
`_LIBCPP_HAS_MUSL_LIBC`.

### CODE REVIEW

**Comment by sbc100** [comment]
Finally catching up with a change @jfbastien made 8 years ago!

**Review by kripken — COMMENTED** [review]
Where do we define `_NEWLIB_VERSION`?

**Comment by sbc100** [comment]
Sorry, brain fart, this has nothing to do with newlib. 

The change is still valid but for a different reason.  Its because we define _LIBCPP_HAS_MUSL_LIBC which in turn defines _LIBCPP_PROVIDES_DEFAULT_RUNE_TABLE.  I will update the PR description.

**Comment by dschuff** [comment]
Was this a downstream localmod or do we need to also upstream the __locale change?

**Comment by sbc100** [comment]
> Was this a downstream localmod or do we need to also upstream the __locale change?

The original change was local change that made its way upstream already, so is not longer a local mod.

This change will become a new local changes that, like all local changes, should be upstreamed at some point.     My philosophy for this is to periodically looks at the deltas from upstream and push any new changes at that point.

**Review by kripken — APPROVED** [review]

**Pull request merged**
