### PR TITLE
Update SIMD instruction names

### PR DESCRIPTION
**Pull request by ngzhian**
- widen -> extend
- v*_shuffle -> i*_shuffle

### CODE REVIEW

**Comment by ngzhian** [comment]
@tlively ptal

**Review by tlively — APPROVED** [review]
Awesome, thanks for doing this! For the neon header, would you mind doing the same change upstream in SIMDe? I think it's fine to do here as well, but next time we import the header, we wouldn't want to accidentally regress.

**Comment by ngzhian** [comment]
Good point, I can do that upstream (didn't even notice it at first.)

**Comment by ngzhian** [comment]
Looks like upstream already fixed this in https://github.com/simd-everywhere/simde/commit/20682c192f1c7e9fd0d0dc653df74f7cc7f4a83a

**Comment by tlively** [comment]
Thanks for checking! It might make sense to split the neon changes out of this PR and do a follow-up PR to import the latest header, wdyt?

**Comment by ngzhian** [comment]
> Thanks for checking! It might make sense to split the neon changes out of this PR and do a follow-up PR to import the latest header, wdyt?

sg!

**Comment by tlively** [comment]
Thanks, @ngzhian!

**Pull request merged**
