### PR TITLE
Functions export optimization

### LINKED ISSUE #5461: Module['_sbrk'] reassignment
With `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[] -s WASM=1` the code I'm getting contains following piece:
```javascript
  function ___setErrNo(value) {
      if (Module['___errno_location']) HEAP32[((Module['___errno_location']())>>2)]=value;
      return value;
    } 
  Module["_sbrk"] = _sbrk;
DYNAMICTOP_PTR = allocate(1, "i32", ALLOC_STATIC);

STACK_BASE = STACKTOP = Runtime.alignMemory(STATICTOP);

STACK_MAX = STACK_BASE + TOTAL_STACK;
....
var _sbrk = Module["_sbrk"] = function() { return Module["asm"]["_sbrk"].apply(null, arguments) };
```

In particular I'm interested in `Module["_sbrk"] = _sbrk;` piece and `var _sbrk = Module["_sbrk"]` few lines below it.

I've tried to find where it comes from and why is even needed. It comes from [this line](https://github.com/kripken/emscripten/blob/3858294f58b2baa03108d08494e837b4ef10d3fd/emscripten.py#L506), from `metadata['declares']`, then through [this line](https://github.com/kripken/emscripten/blob/3858294f58b2baa03108d08494e837b4ef10d3fd/src/jsifier.js#L78) it gets printed [here](https://github.com/kripken/emscripten/blob/3858294f58b2baa03108d08494e837b4ef10d3fd/src/jsifier.js#L388).

Can anyone tell me why is it there and why needed?
For me it doesn't make any sense.

I'm working on a way to reduce build size a bit, but this piece causes issues with final build, since after changes I'm doing `var _sbrk` is not present anymore (while `Module["_sbrk"]` is still there). Since `_sbrk` is not used anywhere else, I'd like to make it disappear.

### PR DESCRIPTION
**Pull request by nazar-pc**
This allows to reduce build size of https://github.com/nazar-pc/supercop.wasm with `-O2 --closure 1 -s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -s EXPORTED_RUNTIME_METHODS=[] -s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[] -s WASM=1 MODULARIZE=1` (pretty strong already) and just 5 exported functions from 20.4 KiB (incoming branch as of right now) to 19.4 KiB.

The size difference depends directly on number of exported functions. More functions - bigger difference. When #5109 is implemented and we can enjoy ES2015 syntax, it will be possible to squeeze a few more bytes and simplify Python code (TODO comments added in corresponding places).

In order to resolve #5461 and eliminate the rest of reassignments that are now unnecessary there is a need to investigate and eliminate generated `Module["_foo"] = _foo;` constructions, but still this PR is feature-complete even without it.

P.S. First time contributing something written in Python:)

### CODE REVIEW

**Comment by kripken** [comment]
I'm not sure what this PR's code does, can you give a summary? It looks like it's moving some work from compile time to runtime, why and how does that help?

**Comment by nazar-pc** [comment]
### The problem # 1
When functions are exported by Emscripten, we have a lot of boilerplate like following:
```javascript
var getTempRet0 = Module["getTempRet0"] = asm["getTempRet0"];
var setThrew = Module["setThrew"] = asm["setThrew"];
var _ed25519_sign = Module["_ed25519_sign"] = asm["_ed25519_sign"];
var _bitshift64Lshr = Module["_bitshift64Lshr"] = asm["_bitshift64Lshr"];
var _bitshift64Shl = Module["_bitshift64Shl"] = asm["_bitshift64Shl"];
var _bitshift64Ashr = Module["_bitshift64Ashr"] = asm["_bitshift64Ashr"];
var _sbrk = Module["_sbrk"] = asm["_sbrk"];
var stackAlloc = Module["stackAlloc"] = asm["stackAlloc"];
var ___muldi3 = Module["___muldi3"] = asm["___muldi3"];
var _i64Subtract = Module["_i64Subtract"] = asm["_i64Subtract"];
var setTempRet0 = Module["setTempRet0"] = asm["setTempRet0"];
var _i64Add = Module["_i64Add"] = asm["_i64Add"];
var stackRestore = Module["stackRestore"] = asm["stackRestore"];
var _ed25519_verify = Module["_ed25519_verify"] = asm["_ed25519_verify"];
var stackSave = Module["stackSave"] = asm["stackSave"];
var ___muldsi3 = Module["___muldsi3"] = asm["___muldsi3"];
var _free = Module["_free"] = asm["_free"];
var runPostSets = Module["runPostSets"] = asm["runPostSets"];
var establishStackSpace = Module["establishStackSpace"] = asm["establishStackSpace"];
var _emscripten_get_global_libc = Module["_emscripten_get_global_libc"] = asm["_emscripten_get_global_libc"];
var _malloc = Module["_malloc"] = asm["_malloc"];
var _ed25519_create_keypair = Module["_ed25519_create_keypair"] = asm["_ed25519_create_keypair"];
```

More functions exported - more boilerplate is generated. Because of quotes used, this code is not compressed well with closure compiler. I though this can be simplified.

### Solution # 1
Turns out, list of exported functions is kept in `*.asm.js` and `*.wasm` files anyway and is in fact accessible in runtime. So I've decided that we can fill `Module` with functions in runtime during initialization and avoid listing all of those functions explicitly. As this is one-time operation during initialization, it shouldn't have any significant performance impact, we just assign function from one object to another, but in a loop instead of plain code.

Basically it boils down to:
```javascript
function onAsmLoaded (asm) {
  var functions = [];
  for (var functionName in asm) {
    if (Object.hasOwnProperty.call(asm, functionName)) {
      functions.push(asm[functionName]);
      Module[functionName] = asm[functionName];
    }
  }
}
```

Regardless of actual number of exported functions, and with ES1025+ to even smaller:
```javascript
function onAsmLoaded (asm) {
  Object.assign(Module, asm);
}

```

### Problem # 2
Another issue that came after that was that some variables like `_malloc` are used in many places and it would be quite difficult to eliminate them and replace with something like `Module['_malloc']` (which again wouldn't compress very well).

### Solution # 2
However, during compilation we also have exactly the same list of exported functions in the same exact order. So instead of `var _malloc = Module['_malloc']` we can essentially write `var _malloc; ... _malloc = functions[index]`, where `index` is index of the corresponding function in the list of exported functions. And writing it this way allows Closure Compiler to happily reduce this to something like `var a; ... a=b[5];`, some of them will, probably, be eliminated entirely.

With ES2015+ all of those assignments can be further simplified to single line:
```javascript
[_malloc, _free] = Object.values(asm);
```

I hope it makes sense, single function with 2 lines body instead of boilerplate.

**Comment by nazar-pc** [comment]
So basically our JavaScript part (not counting `*.asm.js`) will not contain original names of exported function in plain text at all, while they will still be available as properties on `Module` object just like before.

**Comment by nazar-pc** [comment]
Here is commit that switches this PR to ES2015 syntax: https://github.com/nazar-pc/emscripten/commit/17b9cc1a55a3553a1c70c8feab63db621c470963

**Comment by kripken** [comment]
I see, thanks. Ok, this might save some size, but e.g. on hello world it only saves 78 bytes out of 290684. And it has the downside of doing more work at runtime - a function call and especially the loop. Probably the effect is small, but since the code size benefit is small too, I'm skeptical of this being worthwhile. But taking more precise measurements might be helpful.

I also ran a few tests out of curiosity, and it looks like stuff is broken (e.g. `test_loop`).

**Comment by nazar-pc** [comment]
> on hello world it only saves 78 bytes out of 290684

So at least in the most conservative situation it still manages to reduce build size. Now imagine you have about 100 exported functions (like crypto library I'm trying to port). There will be a lot of boilerplate without this patch and difference will be counted in tens of KiBs.

Will run some tests shortly.

**Comment by nazar-pc** [comment]
Turns out it is a bit more complicated than I though, will update when tests become good.

**Comment by dschuff** [comment]
In general I like this idea. I'm not convinced it would really be much slower on load. Previously we'd have to download, parse, and execute one `var foo = Module['foo'] = asm['foo']` per export, and now we just execute one iteration of the above loop per export. Sounds to me like it might even be faster?

**Comment by kripken** [comment]
> thus wrapper functions like following are not used anymore and exported functions are called directly

we should only have those wrappers in unoptimized builds or when ASSERTIONS is on, so I might be missing something but I don't think this PR helps in the optimized case? 

The indirection is also still necessary in some cases, like when SWAPPABLE_ASM_MODULE (worth making sure those tests pass).

> I'm not convinced it would really be much slower on load. Previously we'd have to download, parse, and execute one var foo = Module['foo'] = asm['foo'] per export, and now we just execute one iteration of the above loop per export. Sounds to me like it might even be faster?

Well, a loop will start to involve the optimizing compiler and all that, while flat code that is obviously only going to execute once might be faster. But we should just measure it. It's not easy to measure, I tried to use `perf stat -r 1000`, and I see a 1.6% slowdown. That could be noise, though (perf reports 0.31%).

Overall, I think this is interesting once we can use the ES6 tricks that make it reduce code size. Measuring it now, it's slightly larger in code size both -O0 and -O2 and with and without EXPORT_ALL.

**Comment by nazar-pc** [comment]
> we should only have those wrappers in unoptimized builds or when ASSERTIONS is on

It will also be used with `-s WASM=1`:

https://github.com/kripken/emscripten/blob/9576ca9df8abb49eb9b79e06457109a13a639a7a/emcc.py#L1142-L1145

> The indirection is also still necessary in some cases, like when SWAPPABLE_ASM_MODULE (worth making sure those tests pass).

I've just addressed actual swappability in latest commit, `browser.test_asm_swapping` test is good now.

> Measuring it now, it's slightly larger in code size both -O0 and -O2 and with and without EXPORT_ALL.

Which project are you testing it on?
I've retested [this](https://github.com/nazar-pc/supercop.wasm/blob/master/gulpfile.ls#L33) and got size reduction from 18.6KiB (incoming as of right now) to 17.9KiB (this PR just rebased against exactly the same incoming).

P.S. Interestingly, just 20 days ago (first message here) the same build was 20.4KiB, optimizations actually make it significantly smaller!

**Comment by nazar-pc** [comment]
In fact, the only place left where `SWAPPABLE_ASM_MODULE` does something is following:
https://github.com/kripken/emscripten/blob/9576ca9df8abb49eb9b79e06457109a13a639a7a/emcc.py#L2152-L2163

It looks like `SWAPPABLE_ASM_MODULE` can be dropped altogether now, since it is possible to swap `Module['asm']` anytime now anyway.

P.S. Yes, I like dropping unnecessary code and make stuff smaller 😄

**Comment by nazar-pc** [comment]
Here is another project I'm working on: https://github.com/nazar-pc/noise-c.wasm
This PR results in size reduction from 25.8 KiB to 21.5 KiB. I think this is pretty significant difference.

**Comment by kripken** [comment]
I tested on hello_world.c. Do you see different results there?

I can do another round of comparisons if this passes all tests now.

**Comment by nazar-pc** [comment]
Try something that has exported function instead of hello_world.c.
This passes all tests I've thrown at it, so yes, take a look at it again when you have time.

**Pull request closed without merging**
