### PR TITLE
Re-enable SANITIZER_INTERCEPT_MALLOPT_AND_MALLINFO

### PR DESCRIPTION
**Pull request by sbc100**
The logic of this macro was inverted when the llvm-12 update to
compiler-rt (#14280).  This caused asan.test_setjmp_noleak to start
failing.

Its not clear it we want to keep this long term but restoring
it at least fixes the failing test.

See #14360

### CODE REVIEW

**Comment by aheejin** [comment]
#14280's change for `SANITIZER_INTERCEPT_MALLOPT_AND_MALLINFO` is this, and it doesn't include `SI_EMSCRIPTEN`?
image

**Comment by sbc100** [comment]
> #14280's change for `SANITIZER_INTERCEPT_MALLOPT_AND_MALLINFO` is this, and it doesn't include `SI_EMSCRIPTEN`?
> image

But its defined as a negative conjunction in the old version.. so it ends up being true for emscripten.

**Comment by sbc100** [comment]
> > #14280's change for `SANITIZER_INTERCEPT_MALLOPT_AND_MALLINFO` is this, and it doesn't include `SI_EMSCRIPTEN`?
> > image
> 
> But its defined as a negative conjunction in the old version.. so it ends up being true for emscripten.

The condition on the left if true under emscripten right?

**Comment by aheejin** [comment]
I think you're right... Then wouldn't it be good to reenable the failing test here too?

**Comment by sbc100** [comment]
> I think you're right... Then wouldn't it be good to reenable the failing test here too?

The failing test is an asan test which was never disabled.   Its currently red on the emscripten-releases waterfall.

**Review by aheejin — APPROVED** [review]
Ah right, thanks.

**Pull request merged**
