### PR TITLE
[EH] Warn for ASYNCIFY + -fwasm-exceptions

### PR DESCRIPTION
**Pull request by aheejin**
This combination is currently not supported.

### CODE REVIEW

**Comment by dschuff** [comment]
Does JSPI-based asyncify also use the `ASYNCIFY` setting? If so, I guess this should be more specific?
(but in the long term, maybe we want to give it its own flag)

**Comment by aheejin** [comment]
Not sure. @kripken @brendandahl What's your plan for the flag?

**Review by kripken — APPROVED** [review]

**Comment by kripken** [comment]
Actually, I'm not sure about this. In theory a user can only asyncify a small part of their program, and that part might not contain any try-catch. So this change would prevent them from compiling something that worked before. Perhaps this should just be a warning?

**Comment by aheejin** [comment]
But even compiling this with both options crashes, I guess, because of libraries:
```console
emcc -fwasm-exceptions -sASYNCIFY=1 test.cpp
```
```cpp
int main() {
  return 0;
}
```

**Comment by kripken** [comment]
Yes, that's probably due to libraries. But with an only-list it is possible to not error:
```
$ ./emcc -fwasm-exceptions -sASYNCIFY=1 test/hello_world.c -s ASYNCIFY_ONLY=main
$
```

**Review by kripken — APPROVED** [review]

**Pull request merged**
