### PR TITLE
Validate EM_JS/EM_ASM strings in side modules at build time

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by RReverser** [comment]
FWIW in optimized mode they're already validated at build-time because they're parsed by Acorn in `tools/acorn-optimizer`. Maybe it's worth reusing that somehow where it would just parse but not run any actual optimisations in debug mode?

**Comment by RReverser** [comment]
If not, I'd at least suggest not invoking a process per each EM_JS/EM_ASM block - that can get expensive pretty fast - but rather once on the final file that has those functions inlined.

You can also use Node.js `--check` flag to just validate the syntax without actually executing it - which is what we want.

**Comment by sbc100** [comment]
> If not, I'd at least suggest not invoking a process per each EM_JS/EM_ASM block - that can get expensive pretty fast - but rather once on the final file that has those functions inlined.
> 
> You can also use Node.js `--check` flag to just validate the syntax without actually executing it - which is what we want.

Ah yes, good idea on both counts.  I was assuming the number of EM_JS/EM_ASM blocks would be small but that might not be the case.

**Comment by RReverser** [comment]
I'm still not sure what's the benefit of validating those in individual calls with temporary JS snippets vs validating the final output.js file produced by Emscripten.

Separate checks could be useful if we could pinpoint them back to location in C/C++ source file, but since we can't at the moment anyway, might as well only validate the full output JS file?

**Comment by RReverser** [comment]
> Separate checks could be useful if we could pinpoint them back to location in C/C++ source file, but since we can't at the moment anyway

OTOH _this_ would be really cool and perhaps doable by encoding `__FILE__` and `__LINE__` from macro into that magic string that gets preserved all the way through to postprocessing?

**Comment by sbc100** [comment]
> I'm still not sure what's the benefit of validating those in individual calls with temporary JS snippets vs validating the final output.js file produced by Emscripten.
> 
> Separate checks could be useful if we could pinpoint them back to location in C/C++ source file, but since we can't at the moment anyway, might as well only validate the full output JS file?

This idea actually came from somebody building side modules with EM_JS and EM_ASM in them.    In this case there is no JS output at all.. it just stayed embedded in the wasm binary until load time.   

I suppose we could limit these checks to just the cases where we don't output JS.

In the case where we are not building a side module (and we do output a JS file) would you prefer that I instead validate the entire output file?

**Comment by RReverser** [comment]
> This idea actually came from somebody building side modules with EM_JS and EM_ASM in them. In this case there is no JS output at all.. it just stayed embedded in the wasm binary until load time.

Ah now I understand the usecase.

Yeah I think it makes sense to limit this to side modules.

On full modules we could run validation only if no optimisations are enabled (as otherwise we are going to parse that JS with Acorn anyway).

**Comment by sbc100** [comment]
OK, I decided to simply limit this new check to the SIDE_MODULE case for now.  We can expand it later if we needs be.

**Review by RReverser — APPROVED** [review]

**Pull request merged**
