### PR TITLE
Updating to use emscripten-stored version of upstream

### PR DESCRIPTION
**Pull request by HCLJason**
The config file was generated by emconfigure.

### CODE REVIEW

**Comment by sbc100** [comment]
Looks like a test needs updating:

```
/root/project/tests/third_party/libpng/pngtest.c:2031:9: error: unknown type name 'png_libpng_version_1_6_17'; did you mean 'png_libpng_version_1_6_37'?
typedef png_libpng_version_1_6_17 Your_png_h_is_not_version_1_6_17;
        ^~~~~~~~~~~~~~~~~~~~~~~~~
        png_libpng_version_1_6_37
/root/cache/sysroot/include/png.h:431:15: note: 'png_libpng_version_1_6_37' declared here
typedef char* png_libpng_version_1_6_37;
              ^
1 error generated.
```

You should be able to verify locally by running `./tests/runner other.test_libpng`.

**Review by sbc100 — APPROVED** [review]

**Comment by HCLJason** [comment]
I'm getting an error on my local machine when compiling test_other.other that I'm trying to track down.

The error message is:
wasm-ld: error: unknown argument: --export-if-defined=__start_em_asm
wasm-ld: error: unknown argument: --export-if-defined=__stop_em_asm

It looks like that's because SIDE_MODULE is being cleared in
_test_dylink_dso_needed in tests/runner.py.

**Comment by sbc100** [comment]
> I'm getting an error on my local machine when compiling test_other.other that I'm trying to track down.
> 
> The error message is:
> wasm-ld: error: unknown argument: --export-if-defined=__start_em_asm
> wasm-ld: error: unknown argument: --export-if-defined=__stop_em_asm
> 
> It looks like that's because SIDE_MODULE is being cleared in
> _test_dylink_dso_needed in tests/runner.py.

Which test exactly is failing for you?

**Comment by HCLJason** [comment]
The libpng test passed, then it started building other files and hit a problem in test_other.other.

shared:INFO: (Emscripten: Running sanity checks)
test_libpng (test_other.other)

**Comment by sbc100** [comment]
You should be able to run just one test at a tine `./tests/runner other.test_libpng` for example.  In that case it should not run anything but that one test.

In the case that fails does it now show the name of the failing test?  can you include some more of the output?

Are you using emsdk to get your llvm and binaryen versions?

**Comment by HCLJason** [comment]
I'm using emsdk for both. I just checked, and my emsdk is a couple of versions back, so that might be it.

Original error (clean repo checkout):
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libc_rt_wasm.a... (this will be cached in "/home/jason/repos/emscripten/cache/sysroot/lib/wasm32-emscripten/libc_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libsockets.a... (this will be cached in "/home/jason/repos/emscripten/cache/sysroot/lib/wasm32-emscripten/libsockets.a" for subsequent builds)
cache:INFO:  - ok
wasm-ld: error: unknown argument: --export-if-defined=__start_em_asm
wasm-ld: error: unknown argument: --export-if-defined=__stop_em_asm

This is what I have from when I re-ran the test:
$ ./tests/runner other.test_libpng
runner:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
WARNING: no 'numpy' module, HyBi protocol will be slower
posixtestsuite not found (run git submodule update --init?)
runner: warning: unexpected binaryen version: 100 (expected 101) [-Wversion-check]
Test suites:
['test_other']
Running test_other: (1 tests)
(checking sanity from test runner)
shared:INFO: (Emscripten: Running sanity checks)
test_libpng (test_other.other) ... wasm-ld: error: unknown argument: --export-if-defined=__start_em_asm
wasm-ld: error: unknown argument: --export-if-defined=__stop_em_asm

**Comment by sbc100** [comment]
Ah, the `error: unknown argument: --export-if-defined` error is because you version of llvm is too old.

If you are using emsdk you want to run `./emsdk install tot` so you have the latest version of emscripten dependencies.

**Pull request merged**
