### PR TITLE
Use command line argument over env vars to control test runner.

### PR DESCRIPTION
**Pull request by sbc100**
For the time being I've left the environment variables in place
so its possible to use either `--save-dir` or `EMTEST_SAVE_DIR=1`.

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
I'm not opposed to this, but what is the benefit in you eyes?

**Comment by sbc100** [comment]
> I'm not opposed to this, but what is the benefit in your eyes?

Some of these should simply always have been command line arguments.    One of the main reason I didn't do this earlier was that I was confused by #14513 which made it hard to share global state.  Now that that is fixed its much easier.

In general, as way to control the behaviour of a single command, environment variables have several disadvantages.   They are good for global settings and such, so for some of these we there could be an argument for keeping them around.   However for the one that I use the most often, EMTEST_SAVE_DIR, my arguments against having has an environment variable are:

1. The not the kind of thing one would want to have always on in the environment.  This means I/we always specify it inline on the command line anyway (e.g. `EMTEST_SAVE_DIR=1 ./test/runners ...`)
2. Its more typing than just `--savedir`.   (Also typing a uppercase + underscores is slow compared to hyphen + lowercase)
3. It is easy to spell incorrectly with no way to detect such things (I often do `MTEST_SAVE_DIR=1` by mistake)
4. It is less `--help` friendly.   

A quick google shows some more general arguments against the overuse of env vars: https://support.cloud.engineyard.com/hc/en-us/articles/205407508-Environment-Variables-and-Why-You-Shouldn-t-Use-Them#:~:text=If%20you're%20relying%20on,or%20a%20shared%20data%20source.

**Comment by sbc100** [comment]
More from https://www.gnu.org/software/libc/manual/html_node/Environment-Variables.html:

`The argv mechanism is typically used to pass command-line arguments specific to the particular program being invoked. The environment, on the other hand, keeps track of information that is shared by many programs, changes infrequently, and that is less frequently used.`

**Review by kripken — APPROVED** [review]

**Comment by sbc100** [comment]
Somehow this change is breaking the emscripten-releases builder: https://chromium-review.googlesource.com/c/emscripten-releases/+/2993946

We set `EMTEST_LACKS_NATIVE_CLANG` but it doesn't seem to be having an effect there

**Comment by sbc100** [comment]
Locally this works for me:

EMTEST_LACKS_NATIVE_CLANG=1 python3 ./tests/runner.py other.test_wasm2c_multi_lib
..
skipped 'native clang tests are disabled'
...
```

**Pull request merged**
