### PR TITLE
Don't add `Module.inspect` when building for node

### PR DESCRIPTION
**Pull request by sbc100**
This was added back in 2015 but without any rationale.  See 8d4d62eefc.

My guess is that this was somehow related to node's `util.inspect` function but this doesn't seem to be the way to work with that. We would need to do something more like this to make that work: https://nodejs.org/api/util.html#custom-inspection-functions-on-objects

Perhaps it has some other purpose but I have no idea what that might be.

### CODE REVIEW

**Comment by sbc100** [comment]
@fabiosantoscode do you remember why you added this?

**Comment by fabiosantoscode** [comment]
I don't remember adding this, but I do know that centuries ago this is how you'd create custom inspect strings of objects, for the purposes of console.log() and util.inspect()

https://nodejs.org/docs/latest-v0.12.x/api/util.html#util_custom_inspect_function_on_objects

Today you use `theObject[Symbol.for('nodejs.util.inspect.custom')]` as opposed to just `theObject.inspect`.

https://nodejs.org/dist/latest-v20.x/docs/api/util.html#utilinspectcustom

**Comment by fabiosantoscode** [comment]
Fun issue title. I guess this is why I added it. https://github.com/emscripten-core/emscripten/issues/3416

**Comment by sbc100** [comment]
> Fun issue title. I guess this is why I added it. #3416

I tried to reproduce this in the node interpreter and was not able to.  Can you?

```
$ node 
Welcome to Node.js v16.20.0.
Type ".help" for more information.
> a = { foo: 1 };
{ foo: 1 }
> a.inspect = function() { return 'hello' };
[Function (anonymous)]
> a
{ foo: 1, inspect: [Function (anonymous)] }
> 
```

I also tried printing and emscripten `Module` without this change and it didn't use the inspect function.  So I guess this maybe used to work in the part but no longer?

Anyway I think we can remove it now?

**Comment by sbc100** [comment]
Oh.. I tried it with node 10.19.0 and there I see a deprecation warning:

```
> (node:1009531) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```

So I guess it used to work in the past.

These days node is pretty good and not printing a huge amount when printing the `Module` object (i.e. it truncates memory views etc) so I don't think there is any need to try to port this feature to the new method.

**Comment by fabiosantoscode** [comment]
> These days node is pretty good and not printing a huge amount when printing the Module object (i.e. it truncates memory views etc) so I don't think there is any need to try to port this feature to the new method.

Yeah that makes a lot of sense. Another reason not to retain this behavior is that the browser can't do something similar, so it would be a bit inconsistent.

**Review by kripken — APPROVED** [review]

**Pull request merged**
