### PR TITLE
Header and stubs for LLVM

### PR DESCRIPTION
**Pull request by kripken**
LLVM includes `machine/endian.h` which apparently we need
to redirect to `bits/endian.h`.

Also add `execinfo.h` (also necessary for LLVM) with stubs that
abort, but we could expand them if necessary.

### CODE REVIEW

**Comment by sbc100** [comment]
Where goes the include of `execinfo.h` comes from?  I don't see any uses in llvm that are in portable code:

```
compiler-rt/lib/fuzzer/dataflow/DataFlow.cpp:#include <execinfo.h>  // backtrace_symbols_fd
compiler-rt/lib/gwp_asan/optional/backtrace_linux_libc.cpp:#include <execinfo.h>
compiler-rt/lib/msan/msan_linux.cpp:#include <execinfo.h>
compiler-rt/test/asan/TestCases/Darwin/crashlog-stacktraces.c:#include <execinfo.h>
compiler-rt/test/msan/backtrace.cpp:#include <execinfo.h>
lldb/examples/interposing/darwin/fd_interposing/FDInterposing.cpp:#include <execinfo.h>
lldb/source/Host/freebsd/Host.cpp:#include <execinfo.h>
lldb/source/Host/netbsd/HostNetBSD.cpp:#include <execinfo.h>
llvm/docs/GwpAsan.rst:GNU's ``backtrace_symbols()`` from ``<execinfo.h>`` to unwind. The unwinder
```

**Comment by sbc100** [comment]
Ditto for `machine/endian.h` .. where is that ref coming from?

I don't see anywhere that its likely to be included with emcc?  `llvm/include/llvm/Support/SwapByteOrder.h` looks like that should include just `<endian.h>`.

**Comment by kripken** [comment]
It's hiding! :smile: 

LLVM's build system will generate a `config.h` file in the build directory, which contains `#define BACKTRACE_HEADER <execinfo.h>`. And that macro is used in `llvm/lib/Support/Unix/Signals.inc`.

**Comment by kripken** [comment]
For `endian.h`, it ends up reaching this:
```
#if !defined(BYTE_ORDER) && !defined(_WIN32)
#include <machine/endian.h>
#endif
```
It gets there since we are not "linux" or any of the other options it checks.

**Comment by sbc100** [comment]
> For `endian.h`, it ends up reaching this:
> 
> ```
> #if !defined(BYTE_ORDER) && !defined(_WIN32)
> #include <machine/endian.h>
> #endif
> ```
> 
> It gets there since we are not "linux" or any of the other options it checks earlier.

But we do define `__GNU__` so this first case should fire:

https://github.com/llvm/llvm-project/blob/f5224d437eace9593b64ef2eff501df397bce6a8/llvm/include/llvm/Support/SwapByteOrder.h#L25

```
$ ./emcc -dM -E -x c++ - < /dev/null | grep GNU
#define _GNU_SOURCE 1
#define __GNUC_GNU_INLINE__ 1
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC__ 4
#define __GNUG__ 4
```

**Comment by sbc100** [comment]
> It's hiding! 
> 
> LLVM's build system will generate a `config.h` file in the build directory, which contains `#define BACKTRACE_HEADER <execinfo.h>`. And that macro is used in `llvm/lib/Support/Unix/Signals.inc`.

This looks like a mis-configuration.  

```
#ifdef HAVE_BACKTRACE                                                            
# include BACKTRACE_HEADER         // For backtrace().                                                        
#endif  
```

The correct fix looks like we should not be defining `HAVE_BACKTRACE` .. how is it that this end up getting defined?

**Comment by kripken** [comment]
Good question. I'm not sure offhand of a convenient way to debug the LLVM build system to find that out - is there?

**Comment by dschuff** [comment]
Didn't we already implement `backtrace` when we did the sanitizers?

**Comment by kripken** [comment]
We implemented something like backtrace but simpler, `emscripten_stack_snapshot, emscripten_stack_unwind_buffer`.

**Comment by sbc100** [comment]
I think we decided none of this was needed, and that llvm and other projects were better off being configured not to use such things.

We don't want emscripten to become some universal superset of system headers (unless we really can't avoid it).

**Comment by kripken** [comment]
cc @pfaffe - would this still be useful, or can we close it?

**Comment by pfaffe** [comment]
I _think_ we could get by without this change.

For the `SwapByteOrder.cpp` include of `endian.h`, we need to make llvm include the proper `endian.h`, i.e., not the one in machine/. I wonder if emcc should define either __GNU__ or __linux__? If not, we can fix llvm by also checking for __EMSCRIPTEN__. There few other places in llvm where we've got the same problem. Which of the two would you consider the proper fix?

Interestingly I'm not seeing the backtrace problem anymore. LLVM's Config.h now has `/* #undef HAVE_BACKTRACE */`. @kripen Can you confirm?

**Comment by sbc100** [comment]
Oh, I misread `__GNU__` in `SwapByteOrder.h` as `__GNUC__` which we *do* defined.  My apologies.  

I think defining `__GNU__` (which is guess means GNU hurd?) or `__linux__` is probably not that right answer.   Lets go for adding `__EMSCRIPTEN__` (or mabye  `__MUSL__` .. or whatever that is called) to the first case.   I'm also be interested to see what other relatively modern toolchains such a fuchsia and wasi-sdk do here.

**Comment by sbc100** [comment]
Looks like neither fuchsia nor wasi-sdk  have a `machine/endian.h`  .. so maybe llvm just hasn't been compiled there, but I'm a little surprised by that.

**Pull request closed without merging**
