### PR TITLE
Add a specific flag to enable / disable the use of 'import.meta.url'

### PR DESCRIPTION
**Pull request by adevress**
This fixes the problem reported by #9233 and by #8729 while fixing the regression bug causes by #8940

Thank you for submitting a pull request!

If this is your first PR, make sure to add yourself to AUTHORS.

### CODE REVIEW

**Comment by adevress** [comment]
@VirtualTim  It seems that even with your approval I can not merge the change :(

**Comment by VirtualTim** [comment]
Yeah I'm too untrustworthy to have write access. You'll probably need @kripken to approve this.

**Comment by adevress** [comment]
ping @kripken

**Comment by MarcelKlammer** [comment]
USE_ES6_IMPORT_META should default to 0, no?
Anyway, thanks for adding this flag.

**Comment by sbc100** [comment]
It looks like this reached stage4 almost 5 years ago now: https://github.com/tc39/proposal-import-meta/pull/21.

Can we revisit this now and potentially remove this setting?

**Comment by sbc100** [comment]
Is anyone still using this setting?   I'm hoping to remove it: #23171

**Pull request merged**
