### PR TITLE
Add missed musl sendfile.h

### PR DESCRIPTION
**Pull request by VirtualTim**
For some reason this file was missing, but is present in the musl repo: https://github.com/emscripten-core/musl/blob/master/include/sys/sendfile.h.
I created a bug on emsdk (https://github.com/emscripten-core/emsdk/issues/983), but it looks like the issue was actually here.

Edit: I realise now that this file was intentionally removed (#14248). I've replaced the contents with a compiler warning linking to the PR that removed.
I don't know if this is a good idea or not, so welcome some input.

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
I think this makes sense. A clear compile error sounds good.

Maybe the text could be "sendfile is not supported" instead of "was removed"?

@sbc100 what do you think?

**Comment by sbc100** [comment]
Why not simply not include it?

**Comment by sbc100** [comment]
I think if a header file is completely unsupported (e.g. windows.h) is seems reasonable to not include it at all.

**Comment by sbc100** [comment]
We should probably remove a bunch of other linux-specific headers too I guess.

**Comment by VirtualTim** [comment]
From my point of view, a project I was compiling with 1.39.6 could no longer compile when upgrading to 3.1.3. As the error was a missing system header I thought something was wrong with my Emscripten setup. I wasted a bunch of time before I released that the file had actually been intentionally removed. I could also see this being useful for people trying to port existing software, as something like this will actually tell them what to do.
But I do get that changing a file to error on include is a bit odd.

Maybe instead of this the removal of `sendfile.h` should just be mentioned in the changelog?

**Comment by sbc100** [comment]
Certainly, adding a changelog entry makes sense to me.

**Comment by VirtualTim** [comment]
Closed in favour of just updating the changelog.

**Pull request closed without merging**
