### PR TITLE
Fix emar.py to properly use response files. Remove stale comments.

### PR DESCRIPTION
**Pull request by juj**

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
How about using `shared.get_command_with_possible_response_file`?

**Comment by sbc100** [comment]
I'm not quite sure why this is needed?   The incoming command line is by definition small enough to fit within platform limits isn't it?   Or is the risk that changing arg0 might make it too long?

(I certainly seem strange to use a response file unconditionally here and would make debugging harder for simple cases).

**Comment by sbc100** [comment]
> I'm not quite sure why this is needed? The incoming command line is by definition small enough to fit within platform limits isn't it? Or is the risk that changing arg0 might make it too long?
> 
> (I certainly seem strange to use a response file unconditionally here and would make debugging harder for simple cases).

Ah I see.. its because your other change will auto-expand the command line

**Comment by juj** [comment]
> Ah I see.. its because your other change will auto-expand the command line

Yes, that is due to the suggestion in the other PR to have the rsp expansion occur for all tools.

**Comment by juj** [comment]
Actually, since this PR makes only sense in the context of #13954, I'll merge this into that.

**Pull request closed without merging**
