### PR TITLE
fix glGetString crashing on some erroneous calls

### LINKED ISSUE #10494: Erroneous glGetString call throws TypeError
```
WebGL: INVALID_ENUM: getParameter: invalid parameter name, WEBGL_debug_renderer_info not enabled
Uncaught TypeError: Cannot read property 'length' of null
    at lengthBytesUTF8 (taisei.js:formatted:5053)
    at stringToNewUTF8 (taisei.js:formatted:12107)
    at _glGetString (taisei.js:formatted:14009)
    at wasm-function[2316]:0x190c9d
```

A null value is passed to `stringToNewUTF8` here: https://github.com/emscripten-core/emscripten/blob/430c2911dbe0104beab264cd19a971a2a7c6b793/src/library_webgl.js#L1165

Would it be a good idea to make `stringToNewUTF8` return a null pointer if the argument is null? I think it at least warrants an assertion.

### PR DESCRIPTION
**Pull request by Akaricchi**
fixes #10494

### CODE REVIEW

**Comment by Akaricchi** [comment]
Eh, I believe I have enough GL expertise to claim this is correct. From the [gles3 reference page for glGetString](https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glGetString.xhtml):

> If an error is generated, glGetString returns 0.

Also this function does the exact same thing in the default case: https://github.com/emscripten-core/emscripten/blob/9befbb883f669759456970bdd20a92745c1da5a0/src/library_webgl.js#L1199

**Comment by juj** [comment]
How about
```diff
diff --git a/src/library_webgl.js b/src/library_webgl.js
index c44ac9809..0c05dd9bc 100644
--- a/src/library_webgl.js
+++ b/src/library_webgl.js
@@ -1147,24 +1147,6 @@ var LibraryGL = {
 #endif
         ret = stringToNewUTF8(exts.join(' '));
         break;
-      case 0x1F00 /* GL_VENDOR */:
-      case 0x1F01 /* GL_RENDERER */:
-      case 0x9245 /* UNMASKED_VENDOR_WEBGL */:
-      case 0x9246 /* UNMASKED_RENDERER_WEBGL */:
-#if !GL_EMULATE_GLES_VERSION_STRING_FORMAT
-      case 0x1F02 /* GL_VERSION */:
-      case 0x8B8C /* GL_SHADING_LANGUAGE_VERSION */:
-#endif
-        var s = GLctx.getParameter(name_);
-        if (!s) {
-          GL.recordError(0x500/*GL_INVALID_ENUM*/);
-#if GL_ASSERTIONS
-          err('GL_INVALID_ENUM in glGetString: Received empty parameter for query name ' + name_ + '!'); // This occurs e.g. if one attempts GL_UNMASKED_VENDOR_WEBGL when it is not supported.
-#endif
-        }
-        ret = stringToNewUTF8(s);
-        break;
-
 #if GL_EMULATE_GLES_VERSION_STRING_FORMAT
       case 0x1F02 /* GL_VERSION */:
         var glVersion = GLctx.getParameter(0x1F02 /*GL_VERSION*/);
@@ -1189,6 +1171,25 @@ var LibraryGL = {
         }
         ret = stringToNewUTF8(glslVersion);
         break;
+#endif
+      case 0x1F00 /* GL_VENDOR */:
+      case 0x1F01 /* GL_RENDERER */:
+      case 0x9245 /* UNMASKED_VENDOR_WEBGL */:
+      case 0x9246 /* UNMASKED_RENDERER_WEBGL */:
+#if !GL_EMULATE_GLES_VERSION_STRING_FORMAT
+      case 0x1F02 /* GL_VERSION */:
+      case 0x8B8C /* GL_SHADING_LANGUAGE_VERSION */:
+#endif
+        var s = GLctx.getParameter(name_);
+        if (s) {
+          ret = stringToNewUTF8(s);
+          break;
+        }
+#if GL_ASSERTIONS
+        GL.recordError(0x500/*GL_INVALID_ENUM*/);
+        err('GL_INVALID_ENUM in glGetString: Received empty parameter for query name ' + name_ + '!'); // This occurs e.g. if one attempts GL_UNMASKED_VENDOR_WEBGL when it is not supported.
+        break;
+        // If no GL_ASSERTIONS, fall through to default case to record GL error.
 #endif
       default:
         GL.recordError(0x500/*GL_INVALID_ENUM*/);
```
to fix the issue but also save code size?

**Comment by kripken** [comment]
Looks like there was a review suggestion here, and this is waiting on @Akaricchi ?

**Comment by Akaricchi** [comment]
Yeah I kind of forgot about this one. Also I'm currently recovering from a major data loss, not sure when I'll find some time for emscripten stuff, but I'll what I can do.

**Comment by juj** [comment]
Closing as stale, posted #13784 to replace this.

**Pull request closed without merging**
