### PR TITLE
jsifier: Make JS libraries aliases work even when native export exists

### PR DESCRIPTION
**Pull request by sbc100**
Followup to #19033.

Updating the `test_closure_full_js_library` to include webgl2 caused a lot of `JSC_REFERENCE_BEFORE_DECLARE` closure errors.

This is because we had JS aliases who's target was defined both in JS and in native code.  In this case the jsifier was choosing not to include the JS version, which in the case of the GL symbols not what we want.  I imagine this is why, prior to #19033, we were duplicating the library entries.

This this change JS symbol aliases now force the alias target to be included from the JS library, even in the case that the native code also emits its own version of a symbol.

This happens in the case of pthreads + MAIN_MODULE + OFFSCREEN_FRAMEBUFFER. In this mode webgl2.c defines (and also exports) the entire set of GL library symbols.  In this case we still want the `emscripten_XX` aliases to point to the original JS versions, not the exported native version.

Sadly it looks like we have at testing gap for that particular combination.

### CODE REVIEW

**Comment by sbc100** [comment]
An alternative to this PR would be to revert #19033, but I think I like this solution better.

**Comment by kripken** [comment]
> which in the case of the GL symbols not what we want

Can you explain why that isn't what we want? (If a symbol is defined in both JS and C I'd expect us to always want the C version?)

**Comment by juj** [comment]
This all sounds good to me, though didn't check the code in detail.

Btw, I am wondering if we should rename `emscripten_gl*` function names all to something else, e.g. `_js_gl*` or similar? The API `emscripten_*` is used always for public functions, whereas these renamings for the glGetProc* thing and Offscreen Framebuffer are for internal meaning. End users should never be calling any of the `emscripten_gl*` functions directly/statically.

**Review by kripken — APPROVED** [review]
I see, thanks. lgtm.

Separately from this, it might be worth thinking about simplifying that. One idea might be to reverse the aliasing, that is, make `js_glFoo` contain the actual JS code, and add an alias from `glFoo` to `js_glFoo`. Then native code would implement `glFoo` and call out to `js_glFoo` and no alias would be needed in that case, which seem simpler. But possibly I'm forgetting some issue...

**Comment by sbc100** [comment]
> I see, thanks. lgtm.
> 
> Separately from this, it might be worth thinking about simplifying that. One idea might be to reverse the aliasing, that is, make `js_glFoo` contain the actual JS code, and add an alias from `glFoo` to `js_glFoo`. Then native code would implement `glFoo` and call out to `js_glFoo` and no alias would be needed in that case, which seem simpler. But possibly I'm forgetting some issue...

Agreed, I think these are possible simplifications we can do here.   I'll add a comment here and we can look into followups.

**Pull request merged**
