### PR TITLE
Update closure-compiler. NFC

### PR DESCRIPTION
**Pull request by sbc100**
There is tiny codesize regression with this update, but it seems to be
consistently <10 bytes so I'm tempted to ignore it.

### CODE REVIEW

**Review by dschuff — APPROVED** [review]

**Comment by sbc100** [comment]
There is tiny codesize regression with this update, but it seems to be
consistently <10 bytes so I'm tempted to ignore it.

**Comment by sbc100** [comment]
Looking at the diff for `test_codesize_hello_wasmfs` it looks like this:

```
-    T = "undefined" != typeof TextDecoder ? new TextDecoder : void 0, ja = {
-      b : (a, c, d) => C.copyWithin(a, c, c + d),
+    U = "undefined" != typeof TextDecoder ? new TextDecoder : void 0, ja = {
+      b : (a, c, d) => D.copyWithin(a, c, c + d),
       a : (a, c, d, e) => {
-        for (var n = 0, W = 0; W < d; W++) {
-          var la = D[c >> 2], X = D[c + 4 >> 2];
+        for (var n = 0, X = 0; X < d; X++) {
+          var ma = E[c >> 2], Y = E[c + 4 >> 2];
           c += 8;
-          for (var H = 0; H < X; H++) {
-            var f = C[la + H], I = ia[a];
+          for (var I = 0; I < Y; I++) {
+            var z = a, f = D[ma + I], J = ia[z];
             if (0 === f || 10 === f) {
-              f = I;
+              z = 1 === z ? ba : y;
+              f = J;
               for (var k = 0, m = k + NaN, q = k; f[q] && !(q >= m);)
                 ++q;
-              if (16 < q - k && f.buffer && T)
-                f = T.decode(f.subarray(k, q));
+              if (16 < q - k && f.buffer && U)
+                f = U.decode(f.subarray(k, q));
```

Note the extra `z = 1 === z ? ba : y;` in the new code.

Seems to be one of the UTF8 functions from library_strings.js.. just its hard to figure out what exactly is going on here.

**Comment by dschuff** [comment]
Yeah, seems fine to me. better to be up to date.

**Comment by sbc100** [comment]
@kripken WDYT?

**Review by kripken — APPROVED** [review]
Makes sense, an upstream change this small is probably not worth spending time on.

**Comment by reneleonhardt** [comment]
https://github.com/google/closure-compiler-npm/pull/314
has been released May 15, can you update to v20250226.0.0 to allow building on macOS arm64?

https://github.com/sql-js/sql.js/issues/613
```
building:WARNING: falling back to java version of closure compiler
Command '['/emsdk/node/20.18.0_64bit/bin/node', '--max_old_space_size=8192', '/emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler', '--platform=java', '--version']' returned non-zero exit status 254.
emcc: error: closure compiler (/emsdk/node/20.18.0_64bit/bin/node --max_old_space_size=8192 /emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler --platform=java --version) did not execute properly!
```

**Comment by sbc100** [comment]
We ran into some regressions when trying to update so we are currently blocked on investigating that.

**Comment by sbc100** [comment]
See https://github.com/emscripten-core/emscripten/pull/24679

**Pull request merged**
