### PR TITLE
Avoid duplicating __cxa_find_matching_catch function. NFC

### PR DESCRIPTION
**Pull request by sbc100**
This should be a code size saving for most application that use exception handling.

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
This might be worth measuring. Using `arguments` is slow anyhow, but I seem to recall some specific issue with wasm imports being variadic that was exceptionally slow - it misses some fast path in wasm->JS or such.

**Comment by sbc100** [comment]
> This might be worth measuring. Using `arguments` is slow anyhow, but I seem to recall some specific issue with wasm imports being variadic that was exceptionally slow - it misses some fast path in wasm->JS or such.

This change doesn't effect the use of `arguments`.   `arguments` is use by `__cxa_find_matching_catch` regardless of this change.

All this change does is avoid duplicating the function needlessly.

**Comment by kripken** [comment]
Correct, but after this change do we not have duplicate imports to the wasm? That is, duplicate entries in `wasmImports`. Before, those functions were separate and each had a distinct arity, which might be optimized better, now there is "overloading" IIUC.

(But as I said, maybe the later slowness of using `arguments` makes it moot...)

**Comment by sbc100** [comment]
> Correct, but after this change do we not have duplicate imports to the wasm? That is, duplicate entries in `wasmImports`. Before, those functions were separate and each had a distinct arity, which might be optimized better, now there is "overloading" IIUC.
> 

I'd be very surprised if using a copy of a function for N different `wasmImports` entries was any different to simply referencing the same function.    If the VM can make things faster when making a copy of the function shouldn't we leave it up the VM to do that, rather than copying it ourselves at the source level.  

I imagine what happens in most VMs is that a wrapper/thunk is created for each `wasmImports` entry.. and I can't see how this change would make those thunks any faster or slower.   The target of the thunk is fundamentally a variadic JS function.  If the VM can specialize to a particular arity for `arguments` I don't see why it could make more then one specialization.   This kind of second guessing of how the VM works probably isn't a great idea, right? 

Other arguments for not worrying about this are than it only effect emscripten EH, and that it only effect the exceptional code paths.

> (But as I said, maybe the later slowness of using `arguments` makes it moot...)

**Comment by kripken** [comment]
I agree in general, yes, a VM could do this.

But this isn't random second-guessing. This was, at some point in time, a serious perf issue in SpiderMonkey. I am not sure about the current status, or V8. But the optimization was that when the arity of the wasm import matched the arity of the JS function passed into that import, "magic" happened. If the arity did not match, then the magic was skipped...

OTOH, good point that this is just for exceptional code paths. I guess there's really no reason to focus on those! :smile:

**Comment by kripken** [comment]
(to add to that - that reason is why this split was even added, IIRC)

**Review by kripken — APPROVED** [review]

**Comment by sbc100** [comment]
> I agree in general, yes, a VM could do this.
> 
> But this isn't random second-guessing. This was, at some point in time, a serious perf issue in SpiderMonkey. I am not sure about the current status, or V8. But the optimization was that when the arity of the wasm import matched the arity of the JS function passed into that import, "magic" happened. If the arity did not match, then the magic was skipped...

But here the arity doesn't match.. since the JS function doesn't have a arity at all, right?  Perhaps at one point we did generate unique N-arity handlers?

**Comment by kripken** [comment]
Ah, you're right... the arity does not match. Yes, I think we used to, and must have removed it. This code (removed in this PR) had the right signature for the arity:

```js
LibraryManager.library['__cxa_find_matching_catch_' + n + '__sig'] = new Array(n + 2).join('p');
```

So I guess that was wrong, after we removed the different arities...

**Comment by sbc100** [comment]
> Ah, you're right... the arity does not match. Yes, I think we used to, and must have removed it. This code (removed in this PR) had the right signature for the arity:
> 
> ```js
> LibraryManager.library['__cxa_find_matching_catch_' + n + '__sig'] = new Array(n + 2).join('p');
> ```

Oh, I think it was a mistake to remove that line..  I think that might be reason not to use aliases.. because these functions have different signatures...

**Pull request merged**
