### PR TITLE
mkdirTree  WasmFS implementation 

### PR DESCRIPTION
**Pull request by impact-maker**
Description

Implemented the WASMFS mkdirTree() function.

### CODE REVIEW

**Comment by impact-maker** [comment]
@kripken @tlively Could you take a preliminary look at this pull request.

**Comment by impact-maker** [comment]
https://github.com/emscripten-core/emscripten/issues/15976

**Review by tlively — COMMENTED** [review]
Please add a test!

**Comment by impact-maker** [comment]
@tlively @sbc100  I have added a dummy comment still the test cases are failing. I would need your intervention to resolve this issue

**Comment by tlively** [comment]
@impact-maker, it looks like the diff here includes code from other PRs. Can you either rebase onto or merge main?

**Comment by impact-maker** [comment]
@tlively There are some issues in this Pull request in terms of testing and rebasing. Closing this Pull request and making a new pull request for this function

**Pull request closed without merging**
