### PR TITLE
Handle library funcs added during jsifier process.

### PR DESCRIPTION
**Pull request by sbc100**
Fixes: #20297

### CODE REVIEW

**Review by brendandahl — APPROVED** [review]

**Comment by brendandahl** [comment]
Should document this under: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#implement-a-c-api-in-javascript or somewhere else?

**Comment by sbc100** [comment]
I'm not sure I want to commit to this being part of the public API.   Do you think it will be generally useful?  It still seems a little hacky to me.

**Comment by brendandahl** [comment]
Couldn't a user run into this if they were writing their own library_*.js file? I suppose they could use the command line flag instead.

**Comment by sbc100** [comment]
> Couldn't a user run into this if they were writing their own library_*.js file? I suppose they could use the command line flag instead.

Yes, but I'm not sure adding to settings such as DEFAULT_LIBRARY_FUNCS_TO_INCLUDE is really part of the JS library API.. maybe it should be but I don't think its very common to need to do that.

**Comment by sbc100** [comment]
Adding to most settings in a library.js file doesn't nothing, for example, so that fact this kind of worked at all is kind of just luck.

**Pull request merged**
