### PR TITLE
Make header guards consistent

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by kripken** [comment]
I don't feel strongly, but why not use pragma once everywhere, as it's shorter?

**Comment by sbc100** [comment]
pragma once never really took off and so is just less common in coding styles.  Its not in google's, chomiums's, llvm's, or mozilla's.     I don't feel super strongly but I'd rather follow field here.

**Comment by kripken** [comment]
I see, thanks. lgtm then.

**Comment by juj** [comment]
No wait what, no!

#pragma once is supported everywhere, and it is the proper solution for these kinds of include guard scenarios. Can we revert this, this is silly.

**Comment by sbc100** [comment]
I'm not totally averse to using pragma once.  This change was mostly care about consistency.  I can fix forward.

**Pull request merged**
