### PR TITLE
Rebaseline other.test_minimal_runtime_code_size_random_printf_wasm2js.

### PR DESCRIPTION
**Pull request by brendandahl**

### CODE REVIEW

**Comment by sbc100** [comment]
I recently push a rebaseline of all the tests.. was it no accurate?

See 91629e767.

BTW my process for this is to run `test/runner other.*code_size* other.*codesize* --rebase` and then if the results looks reasonable I push directly (without review)

**Comment by brendandahl** [comment]
I don't see test_minimal_runtime_code_size_random_printf_wasm2js in that rebaseline. It's failed with the last head https://app.circleci.com/pipelines/github/emscripten-core/emscripten/37044/workflows/29a5effd-601b-4df2-8f1c-39c4c03cdc90/jobs/827089

**Comment by sbc100** [comment]
Strange, I wonder what is going on here.

**Comment by sbc100** [comment]
Not sure what happened there.. maybe there was another llvm change that triggered this.  I did another full rebase in 48a057532

**Comment by brendandahl** [comment]
> Not sure what happened there.. maybe there was another llvm change that triggered this. I did another full rebase in [48a0575](https://github.com/emscripten-core/emscripten/commit/48a057532951e31d0b6f0214834cb685063c95f2)

I had to do a `--clear-cache` for the changes to be picked up.

**Pull request closed without merging**
