### PR TITLE
Fix typo in comment for INLINING_LIMIT

### PR DESCRIPTION
**Pull request by connorjclark**
From a quick glance at the code, I think this is what it meant to say.

BTW, is there a good central page that lists all these options? I've been using @surma's https://emsettings.surma.technology/ but jw if there's some other page I've overlooked on the emscripten docs site

EDIT: ah, I had been looking for "empscripten flags" but these are called settings. when I searched for that I do end up https://emscripten.org/docs/api_reference/advanced-apis.html#settings-js which points to the source file, which is OK. Perhaps it'd be nice to also link to surma's page

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Thanks!

**Comment by surma** [comment]
@kripken It updates on every load. It live-fetches the source code of `settings.js` and parses the comments.

If that ever breaks, please file a bug (or PR :D) on [the repo](https://github.com/surma/emsettings).

**Comment by sbc100** [comment]
https://github.com/surma/emsettings is 404.. maybe a private repo?

One thing to note is that I'm about to land a change that uses `true/false` rather than `1/0` for boolean-only settings in the settings.js (so we can type check them): https://github.com/emscripten-core/emscripten/pull/16539.  However, we still expect folks to pass `1/0` on the command line so you might want to turn `true/false` into `1/0` when you show the default values.

**Comment by sbc100** [comment]
Also, I wonder if we should turn the result of your script into a static page in our documentation site?

**Comment by surma** [comment]
My bad. Made the repo public.

I think deprecating my page in favor of something on emscripten.org is the ideal outcome. You could make commits to `master` on the emscripten repo trigger a web hook that causes the page to rebuild. That way it would always stay up-to-date.

**Comment by kripken** [comment]
Thanks @surma !

I opened #16563 to remind us to both add a link for now and hopefully do the full automation idea later.

**Pull request merged**
