### PR TITLE
Move Emscripten-specific bits of WebGPU out from html5.h

### PR DESCRIPTION
**Pull request by juj**
Move Emscripten-specific bits of WebGPU out from html5.h to a dedicated emscripten_webgpu.h header and JS library file.

This is to keep the library_html5.js and html5.h files smaller, as there are already quite big, and it is expected that active development will come up in Emscripten WebGPU support. Placing all of that dev in the existing html5.h would make it a big mixing pot of all kinds of APIs (that it already is a little bit)

### CODE REVIEW

**Comment by juj** [comment]
Users would `#include <emscripten/emscripten_webgpu.h>` to access this. Perhaps the filename should be just `webgpu.h` for `#include <emscripten/webgpu.h>`, although in that case there would be both `#include <emscripten/webgpu.h>` and `#include <webgpu/webgpu.h>`, which might be confusing (and certainly also annoying for e.g. Sublime Text quick-open a file shortcut)

Open to suggestions on file naming.

**Comment by hujiajie** [comment]
May I ask what's the plan for the WebGL bits in html5.h? Are they in the category of "making html5.h a big mixing pot"?

**Comment by juj** [comment]
> If I'm reading correctly it would be `webgpu/emscripten_webgpu.h` currently. I think `emscripten/webgpu.h` or `emscripten/emscripten_webgpu.h` would both be fine. I have no strong opinion between the two.

Err, that's right.

What about `emscripten/webgpu_html5.h`? That would have a different filename for IDE quick open purposes (and easier visual memory purposes), and avoid awkwardly repeating `emscripten` twice?

> May I ask what's the plan for the WebGL bits in html5.h? Are they in the category of "making html5.h a big mixing pot"?

Yes, that was actually the reason that prompted me towards this change. I am about to add a new family of WebGL functions, and don't want to add them in html5.h. I think I could split WebGL offfrom html5.h into `emscripten/webgl_html5.h`, that'd parallel `emscripten/webgpu_html5.h` quite nicely.

**Comment by juj** [comment]
Updated, how does that look?

**Comment by kainino0x** [comment]
I think `library_emscripten_webgpu.js` should probably get the same rename to match.

`webgpu_html5.{h,js}` sounds alright, maybe slightly nicer would be `html5_webgpu.{h,js}` since they sort of "extend" `html5.{h,js}`?

**Comment by kainino0x** [comment]
... though looking at it again, they don't strictly have anything to do with html5 (could feasibly be used in a node target). Still would be ok to use html5 in the naming though.

**Comment by juj** [comment]
Ok, going with html5_webgpu.

**Pull request merged**
