### PR TITLE
Don't change default CMake compiler / linker flags

### PR DESCRIPTION
**Pull request by bmeurer**
It's a bit of a surprise that `Emscripten.cmake` overrides the defaults for CMake's C/C++ compiler and linker flags. In particular `RelWithDebInfo` by default doesn't include debugging information. From the history of this file it wasn't clear why this decision was made in the first place, but nowadays there doesn't seem to be a good reason to keep doing it.

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]
This change looks great to me!  I've often wondered if we could shrink the size of this file over time.

@juj do you have any memory as to why these overrides were originally included?

**Review by kripken — COMMENTED** [review]
I'm not an expert on CMake but this looks good to me.

Please add a `ChangeLog.md` entry, though. I am trying to think what might be a noticeable change for people. Having debug info when requested seems like the only thing, which sounds ok but is still worth mentioning. The only other possible change I see from tinkering with CMake locally are is Release (but not RelWithDebInfo) was `-O2` and will be `-O3`.

**Comment by sbc100** [comment]
I'm not sure this warrants a changelog entry.   Especially since we can't really explain why this was here in the first place.  @bmeurer do you think you could come up with something for the changelog that would be useful?

**Comment by kripken** [comment]
How about this?

```
* Stop overriding CMake default flags based on build type. This will result in builds that are more like CMake does on other platforms. You may notice that `RelWithDebInfo` will now include debug info (it did not before, which appears to have been an error), and that `Release` will use `-O3` instead of `-O2` (which is a better choice anyhow).
```

**Comment by bmeurer** [comment]
Updated the branch with Alon's suggested `ChangeLog.md` entry.

**Comment by sbc100** [comment]
Landed as is.. test failures are unrelated

**Review by sbc100 — APPROVED** [review]

**Pull request merged**
