### PR TITLE
Enable all GL non-debug extensions without maintaining an explicit list of extensions.

### LINKED ISSUE #12638: OES_fbo_render_mipmap not automatically initialized
Hello,
Is there a specific reason why this WebGL extension is not in the list of [automatically enabled extensions](https://github.com/emscripten-core/emscripten/blob/16d018704df2f1cf29ff37c2c1f271ab0caed518/src/library_webgl.js#L1083) ? Is there a performance caveat in using it ?
thanks

### PR DESCRIPTION
**Pull request by juj**
We discussed switching into this form at some point, and the consensus was good.

Fixes #12638.

### CODE REVIEW

**Review by kripken — APPROVED** [review]
I think I remember that too, but don't recall the details.

Maybe you or @kainino0x @kenrussell remember where the discussion was? Would be good to link to it from here.

**Comment by kenrussell** [comment]
I don't think I was involved in conversations around this.

Slight concern that users' code will implicitly require these extensions be supported, instead of knowingly enabling them. But since this large list of extensions has already been automatically enabled for some time, reducing the associated code in emscripten sounds ok.

**Review by kainino0x — APPROVED** [review]
https://github.com/emscripten-core/emscripten/pull/11866#issuecomment-674488212

**Comment by juj** [comment]
> Slight concern that users' code will implicitly require these extensions be supported, instead of knowingly enabling them.

For that bit, we have the Emscripten linker flag `-s GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0`, which can be used to get away from the native GL flag, and opt in to "I'll explicitly enable the extensions I need" scheme. The flag defaults to being enabled for native GL portability.

**Comment by Akaricchi** [comment]
My only concern with this is that filtering out the debug extensions seems hacky and unnecessary. I highly doubt they actually have any performance impact, and they'd be still listed in `GL_EXTENSIONS` while disabled, which technically violates the spec. See also https://github.com/emscripten-core/emscripten/pull/11866#issuecomment-674381471

That being said, this is way better than the whitelist.

**Comment by kainino0x** [comment]
There can be cost to WEBGL_debug_shaders because the implementation must hold onto either the original or translated shader to return the translated shader later. I don't remember whether this actually makes a difference in practice, but we should keep filtering it out. I think it's pretty unlikely that WEBGL_lose_context has any cost but I don't know.

**Comment by Akaricchi** [comment]
Would it be possible to only advertise enabled extensions in `GL_EXTENSIONS`? Last time I investigated this it didn't seem to be the case, but perhaps I missed something.

**Comment by juj** [comment]
I don't think that would be a good idea, because implementations would not then be able to easily know if that extension was available to enable manually.

> they'd be still listed in `GL_EXTENSIONS` while disabled, which technically violates the spec.

There is no spec wording about this behavior to be violated. We define the behavior for automatically enabled extensions in Emscripten, and this is how it is defined.

The intent of the automatically enabled extensions is to ease access to native GLES extensions for ported codebases. debug_shaders, debug_renderer_info and lose_context are not based on native GLES extensions, so there will not exist a codebase that would be using them in the native world (and would expect an eased access without needing to enable an item).

Further, the wording on those extensions has been crafted so that they are wished only to be used on sites for debugging purposes, so it is a good practice to follow that advice and not enable it by default for all built pages that use this portability feature.

**Pull request merged**
