### PR TITLE
Duplicated decalration of ignoring

### PR DESCRIPTION
**Pull request by leyao-daily**
Signed-off-by: Le Yao <le.yao@intel.com>

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Thanks!

Please add yourself to AUTHORS.

@sbc100 , would this conflict with any of your open PRs?

**Review by sbc100 — APPROVED** [review]
lgtm

**Comment by leyao-daily** [comment]
Don't know why the CI/CD timeout, can anyone help re-run the failed test? Thanks

**Review by sbc100 — APPROVED** [review]
Restarted the CI

**Pull request merged**
