### PR TITLE
Update emcc.py

### PR DESCRIPTION
**Pull request by DhairyaBahl**
@sbc100 This is a pull request for issue #12462 . Kindly look into it and tell me if i have to resolve it further.

Thanks for help :)

### CODE REVIEW

**Comment by kripken** [comment]
@DhairyaBahl I'd recommend first seeing that the code works locally. Just running `emcc.py` with you change should show some syntax errors.

See the developer's guide: https://emscripten.org/docs/contributing/developers_guide.html and also the test suite docs, as the next step after running is to test it, https://emscripten.org/docs/getting_started/test-suite.html

**Comment by DhairyaBahl** [comment]
@sbc100 Okay I got it. I will first test it locally and then pass it . Thanks for advice :)

**Comment by DhairyaBahl** [comment]
@kripken I was testing my changes as per ur instructions but i got an error while passing python tests\runner.py test_loop

  File "tests\runner.py", line 24
    print('error: emscripten requires python 3.6 or above', file=sys.stderr)
                                                                ^
SyntaxError: invalid syntax

Kindly tell me what should I do ??

Thanks :)

**Comment by kripken** [comment]
@DhairyaBahl As the error says, you need Python of at least version 3.6. what does `python --version` show? Also try `python3 --version`. If the last one works, you can run emcc.py and the test runner and other python scripts with `python3` before them, and it will use that version.

If you don't have a new enough python installed, you may need to install one.

**Comment by DhairyaBahl** [comment]
@kripken 

C:\Users\Dhairya Bahl\Desktop\cmder
λ python --version
Python 2.7.15

C:\Users\Dhairya Bahl\Desktop\cmder
λ python3 --version
Python 3.7.4

These were the outputs. So I guess I should try python3 behind them. 

Thanks for help :+1: )

**Comment by DhairyaBahl** [comment]
@kripken I am getting the following error :
runner: error: BINARYEN_ROOT is set to empty value in C:\Users\Dhairya Bahl\Desktop\emscripten\.emscripten

I have tried using "emsdk update-tags"  "emsdk install tot-upstream" "emsdk install latest-upstream" but nothing is working. Kindly guide me further.

Thanks for help :)

**Comment by sbc100** [comment]
You also need to run `emsdk activate latest` in order to use the installed SDK

**Comment by DhairyaBahl** [comment]
> You also need to run `emsdk activate latest` in order to use the installed SDK

@sbc100 Sorry I forgot to mention that, but I did run that also.

**Comment by DhairyaBahl** [comment]
@kripken @sbc100 Kindly reply to my previous questions. I was getting few errors which i mentioned earlier. 

Thanks :)

**Comment by DhairyaBahl** [comment]
@kripken I will try reinstalling first, If it still gives the same error, I will let you know. :)

**Pull request closed without merging**
