### PR TITLE
Revert "Fix relative paths in wasm backend source maps. Fixes #9837"

### LINKED ISSUE #9837: Invalid URLs (absolute paths) in source maps in some cases
## Summary

Source maps are supposed to contain only valid URLs in the `sources` array (either relative, or absolute with scheme). Emscripten sometimes emits absolute paths into that array instead, making them impossible to load by a browser.

## Examples

For a file `C:\Users\rreverser\Projects\temp-wasm\temp.c` with arbitary content in a folder `temp-wasm`, I'm trying different formats for the filename.

Note that this is not a Windows-specific issue, and you'll get same results with Unix filepaths.

1. Running `emcc ./temp.c -g4 -o temp.wasm` (relative filename in the same folder):

```js
{"version":3,"sources":["./temp.c"],"names":[],...
```

2. Running `emcc temp.c -g4 -o temp.wasm` (same relative filename, but without explicit `./`):

```js
{"version":3,"sources":["C:/Users/rreverser/Projects/temp-wasm/temp.c"],"names":[],...
```

3. Running `emcc ../temp-wasm/temp.c` (relative filename with a folder):

```js
{"version":3,"sources":["../temp-wasm/temp.c"],"names":[],
```

4. Running `emcc C:\Users\rreverser\Projects\temp-wasm\temp.c -g4 -o temp.wasm` (absolute filename):

```js
{"version":3,"sources":["C:/Users/rreverser/Projects/temp-wasm/temp.c"],"names":[],...
```

## Results

When a filename is relative but without a leading `./` or is specified as absolute, Emscripten outputs an absolute filename in `sources`, which is not a valid URL and can't be handled by DevTools. It could be valid if prefixed with `file:///` specifier, but that's not an ideal solution.

The only case where Emscripten `sources` ends up being valid URL is when a filename is specified as explicitly relative (cases 1 and 3).

Then, Emscripten outputs a relative URL as well, which can be handled well by DevTools both in case of loading from filesystem as well as a static HTTP server.

More so, even though case 3 outputs a relative filename, it's not ideal.

## Suggested solution

Emscripten should always compute relative URL out of the source map filename and the actual sources, and emit that in `sources` array.

### PR DESCRIPTION
**Pull request by sbc100**
Reverts emscripten-core/emscripten#9882

This broke the windows build:
https://chromium-review.googlesource.com/c/emscripten-releases/+/1940591
https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket.appspot.com/8895598112699504816/+/steps/Emscripten_testsuite__upstream__other_/0/stdout

### CODE REVIEW

**Comment by kripken** [comment]
Another option than reverting it is this possible fix https://github.com/emscripten-core/emscripten/compare/map2?expand=1 which I am waiting on tests for.

Based on the logs and reading the code, I think that should work, however I don't have a windows machine to test on. If you want to play it safe then I guess we can just revert.

**Comment by sbc100** [comment]
If you can verify the fix then I think we should land the fix yes.  I we can't verify the fix on the windows machine i worry that we will up committing bunch of speculative fixes that might or might not pass on windows.

The cost of reverting and re-landing in pretty low so I'm tempted to revert.  I also think its a good habit to get into too.

**Comment by sbc100** [comment]
That fix still looks odd to me:  `r'(?im)in main (|[/a-z\.\\]:).*test_lsan_leaks\.c:10:16$',`

The second pair of brackets is supposed to match either a driver letter plus a colon *or* the start of a path (either abs or rel).  

It seems to me like it should be more like `(\.|\/|[a-z]:)`  to represents the three different ways to start a path?

**Comment by sbc100** [comment]
Maybe simpler just to do `.*test_lsan_leaks.....`?

**Comment by kripken** [comment]
Yeah, the square brackets could be adjusted and the regex cleaned up I guess. But meanwhile I realized the regex doesn't need to be changed at all - this should be just a 1-line fix.

I'd suggest landing that, but again, if you prefer to revert the original and delay everything til next week, I'm fine with that too.

I'm not sure what you're suggesting in the last comment?

**Comment by sbc100** [comment]
Happy to land you one line fix.

We should definitely cleanup the regex though.  Right now its seem to be looking for driver letter a-z but also `.` and `/` as driver letters, which makes no sense.

**Pull request closed without merging**
