### PR TITLE
Enable sound and see how circleci responds

### PR DESCRIPTION
**Pull request by Oipo**
#9913 showed that a couple of tests are skipped because of a lack of sound on circleci. This PR aims to enable it.

### CODE REVIEW

**Comment by Oipo** [comment]
Well, I 'd like to fiddle more with it, but I'd be really helped with the "retry with ssh access" option.

**Comment by kripken** [comment]
I think the quickest way to try stuff with ssh is to open a PR on your own fork of emscripten. It should automatically use the `.circleci/` stuff, although you may need to go to `circleci.com` and authorize it, and need to enable the hooks on your github fork's settings page at `settings/hooks`. But that should be just a few clicks (and it's free for open source projects, so it should immediately work).

With that said, though, I'm not sure of the benefit of enabling audio testing on bots not intended for it. Perhaps another approach is to still build tests with that decorator, but not run them? We do a related thing for unresponsive tests, after 10 such tests we still build them, but don't run them. I think we have an `if` in `run_browser` which is where we run the browser portion - so maybe just adding an `if` there for whether the test needs audio, but we lack audio support.

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

Re-opening and re-targeting to master.

**Comment by Oipo** [comment]
It happens. It's a good ping though, I had put this on the back-burner for a while and kind of forgot about it.

The main goal I had was to run the tests, as the problems I ran into with #9913 only triggered run-time. So I'm kind of thinking that if running audio tests on the bots is not desired, perhaps this pull request should be closed. Perhaps a reminder for people making pull requests to run some tests manually on their system would be enough?

**Pull request closed without merging**
