### PR TITLE
bugfix for '--preload-file' under node.js

### PR DESCRIPTION
**Pull request by fs-eire**
This change is a bugfix for `--preload-file` in node.js introduced in #11785.

- fixes preload file in worker_threads. 
   `typeof location !== 'undefined'` is true for both web worker and worker_threads. This is because in implementation for worker_threads, `global.location` is polyfilled. however, in worker_threads, `global.location` does not have a property `pathname`. This causes `location.pathname.toString()` to fail the worker.

- remove global variable `fs`.

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by fs-eire** [comment]
@sbc100 thanks for the approval! looks like v2.0.24 tag is not finalized. does this fix catch up with v2.0.24 or not?

**Comment by sbc100** [comment]
> @sbc100 thanks for the approval! looks like v2.0.24 tag is not finalized. does this fix catch up with v2.0.24 or not?

Indeed v2.0.24 has not yet been released.    This change will be part of the v2.0.24 release.

**Comment by sbc100** [comment]
It looks like circleci is not trigger for this PR.   Can you try logging into circleci?  Sometimes that seems to help.

**Comment by fs-eire** [comment]
> It looks like circleci is not trigger for this PR. Can you try logging into circleci? Sometimes that seems to help.

First-time contributors need a maintainer to approve running workflows. Looks like need a manual triggering from admin

**Comment by sbc100** [comment]
Approved github CI.   That does't seem to have fixed the circleci issue ...

**Comment by fs-eire** [comment]
I set up circle ci for my fork but looks like it still not trigger for this PR. any suggestions?

**Comment by sbc100** [comment]
Can you try rebasing or merging and pushing again?

**Comment by fs-eire** [comment]
> Can you try rebasing or merging and pushing again?

I cannot run the CI for mac because the free plan does not include macOS. It looks like the CI runs under my CircleCI account. There must be something wrong in the process or settings for the CI pipeline.

**Comment by sbc100** [comment]
No probs, this seems like a risk free change.  I will land now.

**Pull request merged**
