### PR TITLE
Disable emar hashing with wasm backend

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
> Oh, why doesn't it have the same issue? lld is smart enough?

Yes, it can read archive files.   fastcomp has to extract them, which mean object can cobber each other if they have the same name.

**Comment by erikmchut** [comment]
I'm in the process of upgrading a corporate emscripten toolchain from 1.38.42 -> 2.0.7, and I'm finding that I'm unable to link some executables, and I've tracked down the issue to this change.

1) We have an external software library that has duplicate filenames in the same static library (despite different symbols in each files).
2) We use the WASM backend for compilation (both before and after this upgrade), but we compile with link-time optimization. Using LTO causes emscripten to fall back to linking with the python code – even in 2.0.7. See this link here: https://github.com/emscripten-core/emscripten/blob/master/tools/building.py#L457

As a result, the library in question contains duplicate files, and we no longer have the nice hashing behavior that prevented collision. At link time the build fails, after [warning about duplicate symbols](https://github.com/emscripten-core/emscripten/blob/master/tools/building.py#L69) and then ultimately missing the symbols in the final executable.

**Comment by sbc100** [comment]
Do you need to be using the "link_to_object" method that you link to? 

Ideally you would like each library as an `ar` archive.. and then only for the final link would you link to an executable.   Linking to and object file (also know as `ld -r`) is kind of obscure and not normally required.   I'm hoping that if you avoid this you can fix you problem?  

Another way of putting it, can you puslish/share/link your library as traditional `ar` archives rather than pre-linking them into `.bc` or `.o` mega-objects?

**Comment by erikmchut** [comment]
I'll investigate this morning how we could skip the pre-linking stage – I can think of way to do so, but I'd be curious to hear your thoughts on this.

We currently combine all of the llvm bitcode into a single `.bc` file, before we transform to any of the WASM output types and flavors (wasm-for-nodejs, wasm-for-browser-js, wasm-with-different-opengl-versions, wasm-with-source-maps, wasm-with-separate-js-and-wasm-files, etc.). Part of the reason is that a single executable file output is a one-to-one semantic match with a typical C/C++ executable and matches what clang/gcc tools that output one file as an end product. Almost all of the non-standard compilation flags that emscripten uses happen in this step, and thus transforming from `.bc` -> `.js+.wasm` is almost analogous from translating native code to web code.

**Comment by sbc100** [comment]
Are you sure you file that ends in `.bc` is actually bitcode and not a giant wasm object file?  emcc will produce object files by default these days not bitcode files (unless you are using `-flto` everywhere?).

My advise would to avoid the pre-linking stage completely and just run the linker N times.   

I think you are correct that our bitcode pre-linking logic does have this bug now since it can't handle those archive with duplicate basenames.   However, rather than double down on this pre-linking I'm inclined to try to error out in this case.  "Pre-linking + lto + archives" with duplicate  based names is not supported. 

Do you need LTO?  Are you seeing benefits from using it?   We haven't seen it be a win in all cases and it slows down builds a fair bit.

**Comment by erikmchut** [comment]
yes, the `.bc` is actually bitcode. In 2.0.7 you need to link with `-r` to recreate the behavior that was standard in older versions of emscripten.

The only solution I currently see to avoid pre-linking is going to be hacky and a bit brittle (*DM if interested in the details). In our specific case the reason is that Bazel cc_binary rules don't export their linking sources in providers to dependent rules. If you don't know what this means, don't worry. From a mental model, emcc is linking and then doing a whole bunch more work to produce `.js`, `.wasm`, and `*.map` outputs. Allowing the llvm linking output to be produced as intermediary step will make integrations much easier with common build toolchains.

Regarding LTO – we take every possible performance win that we can have for our system which does real-time computer vision and video processing. When we first started using it along with a previous toolchain upgrade we saw a modest win, perhaps 3-5% less time per frame. I haven't tried a recent benchmark, but if it is providing no real value we would stop using it.

**Comment by sbc100** [comment]
Can you delay the linking until actual link time and use `ar` archives as linker input rather than the giant bc file?

Are you using the bazel rules from https://github.com/emscripten-core/emsdk/tree/master/bazel?  If so @walkingeyerobot might know more about what you are talking about.

**Comment by sbc100** [comment]
BTW one reason I'd like to remove the bitcode linking features, aside from this issue, is that its really not something that any other toolchain supports.   llvm has a tool called llvm-link but its really not a linker in the traditional sense.. it can't understand archives for example.     So with a normal toolchain like clang or gcc this is simply not possible.  

What about removing `-flto` from your `emcc -r` command so that linking actually happens then, would that work for you?  Then instead of a giant `.bc` you would have a giant `.o` file.  I think you would get all the LTO benefits, plus it might speed up the build as the compilation from `.bc` native would only occur once.

**Comment by erikmchut** [comment]
I'm planning to implement your original suggested solution, which is skipping the `.bc` step. For our specific toolchain, I'm proven to myself that I can hack around a few features to get the dependencies of a cc_binary rule and then separate the link inputs from the tool inputs using some heuristics. It isn't going to win any awards, but it is a workaround that should enable us to upgrade emscripten.

**Comment by erikmchut** [comment]
@sbc100 - I did some current benchmarking to better understand the benefit of LTO in our stack. I found that non-LTO code with wasm object files runs about 15% slower than LTO code.

**Comment by sbc100** [comment]
OK so you do need/use/want LTO.

Sounds like finding a way to drop the `emcc -r` step completely, or at least removing the `-flto` from this one command would solve your problem.

**Comment by erikmchut** [comment]
Thanks. While working on this, I found an unexpected issue when using wasm object files instead of bitcode. I'll file a separate issue.

**Pull request merged**
