### PR TITLE
Avoid garbage-free WebGL APIs when memory size is over 2gb.

### PR DESCRIPTION
**Pull request by sbc100**
Both chrome and firefox see have some issues with passing 2gb+ and 4gb+ offsets to these APIs.

Once the browser issues are addressed we can lift these restrictions over time.

Fixes: #20533

### CODE REVIEW

**Review by kripken — APPROVED** [review]

**Comment by juj** [comment]
I am surprised to read about [this bug](https://issues.chromium.org/issues/324992397) existing in Chrome because I authored conformance tests into WebGL Conformance Test Suite earlier [here](https://github.com/KhronosGroup/WebGL/pull/3592) and I recall the issue would have gotten fixed since then. I wonder if this new Chromium bug indicates that the conformance tests I contributed are somehow spotty?

The [Firefox issue is noted](https://bugzilla.mozilla.org/show_bug.cgi?id=1838218).

There is [also a Safari bug](https://bugs.webkit.org/show_bug.cgi?id=250558) and a fix that shipped in [iOS 16.4, macOS 12.3, Safari 16.4](https://github.com/WebKit/WebKit/pull/9451).

I was hoping that we would not need to bother restore this type of "don't use garbage free APIs" fallback for maybe the third(?) time in Emscripten's history now, and just have browsers have to figure it out.

But it's all ok to do this, and if we do, I think a good way would be to latch the changes against `MIN_FIREFOX/CHROME/SAFARI_VERSION` so that the code changes will then automatically go away if user is building with targeting new enough browser versions. (While the bugs are active, new enough might mean that BROWSER_NOT_SUPPORTED=0x7FFFFFFF flag, and when the fixes come in, then update to the correct versions). That way we wouldn't need to have a new -sSETTING, and the code would be seamlessly self-obsoleting?

Also, ideally, no code size regressions if possible for the users who are building against new enough MIN_x_VERSION that don't need these workarounds 🙏. I wonder if the check could be folded into `{{{ isCurrentContextWebGL2() }}}` at least in some of those places, to turn it into a `{{{ isCurrentContextNotBuggyWebGL2() }}}` or a separate `{{{ isCurrentContextNotBuggyWebGL2() }}}` check that would return implicit `if (true)`.. maybe Closure would then be able to optimize any code size regressions away?)

**Comment by sbc100** [comment]
I factored out a few unrelated parts of this change to make it simple: #21457

I updated the code that determines WEBGL_USE_GARBAGE_FREE_APIS to limit it to when either chrome of firefox is enabled.

My hope is that over time we can reduce and remove these limitations.

**Comment by sbc100** [comment]
This change is now a minor code size win for the webgl code size tests

**Comment by sbc100** [comment]
OK, I factored out the code size improvement and landed that separately.  This change is now code size neutral, at least for our webgl codesize tests.

**Pull request merged**
