### PR TITLE
Fix WASM Worker exception issue in Node.js environment

### PR DESCRIPTION
**Pull request by medns**
The `Atomics.waitAsync()` polyfill does not
take into account that the `navigator` object
does not exist in the Node.js context.

### CODE REVIEW

**Comment by sbc100** [comment]
We do run some wasm worker tests under nodejs today right?   I wonder why they don't fail without this change?  e.g. `core2.test_wasm_worker_hello` and `core0.test_wasm_worker_malloc`?

After this change, are there more tests we can run under node?

**Comment by sbc100** [comment]
I guess the existing tests don't use `emscripten_atomic_wait_async`?

**Comment by medns** [comment]
> I guess the existing tests don't use `emscripten_atomic_wait_async`?

Yes, you are right. 
The  existing tests `test_wasm_worker_hello` and `test_wasm_worker_malloc` do not use the `emscripten_atomic_wait_async` method.
I added a new test `test_wasm_worker_wait_async` to cover this scenario.

**Review by sbc100 — APPROVED** [review]

**Comment by medns** [comment]
I also found a bug in `asyncWaitFinished` sig and fixed it

**Comment by medns** [comment]
After my check, I found 3 failed checks, which don't seem to be related to this PR:
* test-other(other.test_pthread_trap): This case is caused by [test_other.py#L12503](https://github.com/emscripten-core/emscripten/blob/25c104ecbef5c81039f258bfe3e2ead4161d4a25/test/test_other.py#L12503), the actual output should be `at thread_main` instead of `at (test_pthread_trap.wasm.?)thread_main`.
* test-browser-chrome and test-browser-firefox: These two case appear to be caused by environmental anomalies.

@sbc100

**Review by sbc100 — APPROVED** [review]

**Comment by medns** [comment]
Sorry, I rebase the main branch, but the main branch still has issues with Chromium related checks (`test-browser-chrome` and `test-sockets-chrome`).
I think the CI step might need to run `service dbus start` ?

@sbc100

**Comment by sbc100** [comment]
CI issues are unrelated.   Sorry for the friction.

**Pull request merged**
