### PR TITLE
GL emulation: fix glActiveTexture losing track of texture matrix

### PR DESCRIPTION
**Pull request by parasti**
This is a reworked version of PR #10855. I closed that one because I realized that the problem is really with glActiveTexture and not glClientActiveTexture. Also added a test that demonstrates the problem and is fixed by this patch.

### CODE REVIEW

**Comment by parasti** [comment]
Why, though? This is not the only test using SDL2. Is there a problem with SDL2 in Emscripten?

**Comment by parasti** [comment]
Wrong button.

**Comment by kripken** [comment]
It's not a problem with SDL2, just that SDL2 is compiled from C code (and it's a large C codebase) while the others are small JS libraries (like `src/library_glew.js`).

We do have lots of SDL2 tests because it is important to test. But for a new test that isn't specific to SDL2, like here where it's just for GL emulation, it would be better to use something else. However, it's not a big deal, so if it's simpler this way that's fine too.

**Comment by parasti** [comment]
I understand. It's just that I have limited time to spend on these and SDL2 is readily available to me. I'm on Windows so there are some extra steps to get things working for native builds. If you wish, feel free to rewrite.

**Comment by kripken** [comment]
@parasti Sure, we can look into rewriting later perhaps.

For landing your PRs, I think just please split up #10849 as suggested there, then we can land those, and then this one last?

**Comment by kripken** [comment]
I think this is ready to merge, however, CI doesn't seem to have run on the second commit. Not sure why - maybe related to the closing/reopening? Anyhow, merging in latest upstream master should fix it.

**Comment by parasti** [comment]
> 
> 
> I think this is ready to merge, however, CI doesn't seem to have run on the second commit. Not sure why - maybe related to the closing/reopening? Anyhow, merging in latest upstream master should fix it.

CI runs on the last commit, but for some reason Github here shows the commits in reverse order (ordered by date, not by ancestry, perhaps?). I pushed again, but doesn't look like this changed anything.

**Comment by kripken** [comment]
Heh, I think you're right, it does sort by date and not ancestry...

Can you merge latest master to here? It's fine if there's a merge commit, we squash PRs anyhow. That should definitely force a clear test run.

**Comment by kripken** [comment]
I did a merge conflict resolution now here, so that should get CI to run actually...

**Pull request merged**
