### PR TITLE
Disable test_fs_readdir_ino_matches_stat_ino on Windows

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by dschuff** [comment]
On windows, the failing line is
```
readdir a_ino: 780273, b_ino: 780272
stat    a_ino: 7318349395257329, b_ino: 11821949022627824
Aborted(Assertion failed: a_ino == sta.st_ino, at: C:\b\s\w\ir\x\w\install\emscripten\test\fs\test_fs_readdir_ino_matches_stat_ino.c,58,main)
```

**Comment by sbc100** [comment]
I guess inodes are likely to be different on windows.  Strange that stat and readdir would differ though.

**Review by sbc100 — APPROVED** [review]

**Comment by sbc100** [comment]
Feel free to land this once the `test-windows` bot passes.  No need to wait for the rest.

**Comment by dschuff** [comment]
> I guess inodes are likely to be different on windows. Strange that stat and readdir would differ though.

yeah it is; I don't know why that would be.

**Pull request merged**
