### PR TITLE
Fix missing SDL_strtokr.c

### PR DESCRIPTION
**Pull request by ericoporto**
Fix https://github.com/emscripten-ports/SDL2/issues/159

I don't know why the CI doesn't run for my PRs.

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Looks like `stdlib/SDL_crc32.c` is also missing. I'll go check if I missed anything else... (made the mistake of assuming CI would catch everything)

**Comment by ericoporto** [comment]
@Daft-Freak  feel free to open a new PR with all of these, there's something that makes my PRs not trigger the CI, so I think you will be able to merge it sooner.

**Comment by kripken** [comment]
I filed a ticket now with circleci so I hope that CI will be fixed soon.

**Comment by ericoporto** [comment]
I rebased to a single commit, but the CI seems to still be broken. :/

**Comment by kripken** [comment]
I still haven't heard back from circleci. Sorry about that. Let's give it another day - if they still do not respond I will both escalate with them + open a manual PR here myself with your changes to get test coverage.

**Comment by ericoporto** [comment]
@kripken don't worry, have a good afternoon. Things always workout eventually. :)

**Comment by kripken** [comment]
Still no word so I pulled to a branch to force tests. Looks like there is a failure on linting, there is some whitespace added here, a space at the end of a line,

```
./tools/ports/sdl2.py:60:101: W291 trailing whitespace
```
https://app.circleci.com/pipelines/github/emscripten-core/emscripten/18276/workflows/ad31ba1b-d758-404a-9a89-1438d06e2b8c/jobs/493087

Aside from that tests are still running but looks good so far.

**Comment by ericoporto** [comment]
I push forced and removed the trailing whitespace!

**Comment by kripken** [comment]
Tests finished, the only issue is the lint problem.

**Review by kripken — APPROVED** [review]

**Pull request merged**
