### PR TITLE
GL_UNSIGNED_SHORT_5_6_5_REV in webgl2

### PR DESCRIPTION
**Pull request by ddovod**
Adressing #9892

### CODE REVIEW

**Comment by ddovod** [comment]
Also there're other mentions of `GL_UNSIGNED_SHORT_5_6_5` in the library_webgl.js and webgl1.c, I'm not sure if I have to add `GL_UNSIGNED_SHORT_5_6_5_REV` there

**Comment by kripken** [comment]
Thanks @ddovod! Perhaps @juj or @kainino0x can answer that question.

Please also add yourself to `AUTHORS`.

**Comment by juj** [comment]
This does not look correct to me. WebGL 2 does not support `GL_UNSIGNED_SHORT_5_6_5_REV` type. If I run the following code

```c++
#include <GLES3/gl3.h>
#include <GLES2/gl2ext.h>

#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <emscripten.h>
#include <emscripten/html5.h>

// WebGL 2 core does not support GL_UNSIGNED_SHORT_5_6_5_REV extension.
#define GL_UNSIGNED_SHORT_5_6_5_REV 0x8364

int main()
{
  EmscriptenWebGLContextAttributes attrs;
  emscripten_webgl_init_context_attributes(&attrs);
  attrs.majorVersion = 2;
  attrs.minorVersion = 0;
  attrs.enableExtensionsByDefault = 0; // Make sure we don't accidentally enable an extension that would bring GL_UNSIGNED_SHORT_5_6_5_REV support.

  EMSCRIPTEN_WEBGL_CONTEXT_HANDLE context = emscripten_webgl_create_context("#canvas", &attrs);
  assert(context);
  EMSCRIPTEN_RESULT res = emscripten_webgl_make_context_current(context);
  assert(res == EMSCRIPTEN_RESULT_SUCCESS);
  GLuint tex;
  glGenTextures(1, &tex);
  glBindTexture(GL_TEXTURE_2D, tex);
  glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, 16, 16, 0, GL_RGB, GL_UNSIGNED_SHORT_5_6_5_REV, 0);
  assert(glGetError() != 0); // We should be getting an error
  printf("done!\n");
}
```

that does properly report a WebGL error
```
a.js:2556 WebGL: INVALID_ENUM: texImage2D: invalid type
```
in console, and no exception is thrown (like https://github.com/emscripten-core/emscripten/issues/9892#issue-527717737 suggested).

I wonder if the test case to show an error needs to be like something else?

In any case, we should not add `GL_UNSIGNED_SHORT_5_6_5_REV` like shown in this PR, since that does not exist in WebGL 2. Though if there is some new extension to WebGL that adds that support(?), then that is a different case.

**Comment by juj** [comment]
Posted a PR https://github.com/emscripten-core/emscripten/pull/9918 to showcase a way unknown GL color types could be handled if they are observed to throw an exception in some cases.

**Comment by ddovod** [comment]
Hello @juj . Thank you very much for explanations. However I get js exception in case if `GL_UNSIGNED_SHORT_5_6_5_REV` is not handled in `__heapObjectForWebGLType`. I use `Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)` under Ubuntu 18.04 with `emcc (Emscripten gcc/clang-like replacement) 1.39.3 (commit a5082b232617c762cb65832429f896c838df2483)`. I'm not sure I can create a minimal example since the exception comes from gl calls from the bgfx library, but if you need more info, please let me know, I'll provide you with any info I can.

**Comment by juj** [comment]
>  However I get js exception in case if `GL_UNSIGNED_SHORT_5_6_5_REV` is not handled in `__heapObjectForWebGLType`.

Can you post full error log and callstack?

>  I'm not sure I can create a minimal example

The above posted test code should be a minimal example? If you run that on your setup, does it throw an exception?

**Comment by ddovod** [comment]
Sure.
I'm using modified code since the error code path assumes non-null data:
```cpp
  void* data = new char[512];
  glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, 16, 16, 0, GL_RGB, GL_UNSIGNED_SHORT_5_6_5_REV, data);
```
Compiling it like this works fine
```
ddovod@/webgl_test: em++ main.cpp -omain.html --emrun 
ddovod@/webgl_test: emrun main.html 
Starting browser: /usr/bin/xdg-open http://localhost:6931/main.html
Opening in existing browser session.
done!
```
But if I pass `-s USE_WEBGL2=1` I get the error
```
ddovod@/webgl_test: em++ -s USE_WEBGL2=1  main.cpp -omain.html --emrun 
ddovod@/webgl_test: emrun main.html 
Starting browser: /usr/bin/xdg-open http://localhost:6931/main.html
Opening in existing browser session.
exception thrown: TypeError: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': parameter 9 is not of type 'ArrayBufferView'.,TypeError: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': parameter 9 is not of type 'ArrayBufferView'.
    at _glTexImage2D (http://localhost:6931/main.js:2504:17)
    at wasm-function[16]:0x513
    at wasm-function[17]:0x56d
    at Module._main (http://localhost:6931/main.js:2799:32)
    at callMain (http://localhost:6931/main.js:3016:15)
    at doRun (http://localhost:6931/main.js:3075:23)
    at http://localhost:6931/main.js:3086:7
```
Is it okay? Should I just omit `-s USE_WEBGL2=1` on my project?
Thank you very much!

**Comment by juj** [comment]
> I'm using modified code since the error code path assumes non-null data:

Doh of course! My initial test was wrong, naturally the test must submit pixel data to even run that path. Now I was able to repro the exception as well.

Updated the test in PR #9918 to test the scenario. We should close this, #9918 will fix up the issue.

**Comment by juj** [comment]
>  Should I just omit `-s USE_WEBGL2=1` on my project?

No, running with WebGL2 enabled is fine. After #9918 all should go smooth.

**Comment by ddovod** [comment]
Awesome, thanks!

**Pull request closed without merging**
