### PR TITLE
Update Emscripten.cmake to support C++20

### PR DESCRIPTION
**Pull request by nowakowsk**
Same as #8030, but for C++20.

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by kripken** [comment]
Looks like a test needs to be updated, `other.test_cmake_compile_features`. Let us know if you need any help.

**Comment by nowakowsk** [comment]
I am afraid I won't be able to configure the test environment for Emscripten in the near future. If you prefer I can create a new issue with a reference to this PR.

**Comment by sbc100** [comment]
I can push the test update to this PR..

**Comment by sbc100** [comment]
Closing in favor of https://github.com/emscripten-core/emscripten/pull/13616

**Pull request closed without merging**
