### PR TITLE
[CMAKE] Create prejs_tracker in current binary directory 

### PR DESCRIPTION
**Pull request by ravisumit33**
Currently prejs tracker source file is created in global binary directory. If we are building out-of-tree , there can be multiple CMakeLists.txt having different binary directories using functions like `em_link_pre_js` for same prejs file. Current implementation will give error as shown below when using Ninja generator in cmake.
```
 ninja: error: build.ninja:13015: multiple rules generate prejs_js_tracker.c

```

### CODE REVIEW

**Comment by ravisumit33** [comment]
@sbc100 Please have a look.

**Comment by ravisumit33** [comment]
@sbc100 This change is mainly helpful when we are building different variants of wasm out-of-tree. I don't see any of the current tests doing that. If you want, I can add new test.

**Comment by ravisumit33** [comment]
Also, failing tests seem unrelated. Network fluctuation ?

**Comment by ravisumit33** [comment]
@sbc100 @kripken Please let me know if I need to add above linked test so that we can merge this.

**Comment by sbc100** [comment]
Would it be enough to simply call `em_link_pre_js` twice in the same file?  Does you solution work for files that call `em_link_pre_js` more than once?

**Comment by sbc100** [comment]
I was able to replicate the problem simply by calling em_link_pre_js twice in row.  I found a fix that should for for both cases: #19069

**Comment by ravisumit33** [comment]
Your fix doesn't solve the case of generating multiple `prejs_tracker.c` for out-of-tree builds. You can check by building the test which I linked in the comment above i.e. https://github.com/ravisumit33/wasm-variants

**Comment by ravisumit33** [comment]
Issue is happening because we are creating dummy tracker file in the global binary directory even if it is called from some different binary directory. So current implementation will generate same tracker file for different builds thus causing multiple rules to build same file.

**Comment by sbc100** [comment]
> Tracer file issue is happening because we are creating dummy tracker file in the global binary directory even if it is called from some different binary directory. So current implementation will generate same tracker file for different builds thus causing multiple rules to build same file.

But shouldn't the global counter prevent the duplicate filename from being created?  isn't the point the counter to make each filename globally unique?

**Comment by ravisumit33** [comment]
Counter is not used in creating tracker file. https://github.com/emscripten-core/emscripten/blob/main/cmake/Modules/Platform/Emscripten.cmake#L332

**Comment by sbc100** [comment]
I think I found a solution avoids the whole dummy C file and dummy library and just uses direct dependencies: https://github.com/emscripten-core/emscripten/pull/19071

**Comment by ravisumit33** [comment]
Thanks that solves this issue. Hence, closing.

**Pull request closed without merging**
