### PR TITLE
Refactor test_f_exception test. NFC

### PR DESCRIPTION
**Pull request by sbc100**
Also fix inverted naming in test_lto_libcxx test.

### CODE REVIEW

**Comment by sbc100** [comment]
remove_exception_catching

**Comment by aheejin** [comment]
> remove_exception_catching

Sorry, what does this mean?

**Comment by sbc100** [comment]
Sorry, please ignore.    This change already landed as part of #13862

**Comment by sbc100** [comment]
(I pasted that branch name in the comment box by accident).

**Pull request closed without merging**
