### PR TITLE
Use `__stdio_exit` rather then `fflush(0)` on exit

### PR DESCRIPTION
**Pull request by sbc100**
This is how musl internally closes down stdio after main returns
(and its how we do it in standalone mode).

Seems to be a smaller code size too!

### CODE REVIEW

**Comment by kleisauke** [comment]
Great! I remembered that I had a issue with the unflushed content warning not being displayed when I did this (see e.g. commit https://github.com/emscripten-core/emscripten/pull/13007/commits/52e35f3731ceaa758da1fdd925eb02fbcd23d61e), but that doesn't seem to be a issue anymore.

**Review by kripken — APPROVED** [review]

**Comment by sbc100** [comment]
> Great! I remembered that I had a issue with the unflushed content warning not being displayed when I did this (see e.g. commit [52e35f3](https://github.com/emscripten-core/emscripten/commit/52e35f3731ceaa758da1fdd925eb02fbcd23d61e)), but that doesn't seem to be a issue anymore.

Was there a test that caught that?

**Comment by sbc100** [comment]
> Great! I remembered that I had a issue with the unflushed content warning not being displayed when I did this (see e.g. commit [52e35f3](https://github.com/emscripten-core/emscripten/commit/52e35f3731ceaa758da1fdd925eb02fbcd23d61e)), but that doesn't seem to be a issue anymore.

Sorry to duplicate work you have already done!  At least we are thinking alike!

**Comment by kleisauke** [comment]
> Was there a test that caught that?

I think it was `other.test_no_exit_runtime_warnings_flush`, but it was probably my fault. The above mentioned commit didn't use `__stdio_exit` on all places (and didn't include that function in `ASSERTIONS` builds), while this PR does. 

> Sorry to duplicate work you have already done! At least we are thinking alike!

No problem!

**Comment by kleisauke** [comment]
I also noticed that we can probably remove this TODO after this PR:
https://github.com/emscripten-core/emscripten/blob/0c07c15d0ab439b9f3b5dbfc96aaf0e8d7e19df5/tests/test_other.py#L3604

For example applying this patch:
```diff
diff --git a/emcc.py b/emcc.py
index 2505c0385..6914d6ac8 100755
--- a/emcc.py
+++ b/emcc.py
@@ -1984,7 +1984,7 @@ def phase_linker_setup(options, state, newargs, settings_map):
         '$handleException'
       ]
 
-    if settings.FILESYSTEM and not settings.STANDALONE_WASM:
+    if not settings.STANDALONE_WASM:
       # We use __stdio_exit to shut down musl's stdio subsystems and flush
       # streams on exit.
       # We only include it if the runtime is exitable, or when ASSERTIONS
diff --git a/tests/test_other.py b/tests/test_other.py
index 739bc0b7c..654513077 100644
--- a/tests/test_other.py
+++ b/tests/test_other.py
@@ -3603,7 +3603,7 @@ int main() {
           for flush in [0, 1]:
             # TODO: also check FILESYSTEM=0 here. it never worked though, buffered output was not emitted at shutdown
             print(src, no_exit, assertions, flush)
-            cmd = [compiler, src, '-sEXIT_RUNTIME=%d' % (1 - no_exit), '-sASSERTIONS=%d' % assertions]
+            cmd = [compiler, src, '-sEXIT_RUNTIME=%d' % (1 - no_exit), '-sASSERTIONS=%d' % assertions, '-sFILESYSTEM=0']
             if flush:
               cmd += ['-DFLUSH']
             self.run_process(cmd)
```

makes the `other.test_no_exit_runtime_warnings_flush` test still pass.

**Comment by sbc100** [comment]
Thanks, I've got a followup PR for that change.

**Pull request merged**
