### PR TITLE
Remove enormous try/finally in emcc.py.  NFC.

### PR DESCRIPTION
**Pull request by sbc100**
This is a prerequisite for #12640

View this PR with "ignore-whitespace" or you will have a bad time.

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
I seem to recall an issue with this atexit not always running. Does python guarantee it will happen? And, is the guarantee even if an exception happens?

**Comment by sbc100** [comment]
I mean its never guaranteed, since the process could be killed without mercy in either case.

I don't think its any more or less likely to run that a normal exception block...

**Comment by sbc100** [comment]
If you prefer I can instead move the try/finally to the new main function which calls run.   I don't think it matter a huge deal is this only effect users who set EMCC_DEBUG anyway.

**Comment by sbc100** [comment]
I reverted back to try/finally

**Comment by sbc100** [comment]
That didn't work because we call reconfigure_cache during main.  Reverting back to my first attempt here using atexit which I think its totally fine.

**Review by kripken — APPROVED** [review]
My concern here isn't hypothetical - I'm pretty sure we used to use atexit for this, or something very similar, and had to stop because of problems. They may have been python bugs. I did some searching in the git log but can't seem to find it though.

I'd be ok with this if you do some stress testing locally to investigate possible issues. But maybe I'm overly worried as this is just for EMCC_DEBUG, so it wouldn't be an issue in the normal case.

**Comment by sbc100** [comment]
I'd like to go ahead with this as is because:

1. It only effect EMCC_DEBUG use cases
2. If it fails it will be blatantly obvious because emcc will fail to start with "acquiring lock" because some previous process failed to unlock.   We cna be on the look at for that as the primary users of EMCC_DEBUG.
3. This mechanism for serializing access the canonical temp directory by locking the cache probably need to be revisited anyway since it doesn't make much sense.. it should rally be locking the canonical temp directory itself.

**Pull request merged**
