### PR TITLE
Restore other.test_minimal_runtime_code_size and update sizes

### PR DESCRIPTION
**Pull request by kripken**
Some values slightly regressed due to an LLVM change somewhere in

ab96ec41ead8..621388468b51

which we have not investigated. It might be interesting to find out more,
but it could be just noise.

### CODE REVIEW

**Comment by kripken** [comment]
Landing quickly to avoid losing test coverage meanwhile.

**Comment by aheejin** [comment]
Sorry for the delay, and thanks!

**Comment by sbc100** [comment]
Actually it looks like some of the are improvements, no?

**Comment by kripken** [comment]
Yeah, some looks better. I suspect the improvements might have existed before the llvm change, and are just within the range of slack, but I didn't verify.

**Pull request merged**
