### PR TITLE
Fix workers vs pthreads

### LINKED ISSUE #9307: PThread.runningWorkers contents incorrect once a worker is returned to pool
src/library_pthread.js:

in **_spawn_thread()**:
PThread.runningWorkers.push(worker);
here a **worker** object is pushed to the array.

in **returnWorkerToPool()**:
PThread.runningWorkers.splice(PThread.runningWorkers.indexOf(worker.pthread), 1);
here we're looking for a **pthread** instead of worker in the array

in **_kill_thread()**:
PThread.runningWorkers.splice(PThread.runningWorkers.indexOf(pthread.worker.pthread), 1);
same problem

### PR DESCRIPTION
**Pull request by juj**
Fixes #9307 and adds a test.

### CODE REVIEW

**Comment by kripken** [comment]
That build error doesn't look familiar. Perhaps merging incoming to here would fix that?

**Comment by juj** [comment]
Rebased, and removed the for-in iteration. I think the CI is timing out, testing locally, the failing tests pass for me.

**Comment by kripken** [comment]
The errors look like what was temporary breakage on firefox beta. Other PRs are now passing there so it seems to be fixed. I restarted that one job, should pass now too.

**Comment by kripken** [comment]
Everything looks good, merging.

**Pull request merged**
