### PR TITLE
add MODULARIZE=2

### LINKED ISSUE #5820: Undocumented Module.then causes infinite loop
https://github.com/kripken/emscripten/blob/93479ecbd390aec4f8a3765fe04bcb365d0b31b2/src/postamble.js#L118-L141

postamble.js adds `Module.then` when `-s MODULARIZE=1` but using it causes indefinite loop on `Promise.resolve()` and ES2017 `await` statement. 

By the spec the resolving strategy is greedy: if an object has `then` method then it will be called with two function arguments including resolver and rejector. If the resolver is called with an object with a `then` method it will be called again with two function arguments, and then again, again.

`Module.then` resolves with `Module` which still has `then`, so the `await` statement loops indefinitely.

PS: Fixed some wrong concepts.

### PR DESCRIPTION
**Pull request by kainino0x**
Not done, but started. Tested manually. Please take a first look!

Fixes #5820

### CODE REVIEW

**Comment by curiousdannii** [comment]
This shouldn't be tied to modularisation IMO. Ideally you'd get a `.ready` prop even if you don't use MODULARIZE.

**Comment by curiousdannii** [comment]
Sorry, I didn't pick up on that.

Where was the discussion about deprecating `MODULARIZE=1`???

**Comment by curiousdannii** [comment]
I've got opinions on this. I don't like this.

Deprecating `MODULARIZE=1` came out of nowhere and seems completely unmotivated to me. Likewise I don't see the value of this new proposed mode. It adds not insignificant code complexity and just makes the output more restrictive.

`MODULARIZE` is already a poorly named setting because it makes people thinking of file modules, and I don't think it should be overloaded even more. The classic `MODULARIZE=1` output was really a factory function. We discussed this a little in #7835.

So an idea. What if we deprecated `MODULARIZE` in favour of a new setting named something like `OUTPUT_MODE` with options 'plain', 'factory', 'instance', and if you really want a new mode, 'factory-promise'. Or I guess if there are good reasons for deprecating the old mode, then that's what the new 'factory' mode could refer to.

**Comment by curiousdannii** [comment]
It used to be the case that for certain stateless libraries/functions there was no need to wait. But that's probably a very small use case now. Do all builds with wasm require waiting? I think even `SINGLE_FILE` still builds the wasm asynchronously.

I had liked being able to save the factory output and then call `.then`. But it wouldn't be a big change. So I guess I'm on board with changing to returning `.ready` directly for safety reasons. But maybe we can poll the community to see if there's anyone who really needs access to the output before the promise would resolve. And as I said I'd prefer we deprecate `MODULARIZE` entirely rather than overload it.

**Comment by kripken** [comment]
> Do all builds with wasm require waiting? I think even SINGLE_FILE still builds the wasm asynchronously.

`SINGLE` FILE + disabling `WASM_ASYNC_COMPILATION` should be fully synchronous, but probably very rare.

**Comment by kripken** [comment]
It sounds like there's agreement here on returning `.ready()`?

If so I'd like to see us move forward with this. A discussion on the mailing list might be a good idea, I agree we should have a broader discussion as already mentioned. Does someone here want to start that?

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

Re-opening and re-targeting to master.

**Comment by Lectem** [comment]
Any update on this ?
It would be nice to merge this so that we can remove the `delete module.then` workaround

**Comment by curiousdannii** [comment]
@Lectem That should already not be necessary after #10697 was merged.

**Comment by kainino0x** [comment]
Pretty sure that should supersede this; thought we already closed this for that.

**Pull request closed without merging**
