### PR TITLE
Ports: upgrade sdl2 to 2.24.2

### PR DESCRIPTION
**Pull request by ericoporto**
SDL 2.24.2 is released!

### CODE REVIEW

**Comment by ericoporto** [comment]
Hey, SDL 2.24.2 has been released, this should upgrade the port for it. It fixes an important bug in the emscripten build for SDL 2.24.0 and 2.24.1.

**Comment by sbc100** [comment]
Looks good to me assuming tests pass.

I'm not sure why circleci is having issue with this PR.. it doesn't want to run at all.   Can you perhaps log into circleci?  In theory you should not need an account there, but in practice we have seen that sometimes it helps.

**Comment by kripken** [comment]
Some more possible CircleCI issues documented here: https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-

**Comment by ericoporto** [comment]
>  Can you perhaps log into circleci?

Thanks @sbc100 ! I logged in and after setting up the emscripten project in my fork, I force pushed and then it worked!

**Comment by sbc100** [comment]
@Daft-Freak

**Comment by Daft-Freak** [comment]
Seems reasonable.

(I really need to remember to keep this up-to-date...)

**Comment by ericoporto** [comment]
> Hello
> 
> Thank you for raising a support ticket with CircleCI!
> 
> The reason that this is happening is that you are building under your fork of the project.
> 
> We have taken a look at your account and we can see that you are on the free plan.
> 
> The reason for the failure is that the xlarge resource class is only available for customers on the performance or scale plan as shown on our features page

@kripken hey, is there a procedure to do to make it run in Emscripten account instead of mine?

**Comment by kripken** [comment]
That's very strange, I thought that's exactly what it does all the time? We constantly get people opening PRs and it always runs CI using our account to pay for it. Opening a PR here should do that.

Can you cc me in that discussion, if that's not what they are saying? (azakai at google dot com) Maybe there's more context for what "building under your fork" means in that quote.

**Comment by ericoporto** [comment]
Thanks, sent you the email, you can remove above comment with it if you want. :)

**Comment by kripken** [comment]
Thanks, I got the cc.

If they don't offer a solution in a day or so we can try some more things like merging in latest main to here - it's possible doing that on an existing PR will work.

**Review by kripken — APPROVED** [review]

**Comment by ericoporto** [comment]
Thanks, I was trying to figure out the CircleCI UI at lunch time but decided to try again later. Thank you for the merge!

**Pull request merged**
