### PR TITLE
Fix Asyncify + MAIN_MODULE

### LINKED ISSUE #14785: MAIN_MODULE in combination with ASYNCIFY causes runtime error  before launch
EDIT/UPDATE: Setting -O1 or higher to disable assertions solves this error. It does however result in a `RuntimeError: indirect call signature mismatch` in my significantly larger project (doesn't happen in the one below).  I'll try to get a test case for that as well. (edit 2: I got that testcase here: #14801 )

**Original Issue:**

`main.cpp`
```
#include<stdio.h>
int main() {
	printf("Hello World\n");
	return 0;
}
```

built with command line:
`emcc main.cpp -s MAIN_MODULE=1 -s ASYNCIFY  -o main.html`

causes to throw the following exception at runtime:
```
Assertion failed: Missing signature argument to addFunction: function() {
                var originalAsyncifyState = Asyncify.state;
                try {
                  return original.apply(null, arguments);
                } finally {
                  // Only functions in the list of known relevant imports are allowed to change the state.
                  // Note that invoke_* functions are allowed to change the state if we do not ignore
                  // indirect calls.
                  if (Asyncify.state !== originalAsyncifyState &&
                      ASYNCIFY_IMPORTS.indexOf(x) < 0 &&
                      !x.startsWith('__asyncjs__') &&
                      !(x.startsWith('invoke_') && true)) {
                    throw new Error('import ' + x + ' was not in ASYNCIFY_IMPORTS, but changed the state');
                  }
                }
              }
```

 Stacktrace:

```
printErr http://localhost:8080/main.html:1246
    abort http://localhost:8080/main.js:1512
    assert http://localhost:8080/main.js:676
    addFunctionWasm http://localhost:8080/main.js:535
    reportUndefinedSymbols http://localhost:8080/main.js:2321
    preloadDylibs http://localhost:8080/main.js:2333
    run http://localhost:8080/main.js:51476
    runCaller http://localhost:8080/main.js:51397
    removeRunDependency http://localhost:8080/main.js:1496
    receiveInstance http://localhost:8080/main.js:1657
    receiveInstantiationResult http://localhost:8080/main.js:1672
    (Async: promise callback)
    instantiateArrayBuffer http://localhost:8080/main.js:1680
    instantiateAsync http://localhost:8080/main.js:1708
    (Async: promise callback)
    instantiateAsync http://localhost:8080/main.js:1701
    (Async: promise callback)
    instantiateAsync http://localhost:8080/main.js:1698
    createWasm http://localhost:8080/main.js:1730
    <anonymous> http://localhost:8080/main.js:31220
```

I tested this on 2.0.23, 2.0.26 as well as tip of the tree with the same result.

### PR DESCRIPTION
**Pull request by kripken**
In MAIN_MODULE we need to know signatures to add to the
table. Copy the `.sig` property so that we can do so - otherwise
the asyncify wrapper gets in the way.

As suggested by @sbc100 in https://github.com/emscripten-core/emscripten/issues/14785#issuecomment-901499312

Fixes #14785

### CODE REVIEW

**Comment by sbc100** [comment]
And are you sure that its the asyncify versions of the exports that we want to add to the table?    i.e. should all indirect calls use the asyncify wrappers?

**Review by sbc100 — APPROVED** [review]

**Comment by kripken** [comment]
I'm actually not sure how the dynamic linking code gets ahold of these wrappers, now that you mention it. The export wrappers are what we want in the table (to know when we enter the module - entering via a table call is one way to do so). But this is for the **import** wrappers.

I suspect that when we wrap the imports they end up as imports for a wasm module, which then somehow exports them, and then we end up calling addFunction on that? If so, then it's the right thing, as mentioned above, we do need to wrap all entrances to the wasm, including via the table.

If that's not a plausible explanation then I can read the dynanic loading code to try to figure this out?

**Comment by sbc100** [comment]
Here is the place the dynamic linker users the `.sig` attribute.   Its for the case where we have an request for the address of a function that comes from JS.   i.e. the case where the native code depends on the address of a function that function is implemented in JS.

**Comment by kripken** [comment]
Thanks @sbc100 , makes sense now!

Ok, then this PR looks right. When assertions are enabled we need to instrument the imports for asyncify, and that includes indirect calls to imports. So we do want those in the table.

**Pull request merged**
