### PR TITLE
test: passing userData in Fetch API

### PR DESCRIPTION
**Pull request by TroyTae**
related with https://github.com/emscripten-core/emscripten/pull/11729#issuecomment-672268912

### CODE REVIEW

**Comment by kripken** [comment]
What is the difference between the new test here, and `tests/fetch/to_memory.cpp`, `tests/fetch/to_indexeddb.cpp` which also appear to check that `userData` works properly?

**Comment by TroyTae** [comment]
@kripken 
I intend userData check test in async xhr.
But I wrote sync xhr code 😅 
I updated it!

**Comment by kripken** [comment]
Hmm, I'm still confused @TroyTae . What is the difference to the tests I asked about?

What I am trying to understand is why those tests did not already test that `userData` works properly, since they do seem to test it. But is it a different type of fetch? (an async one maybe? but they are all async I think?)

**Comment by TroyTae** [comment]
@kripken 
I confirmed that the pointer address is different in sync and async mode.
(I guess async mode is working in another thread or just using different variable)
As you said, the only different is async or not.
If there is async test code, I wasn't write this test.
But I found only async example files.

Anyway my conclusion is "I wrote this test because the pointer address is different in sync and async"
If an existing test can do the same, please tell me!! (I might not have found it 😅 )

**Comment by kripken** [comment]
Hmm, isn't `tests/fetch/to_memory.cpp` async, like this test?

I don't know the Fetch API that well, but I am looking for `EMSCRIPTEN_FETCH_SYNCHRONOUS` which is how a fetch can be made synchronous? Or is there another way to make a fetch sync or async?

**Comment by TroyTae** [comment]
No `EMSCRIPTEN_FETCH_SYNCHRONOUS` flag makes fetch synchronous.
And it seems `tests/fetch/to_memory.cpp` can cover same test case.
Thank you! I close this PR :)

**Pull request closed without merging**
