### PR TITLE
Process wasm exports in-place. NFC

### PR DESCRIPTION
**Pull request by sbc100**
Rather than making a new copy the entire exports object.

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
I'm surprised this works... The reason we do this is because VMs used to not allow the wasm exports object to be modified (it's not a normal JS object). Did that change or did we misunderstand before?

**Comment by sbc100** [comment]
> I'm surprised this works... The reason we do this is because VMs used to not allow the wasm exports object to be modified (it's not a normal JS object). Did that change or did we misunderstand before?

You are right, modifications are not alowed, so we have to first make a copy of the entire export object using `Object.assign`.  I think doing this once, and then using in-place modification is a little better for code size and performance.. WDYT?

**Comment by sbc100** [comment]
Added some comments.   Maybe this change is not worth it?   WDYT?

**Comment by sbc100** [comment]
BTW, this was the change that inspired this one: https://github.com/emscripten-core/emscripten/pull/17057

I noticed we were making several passes over the module exports..

**Comment by sbc100** [comment]
I'll put this change on ice then.. until I have time to measure some actual performance, or space wins.

**Pull request closed without merging**
