### PR TITLE
Convert deps_info to python so it can include comments

### PR DESCRIPTION
**Pull request by sbc100**
Since there was only a single consumer in python it also
makes no sense to keep it in JSON format.

### CODE REVIEW

**Comment by sbc100** [comment]
turns out we had bunch of duplicate entries in there!

```
$ flake8 tools/
tools/deps_info.py:161:3: F601 dictionary key '_embind_register_std_string' repeated with different values
tools/deps_info.py:162:3: F601 dictionary key '_embind_register_std_wstring' repeated with different values
tools/deps_info.py:166:3: F601 dictionary key '_embind_register_std_string' repeated with different values
tools/deps_info.py:167:3: F601 dictionary key '_embind_register_std_wstring' repeated with different values
tools/deps_info.py:188:3: F601 dictionary key 'emscripten_set_mousemove_callback_on_thread' repeated with different values
tools/deps_info.py:189:3: F601 dictionary key 'emscripten_set_mousemove_callback_on_thread' repeated with different values
```

!!

**Comment by curiousdannii** [comment]
Do you want to take the opportunity to sort them?

**Comment by sbc100** [comment]
ping

**Comment by sbc100** [comment]
ping

**Review by kripken — APPROVED** [review]
I didn't check, but I assume the actual deps are all unchanged?

**Comment by sbc100** [comment]
Yes, unchanged.

**Pull request merged**
