### PR TITLE
Fix source maps with MINIMAL_RUNTIME

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
It looks like the assumption was that MINIMAL_RUNTIME would use the `foo.map` rather than `foo.wasm.map`, but all the later logic in emcc/emscripten.py was assuming `foo.wasm.map`.

Do we think `foo.map` is somewhat nicer?  If so I should instead plum the name those those later phases?

WDYT?

**Comment by sbc100** [comment]
I think I slightly prefer `foo.map` so maybe I should modify this change?

**Comment by kripken** [comment]
I think it's probably not worth fixing this. We will remove source map support once DWARF is stable, I believe, and there are very few users of source maps atm.

**Comment by kripken** [comment]
One option is to make MINIMAL_RUNTIME error on not support source maps, to avoid confusion.

**Comment by sbc100** [comment]
I that case I think landing this change is fine.  It a pretty clean change and fewer lines that adding a warning.

**Pull request merged**
