### PR TITLE
Reapply "Prefer `calloc` over of malloc+zeroMemory. NFC"

### PR DESCRIPTION
**Pull request by sbc100**
This reverts commit 50e0b0785ad5f9adc9bd082451d5cdbf5c4c5229.

This change also adds calloc to the list of symbols that we provide `emscripten_builtin_` variants for.

### CODE REVIEW

**Comment by sbc100** [comment]
See the second commit in this PR for the fix to the lsan issue.

**Comment by dschuff** [comment]
LGTM; can you also mention in the commit message that this makes the calloc symbol handled more like malloc and free?

**Review by dschuff — APPROVED** [review]

**Comment by dschuff** [comment]
This seems to be breaking test_externref_emjs_dynlink in UBSan mode:
https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket/8735974517183441729/+/u/Emscripten_testsuite__UBSan_/stdout

```
error: undefined symbol: malloc (referenced by $withBuiltinMalloc, referenced by $getMemory, referenced by $loadWebAssemblyModule, referenced by $loadDynamicLibrary, referenced by $loadDylibs, referenced by root reference (e.g. compiled C/C++ code))
warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _malloc may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: free (referenced by $withBuiltinMalloc, referenced by $getMemory, referenced by $loadWebAssemblyModule, referenced by $loadDynamicLibrary, referenced by $loadDylibs, referenced by root reference (e.g. compiled C/C++ code))
warning: _free may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: memalign (referenced by $withBuiltinMalloc, referenced by $getMemory, referenced by $loadWebAssemblyModule, referenced by $loadDynamicLibrary, referenced by $loadDylibs, referenced by root reference (e.g. compiled C/C++ code))
warning: _memalign may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: emscripten_builtin_malloc (referenced by $withBuiltinMalloc, referenced by $getMemory, referenced by $loadWebAssemblyModule, referenced by $loadDynamicLibrary, referenced by $loadDylibs, referenced by root reference (e.g. compiled C/C++ code))
warning: _emscripten_builtin_malloc may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: emscripten_builtin_free (referenced by $withBuiltinMalloc, referenced by $getMemory, referenced by $loadWebAssemblyModule, referenced by $loadDynamicLibrary, referenced by $loadDylibs, referenced by root reference (e.g. compiled C/C++ code))
warning: _emscripten_builtin_free may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: emscripten_builtin_memalign (referenced by $withBuiltinMalloc, referenced by $getMemory, referenced by $loadWebAssemblyModule, referenced by $loadDynamicLibrary, referenced by $loadDylibs, referenced by root reference (e.g. compiled C/C++ code))
warning: _emscripten_builtin_memalign may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: emscripten_builtin_calloc (referenced by $withBuiltinMalloc, referenced by $getMemory, referenced by $loadWebAssemblyModule, referenced by $loadDynamicLibrary, referenced by $loadDylibs, referenced by root reference (e.g. compiled C/C++ code))
warning: _emscripten_builtin_calloc may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
```

**Comment by dschuff** [comment]
test_externref_emjs_dylink uses MAIN_MODULE=2.
The reference chain includes  `malloc (referenced by $withBuiltinMalloc, referenced by $getMemory,`
Which seems odd because getMemory doesn't obviously refer to withBuiltinMalloc. Any idea what's happening?

**Comment by sbc100** [comment]
The `$getMemory__noleakcheck: true,` thing is what brings in `withBuiltinMalloc`

**Comment by dschuff** [comment]
ah. so can we fix it by just adding that to the deps? or maybe conditionally?

**Comment by sbc100** [comment]
(a) fix is here: https://github.com/emscripten-core/emscripten/pull/22650

**Pull request merged**
