### PR TITLE
Fix regal build after new clang warning was added. NFC

### PR DESCRIPTION
**Pull request by sbc100**
Followup to #22798

### CODE REVIEW

**Review by dschuff — APPROVED** [review]

**Comment by dschuff** [comment]
Are these new places that need updating showing up on CI, or how are you discovering them?

**Comment by sbc100** [comment]
> Are these new places that need updating showing up on CI, or how are you discovering them?

This showed up in emscripten CI yes.  I guess we don't build regal as part of emscripten-releases?   I guess this is because we don't do `embuilder build ALL` there?

**Comment by sbc100** [comment]
The good news is that this means the llvm changed passed the rollers, and if i passes here too then we should be all good.

**Comment by dschuff** [comment]
Ah yes, we use SYSTEM, and not ALL.

**Pull request merged**
