### PR TITLE
Update glossary.rst

### PR DESCRIPTION
**Pull request by eleensmathew**
I have removed the the glossary entry for LLVM Nativizer

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by sbc100** [comment]
It looks like there is a reference to `LLVM Nativizer` elsewhere in glossary.rst that is causing the build of the docs (`make -C site/ html`) to fail.   Can you remove that reference too?

**Comment by eleensmathew** [comment]
Done. Please review pull request.

**Comment by sbc100** [comment]
You need push your new changes back to github to make them visible.

**Comment by eleensmathew** [comment]
I have sent the pull request and I can view it as well in the pull request
section. Please explain what exactly I should do to resolve the issue.--
Eleena

**Comment by eleensmathew** [comment]
I have made a new pull request. https://github.com/emscripten-core/emscripten/pull/16044 Sorry for the inconvenience

**Pull request closed without merging**
