### PR TITLE
Remove special case JS function proxying from library_pthread.c

### PR DESCRIPTION
**Pull request by sbc100**
The normal `__proxy` method for JS functions works fine in these cases
and avoiding the special cases reduces the dependies of
`library_pthread.c` which is included in all threaded programs.

### CODE REVIEW

**Comment by juj** [comment]
Why call the builtin_malloc directly and not malloc? Doing that prevents people from providing their own malloc wrappers/implementations?

**Comment by sbc100** [comment]
> Why call the builtin_malloc directly and not malloc? Doing that prevents people from providing their own malloc wrappers/implementations?

The the `_builtin` aliases are already used in several places, so I don't think this PR changes any requirements.  These function (aliases normally) are used in asan/lsan builds when we want to make allocations that are not tracked by the santizers.    IIRC, if you want to replace malloc/free in emscripten today, you already need to provide these aliases (we had to add them to both dlmalloc and emmalloc for example).

Maybe we could provide default aliases that are used when the santizers are not enabled, that way folks would only need to include them in their custom allocator if they also want to use the santizers?

**Comment by juj** [comment]
> These function (aliases normally) are used in asan/lsan builds when we want to make allocations that are not tracked by the santizers. IIRC, if you want to replace malloc/free in emscripten today, you already need to provide these aliases (we had to add them to both dlmalloc and emmalloc for example).

Hmm, it looks like there has been an overloaded meaning added to the `emscripten_builtin_malloc` symbol names.

Originally those `_builtin_` names were added so that end users could create a frontend/passthrough to malloc/free e.g. for their own memory allocation tracking purposes, but still keep linking in the original malloc & free. See #4603.

This way end users could implement `malloc()` and `free()` in their code, and then from those functions do some memory alloc tracking, and then call to `emscripten_builtin_malloc()` and `emscripten_builtin_free()` to use the underlying dlmalloc/emmalloc.

However when asan & lsan support was added, it looks like they have "stolen" this use case from the user, and now `malloc()` means asan-tracked call, and `emscripten_builtin_malloc()` means a non-asan tracked call.

Though even with this mutated meaning, it is not obvious to me why these calls would want to bypass asan&lsan? These all look like general memory allocation that would benefit from being taken through memory sanitizers as well?

**Comment by sbc100** [comment]
> > These function (aliases normally) are used in asan/lsan builds when we want to make allocations that are not tracked by the santizers. IIRC, if you want to replace malloc/free in emscripten today, you already need to provide these aliases (we had to add them to both dlmalloc and emmalloc for example).
> 
> Hmm, it looks like there has been an overloaded meaning added to the `emscripten_builtin_malloc` symbol names.
> 
> Originally those `_builtin_` names were added so that end users could create a frontend/passthrough to malloc/free e.g. for their own memory allocation tracking purposes, but still keep linking in the original malloc & free. See #4603.
> 
> This way end users could implement `malloc()` and `free()` in their code, and then from those functions do some memory alloc tracking, and then call to `emscripten_builtin_malloc()` and `emscripten_builtin_free()` to use the underlying dlmalloc/emmalloc.
> 
> However when asan & lsan support was added, it looks like they have "stolen" this use case from the user, and now `malloc()` means asan-tracked call, and `emscripten_builtin_malloc()` means a non-asan tracked call.
> 
> Though even with this mutated meaning, it is not obvious to me why these calls would want to bypass asan&lsan? These all look like general memory allocation that would benefit from being taken through memory sanitizers as well?

Isn't asan using the `_builtin_` function exactly as you describe.  It wants to wrap malloc and then call the underlying version, just as you describe.   The only potential problem here is that there can only be a single interceptor/wrapper installed at a given time and so asan is not compatible with other layers of wrapping/intercepting being active at the same time.

**Comment by sbc100** [comment]
I think these two comments (one from compiler-rt and one from our code) describe why we don't/can't detect leaks in the low level pthread code:

https://github.com/emscripten-core/emscripten/blob/9a644e1a878863b9dc168401174c9f5c775e8c1b/system/lib/compiler-rt/lib/asan/asan_interceptors.cpp#L215-L224

https://github.com/emscripten-core/emscripten/blob/9a644e1a878863b9dc168401174c9f5c775e8c1b/system/lib/pthread/library_pthread.c#L162-L171

**Pull request closed without merging**
