### PR TITLE
Update SIMDe to 0.8.2

### PR DESCRIPTION
**Pull request by mr-c**
https://github.com/simd-everywhere/simde/compare/314452b...71fd833

Follow on to https://github.com/emscripten-core/emscripten/pull/19304

### CODE REVIEW

**Comment by mr-c** [comment]
@sbc100 @tlively Looks like some tests need to be rebaseline; is that easy for you to do?

**Comment by sbc100** [comment]
If this file is purely coming from simde repo should we include as a git submodule perhaps?   (That can be a separate change of course).

**Comment by mr-c** [comment]
@sbc100 The file is modified from the SIMDe repo via https://github.com/emscripten-core/emscripten/blob/main/tools/maint/simde_update.py

**Review by tlively — APPROVED** [review]
mostly rubberstamp LGTM

**Comment by sbc100** [comment]
> @sbc100 The file is modified from the SIMDe repo via https://github.com/emscripten-core/emscripten/blob/main/tools/maint/simde_update.py

Ah yes, thanks for the reminder.  I wonder if we should mention that script both the file content, and also in PR descriptions when we update it.  e.g. `This changes was generated using ...`?

**Comment by mr-c** [comment]
> > @sbc100 The file is modified from the SIMDe repo via https://github.com/emscripten-core/emscripten/blob/main/tools/maint/simde_update.py
> 
> Ah yes, thanks for the reminder.  I wonder if we should mention that script both the file content, and also in PR descriptions when we update it.  e.g. `This changes was generated using ...`?

Sure. I can amend the commit message after the tests pass ( or the merger can do so 👍)

**Pull request merged**
