### PR TITLE
Add new --emit-minification-map flag and use it in metadce tests

### PR DESCRIPTION
**Pull request by sbc100**
This greatly increases the utility of the output files for these tests.

### CODE REVIEW

**Comment by sbc100** [comment]
I noticed that need for this while working on #22429

**Comment by dschuff** [comment]
Do you see this being useful outside the metadce tests?
I guess users aren't usually exposed to the minified imports/exports since they are hooked up to their proper names on the Module object, and users would use a name section or source map to know the names of the functions themselves?

**Comment by sbc100** [comment]
> Do you see this being useful outside the metadce tests?

Only really for debugging.

> I guess users aren't usually exposed to the minified imports/exports since they are hooked up to their proper names on the Module object, and users would use a name section or source map to know the names of the functions themselves?

"proper" names are only used for things that get exported outside the module.  imports/exports that are for internal use only won't get a "proper" name anywhere in the program.

The name section is useful, but doesn't help for imports (which I don't think have names) or data symbols.

**Comment by sbc100** [comment]
Assuming this is only useful for our testing, should I instead make this is internal-only thing (maybe an environment variable that we don't document?)

**Comment by sbc100** [comment]
OK, will land as is.

**Pull request merged**
