### PR TITLE
Static Allocation of Slots for Main Module Imports

### PR DESCRIPTION
**Pull request by awtcode**
The fp$ accessors take a long time to run when called during startup for the LLVM WASM BACKEND when there's a large number of imports (~30k). This PR resolves the issue by calculating the slots for the imports in wasm-emscripten-finalize so that we do not incur a runtime hit. The imports are added to the end of the table anyway so there should not be a functional difference.

At the same time, dl$ accessors are added to set the imports to the correct slots and call the target function. This change is only applied to the main module at this point in time.

For a main module with 30k imports, the time taken to run the ___assign_got_enties function has been reduced from 147931ms to 4ms. 

@sbc100 , this PR has a dependency on https://github.com/WebAssembly/binaryen/pull/2440 and how do we point to that PR in order to pass the CI?

FYI @kripken

### CODE REVIEW

**Comment by kripken** [comment]
> The fp$ accessors take a long time to run

How much is a long time here?

**Comment by awtcode** [comment]
> > The fp$ accessors take a long time to run
> 
> How much is a long time here?

For a program with 20k imports, ___assign_got_enties takes 20s to finish execution. Acad currently has around 30k imports and I believe the specs allow for up to 100k.

**Comment by kripken** [comment]
So around 1ms per entry? That sounds extremely high. Do we know why it takes so long?

**Comment by awtcode** [comment]
@kripken , the number of JS calls that the `___assign_got_enties` function makes is linear to the number of imports so perhaps this is the reason why its so slow? There would be 20k wasm-to-JS calls for 20k imports. This is for the case where the side module is already loaded. If the side module is not loaded, we would need to add the JS stubs to the Wasm table which would take around double the time.

Btw, this PR has a dependency on another PR in binaryen: https://github.com/WebAssembly/binaryen/pull/2440.

How can I point to the above PR so that I can pass the CI?

**Comment by kripken** [comment]
Why is a wasm to JS call taking 1ms, though? That's the key question here. Maybe it's a VM bug. Running a native profiler might help understand that.

I don't think there's a way to point CI here to a specific binaryen build. It downloads builds from the waterfall, which only builds the main branch. You'd have to run tests locally for now.

**Comment by awtcode** [comment]
@kripken, I reran my test app on Chrome Canary 80 instead of Node and found that the performance is better. `__assign_got_enties` took 5.5s to run which means each call roughly took around 0.275ms. The time taken to run 1 fp$ accessor in JS is around 0.1ms so the transition took roughly 0.175ms

However, the above is for a developer machine which is much more powerful than what the typical user would have. On a Core i5 laptop, `__assign_got_enties` takes around 22s which means that each call took around 1ms. The JS implementation in 1 fp$ accessor took around 0.3ms.

I'm sure the VM has room for improvement but when it comes to Firefox, `__assign_got_enties` takes around 1.5s to complete so I believe that's as far as the VM can go in terms of performance.

**Comment by sbc100** [comment]
But what is it that __assign_got_enties is doing in the case that you
measured?  Is the cost in the JS<->wasm boundary itself, or is it, for
example, adding the table entries (which can involve creating an entire
wasm module as a shim)?

cheers,
sam

**Comment by awtcode** [comment]
@sbc100 , each call to a fp$ accessor took around 0.275ms with the JS in the accessor taking around 0.1ms so the transition took around 0.175ms.

**Comment by kripken** [comment]
In the [chromium issue](https://bugs.chromium.org/p/v8/issues/detail?id=10018#c12) it sounds like `table.grow()` is the issue. Perhaps a simple solution like every grow being of minimum size 100, and remembering that reserved space, could work here?

**Comment by awtcode** [comment]
Sure @kripken , this will help. But maybe we should wait for v8 to implement the fix first? I'm not sure if the extra handling will slow down Firefox unnecessarily.

**Comment by kripken** [comment]
Up to you. I don't think this is urgent, so waiting for v8, or measuring on sm, both seem reasonable.

**Comment by sbc100** [comment]
I think grows the table  exponentially here makes sense in any case. Its simple enough to do and it will most like help other implementations too.

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

Re-opening and re-targeting to master.

**Pull request closed without merging**
