### PR TITLE
Enable GLU methods .js implementations only when LEGACY_GL_EMULATION is enabled

### PR DESCRIPTION
**Pull request by gabrielcuvillier**
By default, some glu methods such as gluProject, gluPerspective, gluLookAt are implemented in 'library_webgl.js'. These implementations are relying on the legacy GL emulation layer (GLImmediate variable in the file, defined with LEGACY_GL_EMULATION=1).

The issue is that when someone use another GL 1.x emulation layer such as Regal, these default GLU methods implementation are not functional (because LEGACY_GL_EMULATION mode is not active)... but still they are silently linked! Hence, they are failing if called at runtime.

The error that occurs at runtime is a bit confusing, and it took me some time to figure out that I needed to link explicitly with a more regular GLU implementation in C.

So, I think it would be better to include those default GLU methods implementations only when LEGACY_GL_EMULATION is defined, and let the linker complains in all other cases: for example if someone is trying to call GLU methods without Emscripten Legacy GL Emulation enabled. 

At least, the developer know that GLU is missing and needs to be explicitly provided. This is a little bit like it is done with some GLUT methods such as glutSolidSphere, glutSolidCube, etc: they need to be provided explicitly.

### CODE REVIEW

**Comment by juj** [comment]
Definitely agreed.

Hey any chance you might be interested in separating the glu functions to a file of its own `library_glu.js`? The implementation can then evolve there, explicitly separate from the rest of the code.

**Comment by gabrielcuvillier** [comment]
Sure, I'll put them in a 'library_glu.js' file

**Comment by kripken** [comment]
Sounds good to me too, thanks @gabrielcuvillier !

I think this can land (further refactoring can be later), just need to update that one failing test. Or, can wait until #10010 lands as I want to remove that test...

**Comment by gabrielcuvillier** [comment]
Yes, for sure this can wait on #10010 to be addressed. No need to do job twice :)

Apparently, it looks like that if these GLU functions are also defined in Wasm, they take precedence over the JS one (similar to "weak symbol").  At least, I do not have linker errors by doing so.

**Comment by kripken** [comment]
Yes, that's a general feature of how we link in JS code: we link in JS functions if they are needed, that is, if a symbol is unresolved. So anything already linked in normally as compiled code is resolved. Which means all JS library code is similar to being weakly linked, yes.

**Comment by kripken** [comment]
Ok, #10010 landed, so merging incoming to here should let us land this.

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

Re-opening and re-targeting to master.

**Comment by sbc100** [comment]
This should still land is possible I think.  Can you rebase?

**Pull request closed without merging**
