### PR TITLE
[WasmFS] Implement `unlinkat` and `openat`

### PR DESCRIPTION
**Pull request by tlively**
And use them to replace `unlink`, `rmdir`, and `open` syscalls entirely in both
the JS file system and in WasmFS. Add a few other fixes to get test_unlink
passing on WasmFS as well.

### CODE REVIEW

**Comment by sbc100** [comment]
I think I have similar change in flight: https://github.com/emscripten-core/emscripten/pull/15411.  It had some pushback in the past due to codesize concerns.. but I think we agreed to move forward. 

I'm curious how this change avoids having to define SANITIZER_USES_CANONICAL_LINUX_SYSCALLS given that my change did?

**Comment by sbc100** [comment]
BTW, my change is fairly stale so I'm happy to have this change land rather than try to rebase it, but maybe take a look to make sure this is a superset?

**Comment by tlively** [comment]
> I'm curious how this change avoids having to define SANITIZER_USES_CANONICAL_LINUX_SYSCALLS given that my change did?

Looks like this change does have to define that as well. To keep this change more contained inside WasmFS, I'll leave the system call implementations alone for now, and once we support the other canonical calls like `readlinkat`, we can rebase and apply #15411

**Comment by tlively** [comment]
@sbc100, this should be ready for another look

**Review by sbc100 — APPROVED** [review]

**Pull request merged**
