### PR TITLE
Update Khronos headers to latest versions as of 2020-08-04

### LINKED ISSUE #11801: GLES headers are missing some compressed texture extensions
The following GLES extensions are missing from the headers:

* [EXT_texture_compression_rgtc](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_compression_rgtc.txt); WebGL equivalent: [EXT_texture_compression_rgtc](https://www.khronos.org/registry/webgl/extensions/EXT_texture_compression_rgtc/)
* [EXT_texture_compression_bptc](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_compression_bptc.txt); WebGL equivalent: [EXT_texture_compression_bptc](https://www.khronos.org/registry/webgl/extensions/EXT_texture_compression_bptc/)
* [EXT_texture_compression_s3tc_srgb](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_compression_s3tc_srgb.txt); WebGL equivalent: [WEBGL_compressed_texture_s3tc_srgb](https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_s3tc_srgb/)
* [EXT_texture_compression_astc_decode_mode](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_compression_astc_decode_mode.txt); no WebGL equivalent.

There are probably more missing extensions. The first 3 are the ones I actually ran into a problem with in my codebase, and the ones that are most useful to expose, since they are usable in WebGL. All of these are in the official Khronos `GLES2/gl2ext.h` header.

### PR DESCRIPTION
**Pull request by Akaricchi**
Pulled from the [OpenGL](https://github.com/KhronosGroup/OpenGL-Registry) and [EGL](https://github.com/KhronosGroup/EGL-Registry) registries.

Fixes #11801.

### CODE REVIEW

**Comment by sbc100** [comment]
Nice!   Are there verbatim copies with no local mods at all?

lgtm assuming all the tests pass.

**Comment by Akaricchi** [comment]
Yeah they are. Perhaps there should be a small script to pull them to avoid having to do that manually in the future. FWIW Taisei seems to compile fine with them.

**Comment by kripken** [comment]
ping @juj 

I don't know enough about this, but one thing that I see in the diff is

```
-// Define MESA_EGL_NO_X11_HEADERS for Emscripten
-#define MESA_EGL_NO_X11_HEADERS
```

Maybe that was important?

**Comment by Akaricchi** [comment]
It's not needed. First of all, this macro is deprecated in Mesa's headers and has been replaced with `EGL_NO_X11` upstream:

```c
#if defined(MESA_EGL_NO_X11_HEADERS) && !defined(EGL_NO_X11)
#warning "`MESA_EGL_NO_X11_HEADERS` is deprecated, and doesn't work with the unmodified Khronos header"
#warning "Please use `EGL_NO_X11` instead, as `MESA_EGL_NO_X11_HEADERS` will be removed soon"
#define EGL_NO_X11
#endif
```

But even `EGL_NO_X11` is not relevant because of this branch in the header: https://github.com/emscripten-core/emscripten/blob/f6fa745e1feb6477db87ae53111e524bcb555946/system/include/EGL/eglplatform.h#L80

Note how `EGL_NO_X11` is only ever tested once, in an `#elif` branch way under the `__EMSCRIPTEN__` check: https://github.com/emscripten-core/emscripten/blob/f6fa745e1feb6477db87ae53111e524bcb555946/system/include/EGL/eglplatform.h#L119

It also looks like the emscripten branch has existed even in the old header, and the `MESA_EGL_NO_X11_HEADERS` didn't really do anything.

**Comment by juj** [comment]
Hmm, this PR comes as only one commit that both updates the new header from upstream, but also applies local changes to it. It is difficult to review the files since they are large, and there is no indication of what was changed from the upstream headers.

Are there a lot of changes you did? Any chance you'd be able to separate those to a commit of its own, and we could land that in the tree without squashing as well, so that the next time someone is updating, the local change history can be observed from git logging git commits?

**Comment by sbc100** [comment]
> Hmm, this PR comes as only one commit that both updates the new header from upstream, but also applies local changes to it. It is difficult to review the files since they are large, and there is no indication of what was changed from the upstream headers.
> 
> Are there a lot of changes you did? Any chance you'd be able to separate those to a commit of its own, and we could land that in the tree without squashing as well, so that the next time someone is updating, the local change history can be observed from git logging git commits?

When I asked `Are there verbatim copies with no local mods at all?, the answer was `Yeah they are.`.   Is this answer wrong? 
 Are there actually local changes?

**Comment by juj** [comment]
There is a `#elif defined(__EMSCRIPTEN__)` in eglplatform.h at least - did not look further.

Though now that I look at it, it seems that EGL upstream has taken a `__EMSCRIPTEN__` define in its codebase: [eglplatform.h](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwj73oSupqfrAhWi-ioKHb0aBXsQFjAAegQIBRAB&url=https%3A%2F%2Fwww.khronos.org%2Fregistry%2FEGL%2Fapi%2FEGL%2Feglplatform.h&usg=AOvVaw0Lw_EB0JtlXlzrJuvYcGMD), so maybe I was confused by that, assuming there were some changes of our own.

If there are no custom changes, then LGTM.

**Comment by Akaricchi** [comment]
I made zero changes to the headers, it's just a verbatim copy.

**Pull request merged**
