### PR TITLE
Update SDL2 port to 2.24.0

### PR DESCRIPTION
**Pull request by Daft-Freak**
Pointing at a release tag again. I've run tests locally, so hopefully nothing fails. (Looks like there are some broken tests in test_interactive though)

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

Are those interactive tests broken by this PR, or were they broken before?

**Comment by kripken** [comment]
Thanks, yes, those look like recent breakage... I opened https://github.com/emscripten-core/emscripten/pull/17755 now.

Might be safest to land this after that. Is this otherwise ready to land, or should we check anything else?

**Review by sbc100 — APPROVED** [review]

**Comment by Daft-Freak** [comment]
Looks like those tests pass after that change except beeps, but that was already failing (I think I know why and it's a test issue).

**Comment by kripken** [comment]
Ok, great, landing.

**Pull request merged**
