### PR TITLE
Handle a main module without a main() function. 

### PR DESCRIPTION
**Pull request by kripken**
Fixes a regression from #9143.

### CODE REVIEW

**Comment by sbc100** [comment]
This seems like strange use case to want to support.. but i guess if people are already doing this.

**Comment by quantum5** [comment]
Don't we have the dylink tests with flip? When flipped, the main function goes into the side module.

**Comment by sbc100** [comment]
> Don't we have the dylink tests with flip? When flipped, the main function goes into the side module.

I mean aside from that.   Its not something that is supported on any other platform.

**Comment by kripken** [comment]
Yeah, maybe it is weird. But a MAIN_MODULE that is used as a library (has a custom invocation, instead of `main()`), and which dlopens other sub-libraries, seems like a reasonable use case to me.

@quantum5 about the flip tests, in them we still do have a `main()` function after linking them up at runtime. This bugfix is for the case where there is no `main()` at all, basically. That's why this regression wasn't caught.

**Pull request merged**
