### PR TITLE
Always use bulkmemory memcpy and memset when available

### PR DESCRIPTION
**Pull request by sbc100**
Unlike the JS versions of these function there is no need to only use these for small inputs.

Results of running the test_memcpy_128b test before and after this change:

```
v8-bulk: mean: 1.536 (+-0.071) secs  median: 1.495  range: 1.471-1.650  (noise: 4.630%)  (5 runs)
        size:   149291, compressed:    54249
```

->

```
v8-bulk: mean: 1.489 (+-0.117) secs  median: 1.535  range: 1.268-1.606  (noise: 7.871%)  (5 runs)-
        size:   148387, compressed:    53813-
```

See comments in #19128

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Great!

I guess no significant code size changes since we don't measure there with bulk memory? Did you notice a code size change manually when using bulk memory?

**Comment by sbc100** [comment]
Based on `emcc ~/test/hello.c -mbulk-memory -sEXPORTED_FUNCTIONS=_memcpy,_memset,_main` the wasm size goes down by around 1k (12241 to 11313 bytes).   I forgot to add `-Oz` there.. but looks like a real saving

**Comment by kripken** [comment]
Nice!

**Comment by kg** [comment]
Hi,
Doing a local profile of one of our applications using chrome's devtools, emscripten's mmap is spending a bunch of time calling memset during app startup, and I don't see bulk memory operations inside of the memset from emscripten's musl libc. Is there something we should do to opt-in to the bulk memory version from this PR? It doesn't look like memcpy is using bulk memory either.
Thanks

**Comment by kg** [comment]
If I'm reading https://github.com/emscripten-core/emscripten/blob/918e131fae0b5c7b1d05a5c75d7e8e676c377713/tools/system_libs.py#L1307C7-L1307C16 correctly, it looks like `-Oz` may be unintentionally disabling bulk memory, since it passes its own version of memcpy/memmove?

We do use `-Oz` sometimes, but I tried replacing all our references to it with `-O2` and didn't see a change. I'll keep experimenting...

**Comment by sbc100** [comment]
You should see `libbulkmemory` being included on the link line (e.g. `-lbulkmemory`).

See https://github.com/emscripten-core/emscripten/blob/918e131fae0b5c7b1d05a5c75d7e8e676c377713/tools/system_libs.py#L2296-L2297

**Comment by kg** [comment]
So from looking at my build logs, I'm running:
```
emcc "@/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/src/emcc-default.rsp" -msimd128 "@/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/src/emcc-link.rsp" "@/home/kate/Projects/dotnet-runtime-wasm/artifacts/obj/mono/RayTracer/browser.wasm.Release/browser-wasm/wasm/for-publish/emcc-link.rsp"
```

and if i `cat` the relevant rsp file:
```
kate@reeir-debian2:~/Projects/dotnet-runtime-wasm/src/mono/sample/wasm/dotnet-wasm-raytracer-simd$ cat "/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/src/emcc-default.rsp"
-mbulk-memory
```

So the switch should be getting seen by emcc, and it seems like at some level it is being seen because `--enable-bulk-memory` is making it through to the link step. But as you point out, `-lbulkmemory` is missing from the link arguments. Is it not supported to use response files in this way? As you may notice we have a raw `-msimd128` in the command line there; I previously had to add that to get things working so maybe we've been having rsp file problems this whole time without my notice...

For reference, here are the other two rsp files. You can see bulk-memory is in another one too, since I tried adding it there earlier:

```
kate@reeir-debian2:~/Projects/dotnet-runtime-wasm/src/mono/sample/wasm/dotnet-wasm-raytracer-simd$ cat /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/src/emcc-link.rsp
-s INITIAL_MEMORY=16777216
-s STACK_SIZE=5MB
-s ALLOW_MEMORY_GROWTH=1
-s ALLOW_TABLE_GROWTH=1
-s NO_EXIT_RUNTIME=0
-s FORCE_FILESYSTEM=1
-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE="[]"
-s EXPORTED_RUNTIME_METHODS="['FS','out','err','ccall','cwrap','setValue','getValue','UTF8ToString','UTF8ArrayToString','stringToUTF8Array','FS_createPath','FS_createDataFile','removeRunDependency','addRunDependency','addFunction','safeSetTimeout','runtimeKeepalivePush','runtimeKeepalivePop','maybeExit','abort']"
-s EXPORTED_FUNCTIONS=_free,_htons,_malloc,_memalign,_memset,_ntohs,stackAlloc,stackRestore,stackSave,_fmod,_atan2,_fma,_pow,_fmodf,_atan2f,_fmaf,_powf,_asin,_asinh,_acos,_acosh,_atan,_atanh,_cbrt,_cos,_cosh,_exp,_log,_log2,_log10,_sin,_sinh,_tan,_tanh,_asinf,_asinhf,_acosf,_acoshf,_atanf,_atanhf,_cbrtf,_cosf,_coshf,_expf,_logf,_log2f,_log10f,_sinf,_sinhf,_tanf,_tanhf
--source-map-base http://example.com
-s WASM_BIGINT=1
-s EXPORT_NAME="'createDotnetRuntime'"
-s MODULARIZE=1
-s ENVIRONMENT="web,webview,worker,node,shell"
-Wno-limited-postlink-optimizations
--profiling-funcs
```


```
kate@reeir-debian2:~/Projects/dotnet-runtime-wasm/src/mono/sample/wasm/dotnet-wasm-raytracer-simd$ cat /home/kate/Projects/dotnet-runtime-wasm/artifacts/obj/mono/RayTracer/browser.wasm.Release/browser-wasm/wasm/for-publish/emcc-link.rsp
-O2
-mbulk-memory
-g
-v
-fwasm-exceptions
-s EXPORT_ES6=1 -lexports.js
-s EXPORT_EXCEPTION_HANDLING_HELPERS=1
-s LLD_REPORT_UNDEFINED
-s ERROR_ON_UNDEFINED_SYMBOLS=1
-s INITIAL_MEMORY=22413312
-s STACK_SIZE=5MB
-s WASM_BIGINT=1
--emit-symbol-map
--pre-js "/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/src/es6/dotnet.es6.pre.js"
--js-library "/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/src/es6/dotnet.es6.lib.js"
--extern-post-js "/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/src/es6/dotnet.es6.extpost.js"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/obj/mono/RayTracer/browser.wasm.Release/browser-wasm/wasm/for-publish/pinvoke.o"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/obj/mono/RayTracer/browser.wasm.Release/browser-wasm/wasm/for-publish/driver.o"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/obj/mono/RayTracer/browser.wasm.Release/browser-wasm/wasm/for-publish/corebindings.o"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/obj/mono/RayTracer/browser.wasm.Release/browser-wasm/wasm/for-publish/runtime.o"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libicudata.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libicui18n.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libicuuc.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libmono-component-debugger-static.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libmono-component-diagnostics_tracing-stub-static.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libmono-component-hot_reload-static.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libmono-component-marshal-ilgen-static.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libmono-ee-interp.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libmono-icall-table.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libmono-profiler-aot.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libmono-profiler-browser.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libmono-wasm-eh-wasm.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libmono-wasm-simd.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libmonosgen-2.0.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libSystem.Globalization.Native.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libSystem.IO.Compression.Native.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/libSystem.Native.a"
"/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native/wasm-bundled-timezones.a"
-o "/home/kate/Projects/dotnet-runtime-wasm/artifacts/obj/mono/RayTracer/browser.wasm.Release/browser-wasm/wasm/for-publish/dotnet.native.js"
-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE="[]"
-s EXPORTED_RUNTIME_METHODS="['FS','out','err','ccall','cwrap','setValue','getValue','UTF8ToString','UTF8ArrayToString','stringToUTF8Array','FS_createPath','FS_createDataFile','removeRunDependency','addRunDependency','addFunction','safeSetTimeout','runtimeKeepalivePush','runtimeKeepalivePop','maybeExit','abort']"
-s EXPORTED_FUNCTIONS=_free,_htons,_malloc,_memalign,_memset,_ntohs,stackAlloc,stackRestore,stackSave,_fmod,_atan2,_fma,_pow,_fmodf,_atan2f,_fmaf,_powf,_asin,_asinh,_acos,_acosh,_atan,_atanh,_cbrt,_cos,_cosh,_exp,_log,_log2,_log10,_sin,_sinh,_tan,_tanh,_asinf,_asinhf,_acosf,_acoshf,_atanf,_atanhf,_cbrtf,_cosf,_coshf,_expf,_logf,_log2f,_log10f,_sinf,_sinhf,_tanf,_tanhf
```

**Comment by sbc100** [comment]
`--enable-bulk-memory` is being passed to `wasm-opt` because one of more object files enabled it.

I can't see why `-mbulk-memory` would not work fine in a `.rsp` file.

Can you try adding adding `assert setting.BULK_MEMORY` at the end of `parse_args` in `emcc.py`?

**Comment by kg** [comment]
`setting.BULK_MEMORY` doesn't seem to be defined. I tried `settings.BULK_MEMORY` but:
```
AttributeError: no such setting: 'BULK_MEMORY'
```

`options.BULK_MEMORY` seems wrong too:
```
AttributeError: 'EmccOptions' object has no attribute 'BULK_MEMORY'
```

I see `BULK_MEMORY` in `feature_matrix.py` in my local copy of emsdk, but I don't see it in system_libs.py. So my error is that somehow our install of emscripten is missing this stuff even though it was merged last year, in which case I've wasted your time. :( This explains why the flag is making it through to wasm-opt; it's working, but it's not doing what I expected it to do.

**Comment by sbc100** [comment]
It should be `settings.BULK_MEMORY`.  What version of emscripten are you using?

**Comment by sbc100** [comment]
You can see the setting getting set in the `arg_parse` function: https://github.com/emscripten-core/emscripten/blob/120186106755f87d1a0dfd0c6a6617119f6479bf/emcc.py#L1349-L1352

**Comment by sbc100** [comment]
No worries!  Glad it worked out.

**Pull request merged**
