### PR TITLE
Re-enable test_emmake_python under windows

### LINKED ISSUE #8872: test_emmake_python is broken on Windows
It's failing on the emscripten-releases builder, and it seems to be doing exactly what the test is trying to prevent (i.e. `CC` is being set to `python d:\path\to\emcc.py`).

### PR DESCRIPTION
**Pull request by sbc100**
Fixes #8872

### CODE REVIEW

**Comment by dschuff** [comment]
but... does the test actually work?

**Comment by sbc100** [comment]
Yup.. it seems too.  

Note that this recently change though.  We no longer set CC to a tuple starting with `python` .. we set it to point to the .bat file.     We don't make any assumptions internal that our tools are written in python anymore!

**Comment by sbc100** [comment]
I mean it passed in the CI .. do you have another meaning for "work"?

**Comment by dschuff** [comment]
oh, i meant didn't think we ran all the tests on windows on this CI (only the chromium CI). Did this test get included?

**Comment by sbc100** [comment]
We run a tiny subset here.   I included it as part of the CI run to make sure it passes.

**Pull request merged**
