### PR TITLE
Always run --remove-unused-module-elements when STANDALONE_WASM

### PR DESCRIPTION
**Pull request by kripken**
We always run that pass when optimizing, but normally do not when not optimizing. In standalone mode, though, an unnecessary import may make the wasm not standalone and so not runnable in wasmer/wasmtime/etc. So in that mode, it's best to run it, to avoid a silly import breaking the wasm.

A concrete example of when this is needed is that in hello world with iostreams we end up with unnecessary imports of `atexit` (we will need to fix that eventually, but it's only needed when EXIT_RUNTIME is flipped by the user, as the default ignores `atexit`s).

### CODE REVIEW

**Comment by sbc100** [comment]
lld should never generate an unused import should it?  How does it end up being imported by not used?

**Comment by kripken** [comment]
In the case of `atexit`, we emit it initially but then apply the `NO_EXIT_RUNTIME` transform which removes the need for it. So this is stuff that is added after lld.

**Comment by sbc100** [comment]
Presumably the NO_EXIT_RUNTIME should really remove this?

lgtm though.

**Comment by kripken** [comment]
I think it's simpler for the `-no-exit-runtime` pass to leave optimizations for other passes. But yeah, that does mean we need to run more passes like here...

**Pull request merged**
