### PR TITLE
[WasmFS] Move O_TRUNC handling to avoid crash

### PR DESCRIPTION
**Pull request by tlively**
WasmFS backends like OPFS may reasonably expect that files will only be modified
while open and may be unprepared to modify unopened files. However, when
handling O_TRUNC, we truncated files before opening them in the backend. For the
OPFS backend in particular, this caused a crash because the backend did not yet
have an AccessHandle for the file. Fix the problem by deferring O_TRUNC handling
until after we have asked the backend to open the file.

### CODE REVIEW

**Comment by tlively** [comment]
Current dependencies on/for this PR:
* main
  * **PR #17192** <a href="https://app.graphite.dev/github/pr/emscripten-core/emscripten/17192" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/emscripten-core/emscripten/17192?utm_source=stack-comment).

**Review by kripken — APPROVED** [review]

**Comment by tlively** [comment]
Merged main to see if that fixes the weird unrelated ASan failure in the proxying queue test.

**Comment by tlively** [comment]
Merging manually because this test failure is certainly unrelated.

**Comment by tlively** [comment]
Ah, this fix isn't sufficiently general since `truncate` can be called on files that haven't been opened at all :/

**Pull request merged**
