### PR TITLE
wasm preamble: use Promise.resolve rather than new Promise

### PR DESCRIPTION
**Pull request by aduh95**
Using `Promise.resolve` is more concise than using `Promise` constructor and produces the same result.

### CODE REVIEW

**Comment by kripken** [comment]
The test failures are odd and maybe unrelated... @aduh95 can you merge latest upstream into here, and then we can see the new test results?

**Comment by aduh95** [comment]
@kripken done, the test failures are still there. Weird, I'm not able to reproduce on my local build…

**Comment by kripken** [comment]
It does fail for me locally. Are you using a different node.js perhaps? I see it locally with node 14.1, 12.18.1, and 10.21.0.

What happens for me locally is that in both cases it prints
```
Error: ENOENT: no such file or directory, open '/tmp/emscripten_test/src.cpp.o.wasm.lazy.wasm'
```
In `wasm0`, before this PR, it then continues to run apparently and hits `Runtime error: The application has corrupted its heap memory area (address zero)!` which exits with an error. With this PR, it just hangs, and nothing happens for a while (no CPU), then node exits with no error code.

That is actually not great, as what the test is trying to check is that we error when that `lazy.wasm` doesn't exist. It seems like that error is never propagated out, and instead the test happens to hit another error that is reported. And with this PR, that error doesn't happen somehow.

In `wasm1` (with assertions off, which were necessary for that Runtime error I think), something different happens: before, we'd see this:
```
Error: ENOENT: no such file or directory, open '/tmp/emscripten_test/src.cpp.o.wasm.lazy.wasm'
failed to asynchronously prepare wasm: RuntimeError: abort(Error: ENOENT: no such file or directory, open '/tmp/emscripten_test/src.cpp.o.wasm.lazy.wasm'). Build with -s ASSERTIONS=1 for more info.
```
and an error code is reported. With this PR it only prints the first line,
```
Error: ENOENT: no such file or directory, open '/tmp/emscripten_test/src.cpp.o.wasm.lazy.wasm'
```
and exits immediately, without an error code.

Overall, it looks like this change affects error handling in the Promise. Maybe we need to handle rejection explicitly?

**Comment by aduh95** [comment]
@kripken hum ok, I guess my local setup doesn't actually test my code… Thank you for the detailled explanation though, I think that's because the error is thrown synchronously instead of returning a rejected `Promise`.

I've tried another approach, let's see what the CI have to say about that.

**Comment by kripken** [comment]
And yes, I think you're right, it's the difference between synchronously erroring there or not.

**Pull request merged**
