### PR TITLE
Add '___cxa_is_pointer_type', '___cxa_can_catch' to the list of expor…

### PR DESCRIPTION
**Pull request by vargaz**
…ted functions when exception catching is enabled.

### CODE REVIEW

**Comment by vargaz** [comment]
Without this, running with -s DISABLE_EXCEPTION_CATCHING=0 fails with:
TypeError: Module.___cxa_is_pointer_type is not a function
in:
https://github.com/kripken/emscripten/blob/incoming/src/library.js#L1358

**Comment by kripken** [comment]
Interesting, do you have a testcase showing the problem? We do have a lot of tests on this, so you must be seeing a corner case we don't handle and don't test.

**Comment by vargaz** [comment]
Don't have a simple test case.

**Comment by vargaz** [comment]
Can be worked around by adding them to EXPORTED_FUNCTIONS etc.

**Comment by sbc100** [comment]
Why did this get closed?  Is it not a real issue?  We should at least keep a bug open if it is.

**Pull request closed without merging**
