### PR TITLE
Support pthreads in harfbuzz

### PR DESCRIPTION
**Pull request by kripken**
Fixes https://github.com/emscripten-ports/HarfBuzz/issues/1

### CODE REVIEW

**Comment by ebraminio** [comment]
Please update HarfBuzz version if is possible as that has a check to ensure one mutex implementation is enabled at least (which may need HAVE_PTHREAD also), btw just to note we have a bot with emscripten in our CI :)

**Comment by kripken** [comment]
I agree an update is a good idea. I don't see tests so probably the update should include manual testing or adding some. Not sure if I'll have time for that myself - the reason I jumped on this issue so quickly is I thought it might have been a general wasm backend vs fastcomp difference (pthreads linking is different there), and we're trying to fix any backend-related regressions urgently.

Do you think it would be ok to land this before updating?

Nice about the bot :)

**Comment by ebraminio** [comment]
> I thought it might have been a general wasm backend vs fastcomp difference (pthreads linking is different there), and we're trying to fix any backend-related regressions urgently.

Oh, ok

> Do you think it would be ok to land this before updating?

Sure. Will try do updating myself.

> I don't see tests so probably the update should include manual testing or adding some.

HarfBuzz is main logic is easy to trig, what is the preferred format for such? An example would be nice.

**Comment by kripken** [comment]
@ebraminio 

Here is the part of the test suite for ports testing, https://github.com/emscripten-core/emscripten/blob/incoming/tests/test_other.py#L1809 - looks like we have many of the ports there. A small number are tested elsewhere (like SDL2 in the browser suite).

**Comment by sbc100** [comment]
lgtm.

As an aside my understanding is that this port doesn't currently work on windows because its based on configure?   I think its the only port that is based on configure so we should probably switch it over to be more like the other ports.

**Pull request merged**
