### PR TITLE
Include debug info in system libraries

### PR DESCRIPTION
**Pull request by sbc100**
Add `-g` when building system libraries.  This does not effect the
optimization level but allows users who want it to have debug
information (e.g source maps) for the system libraries.

As far as I can tell the only downside to doing this is that slight
increase in the on-disk side of the system libraries and the minor cost
of the linker having to read this info.

### CODE REVIEW

**Comment by quantum5** [comment]
Nice! This stack traces better in sanitizers, although the tests assume you only get module offsets for `malloc`/`operator new`...

**Comment by kripken** [comment]
I think `-g` is enough (`-g4` at link time also means "source maps").

But this worries me - are we sure this does not affect optimizations in LLVM? How much larger does it make the libraries, and does the extra disk I/O affect build times?

For safety, I would lean towards *not* doing this, as if at any time in the future `-g` affects LLVM opts then it will be a silent perf pitfall which may go unnoticed. Instead, how about a developer option to do this, for local debugging purposes?

**Comment by sbc100** [comment]
You are right I think I only need `-g` (which means generate debug info in the object files).

I'm pretty sure `-g` is defined to not effect codegen.    `-O` is for codegen.    I could be wrong, but it seems to be that if it ever turns out that `-g` is effecting codegen we should fix that rather than avoid `-g`.

**Comment by sbc100** [comment]
I did some investigating. 

It looks like I was correct and `-g` only effects the debug info sections of an object file, not the code sections.

Add `-g` roughly doubles the on-disk side of the libraries.  For example the sum of all library variants goes from 30Mb or 55Mb on disk.   Taking just one example `libc.a` goes from 800k to 2100k.

**Comment by kripken** [comment]
Ah, interesting about the codegen.

The size difference looks big enough to me that I think this should be a default-off option. Emsdk downloads in particular will be larger.

I think an option that has a libc variant (which is now easy to add) would be best. Then if a user does actually need this, it's easily available.

**Comment by quantum5** [comment]
We need to be careful about adding a ton of libc variants, especially if we want to use them in the test suite. Every variant that needs to be used in a test slows down `build-upstream`.

**Comment by sbc100** [comment]
I don't think adding 25mb (uncompressed) to the size of the download is significant.    I imagine that the compressed size will represent a tiny fraction of the total download.   I'll do some measurements.    I also dont really like adding more variants

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

Re-opening and re-targeting to master.

**Comment by sbc100** [comment]
Dup of #13078

**Pull request closed without merging**
