### PR TITLE
Move test_exceptions_white_list_uncaught into tests/core.

### PR DESCRIPTION
**Pull request by sbc100**
I'm not sure why this was originally added under tests/third_party but
it looks like a mistake.

### CODE REVIEW

**Comment by aheejin** [comment]
It's because of @kripken's suggestion here: https://github.com/emscripten-core/emscripten/pull/10720#discussion_r394536667. But I also think that the program is so simple and I even modified it a bit to make it work with Emscripten, so it can be moved to test/core. WDYT @kripken?

**Comment by sbc100** [comment]
Ah.. I see...interesting.   I'm not sure it makes sense to have individual tests and expectations under third_party.

**Comment by kripken** [comment]
I'm fine either way. But I thought @sbc100 you were advocating for `tests/third_party` in general, which is why I put `coremark` under there? Are you saying that's just for entire projects but not individual files?

**Comment by sbc100** [comment]
I do want third party code in general to be in `third_party` but I would expect any of our test entry points or the `.out` files to live there.    I'm not sure this is a significant enough a piece of code to warrant this separation.

**Pull request merged**
