### PR TITLE
docs: html5.h.rst: id[128] changed to id[64]

### PR DESCRIPTION
**Pull request by Daksh2356**
This pull request makes the following changes:

- Fixes issue  #18817 

Checklist:
- [x]  I created a new branch from the correct branch and made my changes in the new branch created
- [x]  My pull request is sent to the correct base branch in the original emscripten-core/emscripten
- [x]  I have linked the issue I worked on to this pull request submitted by me
- [x]  File(s) or folder(s) now contain changes as specified in the issue i worked on
- [x]  I certify that I ran my checklist.

### CODE REVIEW

**Review by waywardmonkeys — CHANGES_REQUESTED** [review]
The mapping also needs fixing, no?

**Comment by Daksh2356** [comment]
> The mapping also needs fixing, no?

What do you mean by mapping ?  

I guess the bug was just in the id [128] and it needed correction .

**Comment by waywardmonkeys** [comment]
Look down at the next field being documented.

**Comment by Daksh2356** [comment]
> Look down at the next field being documented.

Are you saying that there is some error in the line 1671 here ->
Maximum size 128 ``char`` (i.e. ``EM_UTF8 mapping[128]``) 

The documentation lists both the id and mapping data separately.

**Review by sbc100 — APPROVED** [review]

**Comment by Daksh2356** [comment]
thank you @sbc100 for approving my PR.

Should the PR be closed now ??

**Comment by sbc100** [comment]
Actually it looks like @waywardmonkeys had come comments that still need addressing.  I'll defer to them.

**Comment by kripken** [comment]
@waywardmonkeys is correct, the `mapping` field below this should have 64 instead of both 128 numbers there:

https://github.com/emscripten-core/emscripten/blob/b9131b0ea4a99b6964caf7d9edf5d46f7007e3e9/system/include/emscripten/html5.h#L393-L394

https://github.com/emscripten-core/emscripten/blob/b9131b0ea4a99b6964caf7d9edf5d46f7007e3e9/system/include/emscripten/html5.h#L100

**Comment by Daksh2356** [comment]
> @waywardmonkeys is correct, the `mapping` field below this should have 64 instead of both 128 numbers there:
> 
> https://github.com/emscripten-core/emscripten/blob/b9131b0ea4a99b6964caf7d9edf5d46f7007e3e9/system/include/emscripten/html5.h#L393-L394
> 
> https://github.com/emscripten-core/emscripten/blob/b9131b0ea4a99b6964caf7d9edf5d46f7007e3e9/system/include/emscripten/html5.h#L100

Okay, I got the issue now  !!
I will correct it and commit the changes

**Comment by Daksh2356** [comment]
@sbc100 @kripken @waywardmonkeys Please review the latest changes

**Review by waywardmonkeys — APPROVED** [review]
LGTM. Thanks!

**Comment by Daksh2356** [comment]
> LGTM. Thanks!

Thank you for the approval @waywardmonkeys 💯🤝🏼

**Comment by Daksh2356** [comment]
Thank you for approving the pull request with all the changes at the end !!

**Pull request merged**
