### PR TITLE
Avoid a warning which turns into an error in sqlite.

### PR DESCRIPTION
**Pull request by kripken**
Should unbreak the llvm autoroller.

The warning is
```
/b/s/w/ir/tmp/t/tmprZfbf9/emscripten_test_wasm0_C0rW8g/src.c:82483:38: error: implicit conversion from 'long long' to 'double' changes value from 9223372036854775806 to 9223372036854775808 [-Werror,-Wimplicit-int-float-conversion]
  if( n==0 && r>=0 && r<LARGEST_INT64-1 ){
                       ~~~~~~~~~~~~~~^~
/b/s/w/ir/tmp/t/tmprZfbf9/emscripten_test_wasm0_C0rW8g/src.c:82485:46: error: implicit conversion from 'long long' to 'double' changes value from 9223372036854775806 to 9223372036854775808 [-Werror,-Wimplicit-int-float-conversion]
  }else if( n==0 && r<0 && (-r)<LARGEST_INT64-1 ){
                               ~~~~~~~~~~~~~~^~
`

### CODE REVIEW

**Comment by kripken** [comment]
Yeah, I'm not sure which is better of the options. Working around it in the code, or with a flag, seem equal to me. Happy to do whichever you want. But we should decide fast to unbreak the roller.

**Comment by tlively** [comment]
I lean toward using the flag.

**Comment by aheejin** [comment]
+1 using the flag. Can we use different flags for third party code?

**Comment by kripken** [comment]
Ok, done with the flag.

**Comment by kripken** [comment]
The CI here has older clang, so it warned about that flag... which errors :) I pushed another flag to ignore unknown flags. After the CI gets a newer LLVM we can remove it.

**Pull request merged**
