### PR TITLE
Remove ASMFS

### PR DESCRIPTION
**Pull request by sbc100**
This filesystem has not been maintained or tested in a long time and
the new wasmfs is far enough along I can't see us wanted to keep this
one around.

### CODE REVIEW

**Review by tlively — APPROVED** [review]
Would any of the deleted tests be useful to keep around?

**Comment by tlively** [comment]
Also, I'm not sure I would mark this NFC!

**Review by kripken — APPROVED** [review]

**Comment by sbc100** [comment]
> Also, I'm not sure I would mark this NFC!

Oops. I'm so used to do NFC changes my fingers now type it by default :)

**Comment by sbc100** [comment]
Will wait for @juj before landing..

**Comment by sbc100** [comment]
There was one test called 'asmfs/fopen_write.cpp' which was being used in test_other.py to test noderawfs... so I renamed and kept that one.    I don't see anything special about the 3 tests that did end up being deleted... they look like generic file tests to me and I think we have (or we should have) good filesystem API coverage elsewhere.

**Comment by sbc100** [comment]
@juj wdyt?  Is it time?

**Review by juj — APPROVED** [review]
Overall I am not sure what was the complexity that required dropping ASMFS support when adding WASI support, it was never stated in the original issue.

In other words, I never saw an issue about a breakage in ASMFS, but rather a mention that doing something with WASI was hard because ASMFS exists, so Alon called ASMFS unsupported in order to proceed(?)

Nevertheless, I do approve this change, as Alon's reasoning there is accurate that I would not have time to start refactoring ASMFS (for WASI compatibility?).

Hopefully WASMFS is shaping up well as a replacement!

**Comment by kripken** [comment]
> Overall I am not sure what was the complexity that required dropping ASMFS support when adding WASI support, it was never stated in the original issue.

IIRC the issue was that ASMFS implements musl syscalls (like `__syscall_open` etc.). The work on WASI replaced those syscalls with WASI ones. That meant that every implementer of the syscalls had to be rewritten, and so ASMFS basically doubled the work per syscall.

**Comment by sbc100** [comment]
> Overall I am not sure what was the complexity that required dropping ASMFS support when adding WASI support, it was never stated in the original issue.
> 
> In other words, I never saw an issue about a breakage in ASMFS, but rather a mention that doing something with WASI was hard because ASMFS exists, so Alon called ASMFS unsupported in order to proceed(?)
> 
> Nevertheless, I do approve this change, as Alon's reasoning there is accurate that I would not have time to start refactoring ASMFS (for WASI compatibility?).
> 
> Hopefully WASMFS is shaping up well as a replacement!

The motivation for this PR is simply that we now have WASMFS, and it is starting to mature, and IIRC the plan is that it will  completely replace ASMFS.   I'm happy to wait a bit longer before deleting ASMFS if you think there is value is keeping it around a little longer?  (but as far as I know there are no users).

**Comment by juj** [comment]
> I'm happy to wait a bit longer before deleting ASMFS if you think there is value is keeping it around a little longer?

No it's ok to remove this now.

**Pull request merged**
