### PR TITLE
Always add hash to object file names in emar

### PR DESCRIPTION
**Pull request by r0mai**
This fixes an issue where incremental builds can end up with
duplicated object files in static library archives
See: https://github.com/emscripten-core/emscripten/issues/9653

### CODE REVIEW

**Comment by sbc100** [comment]
@r0mai are you already in the AUTHORS file?

**Comment by sbc100** [comment]
If not can you add yourself?

**Comment by r0mai** [comment]
I'm in the AUTHORS already (as András Kucsma)

**Comment by r0mai** [comment]
Thanks @sbc100!

**Pull request merged**
