### PR TITLE
EM_ASM_STRING function series

### PR DESCRIPTION
**Pull request by newnon**
first step of EM_ASM_STRING functions

### CODE REVIEW

**Comment by kripken** [comment]
Nice, good start!

Next steps are to add documentation and tests. For docs see `site/source/docs/api_reference/emscripten.h.rst`. For tests, see `tests/test_core.py`, perhaps add a new test right after `test_em_asm_parameter_pack` (maybe calling it `test_em_asm_string`?).

**Comment by juj** [comment]
Interesting idea, however how does this manage memory allocation so that it doesn't leak? I don't see there being a good place to put the call to freeing memory. It would be good to have an API that has an explicitly visible memory allocation, and name it in a way that developers will know by static reading that there is an allocation involved that one will need to manually clean up. (I think that's the case here?)

**Comment by newnon** [comment]
I think that function name EM_ASM_STRING_MALLOC tells you about memory allocation, and second just repeat logic of emscripten_run_script_string

**Comment by kripken** [comment]
I agree, the name having `MALLOC` is pretty clear. We should also document it carefully too of course.

**Comment by kripken** [comment]
This PR is quite old, closing. Feel free to reopen if still relevant.

**Pull request closed without merging**
