### PR TITLE
Parameterize test_webgl_timer_query. NFC

### PR DESCRIPTION
**Pull request by sbc100**
Also, convert it from C++ to C.

### CODE REVIEW

**Review by kripken — APPROVED** [review]
I don't mind more C vs C++, but I'm curious why do you prefer C?

**Comment by sbc100** [comment]
With test code, the more precise and low level the test can be the better.   I want to include the minimum amount of code needed to support the test itself, without extra baggage.

This is why, for example, I prefer to test using `pthread` API directly rather then C++ threads.   

If you tried debugging a program that does `puts('"hello")` vs `cout << "hello\n";` you know how much baggage pulling in C++ stuff can something bring.

Even though this test doesn't use `cout`, converting to C is a good way to keep tests simple and targeted and without baggage.. IMHO.

**Comment by sbc100** [comment]
Also, it can sometimes make the test more readable.. as in this case were we can remove an cast :)

**Comment by kripken** [comment]
Fair enough. I definitely agree `std::cout <<` brings in a lot of noise. But in C++ you can still use `printf` and usually I think it's easier to use C++ with that style (e.g. no `struct` before declarations like C requires). But, yeah, generally C is simpler I guess.

**Pull request merged**
