### PR TITLE
Update Emscripten.cmake to support C++17

### PR DESCRIPTION
**Pull request by InBetweenNames**
This simple one-line change allows the following CMake directive to work for enabling C++17 support:
~~~
set(CMAKE_CXX17_COMPILE_FEATURES "cxx_std_17")
~~~
Tested both sdk-incoming-64bit and sdk-wasm-master-64bit.
Modified line was pulled from a known working generated `CMakeCXXCompiler.cmake` by CMake (version `3.13.4`)

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

I don't know much about cmake, but this looks right to me. @juj?

@InBetweenNames, please add yourself to AUTHORS

**Comment by juj** [comment]
The items there were added to speed up CMake on Emscripten - i.e. while CMake could dynamically test the different features, prepopulating them was done so that it would be able to see the results cached, and didn't need to run any tests.

Because we are "prewarming" a cache (of known results) into the repository directly, we have a test that runs the check without the cache, and with the cache, and then verifies that the prepopulated entries are correct. Adding a new prepopulated fields requires that we add that field onto the list of tested prepopulated fields.

In order to do this, see the file tests/cmake/stdproperty/CMakeLists.txt. That file needs a new line for CXX17. I think after that, the test `python tests/runner.py other.test_cmake_compile_features` should then include the new field into its test harness.

**Comment by InBetweenNames** [comment]
I added the new line for C++17 in stdproperty/CMakeLists.txt and it appears the test fails.  Oddly enough, when I run the individual cmake directives myself, the C++17 support is clearly listed.  However, when running it through the test runner, it seems that C++17 support isn't being detected via CMake.  Any ideas on what's going on here?

**Comment by juj** [comment]
Try adding `message(STATUS "${CMAKE_CXX17_COMPILE_FEATURES}")` kind of debug checks to see what might be the difference. Also double check that you are really invoking CMake locally exactly the way emcc does. In particular, check that the environment variables are the same (see `def get_building_env` in `tools/shared.py`)

**Comment by InBetweenNames** [comment]
Actually, upon further investigation, I can't even get this test to pass under `incoming` without my patch.  Does it work on your systems?

**Comment by juj** [comment]
The test does pass for me on Windows and macOS. Also on the CI it does currently look green. Is there some specific discrepancy that the test is showing on your system? What do the error logs say?

**Comment by InBetweenNames** [comment]
Found the problem -- it was something in my Gentoo environment interfering with it.  Seems to be working fine now.  Curiously, `test-upstream-browser-chrome` failed on CircleCI, but it doesn't appear to be a failure related to this patch.

**Comment by juj** [comment]
Looks perfect, thanks!

**Pull request merged**
