### PR TITLE
Update actions to version 3

### PR DESCRIPTION
**Pull request by rettinghaus**
This small PR bump the used actions to the latest major version. 
No changes in behavior expected.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

Looks like there is a CI error though.

**Comment by rettinghaus** [comment]
Yes, that's an error from CircleCI, which I didn't touch. The archive workflow went green.

**Comment by kripken** [comment]
It would still be good to see tests pass here, just to be safe (though as you said, it should not be related in any way). I think if you logout from circleCI as the error message says, it might just work.

**Comment by sbc100** [comment]
I think its pretty safe to just merge this and ignore the circleci issues (which seem completely unrelated).

**Comment by kripken** [comment]
Ok, sounds good, merging.

**Pull request merged**
