### PR TITLE
Update discord link - these links expire after a certain number of uses, sadly

### PR DESCRIPTION
**Pull request by kripken**
I made this one the longest-lasting I could, which is 100 uses and no
time expiry.

### CODE REVIEW

**Comment by sbc100** [comment]
Ooo gross.  I guess we should do with a some other service in the long run :(

**Comment by kripken** [comment]
Yeah, I hope we can switch away too. Hopefully someone has time to look into it.

**Comment by kripken** [comment]
@aheejin and @tlively showed me how to remove that limit. So this link will maybe never expire..?

**Comment by kripken** [comment]
I added some text to say we would appreciate help here. Thoughts?

**Comment by kripken** [comment]
Landing as we are getting more reports of this being a problem. But @sbc100 when you get a chance PTAL at the new wording I added.

**Comment by Gideon357** [comment]
@kripken here is an unlimited link https://discord.gg/TeZUsJX

**Comment by Gideon357** [comment]
If you select No Limit and Never Expire, you're fine.

**Comment by kripken** [comment]
@Gideon357 the current link should be unlimited, see https://github.com/emscripten-core/emscripten/pull/10532#issuecomment-589874483 - is there a problem with it?

**Pull request merged**
