### PR TITLE
Remove setImmediate

### LINKED ISSUE #12568: Emscripten glue code fails in strict mode with MAIN_MODULE
Here’s a [small repro case](https://gist.github.com/surma/3010d6ddce7435783821c87bc5409342) that you can just build with `make all`. 

If you comment out the [monkey-patched `setImmediate` global in `index.html`](https://gist.github.com/surma/3010d6ddce7435783821c87bc5409342#file-worker-js-L4), the code fails to run.

```
ReferenceError: setImmediate is not defined
    at main.js:formatted:29783
    at main ((index):7)
    at (index):14
```

### PR DESCRIPTION
**Pull request by kripken**
https://caniuse.com/?search=setImmediate - `setImmediate` is only present in IE11
and older, so it's not worth having special support for, given it's just an optimization
really. Instead, "polyfill" it when `setTimeout(0)` where relevant.

This may be slightly slower on IE11 for users that were using `setImmediate`. However,
it would be more consistent between browsers, which seems more important today.

There should be no observable difference on modern browsers.

The APIs have not been removed, so nothing should break (as mentioned earlier,
we use `setTimeout` instead).

Fixes #12568 (another possible fix could have been to add a closure exception,
but this seems better)

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]
nice!

**Comment by juj** [comment]
`setTimeout(func, 0);` is dramatically inferior to `postMessage(, "*")`. Whereas the former can reach about 250fps max (setTimeouts are throttled to 4ms min delay), postMessages can reach 20000fps or more. For saturating a performance profile with content, this is super useful.

**Comment by kripken** [comment]
@juj What's an actual use case for that style of postMessage? Do you think we still need it?

**Comment by surma** [comment]
@juj has a point. `setImmediate()` is used to schedule a task. Often people use `setTimeout()` as a replacement without knowing that it gets clamped to 4ms minimum. So if we used `setImmediate()` in any hot-paths, replacing it with `setTimeout()` could make things slower. `postMessage()`’ing through a `MessagePort` can be a “better” replacement for `setImmediate()`.

<details>
<summary>Example implementation of <code>setImmediate</code> using <code>postMessage</code>:</summary>

```js
const mc = new MessageChannel();
function setImmediatePolyfill(cb) {
	mc.port1.postMessage(null);
	mc.port2.start();
	mc.port2.addEventListener("message', () => cb(), {once: true});
}
```

</details>

**Comment by kripken** [comment]
@juj @surma I'm still unsure what the use case is for getting more events than `setTimeout` can generate, in an emscripten program. Is it benchmarking the browser's event queue or something like that?

Anyhow, sounds like this PR is not the right approach.

I can try to write a replacement with MessagePort, but would that not have some of the same problems? (is it guaranteed to be as fast as setImmediate, and is it supported in older browsers)

**Comment by brion** [comment]
IIRC MessagePort's `postMessage` is not throttled like timeouts are, and are safe to use in background situations. Note that the 4ms clamp is **not** the only thing to worry about -- if a tab is in the background, timers can be delayed by up to 1000ms, which is fine if they drive something that's not important but *very bad* if they're driving an audio decoder, or some other thing that needs to run ongoing even if the window doesn't have front focus.

I've used `window.postMessage`/`onmessage` to implement this pattern when I wanted to run callbacks after an audio-related call without having the callbacks run during my Web Audio-specific hotpath; this should be effectively the same thing as using a MessageChannel, except sloppier because other objects could catch my calls while a dedicated MessageChannel would not have that risk. :)

Seems to be pretty consistently supported: https://caniuse.com/?search=messagechannel

**Comment by kripken** [comment]
Meanwhile I see that the current code does basically what you say @brion  with `postMessage`:

https://github.com/emscripten-core/emscripten/blob/b7267b58da559aadd9670237ec7f2626bfed1108/src/library_html5.js#L2686-L2696

So that is correct I guess, and the only problem is the writing to a global variable due to strict mode. If so then we don't need this PR, and can continue discussion in the original issue.

**Pull request closed without merging**
