### PR TITLE
Added tests for former PR aliasing uuid_generate_random as uuid_gener…

### LINKED ISSUE #12093: uuid_generate_random from uuid/uuid.h seems unsupported
This makes fontconfig compilation fail and was also noted in https://github.com/dotnet/corert/pull/4624

Maybe an unsecure hack (behind an emcc option?) aliasing uuid_generate as uuid_generate_random could be provided?

### PR DESCRIPTION
**Pull request by sabtt17**
…ate - fixes #12093

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]
Nice!  lgtm

**Comment by kripken** [comment]
I think the build errors here are because of a temporary unrelated problem. Merging in latest `main` to here should fix things.

**Comment by kripken** [comment]
I re-ran tests here but they still fail, oddly... now on harfbuzz. I think maybe this PR was just very unlucky to get failing runs at the wrong times.

Sadly there is no way for me to merge in latest `main` to here (I wish github had that option...) so you will need to do it again.

**Comment by sabtt17** [comment]
Trying once more

**Comment by kripken** [comment]
Tests still fail here, so I tried this patch locally - and I see the same failure, running `./embuilder build harfbuzz` as the linux bot fails on. So this change somehow breaks the harfbuzz build system it seems.

The CMake log says:
```
error: Function uuid_generate_random aliases to target function uuid_generate, but neither the alias or the target provide a signature. Please add a uuid_generate__sig: 'vifj...' annotation or a uuid_generate_random__sig: 'vifj...' annotation to describe the type of function forwarding that is needed!
Internal compiler error in src/compiler.js!
```
So I think this can be fixed by adding a signature annotation, like this:
```diff
diff --git a/src/library_uuid.js b/src/library_uuid.js
index dd392672a..e1e148155 100644
--- a/src/library_uuid.js
+++ b/src/library_uuid.js
@@ -31,6 +31,7 @@ mergeInto(LibraryManager.library, {
   // Write a RFC4122 version 4 compliant UUID largely based on the method found in
   // http://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid-in-javascript
   // tweaked slightly in order to use the 'compact' UUID form used by libuuid.
+  uuid_generate__sig: 'vi',
   uuid_generate: function(out) {
     // void uuid_generate(uuid_t out);
     var uuid = null;
```

**Comment by sabtt17** [comment]
I'm having issues running `./embuilder build harfbuzz` locally.  I'm getting a Permission Denied error on cmake. Do you know what could be causing this? I can also push the change you suggested, but because of this error I haven't been able to make sure the change fixes the problem.

**Comment by sbc100** [comment]
> I'm having issues running `./embuilder build harfbuzz` locally. I'm getting a Permission Denied error on cmake. Do you know what could be causing this? I can also push the change you suggested, but because of this error I haven't been able to make sure the change fixes the problem.

Can you post the full output of the command?

**Comment by sabtt17** [comment]
> > I'm having issues running `./embuilder build harfbuzz` locally. I'm getting a Permission Denied error on cmake. Do you know what could be causing this? I can also push the change you suggested, but because of this error I haven't been able to make sure the change fixes the problem.
> 
> Can you post the full output of the command?

Screen Shot 2021-04-26 at 8 33 51 PM

**Comment by kripken** [comment]
@sabtt17 From the error I think maybe `cmake` is not installed properly locally, unrelated to emscripten? Does `cmake --help` work?

In any case I did verify that change works locally, so I think pushing it and seeing CI is green would be enough.

**Pull request closed without merging**
