### PR TITLE
Put all EM_JS/EM_ASM strings in a specific data section

### LINKED ISSUE #9366: Why are JavaScript inline snippets embedded in wasm data?
I hope it's okay to ask a question here

As a test I put some JavaScript inline in C++ using the EM_ASM_ macro

```
#include <emscripten.h>

extern "C" {
  extern void x2(float v) {
    float t = v * 2.0f;
    EM_ASM_({
      foo($0, "supercalif");
    }, t);
  }
}
```

I then compiled with

```
emcc -O3 -s EXPORTED_FUNCTIONS='["_x2"]' -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]'  -o foo.html foo.cc
```

Like I expected the JavaScript is put in the support .js file (foo.js in this case)

```
var ASM_CONSTS=[function($0){foo($0,"supercalif")}];
function _emscripten_asm_const_id(code,a0){
  return ASM_CONSTS[code](a0)
}
```

And disassembling the wasm I see the call to that JavaScript (recompiled with -g3 for the snippet below for the variable names but verified the same code is in the normal version just with short names)

```
  (func $legalstub$_x2 (export "_x2") (type $t7) (param $p0 f64)
    (drop
      (call $_emscripten_asm_const_id
        (i32.const 0)
        (f64.promote_f32
          (f32.mul
            (f32.demote_f64
              (local.get $p0))
            (f32.const 0x1p+1 (;=2;)))))))
```

But I also see the string of the JavaScript embedded in the wasm as well

```
  (data $d0 (i32.const 1024) "{ foo($0, \22supercalif\22); }"))
```

What is that string for given the JavaScript itself is already in the .js file?

### PR DESCRIPTION
**Pull request by sbc100**
This way, once binaryen has extracted that string data
it can potentially remove the segment or at least zero it
out.

Fixes #9366

### CODE REVIEW

**Comment by kripken** [comment]
Is it worth working on an EM_JS-specific solution? That is, is there no solution for EM_JS and EM_ASM?

**Comment by sbc100** [comment]
> Is it worth working on an EM_JS-specific solution? That is, is there no solution for EM_JS and EM_ASM?

Sure, I'm just doing it one step at a time.   EM_JS is actually quite different to EM_ASM in that the strings don't actually need to have addresses in LLVM sense... so the solution we end up with might look different.

But also I do think and EM_JS-only solution is better than nothing.

**Comment by sbc100** [comment]
This part of the change is really a no-brainer (IMHO).  It doesn't actually do anything except group the EM_JS strings into a single data section.     Even if we never get around to actually purging it on the binaryen side (which I totally think we will) I still think its good for debugging / understandably.

**Comment by sbc100** [comment]
Updated the comment to include plans to further investigate the EM_ASM situation.

**Review by kripken — APPROVED** [review]
Makes sense, sounds great.

**Pull request merged**
