### PR TITLE
Added some missing signatures related to #14405

### PR DESCRIPTION
**Pull request by goldwaving**

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by kripken** [comment]
This looks good @goldwaving , please just add yourself to AUTHORS before we merge, as the bot mentioned.

**Comment by goldwaving** [comment]
Added to AUTHORS.

**Comment by kripken** [comment]
I don't see an update here @goldwaving - maybe you need to push to the branch?

**Comment by kripken** [comment]
Oh, I see now, you opened another PR. Sorry, been a very busy day and I missed that earlier...

**Pull request merged**
