### PR TITLE
[RFC] FFmpeg test

### PR DESCRIPTION
**Pull request by jakogut**
This PR adds sources for FFmpeg 4.2, as well as a runner method for building FFmpeg libs, and a test for building and running the `ffmpeg` binary itself.

FFmpeg is an interesting test case, as it is a large C code base that optionally utilizes SDL2, networking, threading, and has many opportunities for benefiting from SIMD instructions. It also has a built-in option for benchmarking codecs, which should be an interesting indicator of WASM vs. native performance.

More information about benchmarking can be found here: https://trac.ffmpeg.org/wiki/Null

One thing to note with this PR is that `ffmpeg` the program includes `config.h` generated by the configure step, and that header is no longer available during the test. Several other configure generated headers such as `libavutil/ffversion.h` and `libavutil/avconfig.h` are also unavailable. These have been copied into the `tests/ffmpeg` directory to make the build work, but a cleaner solution would be preferable.

### CODE REVIEW

**Comment by sbc100** [comment]
I'm not a huge fan checking in another entire codebase like this.  Are there many modifications to the upstream?  Could we use a git submodule here instead perhaps?

**Comment by jakogut** [comment]
> I'm not a huge fan checking in another entire codebase like this. Are there many modifications to the upstream? Could we use a git submodule here instead perhaps?

I completely agree, I assumed that the existing copies of other codebases were added for a reason, and took the same approach. There are no modifications to the source code, just copies of the headers generated during the config process.

We could use a submodule, or we could download a release tarball.

**Comment by sbc100** [comment]
Either one sounds good.   Happy to have the config headers checked in.

**Comment by sbc100** [comment]
Regarding the existing checked in sub-projects, I don' think they are great either, but I'd rather not make the situation worse in this respect.  Sorry for the mixed message that that sends.

**Comment by jakogut** [comment]
> Regarding the existing checked in sub-projects, I don' think they are great either, but I'd rather not make the situation worse in this respect. Sorry for the mixed message that that sends.

No problem, I was actually thinking about how to address this problem, but I wanted confirmation before submitting any changes.

**Comment by dschuff** [comment]
Is this the sort of thing that https://github.com/emscripten-ports is for?

**Comment by dschuff** [comment]
Also, the wasm CG is looking for good wasm benchmarks (see https://github.com/WebAssembly/benchmarks/blob/master/Overview.md). Could this be a candidate?

**Comment by sbc100** [comment]
This is bit different emscripten-ports.   emscripten-ports are generally things that developers are free to use as part of their projects via flags like `-s USE_SDL2`.   There are other projects, like this one, that are only used in testing.   For example there is an entire copy of box2d in the tests directory.

I'm not a huge fan of the current way either these mechanisms work.

**Comment by quantum5** [comment]
I don't think checking in 1.7 million lines is a great idea... There has to be another way.

**Comment by jakogut** [comment]
> This is bit different emscripten-ports. emscripten-ports are generally things that developers are free to use as part of their projects via flags like `-s USE_SDL2`. There are other projects, like this one, that are only used in testing. For example there is an entire copy of box2d in the tests directory.

It seems to me that there are a couple of things to distinguish here. There is the emscripten-ports organization (https://github.com/emscripten-ports) that maintains modified projects that work with Emscripten, and there's the ports system in the emscripten-core repo that handles downloading, caching, extracting and building projects from source tarballs. Indeed, some projects such as bzip2 and harfbuzz aren't even modified and use upstream sources, just like this FFmpeg test.

It seems the `get_*_library` functions in the test suite duplicate the work of the ports system, as well as the codebases they use. I do greatly prefer the ports approach over maintaining a source copy in the tests directory, as well as a similar but separate build process. It seems a bit inconsistent, where's `TestCoreBase.get_sdl2_library()`? It's not needed, because SDL2 is provided as a port.

Looking at the history, it seems the `get_bullet_library` function was introduced in commit b5bb92c in 2013. It was added as a port in commit 0ca0da7 in 2015, so maybe these library functions are obsolete, and could be replaced using the ports system? Even if they're not libraries we'd like to support for users, the build system still does the job. We could flag them to make them unavailable outside of tests.

Using the ports system would also make it possible to retain access to the configuration headers ffmpeg needs to be built.

**Comment by sbc100** [comment]
The reason I don't love the idea of adding this to the ports list is that then we have to maintain support for it.   This is because emscripten users will be able to access it and start depending on it.    I'd rather keep things that are just used for testing outside of the ports system.

At the same time I don't want to invent yes another way to do things.  

I see a few options:
1) Write your own code to fetch the tarball on demand
2) Use a sub-submodule
3) Allow for private/test-only ports and use the ports system

I kind of like (2), but any of these seem reasonable.  Any other options?

**Comment by kripken** [comment]
I definitely agree with the value of testing a large and important real-world codebase.

It sounds like there are no actual changes to ffmpeg, though, so I don't think we need a repo in emscripten-ports - generally we only add those so we can make local changes. Otherwise the repo url can be the normal upstream one. So it's added to ports normally, in `tools/ports/`, just the url part is different from most of the others.

And then we could add a test to `other`, which I assume we'd want to have disabled by default, so it could be run only when explicitly desired? Not sure we have an option for that, might need to add one.

@sbc100 I agree it might be nice to avoid `USE_FFMPEG` etc. for each new port. Not sure I have a good idea. Maybe it could be `USE_PORTS=[]` so it's just one option? No strong feelings either way. Can also discuss this separately.

**Comment by dschuff** [comment]
IMO we shouldn't have `-s USE_PORT` for any port, even core builtin ones. Is there any reason we can't just put `libport.a` in the sysroot and use `-lport`?

**Comment by sbc100** [comment]
@dschuff  I agree that would be better.   The way emscripten is currently setup we need some way to trigger the building of the port.  If we want to keep that method I think we could do something like "--ports=foo,bar,baz". 

If we are OK with running embuilder to build and install ports then we could just install them in the sysroot as you say.    Perhaps its time to stop adding more link-time on-demand ports and instead ask users run embuilder?

**Comment by dschuff** [comment]
Yeah, this discussion is now beyond the scope of this PR and I noticed you just filed #9353, let's continue it there.

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

Re-opening and re-targeting to master.

**Pull request closed without merging**
