### PR TITLE
Added `qsort_s` and `qsort_r` to standard library (fixes #5423)

### LINKED ISSUE #5423: `qsort_s` not implemented in standard library
I was attempting to build [libgit2](//github.com/libgit2/libgit2) using Emscripten, and the compilation always fails with this error:

```
.../libgit2/src/util.c:656:2: error: implicit declaration of function 'qsort_s' is
      invalid in C99 [-Werror,-Wimplicit-function-declaration]
        qsort_s(els, nel, elsize, git__qsort_r_glue_cmp, &glue);
```

`qsort_s` (apparently also called `qsort_r`) is a variant of `qsort` ([Quicksort](https://en.wikipedia.org/wiki/Quicksort)) which takes an additional `void *` which is forwarded to the sorting function to store context. On most systems it's part of libc and declared in `stdlib.h`. Not so in Emscripten.

The function needs to be added to Emscripten's libc and standard headers so that code which uses it can compile.

### PR DESCRIPTION
**Pull request by bbessemer**
I added `qsort_s` to the standard library. It's identical to `qsort` except it maintains an additional parameter `void *ctx` which it passes to the compare function. `qsort_r` is currently an alias for `qsort_s`. The new functionality has been tested by a new test called `test_stdlib_qsort` with code in `tests/stdlib/test_qsort.cpp`.

This should be a very simple PR except that my editor automatically trimmed trailing spaces in `test_core.py`—sorry about that.

### CODE REVIEW

**Comment by kripken** [comment]
Is `qsort_s` from a newer version of musl?

**Comment by bbessemer** [comment]
It's not currently in the musl tree. This is "original" code, although 95+% of it is copied from musl's existing implementation of plain old `qsort`.

From what research I've done this function is notoriously unportable—glibc's version is called [`qsort_r`](https://linux.die.net/man/3/qsort_r) with this signature:

```c
void qsort_r(void *base, size_t nmemb, size_t size,
           int (*compar)(const void *, const void *, void *),
           void *arg);
```

µClibc also has it with this exact signature.

Meanwhile macOS's version is also named `qsort_r`, but reverses the last two arguments; my `<stdlib.h>` (on macOS 10.12) has (arguments renamed for readability):

```c
void     qsort_r(void *base, size_t nel, size_t width, void *context,
        int (* compar)(void *, const void *, const void *));
```

Microsoft calls it [`qsort_s`](https://msdn.microsoft.com/en-us/library/4xc60xas.aspx), with the same arguments as the GNU version:

```c
void qsort_s(  
   void *base,  
   size_t num,  
   size_t width,  
   int (__cdecl *compare )(void *, const void *, const void *),  
   void * context  
); 
```

The build that led me to discover this bug actually checks for the appropriate name and signature of `qsort_*` and then uses the appropriate one via preprocessor macros. Building with Emscripten, it reports that neither is found, but attempts to use `qsort_s` anyway; I'm not sure why. Regardless, some version of this function exists in every major libc implementation I could think of *except* musl, and it definitely seems there's code in the wild expecting it.

I implemented the function as `qsort_s`, with the Microsoft/GNU argument order, and `#define`d `qsort_r` as `qsort_s`. In hindsight, it would probably have been better to name it `qsort_r` and have the define the other way around, but this should work with code expecting any version of `qsort_*` except Apple's. For example, libgit2, which is the original thing I was trying to build, now builds successfully with this patch.

**Comment by kripken** [comment]
I see, thanks for the explanation. In that case, I think the best thing is to work with musl on this - perhaps they would like to add this function, so it would be good to contribute it to them (and then get it here from upstream). Or, perhaps they have a reason for not adding that function, which it would be good to know.

**Comment by juj** [comment]
> qsort_s (apparently also called qsort_r) is a variant of qsort (Quicksort) which takes an additional void * which is forwarded to the sorting function to store context. On most systems it's part of libc and declared in stdlib.h. Not so in Emscripten.
> 
> The function needs to be added to Emscripten's libc and standard headers so that code which uses it can compile.

What needs to be done is to research which standard specifications these functions conform to, and introduce support by following those standards accordingly.

Searching the web, the situation looks like follows:
 - [qsort_r](https://linux.die.net/man/3/qsort_r): is a non-standard GNU libc extension, introduced in glibc in version 2.8, and available under `#define _GNU_SOURCE` (see https://stackoverflow.com/a/5583764).
 - [qsort_s](http://en.cppreference.com/w/c/algorithm/qsort): Introduced in the C11 standard (ISO/IEC 9899:2011), part of `annex K.3.6.3.2: The qsort_s function (p: 609)`.

One can't just go and arbitrarily add function declarations to `stdlib.h` to refer to these functions, but they need to be approached appropriately with respect to the governing specifications, so that they are placed in correct locations, and included when building applications with the right standards enabled.

Starting with the the C11 standard function `qsort_s`: reading at http://wiki.musl-libc.org/wiki/Open_Issues mentions

```
"Full C11 coverage was added in musl 1.1.5; the main addition was the C11 threads API. The optional (and controversial) Annex K is not included. The current plan is to hold off on taking any action towards supporting Annex K unless/until other implementations adopt it and applications are using it."
```

[Wikipedia](https://en.wikipedia.org/wiki/C11_(C_standard_revision)#Criticism) has some info about what the controversy there refers to. This is why `qsort_s` is not included in the current latest upstream version of [musl 1.1.16](https://git.musl-libc.org/cgit/musl/tree/src/stdlib).

We probably do not care much at all about these kind of controversies, but would be happy to add that function. However because it is not part of upstream musl, the file cannot be added in ` system/lib/libc/musl/src/stdlib/qsort_s.c`, because that would introduce difficulties with following upstream musl. Instead, the file `qsort_s.c` should go to this directory https://github.com/kripken/emscripten/tree/incoming/system/lib/libc/musl/src/compat-emscripten, where we add different functions that are not part of musl itself.

The case of `qsort_r` is very similar. The implementation should go in the `compat-emscripten` directory, and the function declaration should be gated on `#ifdef _GNU_SOURCE` in `stdlib.h`. Both function declarations should go at the very end, with an `/* XXX Emscripten XXX */` comment block added to them.

This way the next person who works on upgrading musl to a newer upstream version will have an easy time to pick up these localmods to the build, and our codebase does not become an arbitrary fork of musl.

If you are still interested in working on adding these in, we could definitely put them in, if the above considerations are accounted for. Although it may be better to work `libgit` itself to use portable APIs instead.

**Comment by tiennou** [comment]
> but this should work with code expecting any version of qsort_* except Apple's. For example, libgit2, which is the original thing I was trying to build, now builds successfully with this patch.

I'm currently researching that exact issue in libgit2 (our macOS build is not actually using qsort_r). Just wanted to point out that `qsort_r` originated in [FreeBSD](http://bxr.su/search?q=qsort_r&defs=&refs=&path=&project=DragonFly&project=FreeBSD&project=NetBSD&project=OpenBSD), so it's not limited to Apple platform (DragonFly has it it virtue of being a fork). glibc implemented it a few years later with a different ordering.

**Comment by ztane** [comment]
Just to note to anyone reading this: unlike @bbessemer claimed, GNU and Microsoft versions are **not** compatible, and Microsoft's version does *not* match the C11 Annex. Of the 4 existing definitions (Gnu, BSD, Microsoft, C11 Annex) **none** are mutually compatible, other than GNU `qsort_r` has compatible prototype with `qsort_s` of the C11 Annex.

**Pull request closed without merging**
