### PR TITLE
Add comment about firefox pinning

### PR DESCRIPTION
**Pull request by sbc100**
See #14401
See #14392

### CODE REVIEW

**Review by kripken — APPROVED** [review]

**Comment by sbc100** [comment]
We still need to open a FF bug here.. but I feel like some minimal investigation should really be done first..

**Comment by kripken** [comment]
I'm not sure how. We've tried to reproduce locally. It has to be something very specific about how CI runs. Like some interaction with FF and the X server setup there. Or maybe the amount of memory.

We can try those some more, but I wonder if the FF side may have ideas. For example maybe there is a bisection tool we could use to download FF builds (there is [mozregression](https://mozilla.github.io/mozregression/quickstart.html), but I'm not sure how to download the builds separately from it).

**Comment by sbc100** [comment]
Can you not repo locally at all?  Have you tried with the same dummy xserver locally?   I'm not even sure if there is a pattern to which test cause fail.. because i didn't really look into it :-/

**Comment by kripken** [comment]
Looking at the last few dozen landings on `main`, I do not think the pinning actually helped. I still see 80% of firefox runs fail. So this might not be a firefox regression.

I'll do some more investigation.

**Pull request merged**
