### PR TITLE
Drop support for targeting IE using -sMIN_IE_VESRION

### PR DESCRIPTION
**Pull request by sbc100**
Followup to #20881 which removed support for EdgeHTML

### CODE REVIEW

**Comment by sbc100** [comment]
Marking this one as draft since it less likely that just using `-sLEGACY_VM_SUPPORT` would work here..

**Comment by sbc100** [comment]
@juj @kripken @RReverser @dschuff WDYT?

**Comment by RReverser** [comment]
Personally I'd go for this. If someone still targets IE for whatever reason, they are very unlikely to use Wasm projects IMO (even Wasm2JS), and likely already include tons of general polyfills, but I'll defer the decision to others.

**Review by juj — APPROVED** [review]
I thought retaining support for EdgeHTML would have been more important than the old IE.

I'm fully ok with dropping both forms of IEs. For us they are indeed long in the past.

**Comment by sbc100** [comment]
Awesome!

**Pull request merged**
