### PR TITLE
Remove obsolete usages of EM_ASM_ARGS, EM_ASM_, EM_ASM_INT_V, EM_ASM_…

### PR DESCRIPTION
**Pull request by waywardmonkeys**
…DOUBLE_V.

### CODE REVIEW

**Comment by sbc100** [comment]
@kripken what do you think?  OK to remove these now?

**Comment by kripken** [comment]
At minimum we should mention this on the changelog.

Could we make the header do an `#error` with a clear message if these are used, pointing to the preferred function, or something like that?

**Comment by waywardmonkeys** [comment]
This is only removing usages, not definitions... There's nothing to put in the changelog here?

**Comment by sbc100** [comment]
Oh sorry, I miss-read.  Seems fine then.

**Comment by kripken** [comment]
I see, sorry for misreading before.

Still, I think we should keep testing code until we actually remove it?

**Comment by sbc100** [comment]
Ok sounds reasonable, lets remove the uses in the same PR that removes the macros themselves.

**Comment by waywardmonkeys** [comment]
I have updated this to remove things and update the ChangeLog, as requested so long ago.

**Comment by kripken** [comment]
Looks like the build fails here due to SDL2 using the older variants. We'll need to update [SDL2](https://github.com/emscripten-ports/SDL2) and then update the port version here before this can pass.

**Pull request closed without merging**
