### PR TITLE
Remove specialized asan implementation of libc functions. NFC

### PR DESCRIPTION
**Pull request by sbc100**
Since we found a bug in `emscripten_asan_memchr.c` it seems much better to
share the implementation and just avoid the clever hacks when building in
asan mode.

Fixes: #14605

### CODE REVIEW

**Review by tlively — APPROVED** [review]
Neat! This is much simpler. Do we not need to add `no_sanitize("address")` to more functions because they don't contain UB and therefore can't cause problems?

**Comment by sbc100** [comment]
> Neat! This is much simpler. Do we not need to add `no_sanitize("address")` to more functions because they don't contain UB and therefore can't cause problems?

For 4 or the 5 functions all the UB was behind the `ifdef __GNU__` macro, so we don't need to make the whole function as `no_sanitize`, we just don't compile in that bad code.

Marking entire functions (especially these core ones) as `no_sanitize` is a bad idea because it will mean that bug in the callers of `strcpy` etc are not found by asan, resulting is loosing some coverage.    Basically whenever we mark a function as `no_sanitize` it means we have less coverage.

**Comment by tlively** [comment]
Makes sense. Does that mean that this patch reduces reduces ASan's power to catch issues with fcntl?

**Review by kripken — APPROVED** [review]

**Review by RReverser — APPROVED** [review]

**Comment by sbc100** [comment]
> Makes sense. Does that mean that this patch reduces reduces ASan's power to catch issues with fcntl?

No, fcntl was already being built with `no_sanitize`.. this patch doesn't change that.

**Comment by sbc100** [comment]
> > Makes sense. Does that mean that this patch reduces reduces ASan's power to catch issues with fcntl?
> 
> No, fcntl was already being built with `no_sanitize`.. this patch doesn't change that.

Previous/existing fcntl:

https://github.com/emscripten-core/emscripten/blob/b87d8a466934ed5626c29124fea55829776cf232/system/lib/libc/emscripten_asan_fcntl.c#L2-L8

**Comment by RReverser** [comment]
Off-topic, but I have to ask: what does NFC mean in PR titles? I thought it was one of "non-functional change" or "not for comments" or "not for CI", but looking at this PR, neither seems to fit 😅

**Comment by sbc100** [comment]
Comes from the llvm world.. means "Non-functional change"

**Comment by sbc100** [comment]
Maybe its not completely accurate for this PR :-/

**Comment by RReverser** [comment]
> 
> 
> Maybe its not completely accurate for this PR :-/

Yeah that's what confused me 😅

**Comment by sbc100** [comment]
IIRC my thinking when I wrote the PR title is that this is its kind of an internal detail (to use a single shared implementation here).  In theory it should not be observable.   Of course, it just a happens to fix any bugs that existed the second implementation because we not longer using it :)

**Pull request merged**
