### PR TITLE
Add support for visualizers to CyberDWARF

### PR DESCRIPTION
**Pull request by hackcasual**
Add support for dumping arrays
Add support for metadata intrinsics

### CODE REVIEW

**Comment by hackcasual** [comment]
Depends on https://github.com/kripken/emscripten-fastcomp/pull/141

**Comment by kripken** [comment]
Looks good.

**Comment by hackcasual** [comment]
Updated to add an automatic collector for variable information. Wait on documentation updates before merging.

**Comment by kripken** [comment]
This PR is quite old, closing. Feel free to reopen if still relevant.

**Pull request closed without merging**
