### PR TITLE
Generate PowerShell wrappers

### PR DESCRIPTION
**Pull request by RReverser**
As discussed in #18213. Unfortunately still doesn't solve the original issue, but useful nevertheless, especially because it sidesteps couple of issues specific to legacy cmd.exe.

### CODE REVIEW

**Comment by RReverser** [comment]
Also added generation of `linguist-generated` section in .gitignore to collapse diffs of all those generated wrappers on Github.

Technically could be split out into a separate PR, but it makes this PR much easier to review by reducing the noise.

**Comment by RReverser** [comment]
> Can you wait on that change (and its followup) to avoid checking these new files into git?

Sure, not urgent.

**Comment by RReverser** [comment]
I rebased this now that #19736 is merged, but not sure if you had further changes planned first / whether this needs to wait.

**Comment by sbc100** [comment]
> I rebased this now that #19736 is merged, but not sure if you had further changes planned first / whether this needs to wait.

Can you not add the generated files, and just rely on `./bootstrap` to generate them (on windows only?)

**Comment by sbc100** [comment]
I'm curious under what circumstances the `.ps1` files will get used by windows?

If you type `emcc` in cmd.exe presumably it will choose the `.bat` version?   What happens if you type `emcc` into a powershell terminal?

**Comment by RReverser** [comment]
> What happens if you type emcc into a powershell terminal?

It will choose ps1 as expected. 

> Can you not add the generated files, and just rely on `./bootstrap` to generate them (on windows only?)

I could but .bat files are currently checked in (why btw?). It seems it would be inconsistent for ps1 not to be?

**Comment by sbc100** [comment]
> > What happens if you type emcc into a powershell terminal?
> 
> It will choose ps1 as expected.
> 
> > Can you not add the generated files, and just rely on `./bootstrap` to generate them (on windows only?)
> 
> I could but .bat files are currently checked in (why btw?). It seems it would be inconsistent for ps1 not to be?

In the long run I hope to remove the `.bat` files.   See https://github.com/emscripten-core/emscripten/pull/20433

I'd rather not add yet more files to the top level directory.

**Comment by RReverser** [comment]
> In the long run I hope to remove the `.bat` files. See #20433

Ok but let's remove ps1 as part of the same PR? I just want all shell scripts to be in consistent state, not single out ps1 somehow here.

**Comment by RReverser** [comment]
> I just want all shell scripts to be in consistent state, not single out ps1 somehow here.

The main problem with singling out is that if ps1 is not yet generated, then PowerShell will quietly pick up the already-present bat file. That's not ideal.

**Comment by sbc100** [comment]
> > In the long run I hope to remove the `.bat` files. See #20433
> 
> Ok but let's remove ps1 as part of the same PR? I just want all shell scripts to be in consistent state, not single out ps1 somehow here.

I'm not sold on the idea that that added value of the ps1 scripts make it worth polluting the top level with all these new files.   Especially since, as you say, it didn't solve your original issue.

If you want to land this soon/now then I would rather you remove the new files otherwise wait for #20433 which is on the back burner.

I admit that might the ps1 scripts a guinea pig, but that will also help us shake out any issue with the bootstrap-generated files :)

**Comment by sbc100** [comment]
> Okay, I don't care too much, just want to avoid that scenario I mentioned above where `.bat` is still chosen automatically when we can generate `.ps1` instead. But on the 2nd thought it shouldn't happen anyway because Emscripten will complain if `./bootstrap` hasn't run yet, right?

Yes, that is correct (% bugs)

**Comment by RReverser** [comment]
I cleaned this up, but I'm probably going to leave open for now as it's indeed not solving any immediate issue as you said.

**Review by sbc100 — APPROVED** [review]
Nice!

I think this something we could consider landed now if you like.   Maybe with a ChangeLog entry?

**Comment by RReverser** [comment]
> I think this something we could consider landed now if you like. Maybe with a ChangeLog entry?

My only concern that I can think of is that this can be technically a breaking change for developers using PowerShell who didn't opt in to allow running arbitrary PowerShell scripts. (PowerShell has stronger security model than batch files too to prevent regular users from running random scripts off the Internet, although that's a bit moot given that Windows still allows arbitrary BAT files.)

This should be very rare since, as a developer who uses PowerShell anyway, you basically always want to allow it to run custom scripts, and it's even part of the developer settings in modern Windows.

image

But it still makes me a little bit worried about breaking someone's edge case workflow who types `emcc --...` in PowerShell console and gets an error after this update.

Another thing that I'm not sure about is if this requires any changes to emsdk / packaging or whether it will generate those files automatically upon Emscripten installation.

**Comment by sbc100** [comment]
> Another thing that I'm not sure about is if this requires any changes to emsdk / packaging or whether it will generate those files automatically upon Emscripten installation.

It should "just work".. we can confirm after this change lands that the `.ps1` scripts are present.

**Comment by RReverser** [comment]
Ok I added a changelog entry. Hopefully it will be enough.

**Comment by RReverser** [comment]
I guess we can give this a try.

**Comment by RReverser** [comment]
Would be nice to get one more Windows user to try this before cutting a release, just in case.

**Pull request merged**
