### PR TITLE
Mark 2.0.22 as released

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Are we waiting for an LTO build for 2.0.22? if so we can hold off on tweeting. cc @RReverser

**Comment by sbc100** [comment]
The test_async_2 failures look consistent... anything recent that could have caused that?

**Review by aheejin — APPROVED** [review]
Thanks!

**Comment by sbc100** [comment]
The failure of browser.test_async_2 looks like it started after to 2.0.22 release.  No need to block this landing on that failure.

**Pull request merged**
