### PR TITLE
Add a `failfast` command-line option to `runner.py`

### PR DESCRIPTION
**Pull request by aardappel**
This is functionality already exposed by `TextTestRunner`.

### CODE REVIEW

**Review by kripken — APPROVED** [review]

**Comment by sbc100** [comment]
Thanks for doing this.  Does this work with the parallel test runner?

**Comment by sbc100** [comment]
It seems not.   For example,  if i force all dylink tests to fail then run wasm2 test suite with --failfast it still tries to runs everything it seems:

```
./tests/runner wasm2 --failfast --skip-slow
...

----------------------------------------------------------------------
Ran 754 tests in 53.236s

FAILED (failures=72, skipped=26)
```

**Comment by sbc100** [comment]
72 failures.. but ran all 754 tests

**Comment by aardappel** [comment]
Yes, it be nice if it worked with parallel tests too.. I guess I usually have all the test debugging stuff on anyway which turns that off.

**Comment by sbc100** [comment]
Would be cool to combine with some kind of "restart-suite-from-last-failure" feature too.. so one could iterate through the test suite fixing one thing at a time.

**Comment by aardappel** [comment]
that would have saved me a lot of time, yes

**Pull request merged**
