### PR TITLE
GL emulation: fix glDrawElements always drawing GL_TRIANGLES

### PR DESCRIPTION
**Pull request by parasti**
Seems like every test is only using glDrawElements with GL_TRIANGLES.

Not sure if this fix is good, but it got my triangle strips working.

### CODE REVIEW

**Comment by parasti** [comment]
> 
> 
> Thanks @parasti , this looks correct!
> 
> Can you please add a test for this? Something similar to one of the existing tests with triangles would be ok I think.

@kripken I added a test for all glDrawElements drawing modes.

Without the patch the only mode that renders correctly is GL_TRIANGLES.

With the patch all except two modes render correctly. GL_POINTS don't (I'm not sure why). I am also testing GL_QUADS, but it seems that in Emscripten GL_QUADS is only implemented for glBegin/glEnd and glDrawArrays. So even with the patch, the test fails - but it fails a lot less, I suppose.

**Comment by parasti** [comment]
Seems that GL_POINTS would require a gl_PointSize assignment in the vertex shader. Without it, nothing gets drawn. I'll see if I can add it.

GL_QUADS isn't implemented for glDrawElements. I don't have a use case for it, either, so I'm happy just to remove that test.

**Comment by parasti** [comment]
Just to summarize the changes, because this PR kind of blew up:

1. Added a test for testing glDrawElements modes. GL_QUADS isn't tested, because it isn't implemented for indexed drawing (and I don't need it).
2. Fixed glDrawElements always drawing with GL_TRIANGLES.
3. Fixed GL_POINTS rendering by assigning gl_PointSize in the vertex shader. As a side effect of this, glPointSize now has an implementation.

**Comment by kripken** [comment]
Thanks @parasti , this looks good - but how about splitting the `GL_POINTS` changes to a separate PR? The benefit to doing it that way is that there is some chance (small, probably) of this ending up causing an issue somehow, and we'd want to be able to easily bisect on commits to find the problem. Having each commit as small as possible is better for that.

**Comment by parasti** [comment]
@kripken I can move that commit to another PR, but that'll make the included test fail until that PR is merged. Is that okay?

**Comment by kripken** [comment]
@parasti oh, in that case, please move the test to the later PR.

**Comment by kripken** [comment]
(i mean, it's fine to land a PR without a test, if we know a later PR will test it)

**Comment by parasti** [comment]
Test and GL_POINTS fix moved to #10954 as requested.

**Comment by kripken** [comment]
Perfect, thanks!

**Pull request merged**
