### PR TITLE
Remove asmjs validation

### PR DESCRIPTION
**Pull request by sbc100**
This only ever worked in spidermonkey and I don't think we care
about asmjs validation anymore anyway.

Perhaps this should wait until after we remove fastcomp which is the
only route to generating valid asm.js that we still maintain.

### CODE REVIEW

**Comment by kripken** [comment]
Yes, let's wait for fastcomp to be removed - the last version with fastcomp support should still support for asm.js validation, like always.

**Comment by sbc100** [comment]
I'm just not sure how much usage or testing this gets since it depends on spider monkey, and we don't install spider monkey on CI (or on local dev machines) that I know of.

**Comment by kripken** [comment]
I've tested this locally, at least I've tried to when we make changes that could affect asm.js validation. It still works AFAIK.

**Comment by sbc100** [comment]
The time as come !

**Comment by sbc100** [comment]
See #11860

**Pull request merged**
