### PR TITLE
Update WebGPU headers 2

### PR DESCRIPTION
**Pull request by shrekshao**
This update is synced to generated headers in dawn commit [@ea5ad06](https://dawn.googlesource.com/dawn/+/ea5ad0628941563fc802df998aaca8670b8ab8bc) (since dawn commit [@a83c434](https://dawn.googlesource.com/dawn/+/a83c434cc785ea55fc9e76f055522378e32bf199). So it is a smaller update)

Besides emscripten-bits gen files updates, there's an API rename: Compute/RenderEncoder `EndPass` -> `End`

Implement `wgpuDeviceGetLimits` (tested with dawn unittests)

### CODE REVIEW

**Comment by shrekshao** [comment]
Intended reviewer: @kainino0x 
The test-core0 fails for test_dlfcn_self. I did a rebaseline for that and it passed locally, yet it still fails on the ci.
Here's the before and after error. I don't know what needs to be fixed here.
```
AssertionError: Unexpected difference:
--- /usr/local/google/home/shrekshao/emsdk/emscripten/main/tests/core/test_dlfcn_self.exports
+++ /usr/local/google/home/shrekshao/emsdk/emscripten/main/tests/core/test_dlfcn_self.exports.new
@@ -1,5 +1,6 @@
 __THREW__
 ___environ
+__data_end
 __environ
 __optpos
 __optreset
```

```
AssertionError: Unexpected difference:
--- /root/project/tests/core/test_dlfcn_self.exports
+++ /root/project/tests/core/test_dlfcn_self.exports.new
@@ -1,6 +1,5 @@
 __THREW__
 ___environ
-__data_end
 __environ
 __optpos
 __optreset
```

**Comment by sbc100** [comment]
That failure requires a rebase (or merge) to fix.

**Comment by shrekshao** [comment]
I rebase to current tot 515af000e1d91be59d60561bdcd86362bddd9795 (which is your most recent commit). Hopefully that should fix. Thanks for the info!

**Comment by shrekshao** [comment]
Hmm... Seems it still fails `test_dlfcn_self` after the rebase

**Comment by sbc100** [comment]
You need to revert/remove your attempted fix: https://github.com/emscripten-core/emscripten/pull/16299/commits/9cbe9bee08f1ec80c7206fef7a77e92f8e41a724

**Comment by sbc100** [comment]
Tests looks good.  Just waiting on lgtm from @kainino0x

**Review by kainino0x — APPROVED** [review]

**Pull request merged**
