### PR TITLE
Remove DYNAMIC_BASE setting and JavaScript global

### PR DESCRIPTION
**Pull request by sbc100**
Users who really need to access this can export `__heap_base`
if they wish but normally this is not a detail that we export.

### CODE REVIEW

**Comment by kripken** [comment]
As in #12183, do we prefer exporting `__heap_base` over calling `sbrk()` during startup? I don't have a sense for which is more "correct". How stable is `__heap_base`?

**Comment by sbc100** [comment]
I update this change to preserve emscripten_metadata, leaving its removal/change as a separate discussion.

**Review by kripken — APPROVED** [review]
Nice!

No code size changes here? I guess it affects pthreads mostly, which we don't have tests for size yet.

**Comment by sbc100** [comment]
> Nice!
> 
> No code size changes here? I guess it affects pthreads mostly, which we don't have tests for size yet.

Not enough to trigger the tests to fail I guess.  I'll try a REBASELINE to see if there are a few bytes perhaps.

**Pull request merged**
