### PR TITLE
Update cmake toolchain file to include system/local (for find_package…

### PR DESCRIPTION
**Pull request by gabrielcuvillier**
For the purposes of cross-compilation of external libraries, I find very handy to install includes and emscripten-compiled libraries inside "$EMSCRIPTEN/system/local" folders, a little bit like it is done with "/usr/local" in a regular compilation.

As so, here is an update to the CMAKE toolchain file to take "system/local" into consideration: CMAKE_FIND_ROOT_PATH, INCLUDE_PATH, LIBRARY_PATH

In my opinion, this is simplifying the building process. 1: you build everything using CMAKE_INSTALL_PREFIX=$EMSCRIPTEN/system/local, 2: make install, 3: you can then build your main project and every dependency will be correctly found automatically.

If this sounds interesting to you, feel free to merge, or you can close the request otherwise.

### CODE REVIEW

**Comment by juj** [comment]
The idea here sounds good, although I have mixed feelings about this: before we have operated on the basis that the `$EMSCRIPTEN/` directory would be immutable/read-only, and when building, one does not modify files in that tree. E.g. on Windows, Emscripten may be installed inside C:\Program Files\, in which case it is a hard read-only directory, so no modifications there will be possible.

I wonder if it would make sense to use some other subdirectory for this purpose to avoid relying on a mutable `$EMSCRIPTEN/` directory?

**Comment by gabrielcuvillier** [comment]
If it is supposed to be read only, then that's right it should be elsewhere then. I work like this because I had the same workflow with Google Native Client SDK.
An interesting thing would be to see how other cross compilers SDK handle this situation (= where are installed the 3rd party libraries & dependencies). 
Maybe some $EMSDK/<"something">/<emscripten_version>, that would contain cross-compiled libraries, includes, shares, for the specified emscripten_version

**Comment by gabrielcuvillier** [comment]
or having some kind of $EMPORTS

**Comment by gabrielcuvillier** [comment]
Well, in the end I do the following locally:
- I defined a specific folder on my system intended to receive the cross-compiled libraries, and a EMPORTS environment variable pointing to it. This is no more <emsdk>/emscripten/<active_version>/system/local

- For cmake libraries I need to cross-compile and install, I use the CMAKE_INSTALL_PREFIX="$ENV{EMPORTS}"  

- On cmake projects using cross compiled libraries, I simply add the following:
list(APPEND CMAKE_FIND_ROOT_PATH "$ENV{EMPORTS}")
list(APPEND CMAKE_SYSTEM_INCLUDE_PATH "$ENV{EMPORTS}/include")
list(APPEND CMAKE_SYSTEM_LIBRARY_PATH "$ENV{EMPORTS}/lib")

In fact, this EMPORTS variable is more or less the "system" image for cross compiled libraries (what was I attempted to do with this PR).

This is working fine like this, so no need to modify the Emscripten cmake toolchain file. Maybe some issues can arise with the "bin" folder (sometime we need system programs to be run, and sometime we need generated programs. This is an unsolved methodology/workflow issue). Just an hint about this in the doc could be useful I suppose, to help users setup their workflows. You can close that PR.

Or, maybe it could be interesting to make the EMPORTS environment variable a standard emscripten thing (or any other name), and include the 3 lines regarding CMAKE_FIND_ROOT_PATH, etc. in the Emscripten cmake toolchain files.

**Comment by gabrielcuvillier** [comment]
I close this PR, as it is 1 year one

I have setup a specific methodology for 3rd party libraries, that is to have an $EMPORTS sysroot on my system

**Pull request closed without merging**
