### PR TITLE
no_binary_data_serialization_into_utf8

### PR DESCRIPTION
**Pull request by juj**
Remove support of (de)serializing binary byte data between raw data buffer and a UTF-8 string. With TextDecoder and eager handling of 0 as a terminator byte that never quite worked, so it is unlikely that anyone would have ever depended on that feature.

### CODE REVIEW

**Comment by kripken** [comment]
I think embind may have depended on this, but maybe it doesn't use that code path? cc @chadaustin @brion

**Comment by juj** [comment]
This is something that people did ask about before, but I don't think anyone used the mechanism in practice, given that TextDecoder path does not support it, and the non-TextDecoder path eagerly stops on first zero byte that is seen. So practically it was just broken for such purpose.

**Comment by kripken** [comment]
Ok, sounds like no comments on this being needed, so lgtm if tests pass (if something did use this, it should have been tested).

**Comment by juj** [comment]
The CI failures here are the same as in #7846 and #7863, that makes me wonder if they are currently in incoming, and not caused by these PRs?

**Comment by kripken** [comment]
Yes, CI looks ok here. (All those should be fixed soon, btw - sorry for the annoyance meanwhile.)

**Comment by juj** [comment]
Great, merged. No worries at all, I know how hard it is to keep it all green all the time :)

**Pull request merged**
