### PR TITLE
ASYNCIFY_IMPORTS: Do not require the default imports, just provide the new ones

### PR DESCRIPTION
**Pull request by kripken**
Change the meaning of `ASYNCIFY_IMPORTS`: it now contains only new imports
you add, and does not need to contain the list of default system imports like
``emscripten_sleep``. There is no harm in providing them, though, so this
is not a breaking change.

This avoids the need for a way to append to `ASYNCIFY_IMPORTS`, which
#10629 proposed as a new `-s X+=[..]` notation, but was too complex.

### CODE REVIEW

**Comment by kripken** [comment]
cc @Akaricchi

**Comment by Akaricchi** [comment]
I don't think this really solves anything. The actual problem with `ASYNCIFY_IMPORTS` and similar options is that they are not composable. Imagine I have a library that provides some async functions. Exactly which functions are async is an implementation detail. Ideally I would like to specify them in e.g. the library's `pkg-config` file's linker flags (or your build system's equivalent), so that the end user doesn't have to care about it. But I can't do that with `ASYNCIFY_IMPORTS`, because I can't assume what the final set of imports will be like for any given program - what if the user wants to add some of their own, or add another library that provides more async functions?

The `+=` proposal would've solved this nicely, and I don't buy the complexity argument.

**Comment by kripken** [comment]
@Akaricchi That's a good point for still needing `+=`, I agree. I reopened that PR now.

Separately, I think this change is worth landing, as it makes things simpler to not let users by mistake remove the defaults. We can still add `+=` notation on top of that later in that other PR. How does that sound to you?

**Comment by Akaricchi** [comment]
> Separately, I think this change is worth landing, as it makes things simpler to not let users by mistake remove the defaults. 

Yes I can agree with that. Although hardcoding a list of built-in imports in `emcc.py` is questionable. Perhaps a new setting in `settings_internal.js` would be a more appropriate place for these? I'm assuming it's not possible to set internal settings from the command line.

A generally much better option would be to deprecate `ASYNCIFY_IMPORTS` and implement JS annotations for these, e.g. `myfunc__asyncify: true`. Then there's no need for a hardcoded list, and the composability problem also disappears (in this specific instance).

**Comment by kripken** [comment]
@Akaricchi 

> Although hardcoding a list of built-in imports in emcc.py is questionable. Perhaps a new setting in settings_internal.js would be a more appropriate place for these? I'm assuming it's not possible to set internal settings from the command line.

Internal settings can't be set on the commandline, that's correct. However, we use the settings for when information is needed across different parts of the code, like sharing between the Python and JS codebases. When something is only needed in one file, we've not used settings for that.

But good point, that's a long list in the middle of code. I moved it up to the definitions area at the top of emcc.py now.

> A generally much better option would be to deprecate ASYNCIFY_IMPORTS and implement JS annotations for these, e.g. myfunc__asyncify: true. Then there's no need for a hardcoded list, and the composability problem also disappears (in this specific instance).

That's an interesting idea! However, it's not practical in this case, as those annotations are visible only when in JS - the Python code never sees those.

**Comment by Akaricchi** [comment]
> That's an interesting idea! However, it's not practical in this case, as those annotations are visible only when in JS - the Python code never sees those.

Well, the JS processor could spit them out in some metadata for the Python code to consume. I think some of the Binaryen tools do the same thing already. That doesn't seem infeasible unless I'm missing something.

**Comment by kripken** [comment]
@Akaricchi 

Good point, yeah - we can actually use an internal setting for that communication. So I think this can work, and be nicer! I opened #10676 so we don't forget it, as I agree it's separate from this PR.

Sounds like no concerns otherwise about this PR? I'll land it later today.

**Comment by kripken** [comment]
Looks like no concerns, landing.

**Pull request merged**
