### PR TITLE
add check_c_source_runs test

### PR DESCRIPTION
**Pull request by ericoporto**
pairs with #14762 , but doesn't solve it, just test for it.

### CODE REVIEW

**Comment by kripken** [comment]
I'm confused, if that is an open issue, shouldn't a test for it fail? Looks like all tests pass here.

**Comment by ericoporto** [comment]
It should fail yes. I am sorry, I can't find the log where it says it passed, I thought running test required some command here in the CI.

**Comment by kripken** [comment]
Something seems wrong with the logs here - I don't see builds running. When you run the test locally does it fail?

Maybe try merging in main to here to restart builds. If that fails I can file a ticket with circleci.

**Comment by ericoporto** [comment]
I am closing this since I am working around this currently and don't have time for a proper fix

**Pull request closed without merging**
