### PR TITLE
[wasm64] Fix `_emscripten_run_callback_on_thread` under wasm64

### PR DESCRIPTION
**Pull request by sbc100**
The only test we have for this was in `test_interactive.py`.  I ran it locally to ensure it now works.

Fixes: #21851

### CODE REVIEW

**Comment by dschuff** [comment]
The code and test changes look fine. Do you think it would be possible to move some of this event-threading coverage out of interactive tests? Presumably things like key or mouse events would have to stay interactive but maybe for proxying we could move to some other kind of event?

**Comment by sbc100** [comment]
> The code and test changes look fine. Do you think it would be possible to move some of this event-threading coverage out of interactive tests? Presumably things like key or mouse events would have to stay interactive but maybe for proxying we could move to some other kind of event?

Actually it looks like we do already have some coverage in the browser tests for this and the test was explictly disabled for wasm64.  Now enabled!

**Review by kripken — APPROVED** [review]

**Review by dschuff — APPROVED** [review]

**Comment by jspanchu** [comment]
Upon pasting that last line in `tools/emscripten.py`, mouse/keyboard/resize all work great in wasm64 + proxy-to-pthread! Assuming this gets merged, will this fix make it to the next release 3.1.59? Any rough estimate when that will happen?

Thanks for working on this!

**Comment by sbc100** [comment]
> Upon pasting that last line in `tools/emscripten.py`, mouse/keyboard/resize all work great in wasm64 + proxy-to-pthread! Assuming this gets merged, will this fix make it to the next release 3.1.59? Any rough estimate when that will happen?
> 
> Thanks for working on this!

3.1.59 is already in the process of being built, so this would go into 3.1.60.

BTW you can always use `emsdk install tot` to get the very largest version of emscripten (usually lags just a few hours).

**Comment by sbc100** [comment]
Given that wasm64 is itself still experimental I wouldn't normally put something like this in the ChangeLog.   I'm happy to make an exception though if you think this will be useful to others too?

**Comment by sbc100** [comment]
> Given that wasm64 is itself still experimental I wouldn't normally put something like this in the ChangeLog. I'm happy to make an exception though if you think this will be useful to others too?

(we normally reserve the ChangeLog for major changes or breaking changes, not bugfixes like this)

**Comment by jspanchu** [comment]
Okay. I don't know of others interested in rendering and event processing with 64-bit wasm outside of the simulation post processing industry, anyone from gaming?

It seems fair enough to leave it out.

**Comment by sbc100** [comment]
BTW the 3.1.60 release should get done today or tomorrow I hope.

**Comment by jspanchu** [comment]
Awesome!

**Pull request merged**
