### PR TITLE
Document COOP/COEP requirement for -pthread

### PR DESCRIPTION
**Pull request by DhairyaBahl**
@RReverser @sbc100 

This will resolve the issue #12472 . Kindly look into this PR. Thanks :+1:

### CODE REVIEW

**Comment by RReverser** [comment]
Please don't close PRs and open new ones - this loses all the comment history and makes it hard to track what's resolved. Just push new commits to the same branch.

**Comment by DhairyaBahl** [comment]
@RReverser I know it causes difficulties for you guys to check them out but I am new with GIT and still practicing its commands. It won't happen again.

Thanks :+1:

**Review by kripken — APPROVED** [review]
Thanks @DhairyaBahl , I think this looks good!

@RReverser what do you think?

**Review by RReverser — APPROVED** [review]
@kripken Oh yeah, sorry, I mentioned on the chat but didn't approve here - this version LGTM.

**Comment by RReverser** [comment]
@DhairyaBahl Thanks for the contribution!

**Comment by kripken** [comment]
Oh, looks like we forgot to have you add yourself to AUTHORS @DhairyaBahl (maybe because of the multiple PRs). No problem, but in one of the other PRs please add yourself there.

**Pull request merged**
