### PR TITLE
Support += in emcc.py -s notation: -s KEY+=[val1, val2] appends to the default

### PR DESCRIPTION
**Pull request by kripken**
This is useful for settings like `EXPORTED_FUNCTIONS`, the
asyncify lists, etc., where the user may want to just add more
but not remove the existing defaults.

If people like this idea perhaps we can replace the `EXTRA_*`
settings with this.

### CODE REVIEW

**Comment by sbc100** [comment]
I would rather not add this complexity if we can avoid it.   For each setting i think we can define what it means when the user specifies something on the command line.

Lets take EXPORTED_FUNCTIONS for example.  Right now this this is initial set of exported functions.  If you don't specify this it defaults to just ["main"].     

I agree we should get rid of the EXTRA_ settings but there are only two those:

```
EXTRA_EXPORTED_RUNTIME_METHODS
BINARYEN_EXTRA_PASSES
```

And EXTRA_EXPORTED_RUNTIME_METHODS only needed for backwards compabiltiy anyway.

So that just leave `BINARYEN_EXTRA_PASSES` vs `BINARYEN_PASSES`.  I'm not sure this is worth adding just for that one flag.  I rather just split that flag into two.  Something like:

```
BINARYEN_PASSES
DISABLE_DEFAULT_BINARYEN_PASSES
```

But honestly do we want to support something like `DISABLE_DEFAULT_BINARYEN_PASSES`?  Won't that break a bunch of internal assumptions?  Do we have users who would want this?

My secret motivation here is that I've been hoping one day to completely replace the `-s` handling, and this would just make it harder to do that.

**Comment by sbc100** [comment]
I agree that `main` things a little awkward today.  

How about this:

`EXPORT_FUNCTIONS` is always empty by default.  `main` gets addded internally to this list (just like we do for malloc/free today) unless the user specified some other flag ?   Something like `--no-entry` or `-s  NO_MAIN`?   I think thats cleaner than requiring the user to know that  `EXPORT_FUNCTIONS` comes pre-loaded with main.

**Comment by kripken** [comment]
Interesting, I'd like to see us remove `-s` somehow in the future, but that seems quite far off? More relevant though, I'm not sure this PR would make that harder? But maybe I don't know how you are thinking of removing `-s`.

There is also `ASYNCIFY_IMPORTS` which happens to not have an EXTRA, but this PR is an alternative to adding an EXTRA for it. So there are 3 such lists. I think it's nicer to add `+=` support for them than to find workarounds, but again, maybe I don't see the downside to the PR yet, as I said earlier.

**Comment by kripken** [comment]
I've come to see @sbc100 's point of view here, closing. I'll open a separate PR with a solution for `ASYNCIFY_IMPORTS`.

**Comment by kripken** [comment]
Replacement PR for asyncify imports: #10640

**Comment by kripken** [comment]
Reopening after @Akaricchi 's point that `+=` is useful for composing flags from different libraries, each adding their own new functions, https://github.com/emscripten-core/emscripten/pull/10640#issuecomment-594370275

**Comment by sbc100** [comment]
I thought I saw somewhere that you decided that added this the library itself might be better (i.e. the the .js file)?

**Comment by Akaricchi** [comment]
That would indeed be better for this particular setting, but someone has yet to implement it, and the `+=` syntax still benefits every other setting that expects a list. I personally think this extra complexity is a drop in the ocean for `emcc.py`.

**Comment by sbc100** [comment]
As far as I cant tell we don't have any other list settings that would benefit from this.

At least in the long run I'm hoping all the defaults can be the empty list, so we won't ever want to append unless the same option appear more than once on the command line.. which I don't think is useful/common is it?

**Comment by sbc100** [comment]
Is there some reason why one big list can't be passed on the command line in your example use case?

**Comment by Akaricchi** [comment]
The flags don't always come directly from the user. I have explained it [here](https://github.com/emscripten-core/emscripten/pull/10640#issuecomment-594370275) with the `ASYNCIFY_IMPORTS` example, but that really applies to everything. If a third-party library (or *my* library that's just decoupled from the rest of the project) wants to add some of its functions into `ASYNCIFY_BLACKLIST` or `EXPORTED_FUNCTIONS` for whatever reason, it should be able to do so without interfering with the rest of the build, and without me (the user) having to care about it.

It can't be one big list because that is not composable. A good CLI is composable. That's why if you have `--foo` you also add `--no-foo`, and if something takes a list it's often a good idea to specify it with multiple arguments. All the same reasons why you have `-s FOO_OPTION -s BAR_OPTION` and not `-s FOO_OPTION,BAR_OPTION`. If the CLI was saner in the first place, you'd have flags like `-femscripten-asyncify-import _foo -femscripten-asyncify-import _bar` and this issue would never come up.

**Comment by sbc100** [comment]
Regarding `-fasyncify foo -fasyncify bar`..  that might not be a bad idea.  Not all emscripten options have to be `-s` settings. 

Better still, as we all agree I think, would be to have the library itself inject this information (either via contents of the JS file or attributes in the object files).    Since this is really a symbol property the information best lives alongside the symbol.

**Comment by Akaricchi** [comment]
I think you're missing the bigger picture here. Suppose today you'll implement awesome annotations that supersede all the clumsy list settings. A week later you'll add another list setting (because that's easy) and it will have the same composability problem. This isn't about any one specific setting in isolation, it's about a systemic problem in the way your CLI works.

> Not all emscripten options have to be -s settings.

From a UX perspective, I would go as far as to say that none of them should've been `-s` settings from the start. The `-s` syntax sticks out like a sore thumb among the other GCC/Clang-style flags, and [gives build systems trouble](https://github.com/mesonbuild/meson/issues/6097) (though admittedly, that's not entirely emscripten's fault there). But I understand that you've done that because a 1:1 mapping to `settings.js` is easier to maintain.

**Pull request closed without merging**
