### PR TITLE
Use clang's new -fignore-exceptions which disables exception catching in the frontend

### PR DESCRIPTION
**Pull request by kripken**
This is faster and better than running LowerInvoke in the backend
later in compilation, as we didn't generate a lot of stuff just to
get rid of it.

h/t to @dschuff 

On a (very artificial, tons of try-catches in a big function) benchmark
I see a 40% speedup, so it can be noticeable.

This also manages to remove `_ZSt18uncaught_exceptionv` in a
metadce test, but that's not very significant as `-O3` would have
removed that too using metadce. Still, perhaps in other cases
something would have been emitted to the table, and not been
removable, that not emitting it at all would have helped avoid?

More details on the new clang flag: https://reviews.llvm.org/D72644

### CODE REVIEW

**Comment by aheejin** [comment]
- We currently allow `-fexceptions` and `-fno-exceptions` to be specified in emcc command lines and set settings like `DISABLE_EXCEPTION_CATCHING` based on them too (So basically if one is set we set the other). Should we do the same thing for `-fignore-exceptions`?
- I understand why this can reduce code size, but why does this make programs faster? (Is the effect of better icache performance as a result of code size decrease that significant?)

**Comment by kripken** [comment]
Good point about the flags - I added support and testing now.

Sorry, I wasn't clear enough about the speed - it mostly speeds up compilation, not execution (just by not even emitting stuff at the frontend). It might speed up execution too, I didn't test that.

**Comment by kripken** [comment]
I believe we still need LowerInvoke in the backend for LTO, but I'm not entirely sure.

**Comment by sbc100** [comment]
One would hope that  -fignore-exceptions would be preserved as an attribute in the bitcode so LTO would "just work"

**Pull request merged**
