### PR TITLE
Do not allow self.emcc_args change unless in test_core.py

### PR DESCRIPTION
**Pull request by quantum5**

### CODE REVIEW

**Comment by sbc100** [comment]
Why not?   It seems reasonable to want to change these.

**Comment by quantum5** [comment]
Only `test_core.py` properly resets `self.emcc_args` in `setUp`. In all other test suites, the changes are just kept around and affect other tests unpredictably.

**Comment by kripken** [comment]
Thinking more on this, I think it's dangerous and confusing that emcc_args exists outside of test_core.py. it's really only intended for use there. Let me do some tinkering with refactoring this to avoid confusion here.

**Comment by sbc100** [comment]
emcc_args can be used to set the arguments for future calls to build(), do_run() etc.. in any test suite.  Not just core.   The emcc args stuff is all handling the core runner.py.

If its not being reset correctly that is a serious bug.

**Comment by sbc100** [comment]
Python unittests always run in a fresh instance of the class, so settings `self.xxxx` in one test doesn't effect any other tests.

**Comment by quantum5** [comment]
It appears that the problem was `self.emcc_args += stuff`, which is quite common in `test_core.py`, modifying the `emcc_args` declared on the class level, in non-`test_core.py` test suites. A fresh instance of the class won't solve this problem.

**Comment by sbc100** [comment]
Ah.. OK in that case I see what happened.  It looks like I broke that in #7435 when I made the class member into arrary.  I think the correct fix is to move emcc_args to be a purely instance member.

**Comment by sbc100** [comment]
How about this #8768

**Comment by quantum5** [comment]
Let's use #8768.

**Pull request closed without merging**
