### PR TITLE
Set INTERFACE_INCLUDE_DIRECTORIES property on SDL2 targets

### PR DESCRIPTION
**Pull request by madebr**
This makes the targets more compatible with upstream SDL2.

### CODE REVIEW

**Comment by sbc100** [comment]
Can you explain the problem a little more and how this solves it?  Does the upstream/normal sdl2-config.cmake do this?  

Should we look into switch to using the upstream version directly?

**Comment by madebr** [comment]
Yes, the upstream SDL2 config script(s) create `SDL2::*` targets with all properties populated.
That way, there's no need anymore for CMake variables.

SDL3 will get rid of all CMake variables in its CMake configuration files, and will only provide targets.
So it's important to get these right when the time comes.
(Feel free to tag me when SDL3 gets introduced in emscripten)

I don't think you can use the upstream cmake config scripts, because emscripten is doing "magic" thinks with `-sUSE_SDL=2` etc.
Also, SDL2 upstream does not create working javascript "executables" with working audio due to a missing link option: `'-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=["$autoResumeAudioContext","$dynCall"]'`.
(CMake currently corrupts link options with `$` characters. It's reported.)

**Comment by sbc100** [comment]
Thanks for the context.  This change lgtm in that case.

Regarding `-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=["$autoResumeAudioContext","$dynCall"]`.. I think we should be able to fix that upstream in the SDL repo using the (relatively) new `EM_JS_DEPS` macro...

**Comment by madebr** [comment]
Thanks for the hint about `EM_JS_DEPS`. This would be very useful for pkg-config too, because it has a similar issue as cmake.

It also avoids the uncertainty when multiple dependencies do `-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=["a","b"]` and `-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=["c","d"]`.
Will emscripten apply both, or only the last option?

**Comment by sbc100** [comment]
> Thanks for the hint about `EM_JS_DEPS`. This would be very useful for pkg-config too, because it has a similar issue as cmake.
> 
> It also avoids the uncertainty when multiple dependencies do `-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=["a","b"]` and `-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=["c","d"]`. Will emscripten apply both, or only the last option?

Currently the last one is the only one that will be honored.   But we have had requests to change that because so its not out of the question that we could do that.

**Comment by sbc100** [comment]
I took a stab at adding the deps to SDL2: https://github.com/libsdl-org/SDL/pull/7935

**Review by sbc100 — APPROVED** [review]

**Comment by ccawley2011** [comment]
This causes an error if `-sUSE_SDL=2` hasn't previously been used to install SDL2:

```
  Imported target "SDL2::SDL2" includes non-existent path
    "/home/runner/work/_temp/008196b0-2889-4b08-b008-b4990cdce441/emsdk-main/upstream/emscripten/cache/sysroot/include/SDL2"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
```

**Comment by madebr** [comment]
Perhaps Emscripten should always create a `include/SDL2` directory containing a dummy `.keep` file?

**Comment by sbc100** [comment]
I decided to go the other way.  

After #24306 the cmake command will fail even earlier since `sdl2-config.cmake` won't be install SDL2 with `./embuilder build sdl2` (or run and `emcc` command with -sUSE_SDL=2 which also implicitly installs it).

**Pull request merged**
