### PR TITLE
Update SDL2 port

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
@Daft-Freak

**Review by kripken — APPROVED** [review]

**Comment by sbc100** [comment]
I'm seeing 7 local test failures with this update:

```
test_sdl2_mixer_wav
test_sdl2_mixer_music
test_sdl2_gl_frames_swap
test_sdl2_pumpevents
test_sdl2_canvas_proxy
test_sdl2_key
test_sdl2_mouse
```

Lets see if the same failures show up on CI.  @Daft-Freak any ideas?

**Comment by sbc100** [comment]
A smaller update seems to only have issues with mouse and keyboard events: https://github.com/emscripten-core/emscripten/pull/21337

**Comment by Daft-Freak** [comment]
Looks like we need to build `joystick/SDL_steam_virtual_gamepad.c` from the CI results.

**Comment by Daft-Freak** [comment]
:thinking: `test_sdl2_canvas_proxy` and `test_sdl2_gl_frames_swap` are both because SDL tries to compile a shader using `GL_OES_EGL_image_external` then checks the compile status, which returns false and asserts because of `--proxy-to-worker`.

**Comment by sbc100** [comment]
> 🤔 `test_sdl2_canvas_proxy` and `test_sdl2_gl_frames_swap` are both because SDL tries to compile a shader using `GL_OES_EGL_image_external` then checks the compile status, which returns false and asserts because of `--proxy-to-worker`.
> 
> Edit: the change from previous versions being that the shaders are compiled at init instead of on-demand, I think.

Oh thats good to know, thanks for the tip.

I'm going to try to land #21337 first and then try this one again.

**Comment by ericoporto** [comment]
I see you are updating to 2.30.0 release, I advise updating to 2.28.5 instead, as 2.30.0 still has some issues to be ironed out.

**Comment by sbc100** [comment]
> I see you are updating to 2.30.0 release, I advise updating to 2.28.5 instead, as 2.30.0 still has some issues to be ironed out.

OK, I'll close this one.

Do you mean emscripten-specific issue?  Or is it just not ready yet?  Was it not released already?

**Comment by ericoporto** [comment]
This is weird, I swear I saw an issue in the tracker about Fullscreen not working but it appears it's only in SDL3.

In any case I really need https://github.com/libsdl-org/SDL/issues/9127 fixed (hopefully in 2.30.1) because otherwise we are having problems with audio in SDL2, but I don't know if that issue in particular affects the Emscripten builds.

**Pull request closed without merging**
