### PR TITLE
Remove dependency on python distutils module

### PR DESCRIPTION
**Pull request by sbc100**
We already had our own Building.which function which does what
we want.

Fixes: #10943

### CODE REVIEW

**Comment by sbc100** [comment]
See the bug.  distutils is apparently somehow deprecated and not shipped in debian/ubuntu `python3` package.  You only get it if you install the extra `python3-distutils` package, which in practice many people have, but not everyone.

**Comment by sbc100** [comment]
Looking that the code the only difference seems to be that our code also looks for `.bat` and `.com` on windows whereas the distutils code looks like it only considers `.exe`.

There is non-zero change this could cause issues, but I think its pretty small.  Also note that code is only used when generating the default config, and therefor never use by emsdk users.

**Comment by Fabrizio-Caruso** [comment]
How can I install the fixed version? I installed the latest version today and I have this error under Kubuntu (recent 64-bit version)
Could someone please give the exact installation steps I should follow to have the fixed version running in Kubuntu?

**Comment by kripken** [comment]
It's possible this isn't in the last release then. We'll probably make a new release soon. Meanwhile, a tip of tree build should work,
```
emsdk update-tags
emsdk install tot
emsdk activate tot
```

**Pull request merged**
