### PR TITLE
Inline single use library function. NFC

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by kleisauke** [comment]
Oh, huh, I thought that auto-merging was only done when all requested reviewers had left a approval.

**Comment by kripken** [comment]
It is a confusing feature, yeah... I'd prefer for it to wait for all approvals, and also to be able to see it easily right before clicking "approve". But it's still useful even so.

**Comment by sbc100** [comment]
For these kinds of changes I think and LGTM from either of one of you is fine.

The auto-merge I think has the same requirements for landing as the normal merge..  I guess if we want to require multiple reviewers we should require it for all PRs not just auto-committed ones.

**Comment by kripken** [comment]
Oh, maybe that's an option in general for PRs then, good point.

And sorry, I wasn't clear before: I agree a single LGTM is enough for these PRs. I was just surprised how easy github makes it to land stuff with this feature :smile:

**Pull request merged**
