### PR TITLE
Update musl to v1.2.3

### PR DESCRIPTION
**Pull request by sbc100**
Sadly I had to revert the definition of NULL as nullptr due to some places where GL calls were made using NULL in place of an integer argument.  If this wasn't third party code we could just fix it:

```
/usr/local/google/home/sbc/dev/wasm/emscripten/cache/ports/cocos2d/Cocos2d-version_3_3/cocos2dx/platform/emscripten/CCEGLView.cpp:439:19: error: no matching function for call to 'eglCreateWindowSurface'
    _eglSurface = eglCreateWindowSurface(_eglDisplay, config, NULL, eglSurfaceAttrs);
                  ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/google/home/sbc/dev/wasm/emscripten/cache/sysroot/include/EGL/egl.h:155:31: note: candidate function not viable: no known conversion from 'std::nullptr_t' to 'EGLNativeWindowType' (aka 'int') for 3rd argument
EGLAPI EGLSurface EGLAPIENTRY eglCreateWindowSurface (EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint *attrib_list);
                              ^
1 error generated.
```

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Nice that it's a small diff when it's just a single minor version bump!

**Comment by kleisauke** [comment]
> Sadly I had to revert the definition of NULL as nullptr due to some places where GL calls were made using NULL in place of an integer argument.

:disappointed:, as I think this would fix these false-positive(?) Clang warnings for wasm-vips:
<details>
  <summary>Details</summary>
  
```
[123/358] Compiling C++ object libvips/resample/libresample.a.p/reducev.cpp.o
../libvips/resample/reducev.cpp:413:9: warning: missing sentinel in function call [-Wsentinel]
                                NULL ) )
                                    ^
                                    , nullptr
../libvips/include/vips/resample.h:67:5: note: function has been explicitly marked sentinel here
int vips_shrinkv( VipsImage *in, VipsImage **out, int vshrink, ... )
    ^
1 warning generated.
[124/358] Compiling C++ object libvips/resample/libresample.a.p/reduceh.cpp.o
../libvips/resample/reduceh.cpp:482:9: warning: missing sentinel in function call [-Wsentinel]
                                NULL ) )
                                    ^
                                    , nullptr
../libvips/include/vips/resample.h:64:5: note: function has been explicitly marked sentinel here
int vips_shrinkh( VipsImage *in, VipsImage **out, int hshrink, ... )
    ^
1 warning generated.
```
</details>

Perhaps Cocos2D can be build with ` -std=c++03`  or ` -std=c++98` instead? Since this is only guarded for the 2011 standard or higher (`201103L`, i.e. `-std=c11` or `-std=iso9899:2011`). Or does this affect other ports as well?

**Comment by sbc100** [comment]
It effected a few of out tests, but I fixed those.  The only non-trivial fix seemed to be Cocos2D.

However this does mean that third party code is likely effected too.    We could proposal a followup change to go with the nullptr definition,  and see if external folks complain.   Would like like to create  PR for that?

**Comment by sbc100** [comment]
Can you confirm it does indeed fix those false positives?

Presumably that code should really be using `nullptr` rather than `NULL` if its C++, right?

**Comment by kleisauke** [comment]
> Would like like to create PR for that?
> Can you confirm it does indeed fix those false positives?

I'll investigate and open a PR if necessary. It should probably be a safe change given that GLib did the same thing recently:
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3033

> Presumably that code should really be using `nullptr` rather than `NULL` if its C++, right?

I think the reasoning behind this is for compatibility with pre-C++11 compilers, for the same reason we cannot use `constexpr` currently.  We might require C++11 or later in the next release cycle of libvips (or only when [Highway](https://github.com/google/highway) is found). /cc @jcupitt

**Pull request merged**
