### PR TITLE
Add support for special event targets in HTML5 API

### LINKED ISSUE #10311: DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR and Shadow DOM
A user has repored that the new behavior, after removing the special `#canvas` behavior etc., is a problem with shadow DOM. IIUC the new behavior just does a `document.querySelector`, but that won't work with shadow DOM in all cases, as the canvas may not be accessible that way.

If that's correct, maybe we need to keep around special event targets?

cc @juj

### PR DESCRIPTION
**Pull request by kripken**
Rename `__specialEventTargets` to `SpecialEventTargets` and
make it a useful API, in that people can assign new targets with
something like
```javascript
SpecialEventTargets["#canvas"] = Module.canvas;
```

While doing this I found a way to also shrink the code, so this
is also a code size win!

Add docs for this new capability, and also update the related
docs around that about HTML5 API registration function values.

fixes #10311 helps #10194

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This will simply things when I go to stop using the deprecated behavior, so I like this approach.

**Comment by kripken** [comment]
ping @juj, would be great to make progress on this.

**Comment by Alfian878787** [comment]
https://sql-js.github.io/sql.js/examples/GUI/

**Comment by Alfian878787** [comment]
alfian.padjialfian/github.com

**Comment by Ecco** [comment]
Shouldn't this be extended to all targets, not just events one?

For instance, what if you need to call `emscripten_set_element_css_size`? You would have the exact same kind of problem 😄

**Comment by kripken** [comment]
@Ecco I think you're right, yeah. Hopefully we can get agreement on this PR and address those other things later. (Or do you see a reason the others can't be done as followups?)

**Comment by Ecco** [comment]
Well, yeah, I guess we can do those sequentially. But I would think it'd be pretty much the same amount of work to handle everything at once 😄 

Also, this would help #10775.

**Comment by Ecco** [comment]
As a side note, I think this is somewhat over-engineered. Follow me on this one:

1. EMSCRIPTEN_EVENT_TARGET_WINDOW is easy and convenient
2. But in my personal use case I want to point to the Module's canvas (pretty much what `#canvas` used to do).
3. So I considered adding `EMSCRIPTEN_EVENT_TARGET_CANVAS`
4. Oh but look, this is exactly what the example of using `SpecialEventTargets["#canvas"]`.

But this raises a question: if the canvas doesn't need its own constant, then why the window or document would?

How about using *only* SpecialEventTargets ? Instead of defining a constant and having to handle separate code path, we could simply pre-populate SpecialEventTargets:

```js
SpecialEventTargets["#window"] = window;
```

Here's a better suggestion which:
 * renames SpecialEventTargets to SpecialTargets since I really believe this shouldn't be limited to events
 * uses a "!" syntax to make it clear this is *not* a CSS selector

```js
SpecialTargets["!window"] = window;
SpecialTargets["!document"] = document;
SpecialTargets["!canvas"] = Module.canvas;
```

Then one could simply do 
```c
emscripten_set_element_css_size("!canvas", 1, 2);
emscripten_set_keypress_callback("!window", ...);
```

**Comment by kripken** [comment]
Thanks for the suggestions @Ecco ! I renamed `SpecialEventTargets` to `SpecialHTMLTargets`, I agree that this might cover more than events. (But I put HTML there as `SpecialTargets` seems too general.) And I changed the examples to use `!canvas` notation which does nicely make it clear it's not CSS.

Separately from this PR I'd also be happy to get rid of the constants, so `SpecialHTMLTargets` is all there is, but that might not be trivial from a backwards-compatibility point of view. Let's discuss separately with @juj.

**Comment by Ecco** [comment]
Thanks a lot @kripken! Yeah, renaming to "SpecialHTMLTargets" makes sense!

Here's a simple suggestion regarding how backwards compatibility could be handled:
* Remove any reference to `EMSCRIPTEN_EVENT_TARGET_*` from the documentation
* But do keep those constants in html5.h (but hint they're being deprecated)
* ... and simply give them a text value, e.g. `"!window"` for `EMSCRIPTEN_EVENT_TARGET_WINDOW`
* Pre-populate `SpecialHTMLTargets` with those values (e.g. `SpecialHTMLTargets["!window"] = window`)
* And then only keep the `SpecialHTMLTargets[foo]` lookup.

This way, any emscripten client using `emscripten_set_element_css_size(EMSCRIPTEN_EVENT_TARGET_WINDOW, 1, 2);` would in fact call `emscripten_set_element_css_size("!window", 1, 2);`, which would in turn simply look it up within `SpecialHTMLTargets` 😄

**Comment by kripken** [comment]
@juj - mainly since it's a constant, not a variable... but as it can be modified by users maybe that's not best. I'll change it to lowercase.

**Comment by juj** [comment]
> if the canvas doesn't need its own `EMSCRIPTEN_EVENT_TARGET` constant, then why the window or document would?

The reason why the code looks like the way it does is because `window`, `document` and `screen` do not have CSS selector strings that could be used to address them. With the exception of the somewhat exotic shadow DOM case that @kripken is addressing here, other DOM elements can be targeted with CSS selectors.

>     2\. But in my personal use case I want to point to the Module's canvas (pretty much what `#canvas` used to do).

There should no longer be a thing called "The Module's canvas". That is the bad abstraction we want to get rid of. Instead, just refer to the canvas you are interested in directly with a CSS selector.

Removing the abstraction of `Module.canvas` helps tear down extra state and code size from Emscripten built-in libraries that people have objected against for several years.

> For instance, what if you need to call `emscripten_set_element_css_size`? You would have the exact same kind of problem

Unless I am mistaken, this PR does address `emscripten_set_element_css_size`? That function calls `_findEventTarget` to locate the target, which is covered by this PR.

> Here's a simple suggestion regarding how backwards compatibility could be handled:

Let's not go to that direction to cater to the legacy EGL API, but instead EGL API should be brought up to date to operate on the modern `Module['canvas']`-less concept. Commented in #10775.

**Pull request merged**
