### PR TITLE
Fix growable heap views

### LINKED ISSUE #10179: RangeError: start offset of Int32Array should be a multiple of 4
Given the test files:
```c
#include <emscripten.h>

int main() {
    EM_ASM({
        GROWABLE_HEAP_VIEW_I32(4, 8);
    });
    return 0;
}
```
and:
```html
<html>
    <head>
        <script src='a.out.js'></script>
    </head>
</html>
```

I get the error `RangeError: start offset of Int32Array should be a multiple of 4`.

By the looks of it, `TypedArray` view offsets and lengths are byte values, so the shifting in the `GROWABLE_HEAP_VIEW_*` functions need to be removed.

### PR DESCRIPTION
**Pull request by kripken**
Fixes #10179

### CODE REVIEW

**Comment by kripken** [comment]
I believe this isn't in use since @brion's recent refactor to just use a function to get the HEAP for all things. But it can be used from JS by users, as in that bug report. We should probably add tests for it if it indeed isn't tested otherwise.

**Comment by sbc100** [comment]
If we don't have any use cases internally why not just remove them?

**Comment by sbc100** [comment]
lgtm to this change either way

**Comment by brion** [comment]
I'd be fine with removing them as well.

**Pull request merged**
