### PR TITLE
Make _emscripten_run_callback_on_thread asynchronous

### PR DESCRIPTION
**Pull request by stbergmann**
...fixing a regression introduced in c41f6590b1f9fcda12b2adb2d32cd352f163e717 "Remove use of legacy proxy API from library_html5.js. NFC (#20370)".

Fixes: #22442

### CODE REVIEW

**Comment by kripken** [comment]
@sbc100 this refers to your PR https://github.com/emscripten-core/emscripten/pull/20370 - has this issue already been resolved?

**Comment by sbc100** [comment]
I'm not totally sure if this is the best solution.   I still need to do more investigation into #22442

**Comment by sbc100** [comment]
Looking at the old code it does look like it was using async dispatch, so this change LGTM.

**Comment by sbc100** [comment]
Its a shame we can't avoid the dynamic allocation here ..

**Review by sbc100 — APPROVED** [review]

**Pull request merged**
