### PR TITLE
Setting errno properly in nanosleep function

### PR DESCRIPTION
**Pull request by abujalski**
This change validates nanosleep arguments and sets errno properly.

It fixes following tests from http://posixtest.sourceforge.net/
- nanosleep/5-1
- nanosleep/6-1
- nanosleep/10000-1

### CODE REVIEW

**Comment by kripken** [comment]
Some internal error happended on our CI, and I can't retry it (which is very odd!). Please merge in latest incoming to here, that should fix it.

**Comment by abujalski** [comment]
Regarding CI see https://github.com/emscripten-core/emscripten/pull/8630#discussion_r285513943.

**Comment by kripken** [comment]
lgtm aside from the whitespace issue with indentation.

Yeah, weird about those CI issues... https://github.com/emscripten-core/emscripten/pull/8659 should fix that, and then we can merge incoming to here. But I'm really not sure why only in your PRs did this fail... puzzling.

**Comment by abujalski** [comment]
I reminded myself that I've wanted to check some failing tests and enabled CircleCI for my fork - I've there was some button but I don't remember now its name exactly. After that I was able to rerun CI on my fork, but then I've started to get this strange error.

So I suspect that when I've enable CI for my fork new version of validator, which is more strict, for yaml config file was deployed.

**Comment by kripken** [comment]
Interesting, yeah, I guess circleci got confused somehow because of an option.

Looks good, thanks!

**Pull request merged**
