### PR TITLE
Add sanitizer_common and ubsan from compiler-rt 8.0.0

### PR DESCRIPTION
**Pull request by quantum5**
As requested in #8651, the upstream code is here as a separate PR, and also sourced from a production release of LLVM. This should make it easier to review.

### CODE REVIEW

**Comment by quantum5** [comment]
There are a bunch of stuff that are omitted because they aren't used, like scripts we don't use that fails flake8, unit tests that we can't run, and the symbolizer which needs to be built with LLVM source, but otherwise, it's all the files from `compiler-rt/lib/{sanitizer_common,ubsan}`.

I can add these if you want.

**Comment by tlively** [comment]
No, I think it makes sense to leave that stuff out :+1: @aheejin any comments?

**Comment by aheejin** [comment]
- Does this `ubsan` directory replace `ubsan_minimal` you previously added?
- Could you add a brief description on what you omitted from the vanilla source? Your answer to @tlviely's comment answers somewhat answers it, but having it on the PR/commit description would be good too.

**Comment by quantum5** [comment]
This does not replace the minimal ubsan. Description of what is omitted will be added in the next update to this PR.

**Pull request merged**
