### PR TITLE
Remove sockets.test_webrtc test which has been disabled since 2015. NFC

### PR DESCRIPTION
**Pull request by sbc100**
This test was disabled back in 03ba458a1690cf5f6dce99e89ca901c3c00ec462.
Keeping this dead code around is a maintenance burden.  We can resurect
it from history if needed.

Also remove the third party code that was checked in for use only in this one
test.

Also remove the commented out test above.

### CODE REVIEW

**Comment by juj** [comment]
lgtm, this can go, not used anymore.

**Review by kripken — APPROVED** [review]
I remember when we played multiplayer BananaBread using WebRTC once... good times.

**Comment by juj** [comment]
There may still be some value in WebRTC - we have a research task on the board to experiment with transparently wrapping WebSockets+WebRTC+QuicTransport to a common app-level UDP+TCP API to enable networked apps to connect via whatever is the best available interface.

**Comment by kripken** [comment]
@juj Oh, that sounds cool! Would be nice to get benefit from WebRTC in this area.

**Pull request merged**
