### PR TITLE
file_packager: fix computation of `remote_package_name` when package is not at root

### LINKED ISSUE #21289: file_packager.py: REMOTE_PACKAGE_BASE does not work when data is not a the root
Please include the following in your bug report:

I'm using `emscripten/tools/file_packager.py` and I noticed something strange, and I guess it's an error

https://github.com/emscripten-core/emscripten/blob/21f25339df9c6aa8c288297de73236e6aaa79582/tools/file_packager.py#L765-L770

As you can see, the var `REMOTE_PACKAGE_BASE` has value `js_manipulation.escape_for_js_string(remote_package_name)`, which is equals to `remote_package_name = os.path.basename(package_name)
`

If during the packing phase, I want to put the data in a subfolder, let's say `build/php-web.data` with the option `--js-output=build/php-web.data.js`, I got the following code:

```js
var PACKAGE_NAME = 'build/php-web.data';
var REMOTE_PACKAGE_BASE = 'php-web.data';
```

And this looks wrong, because the data are in the `build/` directory.

---

The full command to reproduce:

```bash
'python3' \
    '/emsdk/upstream/emscripten/tools/file_packager.py' \
        'build/php-web.data' \
        '--use-preload-cache' \
        '--lz4' \
        '--preload', '/src' \
        '--js-output=build/php-web.data.js' \
        '--no-node' \
        '--exclude' '*/.*' \
        '--export-name=createPhpModule'
```

### PR DESCRIPTION
**Pull request by lyrixx**
fixes #21289

### CODE REVIEW

**Comment by sbc100** [comment]
Maybe we can write a test for this?  See the `test_file_packager..` tests in `test_other.py`.   The main `test_file_packager` looks like it already deals relative directory stuff so maybe we could update that, or create completely new test?

**Comment by lyrixx** [comment]
Hello, I tried to fix the broken tests `test.browser.test_output_file_escaping` but I cannot succeed :( 

I don't really know how I can fix thems. I really new to this ecosystem, and I don't know how the test suites works.

I'm deeply sorry, but I fear I'll not able to finish this PR. I would love to be able to finish it, but I miss time to learn.

**Comment by sbc100** [comment]
No problem @lyrixx.  Hopefully someone else can pick this up and get it landed.

BTW if you do want to run the tests locally you would use `./test/runner browser.test_output_file_escaping`  (See https://emscripten.org/docs/getting_started/test-suite.html#emscripten-test-suite)

**Comment by lyrixx** [comment]
Yes I did that. But then I don't really know how to fix the tests

**Comment by lyrixx** [comment]
I'm sorry, But i'll never be able to finish this PR. I think it's better to close it, to keep the number of PR close to 0

**Pull request closed without merging**
