### PR TITLE
Fix return code from alcMakeContextCurrent

### PR DESCRIPTION
**Pull request by sbc100**
Fixes: #11708

### CODE REVIEW

**Comment by kripken** [comment]
Reading the OpenAL docs I'm not sure if this change is correct or not - it doesn't say if null is a valid context or not (if not, it should return an error as it does now). That is on

https://www.openal.org/documentation/OpenAL_Programmers_Guide.pdf

Are there clearer docs?

**Comment by kripken** [comment]
Correct, but what should the return value be? "null" is ok to give to it, but does it count as a 'valid context'? Anyhow, maybe this is just obvious and I'm overthinking it...

**Review by kripken — APPROVED** [review]
OpenAL docs seem ambiguous to me, but if this looks right to you and the issue submitter then you are likely both right.

**Comment by sbc100** [comment]
> Correct, but what should the return value be? "null" is ok to give to it, but does it count as a 'valid context'? Anyhow, maybe this is just obvious and I'm overthinking it...

ACL_TRUE is returned in the function succeeds.  Here is an example implementation: https://github.com/blackberry/OpenAL/blob/631ad459dda5f5598863f7efc21070347aed757d/Alc/ALc.c#L2393

**Comment by kripken** [comment]
I see, thanks @sbc100 ! Easier to read implementations than specs sometimes :smile:

**Pull request merged**
