### PR TITLE
[embind] Cleanup createJsInvoker. NFC

### PR DESCRIPTION
**Pull request by sbc100**
I couple of minor cleanups:

1. I noticed that argCount was always followed by - 2.
2. I noticed that argsListWired was always being used `fn` as the first argument
3. The `argsLists` were being constructs as comma separated strings, which `join` is really good at.

### CODE REVIEW

**Comment by sbc100** [comment]
I guess we don't have any code size tests that include this function?

**Comment by brendandahl** [comment]
> I guess we don't have any code size tests that include this function?

Yeah, it looks like embind_val_hello_world.cpp only tests embind's `val`. We should expand the test or add another test that includes some `EMSCRIPTEN_BINDINGS`.

**Comment by sbc100** [comment]
With the new test from #22418 we can now see the code size improvment.

**Comment by sbc100** [comment]
ptal

**Review by brendandahl — APPROVED** [review]

**Pull request merged**
