### PR TITLE
add argument to emrun for file dump_out directory

### PR DESCRIPTION
**Pull request by arsnyder16**
add options for dump_out directory

I am not sure where the true emrun is i also made the following PR https://github.com/juj/emrun/pull/17. 

Also tweak the following.
* Unquote the file path passed in the request, this fix cases with spaces in the path 
* Build full directory structure for where the file should be dumped

### CODE REVIEW

**Comment by sbc100** [comment]
Maybe add to something to the emrun test in tests/test_browser.py?

**Review by sbc100 — APPROVED** [review]

**Review by juj — APPROVED** [review]
Great!

**Comment by juj** [comment]
> I am not sure where the true emrun is i also made the following PR [juj/emrun#17](https://github.com/juj/emrun/pull/17).

Yeah, I should probably sunset that repo - there are a few people that are still reading from there, but the development has moved to Emscripten repo practically fully.

**Comment by kripken** [comment]
The test failures here look random or stale. Please merge in latest `main`, that should fix them.

**Pull request merged**
