### PR TITLE
Fix lzma build on Cheerp

### PR DESCRIPTION
**Pull request by alexp-sssup**
Minor fix to build LZMA test using Cheerp. The only problem was that CFLAGS were not correctly used by the Makefile.

### CODE REVIEW

**Comment by kripken** [comment]
If cflags contains say `-O3`, would having `-O2` later override it? If not, then we may end up with different  opts in different places.

**Comment by alexp-sssup** [comment]
> If cflags contains say `-O3`, would having `-O2` later override it? If not, then we may end up with different opts in different places.

I would argue that the -O2 flag should not be there at all

**Comment by kripken** [comment]
Yeah, it could make sense that way. However, right now we don't set CFLAGS for anything but cheerp, so we'd need to set it in the others as well.

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

Re-opening and re-targeting to master.

**Pull request closed without merging**
