### PR TITLE
--extern-pre-js / --extern-post-js

### PR DESCRIPTION
**Pull request by kripken**
A request for these has come up now and then, but it's never been
urgent I guess and no one's submitted a PR. This came up again
now so I figured I'd do that.

The new options just prepend/append JS code, after all other
work has been done. A build system could just prepend/append
after emcc runs, but sometimes that's less convenient. For example,
in Binaryen we need something like this now that
`MODULARIZE_INSTANCE` is gone, and the build system there is
CMake, where there isn't an obvious simple way to append text
to a file that I am aware of.

Helps https://github.com/WebAssembly/binaryen/pull/2830

### CODE REVIEW

**Comment by sbc100** [comment]
Makes me sad to add more options like this, but I'm not going to block it.

Can we come up with a better name?  Something describes the reason you might want to use there options?

Can you explain why you don't what this parts going through the optimizer?  That might help us come up with a better name?

**Comment by kripken** [comment]
It's "external": on the outside of the actual emscripten output. So it's on the outside of the MODULARIZE scope if that option is used, outside of optimizations if they are done, etc. I thought for a while and "external" is the best I could find... I was quite happy actually until I read your comment :rofl: 

I don't feel strongly about this btw. But this has come up more than once in the past, and I suspect that there are users of `MODULARIZE_INSTANCE` (that don't read the mailing list or follow PRs here) that will be inconvenienced, and this option would help them (same as it can help binaryen, as I wrote above). Still, if there's a better idea (e.g. for binaryen) that sounds better.

**Comment by sbc100** [comment]
When you say `outside of the actual emscripten output` what does that mean?  In what sense if `pre-js` inside the emscripten output that this isn't?

Is it the fact the it doesn't get optimized?  Or is the fact that its outside the module scope?  Does this code run in a different scope the pre-js code?

**Comment by kripken** [comment]
I mean the emcc output is this:
```
extern-pre-js
NORMAL_EMSCRIPTEN_OUTPUT
extern-post-js
```
Literally the same as running
```
run emcc, get output
prepend extern-pre-js to that
append extern-post-js to that
```

**Comment by kripken** [comment]
> In what sense if pre-js inside the emscripten output that this isn't? Is it the fact the it doesn't get optimized?

That's the main thing, and the reason pre-js exists basically. pre-js also has various interactions with options, e.g. MODULARIZE puts it inside the module (this PR changes none of that).

**Comment by sbc100** [comment]
> I mean the emcc output is this:
> 
> ```
> extern-pre-js
> NORMAL_EMSCRIPTEN_OUTPUT
> extern-post-js
> ```
> 
> Literally the same as running
> 
> ```
> run emcc, get output
> prepend extern-pre-js to that
> append extern-post-js to that
> ```

I think the issue is that in my mental model thats what `--pre-js` and `--post-js` already do.  So I think other might be confused too.

Is the main purpose to keep it outside of the module in the MODULARIZE mode?   In which case how about `--pre-module-js` and `--post-module-js` and have them only work in MODULARIZE mode?  That would certainly seem more clear to me as a naive reader.

**Comment by kripken** [comment]
> I think the issue is that in my mental model thats what --pre-js and --post-js already do. So I think other might be confused too.

That's basically true, but the pre and post js files are also considered part of the emscripten output. So we optimize it all together, we instrument it all together, we put it all in the same scope if we MODULARIZE, etc.

The external stuff proposed here would be external to all that processing (so, not optimized, etc.).

> Is the main purpose to keep it outside of the module in the MODULARIZE mode?

No. The main point is not being part of the main JS we process and generate. Not being part of our main processed JS means:

* We don't optimize it.
* We don't instrument it with stuff like `SAFE_HEAP` or `GROWABLE*`
* We don't put it inside the module in MODULARIZE mode.

**Comment by kripken** [comment]
Note that the (existing) emcc docs for `--pre-js` start like this:

```
"--pre-js <file>"
   Specify a file whose contents are added before the emitted code and
   optimized together with it. [..]
```
So I think it is clear in the docs that pre-js optimizes together. This new thing would not.

**Comment by sbc100** [comment]
OK fair enough.  I do wish for a more meaningful, less overloaded term than `extern` but I can't think of one.

**Comment by kripken** [comment]
Add some docs improvements following this discussion.

**Pull request merged**
