### PR TITLE
Fix crash introduced in #22874

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Can we add a test for this?

**Comment by sbc100** [comment]
> Can we add a test for this?

I think writing an automated test would be non-trivial, and given how many gaps we have in automatic GUI testing I'm not sure its worth it.

**Comment by sbc100** [comment]
I think I would need to simulate a `visibilitychange` or `blur` event in between key presses.

**Comment by kripken** [comment]
I agree it's non-trivial, but I think we can simulate such events like we do keypresses and mouse moves, and interleave it with them. The order of such event handling is deterministic. I'm just worried we have big gaps in testing of those GUI APIs, and it would be good to think about improving it, basically.

**Comment by sbc100** [comment]
> I agree it's non-trivial, but I think we can simulate such events like we do keypresses and mouse moves, and interleave it with them. The order of such event handling is deterministic. I'm just worried we have big gaps in testing of those GUI APIs, and it would be good to think about improving it, basically.

I totally agree.   I'll take a look at this one.   My reaction was basically broken windows syndrome I suppose:  There are way bigger and more important gaps than this one :)

**Pull request merged**
