### PR TITLE
FS - Support both '/path' and '/path/' for directories

### PR DESCRIPTION
**Pull request by VirtualTim**
Previously trying to do something like `FS.mkdir('/a_directory/');` would throw. I think this change should fix all the related functions, since this seems to be the common point.

### CODE REVIEW

**Comment by VirtualTim** [comment]
Don't know if this is something people actually want, but figured I'd open a PR to see.

**Comment by kripken** [comment]
Thanks @VirtualTim!

Personally I have mixed feelings about this. Making the JS API nicer is fine, but if there is a cost to code size then I'm not sure it's worth it. Looking at the code here, I think it needs some more work to be correct, as right now it would return `base/` as the basename for `/foo/bar/base/`? (it leaves the slash in the basename) Fixing that isn't hard, but I feel maybe it isn't worth it. (Documenting this better seems uncontroversial, though.)

**Comment by VirtualTim** [comment]
> I think it needs some more work to be correct, as right now it would return `base/` as the basename for `/foo/bar/base/`?

Ah, you're right. Whoops. I thought that would be the way to minimise code size, but I forgot about the `path.substr`.

Personally my motivation was that I was trying to `FS.mkdir('/tmp/directory/')`, and that was throwing, and it took some time trying to track down what was wrong. But maybe logging something in an ASSERTIONS block, and updating the doco would be better?

**Comment by kripken** [comment]
Nice, attempt 2 is smaller and does handle the trailing `/`. The one downside I can see is that the `split` will allocate an array. Probably smart VMs can avoid much overhead there, but this is trading off code size for runtime overhead. I'm inclined to go with the change though so it also makes the API nicer. Maybe let's see if anyone else has thoughts or ideas before landing though.

**Comment by sbc100** [comment]
I agree that mkdir  '/path/' should work but I'm not totally sure that changing basename in this way is the way to fix it.  basename for a file ending in "/", at least in python, returns the empty string:

```
>>> os.path.basename("foo/bar")
'bar'
>>> os.path.basename("foo/bar/")
''
```

Perhaps have mkdir call some kind of `normpath` function to strip the trailing `/` instead?

Also, can you add a test?

**Comment by VirtualTim** [comment]
Hm, [POSIX basename](http://man7.org/linux/man-pages/man3/basename.3.html) performs differently... [Online example](http://cpp.sh/66i7d):
```
#include <iostream>
#include <libgen.h>

int main() {
    char path1[] = "foo/bar";
    char path2[] = "foo/bar/";
    printf("no-trailing:\t%s\n",  basename(path1));
    printf("trailing:\t%s\n",  basename(path2));
}
```
prints:
```
no-trailing:	bar
trailing:	bar
```
Also turns out there is also a [GNU version](https://linux.die.net/man/3/basename) which returns the empty string when path has a trailing slash, and in particular also when [the path] is "/".

So I guess for `basename` we should pick an existing spec to conform to (POSIX, GNU, Python), and then make things like `mkdir` work with that. Just as long as we don't go with [Node.js basename](https://nodejs.org/api/path.html#path_path_basename_path_ext).

**Comment by sbc100** [comment]
The deletion of the `incoming` branch triggered the automatic closing of this branch.  My apologies.  This was an unexpected side effect.

Re-opening and re-targeting to master.

**Comment by VirtualTim** [comment]
Well it's been a year, and no one seems to interested in this.
I still don't like that we have a basename implementation that's different from the POSIX one, but it's not that big a deal.

**Pull request closed without merging**
