### PR TITLE
Update SIMDe

### PR DESCRIPTION
**Pull request by ngzhian**

### CODE REVIEW

**Comment by ngzhian** [comment]
Going to resolve these first, marking as draft.

**Comment by ngzhian** [comment]
Upstream fix is included in this update, tests should go green now. Ready for review.

**Review by tlively — APPROVED** [review]
Rubberstamp LGTM. I noticed that there are some emscripten temp directly names in the output (e.g. emscripten_temp_3aigvmxa). It might be good in a follow up to have the update script scrub those to reduce unnecessary noise in the diffs when updating.

**Comment by ngzhian** [comment]
I can do that in a follow-up, meanwhile, the CI looks stuck, I'll put up another PR.

**Pull request closed without merging**
