### PR TITLE
Rebaseline code size test expectations. NFC.

### PR DESCRIPTION
**Pull request by sbc100**
Generated by running:

```
EMTEST_REBASELINE=1 ./tests/runner other.test_minimal_runtime_code_size*
```

### CODE REVIEW

**Comment by kripken** [comment]
#13936 just did this a few moments ago - I'm surprised there are any changes?

**Comment by sbc100** [comment]
Hmm.. I think maybe my llvm was at tot which has not rolled in yet.. checking

**Comment by sbc100** [comment]
These changes are valid according to llvm at dc35593e3f2bfd04d85cf151c97e0738ce66887e which is currently tot in emscripten-releases.

if you like you can confirm locally?

**Comment by sbc100** [comment]
I decided to split out the metadce change in tests_core.py: https://github.com/emscripten-core/emscripten/pull/13942

**Review by kripken — APPROVED** [review]

**Pull request merged**
