### PR TITLE
Deprecate `EM_LOG_FUNC_PARAMS` flag to emscripten_log/emscripten_get_callstack

### PR DESCRIPTION
**Pull request by sbc100**
Supporting this flag requires using `arguments.callee` which is deprecated, and won't work if any of functions on the callstack are in strict mode (or are arrow function, which implies strict mode).

The effect of these flag seem to not actually be tested, even though it is used in `test_emscripten_log`.

### CODE REVIEW

**Review by dschuff — COMMENTED** [review]
This should probably have a changelog entry.

**Comment by sbc100** [comment]
Done

**Comment by kripken** [comment]
Side note, I don't think arrow functions imply strict mode. They do have different behavior of `this` which is maybe more like strict mode, but that's all AFAIK? I see nothing on MDN otherwise.

**Comment by sbc100** [comment]
> Side note, I don't think arrow functions imply strict mode. They do have different behavior of `this` which is maybe more like strict mode, but that's all AFAIK? I see nothing on MDN otherwise.

Ah yes you are right.  But its not just `this`: `Arrow functions don't have their own bindings to this, arguments, or super`

**Pull request merged**
