### PR TITLE
Add check for not supported webassembly.exception.stack

### PR DESCRIPTION
**Pull request by ravisumit33**
`Webassembly.Exception.stack` is still on supported on latest safari browser (16.2). Although [MDN](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Exception) shows supported since 15.2 but its incorrect and I have reported the issue [here](https://github.com/mdn/browser-compat-data/issues/18938). As mentioned in the issue it can be easily verified by running below code:

```js
const tag = new WebAssembly.Tag({ parameters: ["i32"] });

function throw_exception_with_stacktrace(param) {
    return new WebAssembly.Exception(tag, [param], { traceStack: true });
}

const ex = throw_exception_with_stacktrace(42);
console.log(ex.stack);
```

Added a safety check in this PR for cases like this where stack comes undefined.

### CODE REVIEW

**Comment by ravisumit33** [comment]
@aheejin @sbc100 Please review.

**Review by sbc100 — APPROVED** [review]

**Review by aheejin — APPROVED** [review]

**Comment by aheejin** [comment]
I tried to run this but it says this. I tried logging out and back in both for Github and CircleCI to no effect. 
image

**Comment by ravisumit33** [comment]
> I can't see why circleci didn't run this.. can you maybe rebase and try again?

Rebased but CircleCI still showing the same error.

**Comment by ravisumit33** [comment]
retest

**Comment by sbc100** [comment]
I think this must be some kind of circle ci authentication issue.  Can you try logging into circleci to see the results?

**Comment by ravisumit33** [comment]
I wasn't logged in into circleCI earlier. I logged in but I can't re-trigger the job due to access issue.

**Comment by sbc100** [comment]
I don't really know what this issue could be.   Can you try rebasing one more time now that you have logged in?   Alternatively we could try simply closing this PR and opening another one.. seems unfortunate to have to do that :(

**Pull request closed without merging**
