### PR TITLE
Rebaseline code size tests

### PR DESCRIPTION
**Pull request by kripken**
Ran into the need for this because a reversion PR (#15460) fails unexpectedly.

### CODE REVIEW

**Comment by kripken** [comment]
@sbc100 This fails even though I just updated the numbers using `emsdk install tot`. And I verified the `tot` has not changed since I created the PR - `emsdk install tot` locally has nothing new to download. Do I need to do anything else to update these?

**Comment by sbc100** [comment]
> @sbc100 This fails even though I just updated the numbers using `emsdk install tot`. And I verified the `tot` has not changed since I created the PR - `emsdk install tot` locally has nothing new to download. Do I need to do anything else to update these?

No, I think that should work...

**Comment by kripken** [comment]
Very strange...

I guess I can update this file manually to the expectation. But I'm worried as that suggests different codegen is happening on my machine versus the bots.

If you have time can you see if rebaselining locally for you agrees with me or with the bots?

**Comment by sbc100** [comment]
> Very strange...
> 
> I guess I can update this file manually to the expectation. But I'm worried as that suggests different codegen is happening on my machine versus the bots.
> 
> If you have time can you see if rebaselining locally for you agrees with me or with the bots?

Sure.

My process is normally to build llvm and binaryen from source at ToT before doing the rebaselining, but I think emsdk tot should work just as well.

**Comment by kripken** [comment]
I've tried building locally, I've tried verifying I get the exact same emsdk hash as CI, but I still get the same difference...

Anyhow, there's clearly something wrong on either my machine or on CI. When you get a chance to compare @sbc100 let's see which results your machine agrees with.

**Comment by kripken** [comment]
It seems like the problem might be that I had newest emscripten+llvm+binaryen, but had not manually run `npm install`, so I was on an older closure. Hopefully that fixes it...

**Review by sbc100 — APPROVED** [review]

**Pull request merged**
