### PR TITLE
Make emscripten_webgl1_get_proc_address() aware of functions suffix.

### PR DESCRIPTION
**Pull request by paraboul**
Make emscripten_webgl1_get_proc_address() aware of functions suffix.

This fix an issue where emscripten_GetProcAddress() can't find functions with suffix because of strict lookup (they are currently unreachable)

### CODE REVIEW

**Comment by kripken** [comment]
Thanks for the PR!

I'm not entirely sure why those functions are strict (perhaps @juj can elaborate?) but can you call the non-strict one instead?

**Comment by paraboul** [comment]
To make it clean, currently there is no way for `emscripten_GetProcAddress()` to find a function with a suffix (provided or not).

e.g. both this call will fail.
```
emscripten_GetProcAddress("glBindVertexArray");
emscripten_GetProcAddress("glBindVertexArrayOES");
```

With the PR i'm submitting, both of these calls will succeed and find `glBindVertexArrayOES`.

**Comment by juj** [comment]
If one is using a WebGL 1 context that supports WebGL OES_vertex_array_object extension, then the following function pointer query calls should succeed

```c
emscripten_webgl1_get_proc_address("glBindVertexArrayOES");
emscripten_GetProcAddress("glBindVertexArrayOES");
```
and the following function pointer query call should fail
```c
emscripten_webgl1_get_proc_address("glBindVertexArray");
```
since no such function exists. Given that `emscripten_GetProcAddress` has had a history of being a "sloppy" compatible way to attempt to give the best match in any case, then calling
```c
emscripten_GetProcAddress("glBindVertexArray");
```
has also been made to succeed.

This PR would incorrectly make the function call
```c
emscripten_webgl1_get_proc_address("glBindVertexArray");
```
also succeed, which would be wrong: there is no such function in WebGL 1, but only the function `glBindVertexArrayOES` exists there.

If there's a bug that currently neither of 
```c
emscripten_GetProcAddress("glBindVertexArray");
emscripten_GetProcAddress("glBindVertexArrayOES");
```
will succeed, then that is indeed a bug, both of those should work - but it looks like the fix in the PR is in incorrect place? To make those succeed, `emscripten_webgl1_get_proc_address()` should not be reverted to also follow the sloppy search behavior. The intent is that `emscripten_webgl1_get_proc_address()` (and `emscripten_webgl2_get_proc_address`) should provide the strict/exact WebGL1/WebGL2 behavior, and the old `emscripten_GetProcAddress()` function will give the old legacy GL emulation related behavior.

**Comment by paraboul** [comment]
@juj Thanks for the reply.

Just pushed some changes to match the behaviour you described.
I couldn't find a cleaner way than adding a new `emscripten_webgl1_ext_get_proc_address` (and `emscripten_webgl2_ext_get_proc_address`) in order to decouple `emscripten_GetProcAddress` sloppy behaviour and `emscripten_webgl_get_proc_address()`.

It's needed because library_egl (and other gl frontend) are using emscriten_GetProcAddress (https://github.com/emscripten-core/emscripten/blob/incoming/src/library_egl.js#L706).

Let me know if you have a better idea, i'd be glad to help on this.

**Comment by paraboul** [comment]
Bump on this.
Sorry for bugging you. It's just that there is currently no way to `getProcAddr` a WebGL extension in the current release.

Thanks!

**Comment by paraboul** [comment]
Anything else I can do to get this merged?

For reference, I'm trying to get this bug fixed on Google's Skia with this : https://bugs.chromium.org/p/skia/issues/detail?id=8974

**Comment by kripken** [comment]
@paraboul sorry for the delay here. Would be best if @juj can review this, but if not, I think I understand his concerns from before, and I believe you addressed them.

Let's give @juj another day for this, if he has no concerns then I'll merge it.

**Comment by juj** [comment]
Sorry for the delay in coming back to review - have had only few extra cycles to attend to Emscripten side recently. Functionally this looks now good, the `emscripten_webgl1_get_proc_address()` and `emscripten_webgl2_get_proc_address()` functions now retain the strict behavior, while `emscripten_GetProcAddress()` restores the sloppy emulation behavior. Thanks for the fix!

However, there are odd naming discrepancies now in play here. The functions `emscripten_webgl1_get_proc_address()` and `emscripten_webgl2_get_proc_address()` have the "strict" semantics, but the new functions `emscripten_webgl1_ext_get_proc_address()` and `emscripten_webgl2_ext_get_proc_address()` implement "sloppy" semantics. Further, the existence and naming of these two new functions imply that the role of the functions `emscripten_webgl1_get_proc_address()` and `emscripten_webgl2_get_proc_address()` would be not to return function pointers to GL extensions (but the `_ext_get_` functions would do that) - but that is not the intent: both functions `emscripten_webgl1_get_proc_address()` and `emscripten_webgl2_get_proc_address()` can be used to query function pointers to extension functions.

Another naming inconsistency is that `emscripten_webgl1_ext_get_proc_address()` and `emscripten_webgl2_ext_get_proc_address()` have "public" API names, as if they are end user facing functions, but that was not the intent here, instead these are only meant for `emscripten_GetProcAddress()` to call internally.

Posted PR #8541 to rename the function names to avoid confusion from the above.

**Pull request merged**
