### PR TITLE
Fix AUDIO_WORKLET + MODULARIZE

### PR DESCRIPTION
**Pull request by sbc100**
Fixes: #21908

### CODE REVIEW

**Comment by sbc100** [comment]
Verified fix using interactive tests

**Comment by kripken** [comment]
Can you please explain why renaming this makes a difference? I can't figure it out.

**Comment by MuTsunTsai** [comment]
@kripken Looks like the key is adding `await` in this line:

https://github.com/emscripten-core/emscripten/blob/a36f43c1c3357442da300d43db7b363c74985e80/src/audio_worklet.js#L164

**Comment by juj** [comment]
LGTM, but has there been a semantics change to how MODULARIZE works? The `await` there is surprising to me.

**Comment by sbc100** [comment]
> LGTM, but has there been a semantics change to how MODULARIZE works? The `await` there is surprising to me.

With `MODULARIZE` the constructor functions has always returned a Promise of a module (IIUC, thats the main difference between `MODULARIZE` and now removed `MODULARIZE_INSTANCE`).   

There was a semantic change back in #21775 where the argument passed into the module constructor was not modified in-place.. this avoids leaking the module before the promise resolves.

**Comment by sbc100** [comment]
> Can you please explain why renaming this makes a difference? I can't figure it out.

Sorry the rename is unrelated.  I will revert that.

**Comment by sbc100** [comment]
Hopefully all these code will be removed soon anyway once I figure out how to inline the `ww.js` and `aw.js` files like I did for the pthread `worker.js`

**Comment by sbc100** [comment]
Simplified this PR by removing the rename.  PTAL.

**Comment by kripken** [comment]
Thanks @MuTsunTsai , I missed that part among the rest of the diff...

**Review by kripken — APPROVED** [review]
Can we add a test for this?

**Comment by sbc100** [comment]
> Can we add a test for this?

This failure was already showing up but only in the interactive tests... so it was already tests, just not by CI tests (that same goes for pretty much all our audio tests).

**Pull request merged**
