### PR TITLE
Emit length of the external_debug_info value

### PR DESCRIPTION
**Pull request by pfaffe**
The external_debug_info section contains a string which should be prefixed with an LEB encoded length (https://yurydelendik.github.io/webassembly-dwarf/#external-DWARF).

The length is currently missing.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks @pfaffe ! Please add yourself to AUTHORS before we merge.

**Comment by sbc100** [comment]
I can't see from the documentation there the LEB is mentioned.  Maybe I'm missing something?

Are there other tools that read/write this section?  How is it that we've managed to get away with this bug so far?  Will fixing it break some other tool?

@yurydelendik what was the intention here?  Should there be size LEB before the string data?

**Comment by yurydelendik** [comment]
`section_name = b'\x13external_debug_info' ` -- is `\x13` here expected LEB? 

> I can't see from the documentation there the LEB is mentioned. Maybe I'm missing something?

I guess `ed_data        ::= b∗:vec(byte)  ` shall be written as `ed_data        ::= name b∗:vec(byte) ` based https://webassembly.github.io/spec/core/binary/modules.html#custom-section example

> Are there other tools that read/write this section? How is it that we've managed to get away with this bug so far? Will fixing it break some other tool?

Not sure there are tools that reads this section. But based on the existing code it is not the issue thus patch is not correct. We need to fix the proposal text though.

**Comment by yurydelendik** [comment]
Okay, I misread asbytes(). So patch is good. LEB is part of `vec()` definition, it is not clear though from https://webassembly.github.io/spec/core/binary/conventions.html#binary-vec

**Comment by sbc100** [comment]
Also I guess this shows we have no tests for this?   Maybe OK for now?

**Comment by kripken** [comment]
To fix those tests, please merge in latest upstream to this branch.

I think I've seen other github repos that have a button that people can press to do that manually. Anyone know how those work?

**Pull request merged**
