### PR TITLE
Exit on llvm-nm failure rather than just warning.

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Review by kripken — APPROVED** [review]
Odd such a bug went unnoticed til now... I guess these errors are very rare?

**Comment by sbc100** [comment]
Oops, I guess we can't rely on this.. abandoning.

**Comment by kripken** [comment]
What was the problem? Do we have actual errors we need to ignore?

**Comment by sbc100** [comment]
Its valid to have non-object files in libraries so we have have to access object files where llvm-nm fails.   We even have a test for this that usefully caught this change before it landed!

**Pull request closed without merging**
