### PR TITLE
Handle relocations on the main module

### PR DESCRIPTION
**Pull request by kripken**
So it can dlopen itself properly. This fixes us after the breaking change on wasm globals to make them be objects. The fix is to move the relocation function around, and to just call it for the main module.

Disable some other dylink tests which hit a v8 bug

After this all tests should pass with new node on our CI.

### CODE REVIEW

**Comment by sbc100** [comment]
Hmm.. I'm surprised this wasn't already broken before since even if were exporting numbers directly we weren't adding memortBase.

**Comment by kripken** [comment]
Hmm, I disabled one more test now, on wasm2js. It has a hugely nested function there, and hits a stack recursion limit in newer node. That's not too surprising by itself as the limit is arbitrary. But apparently the limit is not fixed, since it passes some of the times - we may see more flakey tests like this :(

**Comment by sbc100** [comment]
I'm still in favor of using the current node release to do all our testing since that is going to close to what is shipped in stable chrome, and also closer to what node users on the server are probably using.

**Comment by kripken** [comment]
How old is v8 in the typical current node release?

**Comment by sbc100** [comment]
Thats a good question.   v8 versions don't seem to be listed here:  https://nodejs.org/en/about/releases/.    However you can bet that it will be older than chrome stable at any given time.  I'm pretty sure they would never pull a v8 version into a stable release of node that hadn't already shipped in chrome stable.  @mathiasbynens would have a better answer I'm sure.

**Comment by kripken** [comment]
> Hmm.. I'm surprised this wasn't already broken before since even if were exporting numbers directly we weren't adding memortBase.

Ah, you're right. Looking more closely, we do have another place that does relocations, the `NAMED_GLOBALS` stuff in emscripten.py,
```javascript
for (var named in NAMED_GLOBALS) {
  Module['_' + named] = gb + NAMED_GLOBALS[named];
}
```
So that also adds the base offset for main module symbols. I suspect somewhere if it can't find one it falls back to the other, but I haven't looked at this code for quite a while. (Trying to remove it breaks tests.)

**Pull request merged**
