### PR TITLE
Fix LZ4 file packaging support when MODULARIZE=1

### PR DESCRIPTION
**Pull request by mdboom**
This fixes a small bug that using the `--lz4` flag to `file_packager.py` doesn't work if `-s MODULARIZE=1`

### CODE REVIEW

**Comment by kripken** [comment]
Thanks, lgtm! Not sure why the build failed, I set it to re-run.

**Comment by kripken** [comment]
Something is very bad on the bots,
```
ERROR:root:Emscripten, llvm and clang repo versions do not match, this is dangerous (1.38.0, 1.38.12, 1.38.12)^M
```
Like it is getting the wrong emscripten version (1.38.0 instead of latest). No code change appears to have caused that, and it works on another PR. It's possible this PR was just lucky and got a bad build twice, or perhaps circle builds are not actually independent somehow...

Let me try to close and reopen this to start CI perhaps more from scratch.

**Comment by kripken** [comment]
Sorry about this @mdboom - I'm not sure what's going wrong with CI here.

Can you maybe push a commit to this branch that undos that one? I'm curious if making this PR a no-op will pass CI. If so, then maybe somehow the commit here is related to that breakage.

**Comment by mdboom** [comment]
The testing seems better now -- there is still 1 test in each of the browser jobs that seems to be failing that seems unrelated (maybe)...

**Comment by kripken** [comment]
The second, `./tests/runner.py  browser.test_fs_lz4fs_package`, actually does look related, I see it fail locally too. Looks like the issue is that LZ4 was not being exported, so in the non-modularize case it didn't work. This diff fixes it for me:
```
diff --git a/emcc.py b/emcc.py
index d84e79a..83afd51 100755
--- a/emcc.py
+++ b/emcc.py
@@ -1079,6 +1079,10 @@ There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR P
       if shared.Settings.EMULATE_FUNCTION_POINTER_CASTS:
         shared.Settings.ALIASING_FUNCTION_POINTERS = 0
 
+      if shared.Settings.LZ4:
+        # Let the file packager code access LZ4 on Module
+        shared.Settings.EXPORTED_RUNTIME_METHODS += ['LZ4']
+
       if shared.Settings.LEGACY_VM_SUPPORT:
         # legacy vms don't have wasm
         assert not shared.Settings.WASM, 'LEGACY_VM_SUPPORT is only supported for asm.js, and not wasm. Build with -s WASM=0'
diff --git a/src/modules.js b/src/modules.js
index c690bf1..bbc5c2f 100644
--- a/src/modules.js
+++ b/src/modules.js
@@ -387,6 +387,7 @@ function exportRuntime() {
     'FS_createDevice',
     'FS_unlink',
     'GL',
+    'LZ4',
     'staticAlloc',
     'dynamicAlloc',
     'warnOnce',
```
It would be good to add a MODULARIZE case to that test (not necessarily in this PR).

**Comment by kripken** [comment]
Any updates here @mdboom? Are you stuck on that test?

**Pull request closed without merging**
