### PR TITLE
Update FindOpenAL.cmake

### PR DESCRIPTION
**Pull request by Green-Sky**
as the [docs state](https://emscripten.org/docs/porting/Audio.html)

### CODE REVIEW

**Comment by sbc100** [comment]
Is this getting tested anywhere?

**Comment by kripken** [comment]
Looks like we do test OpenAL, but without `-lopenal`. The docs recommend using that as we may make it mandatory in the future, and it is required with strict mode I believe. So it's probably a good idea, I agree.

In fact maybe we should add that to one of the tests, to make sure, like `test_openal_error` in `tests/test_browser.py` for example?

Please also add yourself to AUTHORS, @Green-Sky - thanks!

**Comment by sbc100** [comment]
Right, but do we test our openal cmake plugin thing?  The thing this change effects?

**Comment by kripken** [comment]
Oh - I think we don't. I don't see any CMake + OpenAL tests.

**Comment by Green-Sky** [comment]
> Please also add yourself to AUTHORS, @Green-Sky - thanks!

done!

**Comment by kripken** [comment]
Great, thanks @Green-Sky!

**Pull request merged**
