### PR TITLE
Replace var with const/let in library_(html5_)webgpu.js

### PR DESCRIPTION
**Pull request by kainino0x**
~Needs rebase after #21454~

### CODE REVIEW

**Review by sbc100 — COMMENTED** [review]
The funny thing about using these newer constructs is that they can come with downsides:

1. At runtime IIUC `var` can be a little faster since `let` and `const` involve tracking some kind of dead zone information.
2. They can make the JS larger because `const` is a longer string that `var`
3. They prohibit closure from re-writeing all `var` declaration into a single one per function (since `let`/`const` inside blocks are not supposed to be visible outside block).

None of these are a huge deal.. but its why we haven't made efforts to convert over yet.

CC @syg

**Comment by kainino0x** [comment]
interesting, I had guessed that Closure's analysis would take care of problems like that. A transform must be required for targeting ES5 so I kind of assumed that they would just do it unconditionally instead of going through the work of preserving let/const when the target is ES6. Since they do variable renaming they already know what all the variables resolve to so I'd think they can do it without causing any observable behavior difference.

This comment does seem to agree with my suspicion although it's 3.5 years old. https://github.com/google/closure-compiler/issues/3680#issuecomment-689914335

**Comment by sbc100** [comment]
> interesting, I had guessed that Closure's analysis would take care of problems like that. A transform must be required for targeting ES5 so I kind of assumed that they would just do it unconditionally, instead of going through the work of preserving let/const when the target is ES6+. Since they do variable renaming, they already know what all the variables resolve to so I'd think they can do it without causing any observable behavior difference.
> 
> This comment does seem to agree with my suspicion, although it's 3.5 years old. [google/closure-compiler#3680 (comment)](https://github.com/google/closure-compiler/issues/3680#issuecomment-689914335)

It was my assumption that closure compiler would indeed do this, but last time I tried to do `var` -> `let` conversions they came with a code size code because of the lack of coalescing.   Might be worth further investigation?

**Comment by kainino0x** [comment]
Sounds like it's time to finally add a WebGPU code size test. I'll try to look into that next week.

**Comment by kainino0x** [comment]
Closing for now, filed as a bug in #22496.

**Pull request closed without merging**
