### PR TITLE
Add test for EM_JS and i64 arguments

### PR DESCRIPTION
**Pull request by sbc100**
See #15871

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
It looks like we have `other.test_EM_ASM_i64` which checks that this fails (without `WASM_BIGINT`). Maybe this PR can add to that test, or otherwise keep the two things close together?

Btw, that test shows that we fail to compile with EM_ASM. I wasn't aware that EM_ASM and EM_JS differed there...

**Comment by sbc100** [comment]
Added a check and error

**Comment by sbc100** [comment]
It makes sense to me to (a) have this test in core since it effect the JS/wasm boundary and (b) grouping em_js tests together makes sense to me.

**Review by kripken — APPROVED** [review]
Am I correct that EM_JS with i64 never worked, because while in theory the JS side could have two i32 params (the legalized i64), there is a single place defining the function for both JS and C, so the C would not have an i64 in that case? So writing an i64 there would not be possible with JS getting two legalized parameters. (Just checking this new error does not prevent anything that worked before.)

**Comment by sbc100** [comment]
> Am I correct that EM_JS with i64 never worked, because while in theory the JS side could have two i32 params (the legalized i64), there is a single place defining the function for both JS and C, so the C would not have an i64 in that case? So writing an i64 there would not be possible with JS getting two legalized parameters. (Just checking this new error does not prevent anything that worked before.)

Yes, you are mostly correct in your assessment I believe.    Using int64 with EM_JS results in the JS signature that doesn't match the one used in C, or that one called at runtime.  However its conceivable that you could ignore the JS arguments that instead just peek into `arguments` to make it work.    So its not completely impossible today.

I do plan to make this work in the long run.. so perhaps I should just make this into a warning rather than an error for now?

**Comment by sbc100** [comment]
I went with the warning instead..

**Pull request merged**
