### PR TITLE
WebGPU: fix memory leak when calling destroy on a buffer

### PR DESCRIPTION
**Pull request by kohakukun**
- Call custom emscripten `onUnmap` callbacks also when calling destroy on a buffer.

### CODE REVIEW

**Comment by kohakukun** [comment]
@kainino0x PTAL

**Review by kainino0x — APPROVED** [review]
Apologies for the delay, just got back from vacation. This looks great, nice catch and thank you for the fix!

**Comment by kainino0x** [comment]
Failure appears to be unrelated and happening on other PRs. @azakai could you help get this merged?

**Comment by kripken** [comment]
Sorry for the flakiness - we do have some recent issues there it seems... I restarted the tests a few times now til they passed.

**Pull request merged**
