### PR TITLE
Fix syncfs with existing directories

### LINKED ISSUE #12562: IDBFS syncfs should not throw error when directory timestamps change
`syncfs(true)` would try to create directories that already exist and fail.

`mayCreate` https://github.com/emscripten-core/emscripten/blob/81a65b1270c7c3017813ea50d9829843f0aa9df9/src/library_fs.js#L355

Called by `mknod` https://github.com/emscripten-core/emscripten/blob/81a65b1270c7c3017813ea50d9829843f0aa9df9/src/library_fs.js#L656

Called by `mkdir` https://github.com/emscripten-core/emscripten/blob/81a65b1270c7c3017813ea50d9829843f0aa9df9/src/library_fs.js#L676

Called by `storeLocalEntry` https://github.com/emscripten-core/emscripten/blob/e099f2ad1fe6b7af602683c6ea24eee07b748e18/src/library_idbfs.js#L172

It seems to be that there is a larger issue here in that directories cannot be synced when their `timestamp` change? This is different from the behavior of files since `writeFile` https://github.com/emscripten-core/emscripten/blob/e099f2ad1fe6b7af602683c6ea24eee07b748e18/src/library_idbfs.js#L174 overwrites a possible existing file by the same name.

This causes `syncfs(true)` to fail in some cases with a bogus `File Exists` (`EEXIST`) error.

I doubt this is intended.

(referenced https://github.com/emscripten-core/emscripten/pull/12560#issuecomment-713204657)

### PR DESCRIPTION
**Pull request by camilstaps**
This is the same PR as https://github.com/emscripten-core/emscripten/pull/12569, which was intended to fix an exception when `syncfs` encounters a directory which already exists. Modifications to the original PR:

- I have squashed the commits because the final diff was only one line. I hope this is fine with you @VinnyOG.
- A new test has been added (which is what prevented #12569 from getting merged).

Closes #12562.

### CODE REVIEW

**Comment by camilstaps** [comment]
I don't seem to have access to CircleCI t see the failing tests, if a maintainer could check what's going on there I would be very grateful!

**Comment by kripken** [comment]
(Sorry about the CircleCI test issue - that's a bug that they still haven't fixed. Anyhow, no tests look like they are affected by this PR.)

**Comment by VinnyOG** [comment]
Yeah looks good. We've been using this change in prod since I submitted the original PR. I just never got around to writing out the tests.

**Comment by kripken** [comment]
Great!

**Pull request merged**
