### PR TITLE
Improve error message for missing .emscripten file to advice "/emsdk activate latest" usage

### PR DESCRIPTION
**Pull request by ShahriyarR**
First PR :)
Based on this: [installing-the-portable-sdk](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#windows-osx-and-linux-installing-the-portable-sdk)

If you missed this step:

```
# Make the "latest" SDK "active"
./emsdk activate latest
```

The result will be something like:

```
./emcc tests/hello_world.c
Traceback (most recent call last):
  File "./emcc", line 11, in <module>
    import emcc
  File "/home/sh/REPOS/emscripten/emsdk_portable/emscripten/master/emcc.py", line 28, in <module>
    from tools import shared, jsrun, system_libs
  File "/home/sh/REPOS/emscripten/emsdk_portable/emscripten/master/tools/shared.py", line 205, in <module>
    raise Exception('File ' + EM_CONFIG + ' passed to --em-config does not exist!')
Exception: File /home/sh/.emscripten passed to --em-config does not exist!
```

It took me some time to figure out that, I have missed something.
The raised exception message is not quite informative so basically it can be improved to something like:

```
if EM_CONFIG and not os.path.isfile(EM_CONFIG):
  if EM_CONFIG.startswith('-'):
    raise Exception('Passed --em-config without an argument. Usage: --em-config /path/to/.emscripten or --em-config EMSCRIPTEN_ROOT=/path/;LLVM_ROOT=/path;...')
  if not '=' in EM_CONFIG:
    raise Exception('File ' + EM_CONFIG + ' passed to --em-config does not exist! Call "./emsdk activate latest" to create this file for you')
  else:
    EM_CONFIG = EM_CONFIG.replace(';', '\n') + '\n'
```

### CODE REVIEW

**Comment by kripken** [comment]
Thanks for the PR!

First thing, I'd like to understand if this isn't a bug in the SDK (and so perhaps the fix needs to go there?) - @juj, what do you think?

**Comment by hrj** [comment]
In my case, I encountered this when I installed on one machine, zipped the `emsdk_portable` folder and unzipped it on another machine. The new host where I had unzipped the installation didn't have the `.emscripten` file and gave this error.

**Comment by erlangp** [comment]
thanks @ShahriyarR

**Comment by juj** [comment]
> when I installed on one machine, zipped the emsdk_portable folder and unzipped it on another machine.

When doing this kind of installation, it is recommended to use the `--embedded` option to `emsdk activate` command, which will then write the `.emscripten` config file inside the `emsdk/` directory, after which you can use `source ./emsdk_env.sh` in the target directory without needing to `emsdk activate` after moving to the new system.

The reason why `--embedded` command was added was exactly to support this kind of "zip up in one system, unzip in another" use case.

If you don't want to use `--embedded` here, then certainly reinvoking `emsdk activate` is a good option to resolve this. I would however recommend changing the message from `Call "./emsdk activate latest" to create this file for you` to `If you are using emsdk, call "./emsdk activate <sdk|tool(s)>" to create this file for you`, since not all Emscripten users are bootstrapping via emsdk, and different users use different set of SDKs, so hinting that one would specifically have to pass `latest` here might be misleading (but instead one can activate any SDK they prefer).

**Comment by kripken** [comment]
This PR is quite old, closing. Feel free to reopen if still relevant.

**Pull request closed without merging**
