### PR TITLE
Ignore new clang -Wint-in-bool-context warning, which affects musl, compiler-rt, etc.

### PR DESCRIPTION
**Pull request by kripken**
Clang added a new warning, `-Wint-in-bool-context`, which warns on common stuff in musl, compiler-rt, etc., like `(x >> 1) ? y : z`. Instead of modifying a bunch of places in those projects, it seems best to ignore the warning in system libs for now, and eventually when we upgrade them they'll be fixed.

The new clang hasn't rolled, so CI here doesn't have a clang build that recognizes that, so temporarily pass `-Wno-unknown-warning-option` so we can pass here. That way we can keep all CI green while getting the LLVM roll in.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks @davidbolvansky, I subscribed to that review and I'll try after it lands.

**Comment by davidbolvansky** [comment]
It landed

**Comment by kripken** [comment]
Oh thanks, I don't read much LLVM reviews and I missed the landed part there. Yes, looks like we don't need the workaround anymore, I opened #9508

**Comment by davidbolvansky** [comment]
Thanks :)

**Pull request merged**
