### PR TITLE
cmake: Update to work with cmake 3.15 and later.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
CMake 3.15 and later weren't correctly handling `CMAKE_CXX_STANRDARD`
and friends when using the emscripten cmake modules. This was because
there is a new variable that needs to be set to indicate whether
the compiler is using GNU or MSVC command line options.

### CODE REVIEW

**Comment by kripken** [comment]
Thanks @waywardmonkeys!

I don't know much about this, and I can't find any docs for that new option? Is it very new?

Btw, would this fix issues like https://github.com/emscripten-core/emscripten/issues/9100 (which refers to the same `CMAKE_CXX_STANRDARD`)?

**Comment by waywardmonkeys** [comment]
> Thanks @waywardmonkeys!
> 
> I don't know much about this, and I can't find any docs for that new option? Is it very new?
> 

It is new to cmake 3.15 and is basically an internal detail of cmake. I don’t think it is documented.

> Btw, would this fix issues like #9100 (which refers to the same CMAKE_CXX_STANRDARD)?
> 

Yes, that is what this fixes.

The test that doesn’t fail mentioned in that issue is because it would only fail with cmake 3.15 and later.

 - Bruce

**Comment by kripken** [comment]
Sounds good to me, thanks!

**Comment by bradking** [comment]
FWIW, setting this internal undocumented CMake variable is necessary only because emscripten is already setting other internal undocumented CMake variables:

```cmake
	set(CMAKE_C_COMPILER_ID_RUN TRUE)
	set(CMAKE_C_COMPILER_FORCED TRUE)
	set(CMAKE_C_COMPILER_WORKS TRUE)
```

Those block some of CMake's internal steps that it uses to populate other internal variables.  Therefore any time CMake adds an internal variable, toolchain files doing the above will need to be updated.  This is not supported by upstream CMake.

**Comment by kripken** [comment]
Interesting, thanks @bradking. cc @juj who may have thoughts here too.

**Comment by juj** [comment]
Thanks for the insight @bradking! The specific directives were added originally to fix issue https://github.com/emscripten-core/emscripten/issues/4129 (was originally #4134, landed in #4571), but perhaps the fix was not appropriate. I recall there was interest to add the prepopulated IDs also since having CMake run through the IDing would be slow, since it was driving many test compilations through Emscripten, which takes noticeably more time than on native platforms.

**Comment by bradking** [comment]
@juj CMake 3.15 comes with changes that reduce the number of checks it needs to run (particularly for compile features) with modern compilers.  I encourage you to at least let CMake detect the compiler id which requires only a single invocation of the compiler and populates many internal values.

**Comment by Lectem** [comment]
I can confirm that removing all the code in the branch
```
if(EMSCRIPTEN_FORCE_COMPILERS)
```
Works fine in CMake 3.15 (though still a bit slow but not that bad).
I was able to compile both a c++11 and c++17 code.

I'm not sure about other CMake versions

**Comment by juj** [comment]
Benchmarking CMake 3.12 and CMake 3.15 with predetecting compiler vs not, the timings to run CMake are:

CMake 3.12 predetected compiler: 0.8 seconds
CMake 3.12 no predetected compiler: 18.3 seconds
CMake 3.15 predetected compiler: 1.1 seconds
CMake 3.15 no predetected compiler: 8.5 seconds

CMake 3.15 is much better, but still there is a jarring difference. :/

Commenting out the compiler ID variables, i.e.
```diff
-       set(CMAKE_C_COMPILER_ID_RUN TRUE)
+#      set(CMAKE_C_COMPILER_ID_RUN TRUE)
        set(CMAKE_C_COMPILER_FORCED TRUE)
        set(CMAKE_C_COMPILER_WORKS TRUE)
        set(CMAKE_C_COMPILER_ID Clang)
        set(CMAKE_C_COMPILER_FRONTEND_VARIANT GNU)
        set(CMAKE_C_STANDARD_COMPUTED_DEFAULT 11)
 
-       set(CMAKE_CXX_COMPILER_ID_RUN TRUE)
+#      set(CMAKE_CXX_COMPILER_ID_RUN TRUE)
        set(CMAKE_CXX_COMPILER_FORCED TRUE)
        set(CMAKE_CXX_COMPILER_WORKS TRUE)
        set(CMAKE_CXX_COMPILER_ID Clang)
```

results in CMake run taking up about half the time from full run, i.e. 4.5 seconds, and looks like it results in two invocations of Emscripten version checks, and two build invocations of the compiler.

To me it seems that the time difference is still too large that Emscripten takes too long to run the compiler detection. I hope that we have a good enough test in place with `python tests/runner.py other.test_cmake` to keep in check if the fields change in upstream CMake.

**Pull request merged**
