### PR TITLE
Run ./tools/update-symbols.py to regenerate symbols files

### PR DESCRIPTION
**Pull request by sbc100**
These are three different sets of change here:
    
- New "noexcept" files.  These should have been added in #9478
- New compiler-rt symbols for wasm. These should have been part of #9482
- `__THREW__` and other exception-related sybmosl added to libc++abi 
  and libc++abi-mt.   I'm not sure about these..

### CODE REVIEW

**Comment by kripken** [comment]
`__THREW__` etc. do seem odd. Maybe good to check if they actually didn't exist before, as it seems that symbol at least always should have been.

**Comment by sbc100** [comment]
`__THREW__` and   the `__cxa` functions are all undefined symbols that get generated by the llvm backend.  Here they are getting added to the list of symbols needed by the regular version of libc++abi.. not the noexcept version.  So its seems to make sense that they should be there.  I'm just not sure what change would have triggered them to appear.

**Comment by sbc100** [comment]
I found the culprit: #9478.  With this change libc++abi split into libc++abi and libc++abi-noexcept.

This has the effect of adding `-s DISABLE_EXCEPTION_CATCHING=0` to the exception handling version.    So we starting adding exception catching to libc++abi.  I'm not sure if that was indented. 

Either way this change is good as its simply reflects the current state.

**Comment by hujiajie** [comment]
Will you be interested in adding a check in the CI, so that one won't forget to run update_symbols.py in the future?

**Comment by sbc100** [comment]
Yes, although I'm hoping to land #9457 soon which will significantly reduce out dependence on these symbols files.

**Pull request merged**
