### PR TITLE
Pass -fno-threadsafe-statics when not building for pthreads

### PR DESCRIPTION
**Pull request by sbc100**
This means the compiler won't generate calls
`__cxa_guard_acquire`/`__cxa_guard_release` around static intitializers.
Even through those funtions don't really do much in non-threads builds
(since lockas and atomics don't do much) it seems that neither llvm nor
binaryen can completely remove them.

For example:

```
int foo() {
  return 42;
}

int main() {
  static int a = foo();
  return 0;
}
```

When compiled, without threading normally generates this code:

```
0000ef func[2] <main>:
 0000f0: 02 40                      | block
 0000f2: 41 b8 08                   |   i32.const 1080
 0000f5: 2d 00 00                   |   i32.load8_u 0 0
 0000f8: 41 01                      |   i32.const 1
 0000fa: 71                         |   i32.and
 0000fb: 0d 00                      |   br_if 0
 0000fd: 41 b8 08                   |   i32.const 1080
 000100: 10 05                      |   call 5 <__cxa_guard_acquire>
 000102: 45                         |   i32.eqz
 000103: 0d 00                      |   br_if 0
 000105: 41 b8 08                   |   i32.const 1080
 000108: 10 0d                      |   call 13 <__cxa_guard_release>
 00010a: 0b                         | end
 00010b: 41 00                      | i32.const 0
 00010d: 0b                         | end
```

With `-fno-threadsafe-statics` we get just:

```
0000cb func[1] <main>:
 0000cc: 41 80 08                   | i32.const 1024
 0000cf: 2d 00 00                   | i32.load8_u 0 0
 0000d2: 45                         | i32.eqz
 0000d3: 04 40                      | if
 0000d5: 41 80 08                   |   i32.const 1024
 0000d8: 41 01                      |   i32.const 1
 0000da: 3a 00 00                   |   i32.store8 0 0
 0000dd: 0b                         | end
 0000de: 41 00                      | i32.const 0
 0000e0: 0b                         | end
```

### CODE REVIEW

**Comment by sbc100** [comment]
Attempt at doing this upstream: https://reviews.llvm.org/D118571

**Comment by kleisauke** [comment]
> This should always be safe because, in WebAssembly, it is not
possible to link object compiled without the atomics feature into a
mutli-threaded program.

Ah, great. I was just about to ask that.

**Comment by kleisauke** [comment]
Note that we could extend `other.test_cxx11` to check whether `-fno-threadsafe-statics` is effective. For example:
```diff
--- a/tests/hello_cxx11.cpp
+++ b/tests/hello_cxx11.cpp
@@ -9,6 +9,10 @@
 #error This file should be compiled with -std=c++11!
 #endif
 
+#ifdef __cpp_threadsafe_static_init
+#error This file should be compiled without -pthread!
+#endif
+
 int main( int argc, const char *argv[] ) {
   printf("Hello world!\\n");
   return 0;
```

**Comment by sbc100** [comment]
Good idea!

**Review by kripken — APPROVED** [review]

**Pull request merged**
