### PR TITLE
Remove CyberDWARF from docs and library code

### PR DESCRIPTION
**Pull request by sbc100**
Fixes: #12194

### CODE REVIEW

**Review by kripken — APPROVED** [review]

**Comment by polx** [comment]
... and it would be interesting to have hints on where to get a better C-level debugging... Today no dwarf debugging is working (and maybe tomorrow some will). Cyberdwarf was a hope.

**Comment by sbc100** [comment]
@kripken can you take care of removing CyberDWARF.html from the website?  Perhaps you update script is not deleting stale files?

**Comment by kripken** [comment]
@sbc100 Done, sorry for the confusion.

@polx DWARF debugging should definitely be working today, though it does require a few extra steps. See https://developer.chrome.com/blog/wasm-debugging-2020/ Let us know if you find any issues!

**Comment by polx** [comment]
Thanks @sbc100 and @kripken : CyberDWARF debugging is now 404.

Thanks @kripken about the hint "it should work". I had followed the tutorial of Google there but had believed that the C source files weren't indexed since they were not displayed among the sources. 
Having used cmd-P to ask for it made it work! What a wonder and what a luxury to see properly named C variables, object-classes... 
Using `-g3` and source maps seemed also to prevent dwarf output but I haven't inspected deeply (if there's a way to generate both, that should be the default debug output, I feel, even if very resource-hungry). Using `-g` got me dwarf and that's enough for my project today.

A bright future ahead!

**Pull request merged**
