### PR TITLE
Update codesize changes after wasm-ld string merging enabled

### PR DESCRIPTION
**Pull request by sbc100**
See: https://reviews.llvm.org/D97657

These are mostly wins, but there are couple of very small
regressions that I don't understand yet.

### CODE REVIEW

**Comment by sbc100** [comment]
Attached one of the wasm files that oddly regressed here
 
[wasm_files.zip](https://github.com/emscripten-core/emscripten/files/6395610/wasm_files.zip)

**Comment by kripken** [comment]
Diffing those files, it looks like LLVM has optimized some code in a very different way. In particular there is one less loop (!) in the "good" (smaller) file. I'm not sure what LLVM optimization would do changes like that.

Is the "good" file older, and "bad" newer? Then I'd bet there's a new LLVM optimization that breaks off part of a loop into another loop right before it. Can maybe bisect to verify, but it seems unrelated to your string merge changes?

**Comment by sbc100** [comment]
> Diffing those files, it looks like LLVM has optimized some code in a very different way. In particular there is one less loop (!) in the "good" (smaller) file. I'm not sure what LLVM optimization would do changes like that.
> 
> Is the "good" file older, and "bad" newer? Then I'd bet there's a new LLVM optimization that breaks off part of a loop into another loop right before it. Can maybe bisect to verify, but it seems unrelated to your string merge changes?

Yes, good is the older file and bad is with string merging.   Thats the only difference.   So any code changes must be from binaryen I imagine.

**Comment by sbc100** [comment]
> > Diffing those files, it looks like LLVM has optimized some code in a very different way. In particular there is one less loop (!) in the "good" (smaller) file. I'm not sure what LLVM optimization would do changes like that.
> > Is the "good" file older, and "bad" newer? Then I'd bet there's a new LLVM optimization that breaks off part of a loop into another loop right before it. Can maybe bisect to verify, but it seems unrelated to your string merge changes?
> 
> Yes, good is the older file and bad is with string merging. Thats the only difference. So any code changes must be from binaryen I imagine.

I guess I can take a look at the bare wasm-ld output and compare that to be sure.  I will do that later..

**Comment by kripken** [comment]
> Yes, good is the older file and bad is with string merging. Thats the only difference. So any code changes must be from binaryen I imagine.

Wait, there are really no other LLVM changes in the middle? This really looks like different LLVM optimizations being hit...

Yes, looking at the bare wasm-ld output might clarify this. Maybe somehow the string change leads the LLVM optimizer to take different paths..?

(I do not see how binaryen could cause changes like this. We don't have an optimization that can split loops. I suppose in theory there could be some other combination of opts that has an effect that looks like that, though, but seems very theoretical...)

**Comment by sbc100** [comment]
> > Yes, good is the older file and bad is with string merging. Thats the only difference. So any code changes must be from binaryen I imagine.
> 
> Wait, there are really no other LLVM changes in the middle? This really looks like different LLVM optimizations being hit...
> 
> Yes, looking at the bare wasm-ld output might clarify this. Maybe somehow the string change leads the LLVM optimizer to take different paths..?
> 
> (I do not see how binaryen could cause changes like this. We don't have an optimization that can split loops. I suppose in theory there could be some other combination of opts that has an effect that looks like that, though, but seems very theoretical...)

I'm pretty sure the only change is the string merging which happens in the linker *after* llvm codegen.. even when LTO is involved it always after codegen.

**Comment by sbc100** [comment]
[results.zip](https://github.com/emscripten-core/emscripten/files/6396336/results.zip)

**Comment by sbc100** [comment]
Indeed.  The emcc-0-base.wasm output by the linker for this example differs only in the layout of the data segment.   Instructions are identical at that point.  So divergence here must be due to binaryen or some other post-link passes.

**Comment by kripken** [comment]
Really... how interesting. I'll take a look at the binaryen optimizer on this after lunch.

If you see this before then, for which test is that (so I know what opts to run)?

**Comment by sbc100** [comment]
These are the results for `other.test_minimal_runtime_code_size_hello_webgl_wasm2js`

**Comment by kripken** [comment]
Fascinating...

Ok, what seems to happen is this: only static locations of strings are changed. But the code cares about the alignment of those static positions... and the alignment changed.

Before, we had this:
```wat
  (local.set $3
   (i32.const 1024)
  )
  (block (result i32)
   (local.set $0
    (local.get $3)
   )
   (block $label$1
    (if
     (i32.and
      (local.get $3)
      (i32.const 3)
     )
```
and after we have this:
```wat
  (local.set $3
   (i32.const 1045)
  )
  (block (result i32)
   (local.set $0
    (local.get $3)
   )
   (block $label$1
    (if
     (i32.and
      (local.get $3)
      (i32.const 3)
     )
```

The only difference between those snippets is `1024` turned into `1045`. But that matters, because lower down we do `num & 3`, and that returns 0 for 1024 but 1 for 1045...

So the binaryen optimizer is indeed doing something different. Before it could see that the if condition was always 0, and it removed the entire if and the loop inside if (that's why a loop vanished...). After, it thinks the if condition is always 1, so the code sticks around.

So my guess is that the string deduplication in LLVM is not aware that it needs to keep that particular string aligned, or something like that? Looks like a bug, as the new code behaves potentially different than the old.

**Comment by sbc100** [comment]
Great!   That kind of fits and is the kind of issue I would expect to see with string merging.

So you know which string in particular is causing the issue?  (I guess I can just look at the binary and its the first string in bare binary (at 1024?)).

**Comment by kripken** [comment]
Yes, the problem is the string at absolute offset 1024 that was moved to 1045.

**Comment by kripken** [comment]
Btw, it's possible this is not a bug. It could be that the string is ok to be moved to an unaligned address, and that the function we are talking about is `memcpy` or such - and the code that used to vanish was the alignment optimization loop. I suspect that's the case because this happens after DeadArgumentElimination (i.e. DAE sees there is a single call to that function, removes the argument, and places the const in the function instead), and also the code looks like an alignment pre-loop. To confirm that, can build with enough debug info to see the function name.

If so, then this may not need to be fixed, if the string just happened to be lucky enough to be at an aligned address before. But otherwise even just for speed it would be good to keep them aligned.

**Comment by sbc100** [comment]
> Btw, it's possible this is not a bug. It could be that the string is ok to be moved to an unaligned address, and that the function we are talking about is `memcpy` or such - and the code that used to vanish was the alignment optimization loop. I suspect that's the case because this happens after DeadArgumentElimination (i.e. DAE sees there is a single call to that function, removes the argument, and places the const in the function instead), and also the code looks like an alignment pre-loop. To confirm that, can build with enough debug info to see the function name.
> 
> If so, then this may not need to be fixed, if the string just happened to be lucky enough to be at an aligned address before. But otherwise even just for speed it would be good to keep them aligned.

I see that makes sense now.

The linker will honor alignment, but C strings default to align of 1..  we could propose changing that but that is unrelated to this change I believe.   (it would also probably defeat string merging in most cases).

**Comment by sbc100** [comment]
So are you OK with this tiny regression?   I think we can move forward with the llvm string merging change because:

1. Most of the change here are improvments.
2. This regressions we see here is due to reordering strings .. which could happen just as easily by just adding strings to the input program.
3. But bug improvements will come in larger programs with more strings

**Comment by kripken** [comment]
I'm ok with everything if

* We are sure string merging does not change the required alignment.
* We are sure string merging does not increase the chance to be misaligned. That is, that LLVM did not previously overly-align things, and the string merging decreases that to the actual required alignment which was lower. (My guess is that it's not a problem, as I see unaligned offsets before as well.)

**Comment by dschuff** [comment]
IMO it probably makes sense to go ahead with this. There are benefits of having strings aligned, e.g. speed of memcpy/strcmp/etc (can't really think of other speed benefits?) and size when the aligned/unaligned case can be eliminated, don't seem to be super common. 
Also: did we previously separate strings into an rodata section? If so, then they presumably got laid out kind of randomly-unaligned (if we assume strings usually don't have lengths that happen to be aligned), so this probably won't change much overall. Otherwise if they were previously laid out interspersed with other data types, I'd expect that they would more commonly end up aligned on a 4 byte boundary and maybe it would happen a little more.

**Comment by sbc100** [comment]
> I'm ok with everything if
> 
> * We are sure string merging does not change the required alignment.

I'm adding more tests on the llvm side to verify this and more.   The linker is not ever allowed to change the alignment of anything.. it would be linker bug if it did.

> * We are sure string merging does not increase the chance to be misaligned. That is, that LLVM did not previously overly-align things, and the string merging decreases that to the actual required alignment which was lower. (My guess is that it's not a problem, as I see unaligned offsets before as well.)

Any relative layout and over alignment in input object files is already completely ignored.  All llvm can do is specify the alignment of given chunk of data and the linker must obey that.. but relative placement of the chunk is otherwise completely up to the linker.  (llvm obviously controls data layout with each chunk and the linker can't touch that).

**Comment by sbc100** [comment]
> IMO it probably makes sense to go ahead with this. There are benefits of having strings aligned, e.g. speed of memcpy/strcmp/etc (can't really think of other speed benefits?) and size when the aligned/unaligned case can be eliminated, don't seem to be super common.
> Also: did we previously separate strings into an rodata section? If so, then they presumably got laid out kind of randomly-unaligned (if we assume strings usually don't have lengths that happen to be aligned), so this probably won't change much overall. Otherwise if they were previously laid out interspersed with other data types, I'd expect that they would more commonly end up aligned on a 4 byte boundary and maybe it would happen a little more.

Ah yes, that is one change I'd not considered.  Previously string data and other `rodata` were in the same segment and interspersed.  Now string data will all be grouped together it is own segment.

**Comment by sbc100** [comment]
@kripken PTAL

**Review by kripken — APPROVED** [review]

**Pull request merged**
