### PR TITLE
Remove polyfills for Fetch and Object.assign

### PR DESCRIPTION
**Pull request by sbc100**
This change required the minimum supported browser versions to be bumped just a little.

### CODE REVIEW

**Comment by sbc100** [comment]
@kripken @dschuff WDYT about bumping the min browser versions a little more for this release?

**Comment by dschuff** [comment]
I guess the question is what do we lose from dropping these. People wanting to target really old browsers will either have to bundle their own versions of these polyfills (short term) and in the long term there may be other things that we drop support for (although since we don't actually test on those browser versions, there could be other things we depend on that we aren't aware of). If someone is targeting those old browsers today and is unable to update emscripten anymore, what do they lose? most of the work on emscripten these days is targeting modern development (new Wasm features, modern tooling, etc). It doesn't seem too likely that they would benefit from much of that work anyway. And 8 years is still pretty good. I think I'm OK with this.

**Comment by sbc100** [comment]
> I guess the question is what do we lose from dropping these. People wanting to target really old browsers will either have to bundle their own versions of these polyfills (short term) and in the long term there may be other things that we drop support for (although since we don't actually test on those browser versions, there could be other things we depend on that we aren't aware of). 

Yes, there are many other tools out there than can bundle JS for very old browsers and supply pollyfils for the very long tail of users who are targeting 10 year old browsers, but honestly I'm not sure sure if there are any such emscripten users.   Perhaps I'll send a message the mailing list to see any anyone responds.

> If someone is targeting those old browsers today and is unable to update emscripten anymore, what do they lose? most of the work on emscripten these days is targeting modern development (new Wasm features, modern tooling, etc). It doesn't seem too likely that they would benefit from much of that work anyway. And 8 years is still pretty good. I think I'm OK with this.

**Review by kripken — APPROVED** [review]
lgtm unless we get feedback on the mailing list or [bluesky](https://bsky.app/profile/did:plc:ynytall76qraih77z4gfwomw/post/3lcxrmbdr622j) with a use case that justifies keeping this

**Pull request merged**
