### PR TITLE
Add `emscripten_memset_big` based on `HEAPU8.fill()`

### PR DESCRIPTION
**Pull request by sbc100**
Improves benchmark.test_memset_1mb from 500ms to 170ms.

This should help with #18628.

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
The code size regression here is unfortunate. How far away is the improvement to use bulk memory, do you think? If that's close then this doesn't worry me.

**Comment by sbc100** [comment]
> The code size regression here is unfortunate. How far away is the improvement to use bulk memory, do you think? If that's close then this doesn't worry me.

The change is already done: https://github.com/emscripten-core/emscripten/commit/ac79510f47d17eedc7117d800bed1eef1c4a0848.  Its that it we might not be able to enable it by default for while.

**Comment by sbc100** [comment]
BTW, did you see that these JS helper function are not defined when `SHRINK_LEVEL < 2`?  We continue to have a completely different code path for `EMSCRIPTEN_OPTIMIZE_FOR_OZ` in `emscripten_memset.c`.. so folks that really care about code size won't be effected at all.

**Comment by kripken** [comment]
Good point that `-Oz` is unaffected. And good to know bulk memory is ready for when browsers are.

Still, as we are stopping the zeroing out of the stack, is this urgent to land? After we don't zero, do we have benchmarks that this helps with? I'm just suggesting that we can wait on landing this for when there's a clear need, or after bulk memory is on by default.

**Comment by sbc100** [comment]
This helps with the `benchmark.test_memset_1mb` and I imagine with all the other `test_memset_xx` benchmarks (although I guess you are asking about non-micro-benchmarks here?).   Its not really related to the pthread stack issue.   Anyone doing memset on anything larger than 256 should benefit.    

I guess memcpy is more common than memset which is why one might argue for a world in which we have  `emscripten_memcpy_big` but not `emscripten_memset_big`?

**Comment by kripken** [comment]
Yes, that's what I'm thinking. memcpy is just so common we've seen it on benchmarks and so we've optimized it. While the pthreads issue is the first time I've seen memset be worth optimizing. It's possible it's more common than I think, but given the current code size downside, I'm not sure if it's worth it. I lean towards waiting for bulk memory, since we've waited so far anyhow.

**Pull request closed without merging**
