### PR TITLE
Export cDefs.SIG* signals

### PR DESCRIPTION
**Pull request by RReverser**
This is useful for external --js-libraries.

### CODE REVIEW

**Review by sbc100 — COMMENTED** [review]
In general I've been trying to avoid putting anything in here that isn't directly used by the core library. 

I even have a tool to help me cleanup such things: tools/maint/check_struct_info.py.


However, I guess we could consider relaxing that rule.    Can you explain your use case a little?

**Comment by RReverser** [comment]
Well my xterm-pty integration - that is meant to be just a `--js-library` - needs to raise signals in Emscripten. The core library emits those signals as names, and then I want to do things like

```js
let signalNameToCode = {
  'SIGINT': {{{ cDefs.SIGINT }}},
  'SIGWINCH': {{{ cDefs.SIGWINCH }}},
  ...
};
```

I could inline constants myself, but it seemed cleaner to have those exposed by Emscripten instead.

**Comment by sbc100** [comment]
I wonder if you could add `_SIGINT` and `_SIGWINCH` as `__deps` in your library to export those two symbols and then use them directly as `SIGINT` and `SIGWINCH` in your JS library function?

**Comment by sbc100** [comment]
> I wonder if you could add `_SIGINT` and `_SIGWINCH` as `__deps` in your library to export those two symbols and then use them directly as `SIGINT` and `SIGWINCH` in your JS library function?

Ah not that don't work since they are not symbols, but macros :(

**Comment by sbc100** [comment]
Maybe you could just add the ones you need with a comment about how/where they are useful?

**Comment by sbc100** [comment]
Really we need a mechanism for adding custom `cDefs` entries in user-specified JS libraries.. but that sounds tricky.

**Comment by RReverser** [comment]
If it's too much of a trouble it's honestly not a big deal, I can just inline the constants myself for now since it's only like 4 of them I need.

> Really we need a mechanism for adding custom `cDefs` entries in user-specified JS libraries.. but that sounds tricky.

Yeah this would be best. It's currently not very clear what utilities external `--js-library` libs can or cannot depend on.

**Comment by sbc100** [comment]
> If it's too much of a trouble it's honestly not a big deal, I can just inline the constants myself for now since it's only like 4 of them I need.
> 
> > Really we need a mechanism for adding custom `cDefs` entries in user-specified JS libraries.. but that sounds tricky.
> 
> Yeah this would be best. It's currently not very clear what utilities external `--js-library` libs can or cannot depend on.

Yes, that is more general problem that I'm not sure how to solve.  I guess we use name mangling?   @juj has always argued that use `--js-library` files should have full access to all the same functions as internal libraries.   I'm not sure about that since it limits are ability to refactor internally.   I did add an `__internal` decorator that explicitly prevents external libraries fro depending on a given symbol.

**Comment by sbc100** [comment]
Yeah, maybe just hardcoding the values for now in your code is the simplest solution.. these values are not going to be changing any time soon.

**Comment by RReverser** [comment]
Okay.

**Pull request closed without merging**
