### PR TITLE
Remove tools/ffdb.py

### PR DESCRIPTION
**Pull request by sbc100**
We have no tests for this code and it seems to relate to
firefox OS which I believe is not longer a thing.

Fixes: #12800

### CODE REVIEW

**Comment by kripken** [comment]
> firefox OS which I believe is not longer a thing.

https://en.wikipedia.org/wiki/KaiOS ?

**Review by kripken — APPROVED** [review]
But lgtm to remove this, I doubt anyone is using it. We can always restore it if someone files an issue.

**Comment by sbc100** [comment]
I'll give @juj a day or two speak up for this file before removing it :)

**Review by juj — APPROVED** [review]

**Comment by juj** [comment]
lgtm.

**Pull request merged**
