### PR TITLE
Remove getLightTypeID duplication. NFC

### PR DESCRIPTION
**Pull request by RReverser**
Unless I'm missing something, those are identical.

### CODE REVIEW

**Review by sbc100 — COMMENTED** [review]
Looks the same to me yes.  Maybe @brendandahl can see something we are not?

**Comment by RReverser** [comment]
At least it's good tests catch whatever I'm breaking... but yeah, not sure what.

**Comment by brendandahl** [comment]
The current `getActualType` function will dereference the `ptr` at runtime and get the type. With your changes you'll get the type of ptr which could actually contain a derived class.

In the failing test case the function returns `std::shared_ptr<PolyBase>` but the function actually creates a `PolyDerived` class and returns it.

**Comment by RReverser** [comment]
> will dereference the `ptr` at runtime and get the type

Huh... how can C++ get type at runtime? It uses RTTI to invoke correct template?

**Comment by RReverser** [comment]
Can at least part before `return` be safely deduplicated?

**Comment by brendandahl** [comment]
> > will dereference the `ptr` at runtime and get the type
> 
> Huh... how can C++ get type at runtime? It uses RTTI to invoke correct template?

`typeid()` handles polymorphic lvalues at runtime.  

If you run the test_embind with no changes and `-fno-rtti -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0` it will also fail in the same way as your patch.

**Comment by RReverser** [comment]
> `typeid()` handles polymorphic lvalues at runtime.

Right, but what I don't understand is that regular `LightTypeID::get` also calls `typeid()`, so why does it work differently? Surely there has to be some generic type we can substitute so that this function behaves in the same way... no?

**Comment by brendandahl** [comment]
I can't think of a way to make a generic one. `typeid` is weird since it's an operator that can handle taking a type or a value.

**Comment by RReverser** [comment]
Unfortunate but fair enough. I guess we could at least move out `static_assert` to avoid duplicating the message, but that's already way too different from what I tried in this PR, so closing.

**Pull request closed without merging**
