### PR TITLE
Update code size and metadce expectations after an LLVM roll broke things

### PR DESCRIPTION
**Pull request by kripken**
Looks like some minor regressions perhaps due to less inlining happening? (as
more functions appear in metadce output)

### CODE REVIEW

**Comment by kripken** [comment]
Looks like this fails on mac as the regression has not reached the mac builds yet...

**Review by aheejin — APPROVED** [review]
Thanks!

**Comment by kripken** [comment]
I'm not sure this is the right fix actually. As best we can guess so far, there is some new nondeterminism that is causing the errors. So we need to investigate this more.

Another option might be to disable these tests for now.

**Comment by sbc100** [comment]
I can't repro this failure locally, can you?

**Comment by sbc100** [comment]
I was able to repro locally with `emsdk install tot`, but not when I build llvm and binaryen myself .. as the same rev... strange.

**Comment by kripken** [comment]
I won't have more time to look into this today, I'm afraid. I did repro it with a tot build. I will try a local build tomorrow.

**Comment by sbc100** [comment]
This is very odd.   The problem occurs when I compile with `libdlmalloc-mt.a` with the tot build of the SDK, but if I build that library with my local llvm build I don't see the issue.

**Comment by kripken** [comment]
Doing more testing, this is what I see. The problem shows itself when LLVM compiles dlmalloc. To see the issue, it is enough to build `dlmalloc.o`. This is the command:
```
clang -D__EMSCRIPTEN_PTHREADS__=1 -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Xclang -iwithsysroot/include/SDL -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=13 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration --sysroot=cache/sysroot -Xclang -iwithsysroot/include/compat -Werror -O2 -fno-builtin -DNDEBUG -c -pthread system/lib/dlmalloc.c -o dlmalloc-01.o
```
On the last working `tot`, `01f5187ea1a57867d92cd75b0f36f1d0688ff50b`, there is no `$tmalloc_small` function emitted - it is inlined I suppose. On the very last `tot`, which is broken, `d5bd55eeaa37e4524471e1abe16b5d20ffc04d3e`, that function is emitted.

Building latest LLVM locally, `a0749f9bcc7c67ecca9e60f8844da9532da3e828`, I do not see the problem any more. But the CI on that revision still fails on having the problem, https://ci.chromium.org/ui/p/emscripten-releases/builders/try/linux/b8856125494747312624/overview

Is it possible that our CI is still running the old build somehow? If so a clobber may help here.

Also odd is that I reran CI here on github, on this PR. This PR updates the expectations to add that function. It then passes on linux but fails on mac. That could be consistent with the linux build needing a clobber, but the mac build not.

I opened https://github.com/WebAssembly/waterfall/pull/686 for a clobber, but I do not have a strong sense of whether it will actually help or not..?

**Comment by sbc100** [comment]
Lets hope a clobber works.  Very strange.

Were you unable to reproduce at any revision locally?  (Like me).  Its sounds like you were not.

**Comment by kripken** [comment]
> Were you unable to reproduce at any revision locally? (Like me). Its sounds like you were not.

Correct. I see different results with a local build (ok) versus what the CI runs (bad).

I did not try many revisions locally though, just the one I mentioned (it was the revision of the last abandoned roll).

**Comment by kripken** [comment]
We finally figured out that the real issue here was LLVM enabling the new pass manager by default. Due to the CI's incremental builds that took effect at a surprising time.

https://github.com/emscripten-core/emscripten/pull/13426 should fix things for now.

**Pull request closed without merging**
