### PR TITLE
Revert removal of `createRequire`

### PR DESCRIPTION
**Pull request by sbc100**
This change effectively reverts #23169 because it turns out there are quite a few other places in the codebase that depend on being able to call `require`.

### CODE REVIEW

**Comment by kripken** [comment]
What is the advantage? On code size it doesn't seem to help here IIUC

**Comment by sbc100** [comment]
See https://github.com/emscripten-core/emscripten/pull/23169#issuecomment-2556691146.

We have a lot of uses of `require` in the codebase.  So this is basically fixing a regression caused by #23169

**Comment by kripken** [comment]
I see, but if it's fixing a regression, why doesn't code size improve here? Or is the regression not covered by existing tests?

**Comment by sbc100** [comment]
> I see, but if it's fixing a regression, why doesn't code size improve here? Or is the regression not covered by existing tests?

The regression is not covered by the existing tests.   We would need to add tests that target each of our `require` usages, and combine them with `-sMODULARIZE`.

The code size regressions are pretty minor and bascially the inverse of the improvments from #23169

**Review by kripken — APPROVED** [review]
Got it, thanks, sounds good.

**Review by kleisauke — APPROVED** [review]

**Pull request merged**
