### PR TITLE
Default-enable -sGL_ENABLE_GET_PROC_ADDRESS

### PR DESCRIPTION
**Pull request by juj**
Given that some developers find it untenable to manually add the link flag `-sGL_ENABLE_GET_PROC_ADDRESS` into their builds when they need glGetProcAddress, make it default-enabled to let developers opt in to removing support for it manually.

Also make GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS imply the use of allowlist for a paranoia check when new WebGL extensions might not match their OpenGL counterparts.

### CODE REVIEW

**Comment by sbc100** [comment]
Sorry you are the first to run into my automatic settings documentation change.    Any changes to settings.py now need to be reflected in the rst file using `tools/maint/update_settings_docs.py`.   Hopefully that script should work for.. you are the first the need to run it.

**Review by kainino0x — APPROVED** [review]
LGTM

Could you explain to me a bit why it's useful to filter the list with GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS, but it still isn't when neither of these options is enabled? Is it just because we only want to auto-enable known extensions?

**Comment by juj** [comment]
Originally, enabling the allowlist when glGetProcAddress() is used fixed the original issue with glGetProcAddress() returning null on future extension function pointers.

However, codebases that automatically enable WebGL extensions might expand to enable a new WebGL extension in the future. And maybe browsers would do something different all of a sudden with that extension enabled.

So by extending the allowlist to cover builds that use that feature, this possibility is avoided.

> Sorry you are the first to run into my automatic settings documentation change. Any changes to settings.py now need to be reflected in the rst file using tools/maint/update_settings_docs.py. Hopefully that script should work for.. you are the first the need to run it.

Sam, I am actually on Christmas vacation starting this week.. any chance you might be able to tend to this? (sorry, I'll be back at the start of the next year, can dig into it then)

**Comment by sbc100** [comment]
Sure thing!   Have a great vacation

**Comment by kainino0x** [comment]
> Originally, enabling the allowlist when glGetProcAddress() is used fixed the original issue with glGetProcAddress() returning null on future extension function pointers.
> 
> However, codebases that automatically enable WebGL extensions might expand to enable a new WebGL extension in the future. And maybe browsers would do something different all of a sudden with that extension enabled.
> 
> So by extending the allowlist to cover builds that use that feature, this possibility is avoided.

Great, this is exactly what I suspected was the reason. SGTM

**Pull request merged**
