### PR TITLE
Fix default_setting to handle the NO_ option prefix

### PR DESCRIPTION
**Pull request by sbc100**
Fixes: #16348

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
`apply_settings` runs before this code, doesn't it? That already standardizes out the `NO_` in `standardize_setting_change`.

It seems odd for the `NO_` stuff to appear in more than one place - we should parse it as the user input arrives (which is what `standardize_setting_change` is, I think) and then not need to ever think about it again?

**Comment by sbc100** [comment]
> `apply_settings` runs before this code, doesn't it? That already standardizes out the `NO_` in `standardize_setting_change`.
> 
> It seems odd for the `NO_` stuff to appear in more than one place - we should parse it as the user input arrives (which is what `standardize_setting_change` is, I think) and then not need to ever think about it again?

Yes, but `default_setting` operates on the raw `settings_map` based on the actual command line args... since it cares about what the user supplies.   Perhaps I can refactor, but this is certainly fixes the issue at hand.. although writing a test might is more annoying than usual.

**Comment by kripken** [comment]
> Yes, but default_setting operates on the raw settings_map based on the actual command line args...

Then perhaps we can apply the `NO_` processing once on the input before it reaches `settings_map`? If we applied it to the commandline args themselves, for example, that might be a single place that works, if there's nothing better.

**Comment by sbc100** [comment]
> > Yes, but default_setting operates on the raw settings_map based on the actual command line args...
> 
> Then perhaps we can apply the `NO_` processing once on the input before it reaches `settings_map`? If we applied it to the commandline args themselves, for example, that might be a single place that works, if there's nothing better.

Perhaps.. but once I land #16366, I think this single extra check is not a huge deal.   If we process all the "NO_" prefixes we also have to integer parsing and invert the `NO_` settings..   keeping this as raw user settings is kind of simple.

**Comment by kripken** [comment]
I worry that without a single location that edits out the `NO_` stuff then we might need a third location as well that handles it. Unless we have a simple guarantee that only two data structures ever read the user settings, so two will be enough forever?

**Comment by sbc100** [comment]
Updated to normalize settings in the user_settings map

**Review by kripken — APPROVED** [review]
Nice!

**Pull request merged**
