### PR TITLE
Added --no_private_browsing emrun argument

### PR DESCRIPTION
**Pull request by titrindl**
Added --no_private_browsing argument to emrun to allow running tests which require features which are disabled in private browsing modes (for example, indexeddb).

### CODE REVIEW

**Comment by kripken** [comment]
Thanks @titrindl! Code looks good.

Please add yourself to AUTHORS, and also add testing for this - can add to the existing `test_zzz_emrun` in `tests/test_browser.py` (maybe just run it again with this new option, to see that works too).

**Comment by titrindl** [comment]
There's a problem with the test as it is. It does test that nothing in the python script breaks, but it doesn't use --kill_start, so the firefox profile is ignored. I'd add --kill_start, but I wasn't sure if it was ok to close the main test window.

**Comment by titrindl** [comment]
It looks like test-upstream-browser-chrome failed due to "Opening in existing browser session." causing "[0327/205343.147107:ERROR:nacl_helper_linux.cc(310)] NaCl helper process running without a sandbox!". I've been doing some testing with --kill_start and --kill_exit and they don't seem to do anything unless EMTEST_BROWSER is set (because the default options.browser on windows is "start"). I'm not sure how to fix this.

**Comment by titrindl** [comment]
The tests which failed in test-browser-chrome don't seem related

**Comment by kripken** [comment]
Thanks @titrindl, looks good - just rerunning the last browser-chrome one to make sure those emrun failures aren't related.

**Pull request merged**
