### PR TITLE
Add support for -### compiler flag

### PR DESCRIPTION
**Pull request by sbc100**
From the gcc man page:

```
-###
  Like -v except the commands are not executed and arguments are quoted unless they
  contain only alphanumeric characters or "./-_".  This is useful for shell scripts to
  capture the driver-generated command lines.
```

Fixes: #20468

### CODE REVIEW

**Review by kripken — APPROVED** [review]
I've never heard of this flag, but lgtm if we want to support it. I don't have an opinion on that myself - do we think it's worthwhile?

**Comment by RReverser** [comment]
I only ran into it because it seemed to be somewhat regularly suggested on SO, e.g. it's first result for search "clang print commands":

image

image

One could argue the question is somewhat rare / obscure, but I don't see why not support it.

**Comment by kripken** [comment]
I see, thanks. Sgtm to support it then, given that.

**Comment by sbc100** [comment]
The only place I've seen it is in clang unit test... but it does some like it could have some uses.

**Pull request merged**
