### PR TITLE
Split up monolithic run() method in emcc.py. NFC

### PR DESCRIPTION
**Pull request by sbc100**
This is huge refactor that will cause all kind of merge conflicts for
folks who work on emcc.py but its really been a long time coming and is
going to make future maintenance much more manageable.  Although
the diff view of this patch will not make much sense this patch is 90%
moving code around.

I basically split all each of the blocks that were being profiled into
separate functions, with a new EmccState object to hold any common
shared state.  A big advantage of this is that it becomes much more
clear what parts of the state are shared vs local.

The previous run() was 1468 lines.  Now its only 140.

### CODE REVIEW

**Comment by sbc100** [comment]
I have some ideas for how to cleanup the State object but in the interests to keeping this change relatively simple (mostly just moving code around) I'll do that as a followup.

**Comment by kripken** [comment]
I am a little hesitant to start reading this PR because tests do not pass, and the diff is very large and in a single file, so any later fix will force me to re-read the entire thing. Perhaps ping when tests all pass?

**Comment by sbc100** [comment]
Sorry tests were passing until I re-based.

I don't really expect you to be able to read this diff ..  since its just a huge refactor.  Unless you have a very nice diff viewer perhaps.   Let me see what `meld` does with it ..

**Review by kripken — APPROVED** [review]
Not really practical to review, but our test suite should be good enough to verify this.

**Comment by sbc100** [comment]
I split out #14018 should be reviewable.

**Pull request merged**
