### PR TITLE
Split pthread functions out of library_pthread.c. NFC

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Review by kripken — APPROVED** [review]

**Comment by kripken** [comment]
Before landing this it might be good to see if it would conflict with any large outstanding changes to that file.

**Comment by sbc100** [comment]
This change is really in prep for the musl upgrade which I think is a major change to these functions.. I don't know if anyone else is working on these except maybe @kleisauke .. so maybe I'll wait for their lgtm.

**Comment by kleisauke** [comment]
It will probably collide a bit, but don't worry, that can be resolved easily.

**Review by kleisauke — APPROVED** [review]
LGTM! I added a small inline comment.

**Pull request merged**
